### ISSUE TITLE
Incorporating mootools scripts into a gwt application

### ISSUE THREAD

**Issue by superuserpro** [gwtproject/gwt#10000]
My issue involves creating an animation on a Composite that should start when data is loading. To test this, I created animations on regular divs using HTML:

```
<div class="LoadDataWidget">
    <div id="arrow" class="greenArrow"></div>
</div>


.LoadDataWidget {
    width: 995px;
    height: 591px;
    background-image: url('images/loading-data.png');
    background-repeat: no-repeat;
    position: relative;
    margin: 0px auto;
    visibility: hidden;
}

.LoadDataWidget .greenArrow {
    width: 102px;
    height: 141px;
    background-image: url('images/loading-arrow.png');
    background-position: bottom;
    background-repeat: no-repeat;
    position: absolute;
    left: 500px;
    top: 205px;
}
```
Here is the JavaScript+mootools animation script:
```
window.addEvent('domready', function(){
        var effect = new Fx.Tween('arrow', {duration: 800}),periodical;

        // Create the function to run the effect
        var fx = function() {
            effect.start('height', '141').chain(function(){
                effect.start('height', '161');
            });
            return fx;
        };

        fx().periodical(1700);

        var singleImage = $$('.LoadDataWidget');

        singleImage.set('styles', {
            'opacity': 0,
            'visibility': 'visible'
        });

        singleImage.fade('in');


});
```
The animation works successfully, moving the arrow from top to bottom.

However, when attempting to use this script in a GWT application with elements having the class "LoadDataWidget" and ID "arrow," it does not function as expected.

Below is the Java code for the GWT Composite that I am trying to animate:

```
import com.google.gwt.user.client.ui.SimplePanel;

public class LoadDataWidget extends SimplePanel {

    public LoadDataWidget() {
        setStyleName("LoadDataWidget");
        SimplePanel arrow = new SimplePanel();
        arrow.setStyleName("greenArrow");
        arrow.getElement().setId("arrow");
        setWidget(arrow);
    }
}
```
Could the issue be related to the domready event? Any suggestions on how to resolve this problem?

Source https://csser.space/questions/incorporating-mootools-scripts-into-a-gwt-application

**Comment by jnehlmeier** [comment]
If you have not configured anything in your `*.gwt.xml` file then GWT code loads within an iframe by default which then results in a timing issue.

Usually you would install the hand written JS via GWT once GWT's `onModuleLoad()` method executes. You can do that using [ScriptInjector](https://www.gwtproject.org/javadoc/latest/com/google/gwt/core/client/ScriptInjector.html). It can either download the JS by providing a URL or you combine it with [ClientBundle and TextResource](https://www.gwtproject.org/doc/latest/DevGuideClientBundle.html#TextResource) to bundle your hand written JS together with the GWT app. In that case you can access the JS code as `String` and provide it to `ScriptInjector`. The `ScriptInjector` class also has an option to choose into which `Window` the JS code should be installed. Sometimes 3rd party libraries require the script to be installed into the top window and not the GWT iframe.

A second option is to have your JS provide a JS method that the GWT application calls once it is loaded.

Lastly you can change GWT's [linker](https://www.gwtproject.org/doc/latest/DevGuideLinkers.html) which is responsible to produce the final JS output of GWT. To get rid of the iframe loading strategy you would choose the `sso` linker. However it requires that your application only produces a single compilation result (= permutation). To achieve that you usually combine the `sso` linker with `<collapse-all-properties />` in the application's `*.gwt.xml` file.

**Comment by niloc132** [comment]
Closing until there is more information - this might be better served as a question on stackoverflow, the [mailing list](https://groups.google.com/g/google-web-toolkit), or the [gitter chat](https://matrix.to/#/#gwtproject_gwt:gitter.im).
