### ISSUE TITLE
Is enabling debugId for prod safe?

### ISSUE THREAD

**Issue by JanikkinaJ** [gwtproject/gwt#10003]
**GWT version: ALL** 
**Operating System:  ALL** 

--

##### Description
As far as i know all `ensureDebugID()` does is add an ID with the "gwt-debug" prefix and further distinguishes subelements of the element with string such as "-input". Does inheriting `com.google.gwt.debug.Debug`  do anything other than enable debugIds? If not, does this pose any threat that adding many well named IDs wouldn't? 

The Idea is to add this to production with the prefix disabled instead of adding the IDs the manual way.

**Comment by jnehlmeier** [comment]
It does not pose any threat. But you still have to call `ensureDebugId` manually and also make sure the ID is unique if the same component is used multiple times on the same page. `Document.get().createUniqueId()` can help with that.

**Comment by JanikkinaJ** [comment]
Thank you for the clarifying :)

**Comment by Lonzak** [comment]
Inheriting `com.google.gwt.debug.Debug` seems to automatically enable debug-ids. This is not problematic I agree, however the remaining question is what else might be activated / enabled / not done (like obfuscation) when using `<inherits name='com.google.gwt.debug.Debug'/>`
Might be just a feeling but to have this import inside production environment one really needs to be sure not to introduce anything else / open up unwanted attack vectors / information gaining possibilities....

**Comment by jnehlmeier** [comment]
@Lonzak @JanikkinaJ Currently it only activates debug ids. However `com.google.gwt.debug.Debug` is pretty generic named so GWT could potentially add other debug features into it that you might not want to be active in production. That is something you have to keep in mind if you start to "misuse" it for managing id attributes in production.

However whatever is added to Debug in the future does not make the app less secure. It is a JS app and thus insecure by definition as the attacker has full access to the source code, obfuscated or not.

**Comment by Lonzak** [comment]
So if someone wants to add ids to components like textfields, buttons, checkboxes etc. then better use its own ids/mechanism. Using debug ids was probably a quite convenient way since it is not only adding IDs but also differentiates subelements etc...
