### ISSUE TITLE
Missing sources for type annotations trip the compiler

### ISSUE THREAD

**Issue by zbynek** [gwtproject/gwt#10020]
**GWT version:** 2.11
**Browser (with version):** any
**Operating System:** Windows

---

##### Description
Some usages of annotations lead to missing source errrors.

##### Steps to reproduce

**Usecase 1)**
* Add jsinterop 1.0.2 to your project
* Compile with GWT 2.11

```
[ERROR] Errors in 'jar:file:/.../base-1.0.2.jar!/jsinterop/base/Js.java'
         [ERROR] Line 140: Nullable cannot be resolved to a type
```

**Usecase 2**
Same  issue also reproducible with [j2objc annotations 2.8](https://mvnrepository.com/artifact/com.google.j2objc/j2objc-annotations/2.8), depending on placement. Annotating a field is OK

```java
@WeakOuter Object foo = new Object();
```

Annotating an anonymous class is not

```java
foo =  new @WeakOuter Object() {
   @Override
   public String toString() {
      return "Foo";
   }
}

```

##### Known workarounds

* Include all annotation sources

##### Links to further discussions

https://github.com/google/jsinterop-base/issues/19

**Comment by cpovirk** [comment]
I got [asked](https://github.com/google/jsinterop-base/issues/19#issuecomment-2442943246) if I could share how to reproduce the trouble we've seen with this in Guava.

It's pretty easy: Currently, we strip out our type-use nullness annotations to avoid that problem. So I pushed [a commit to my Guava fork to stop stripping them](https://github.com/google/guava/compare/master...cpovirk:guava:gwt10020). With that change, I can run `./mvnw clean install -DskipTests`, and I get a flood of errors like this:

```
[INFO] Tracing compile failure path for type 'com.google.common.collect.SortedSetMultimap'
[INFO]    [ERROR] Errors in 'file:/usr/local/google/home/cpovirk/clients/guava-black/guava/guava-gwt/target/classes/com/google/common/collect/SortedSetMultimap.java'
[INFO]       [ERROR] Line 53: No source code is available for type org.checkerframework.checker.nullness.qual.Nullable; did you forget to inherit a required module?
[INFO]    [ERROR] Errors in 'file:/usr/local/google/home/cpovirk/clients/guava-black/guava/guava-gwt/target/classes/com/google/common/collect/SetMultimap.java'
[INFO]       [ERROR] Line 56: No source code is available for type org.checkerframework.checker.nullness.qual.Nullable; did you forget to inherit a required module?
[INFO]    [ERROR] Errors in 'file:/usr/local/google/home/cpovirk/clients/guava-black/guava/guava-gwt/target/classes/com/google/common/collect/Multimap.java'
[INFO]       [ERROR] Line 168: No source code is available for type org.checkerframework.checker.nullness.qual.Nullable; did you forget to inherit a required module?
[INFO]    [ERROR] Errors in 'file:/usr/local/google/home/cpovirk/clients/guava-black/guava/guava-gwt/target/classes/com/google/common/collect/Multiset.java'
[INFO]       [ERROR] Line 98: No source code is available for type org.checkerframework.checker.nullness.qual.Nullable; did you forget to inherit a required module?
```

**Comment by niloc132** [comment]
I've put up a PR with a test that reflects the six different ways that JDT can encounter annotations, and I think this simple fix will resolve this bug.
