### ISSUE TITLE
Support regarding removal of unsafe-eval

### ISSUE THREAD

**Issue by imrozeH** [gwtproject/gwt#10047]
**GWT version:2.9.0 
**Browser (with version): Chrome 130.0.6723.92
**Operating System: Mac

---

##### Description

Basically I am trying to remove unsafe-eval and as per a previous issue I upgraded th rpc version to 8 and as well as increased the maxPayloadChunkSize. Everything seems to be working really nice apart from the string with node size more than 64kb, those were throwing eval errors. So I have increased the node size as well. But once I increase the node size, the entire project doesn't load at all, keeps reloading at a certain init phase.
Seems like in the clas ServerSerializationStreamWriter.java, 

private void writeHeader(LengthConstrainedArray stream) {
    stream.addToken(getFlags());
    if (stream.isJavaScript() && getVersion() >= SERIALIZATION_STREAM_JSON_VERSION) {
      // Ensure we are not using the JSON supported version if stream is Javascript instead of JSON
      stream.addToken(SERIALIZATION_STREAM_JSON_VERSION - 1);
    } else {
      stream.addToken(getVersion());
    }
  }

When ever the large strings are being passed through SERIALIZATION_STREAM_JSON_VERSION > 7 it is going into some spiral mode. Can anybody help here?

**Comment by niloc132** [comment]
This sounds a little like https://github.com/gwtproject/gwt/issues/10043, where one of the flags was missed. To confirm, you raised both`gwt.rpc.maxPayloadChunkSize` and `gwt.rpc.maxStringNodeLength` using server-side system properties to something like Integer.MAX_VALUE, and `gwt.rpc.version` to 8?

**Comment by imrozeH** [comment]
It was the 3rd case in #10043. Thank you so much. Got it resolved.
