### ISSUE TITLE
Window.onClosing() doesn't work in GWT 2.12

### ISSUE THREAD

**Issue by InforBG** [gwtproject/gwt#10072]
**GWT version: 2.12.0 and 2.12.1** 
**Browser (with version): Chrome** 
**Operating System: Windows 11** 

---

##### Description
com.google.gwt.user.client.Window.onClosing() method doesn't work after upgrading to GWT 2.12.x.
This is an issue introduced from https://github.com/gwtproject/gwt/pull/9984 in GWT 2.12.0.

When calling `Window.addWindowClosingHandler(ClosingHandler)`, it will set the new class member beforeCloseHandlersInitialized = true.
Unfortunately, onClosing() method is still checking closeHandlersInitialized. It should check the beforeCloseHandlersInitialized instead. See source code in https://github.com/gwtproject/gwt/blob/a48140fe3a57fb8975ccdd31acbcf9db0ebe1882/user/src/com/google/gwt/user/client/Window.java#L856
```java
  static String onClosing() {
    if (closeHandlersInitialized) {  // should be beforeCloseHandlersInitialized !!
      Window.ClosingEvent event = new Window.ClosingEvent();
      fireEvent(event);
      return event.getMessage();
    }
    return null;
  }
```

##### Steps to reproduce
Call `Window.addWindowClosingHandler(ClosingHandler);`.
When the window closes or redirects to other website, the Window#onClosing() or ClosingHandler#onWindowClosing method is not invoked.

##### Known workarounds
Have to temporarily call the deprecated method Window.addCloseHandler() to set the closeHandlersInitialized=true and then Window#onClosing() method will work. This is an ugly workaround.

**Comment by niloc132** [comment]
Thank you for finding, reporting, and fixing this bug (that I introduced). We'll merge it to main shortly, then backport for a 2.12.2 release.

**Comment by niloc132** [comment]
Thanks for bringing this up @huettesn - can you confirm that you've either tested with a nightly build or built locally to confirm the fix? With a little more validation to assist in getting the release out, I'll start the process of shipping 2.12.2.

**Comment by huettesn** [comment]
Thanks for your answer. Where do I find the version numbers of a nightly build?

**Comment by niloc132** [comment]
If you're getting your jars from maven central (via maven/gradle/ivy/etc), you can add the following repository to your project:
https://oss.sonatype.org/content/repositories/snapshots/
Using that, you can specify HEAD-SNAPSHOT as the version, or can specify an exact version by browsing for each artifact (gwt-dev, gwt-user, gwt-servlet, etc).

If you would like a GWT SDK zip download instead, you can get a nightly build of `main` from https://github.com/gwtproject/gwt/actions?query=event%3Aschedule+branch%3Amain - click a passing build, scroll to "artifacts" and download one of the gwt-*.zip files. They are all the same - the Java version attached tells you only what version it was built with, but all will run on Java 11+ at this time.

**Comment by benjaminalbanese** [comment]
Hi @niloc132, thanks a lot for your info. 
With that I could build a HEAD-SNAPSHOT version to test it for my colleague @huettesn. With the HEAD-SNAPSHOT we get a confirm popup when trying to close the window. 

However, in this version, as it seems was already the case in GWT 2.10.0, calling com.google.gwt.user.client.Window.ClosingEvent#setMessage would set the event's message but its message didn't appear for me in the popup. In the popup window instead the default message of each browser was displayed. 

I tested it on MacOS with Chrome 133, Firefox 135 and Safari 18.1.1

This is for us however not really an issue and we wanted to report this only for the sake of completeness. 

Thanks for your time!

**Comment by benjaminalbanese** [comment]
> This is the browsers' behavior. It's even part of the spec, and it's been that way for years already.

Thank you for the explanation!
