### ISSUE TITLE
JSOs cannot have abstract superclasses

### ISSUE THREAD

**Issue by dankurka** [gwtproject/gwt#4859]
Originally reported on Google Code with ID 4859
```
Found in GWT Release (e.g. 1.5.3, 1.6 RC):

2.0

Encountered on OS / Browser (e.g. WinXP, IE6-7, FF3):

all

Detailed description (please be as specific as possible):

If you try to use an abstract JSO you expose a bug in JSORestrictionsChecker leading
to a stack 
trace:


22:39:10.049 [ERROR] [expensesScaffold] Failed to load module 'expensesScaffold' from
user 
agent 'Mozilla/5.0 (Macintosh; U; Intel Mac OS X 10.5; en-US; rv:1.9.2.3) Gecko/20100401

Firefox/3.6.3 GTB6' at localhost:63600
com.google.gwt.dev.jjs.InternalCompilerException: Already seen an implementing JSO
subtype 
(EmployeeRecordImpl) for interface (Record) while examining newly-added type 
(ReportRecordImpl). This is a bug in JSORestrictionsChecker.
    at 
com.google.gwt.core.ext.typeinfo.TypeOracle.computeSingleJsoImplData(TypeOracle.java:702)
    at com.google.gwt.core.ext.typeinfo.TypeOracle.finish(TypeOracle.java:362)
    at com.google.gwt.dev.javac.TypeOracleMediator.addNewUnits(TypeOracleMediator.java:359)
    at com.google.gwt.dev.javac.CompilationState.assimilateUnits(CompilationState.java:135)
    at com.google.gwt.dev.javac.CompilationState.<init>(CompilationState.java:79)
    at 
com.google.gwt.dev.javac.CompilationStateBuilder.doBuildFrom(CompilationStateBuilder.java:286
)
    at 
com.google.gwt.dev.javac.CompilationStateBuilder.buildFrom(CompilationStateBuilder.java:182)
    at com.google.gwt.dev.cfg.ModuleDef.getCompilationState(ModuleDef.java:287)
    at 
com.google.gwt.dev.DevModeBase$UiBrowserWidgetHostImpl.createModuleSpaceHost(DevModeB
ase.java:99)
    at 
com.google.gwt.dev.shell.OophmSessionHandler.loadModule(OophmSessionHandler.java:176)
    at 
com.google.gwt.dev.shell.BrowserChannelServer.processConnection(BrowserChannelServer.java:5
10)
    at com.google.gwt.dev.shell.BrowserChannelServer.run(BrowserChannelServer.java:352)
    at java.lang.Thread.run(Thread.java:637)

```

Reported by `rjrjr@google.com` on 2010-04-16 19:11:49

**Comment by ozguraydinli** [comment]
any plans on tackling this? or any workarounds?

**Comment by rluble** [comment]
The sensible patch here would be to make it an error and disallow abstract in the JSO declaration. There is a patch in this thread that takes a more nuanced approach (I believe it allows it as long as there is only one implementation for the methods) in this thread.

Feel free to contribute a patch (http://www.gwtproject.org/makinggwtbetter.html).

Why do you need an abstract JSO class?

**Comment by dankurka** [comment]
Starting with GWT 2.8 users should be using jsinterop instead of JSOs, so I think changing/fixing anything in JSOs is not worth it anymore.

**Comment by ozguraydinli** [comment]
@rluble what I actually want is to be able to implement an interface in 2 different JSOs, so that i can reuse my code which is written to that interface.

@dankurka How would I use JsonUtils.stringify(myJso) with jsinterop?

**Comment by gkdn** [comment]
Implementing an interface in 2 different JSOs is against the fundamentals of JSOs; that is not possible.
Any @JsType(isNative=true) could be cast to JSO so can be used with JsonUtils.stringify or you can define your own native @JsMethod that maps "JSON.stringify" and you can call it with any object that you want.

**Comment by ozguraydinli** [comment]
@gkdn thanks. thats exactly what i just discovered. I think I didnt totally understand what I can do with jsinterop in the beginning.
