### ISSUE TITLE
ImageResource is hard to use in UiBinder

### ISSUE THREAD

**Issue by dankurka** [gwtproject/gwt#6148]
Originally reported on Google Code with ID 6149
```
We need a ui:sprite attribute in <img>, e.g.

<div><img ui:sprite={myImageResource}/>

The workaround is to create a sprite, but that requires obscure boilerplate in a <ui:style>

This is particularly a problem because people often incorrectly do this:

<img src={myImageResource.getUrl}/>

which used to accidentally work (except on IE which will show the full content of a
sprite), and which is now fully broken after the UiBinder SafeHtml integration
```

Reported by `rjrjr@google.com` on 2011-03-15 13:55:56

**Comment by tbroyer** [comment]
`ImageResource` now no longer uses sprites by default so `<img src="{bundle.myImageResource.getSafeUri}"/>` is relatively safe, and it's still possible to use a `<g:Image resource="{bundle.myImageResource}"/>`, which no longer uses a background-image in this case. So let's close this; setting milestone to 2.6 as that's when `Image` stopped using a _clipped state_ for `ImageResource` unconditionally.
