### ISSUE TITLE
String.charAt(int) should throw IndexOutOfBoundsException if index is pointing out of bounds

### ISSUE THREAD

**Issue by dankurka** [gwtproject/gwt#6942]
Originally reported on Google Code with ID 6943

```
Found in GWT Release (e.g. 2.4.0, 2.5.0 RC): 2.4.0

Encountered on OS / Browser (e.g. WinXP, IE8-9, FF7): FF7, Chrome15

Detailed description (please be as specific as possible):
String.charAt(int) should throw IndexOutOfBoundsException if index is pointing out
of bounds. Now it returns NaN in production mode.

In development it works correctly. 
Shortest code snippet which demonstrates issue (please indicate where
actual result differs from expected result):
"test".charAt(100); // should throw IndexOutOfBoundsException exception instead of
returning NaN.

Maybe relates to Issue 6381.

Workaround if you have one:
Check bounds on your own.

```

Reported by `m.zdila` on 2011-10-31 10:45:33

**Comment by mwasson** [comment]
Just found this in the wild using an early 2.8.0 nightly release. This was unexpected behavior, given that it contradicts the JavaDoc of String.charAt and isn't producible running the code in a JVM. 

I know that this is a weird edge case of the documentation to rely upon, but unfortunately I'm relying on a parsing library that uses exceptions for control flow. Of course it's easy to check for an invalid index and throw the exception myself now that I know this is an issue.

I understand that the additional code required to check for this probably isn't worth it, especially as the return value in this case doesn't seem well-defined across browsers. (ECMAScript-262 says it should be an empty string, but Chrome is returning NaN.) Is there any way to more easily communicate to the user that this has unexpected results? Maybe a compiler warning when using charAt?

**Comment by gkdn** [comment]
I think it is OK to add a precondition check here.

**Comment by jnehlmeier** [comment]
I'll add a precondition check for 2.8.1 to match JRE behavior

**Comment by jnehlmeier** [comment]
More likely to end up in 2.8.2

**Comment by mwasson** [comment]
Thank you, Jens!

**Comment by niloc132** [comment]
https://gwt-review.googlesource.com/#/c/gwt/+/19580/
