### ISSUE TITLE
GWT.log() should log deobfuscated stack traces when in Super Dev Mode

### ISSUE THREAD

**Issue by dankurka** [gwtproject/gwt#7457]
Originally reported on Google Code with ID 7460
```
For example, GWT.log("something failed", myException); should dump the deofuscated stack
trace to the JavaScript console.

We could either send stack traces to the code server for deobfuscation (requiring a
round trip delay before the message is logged) or load the sourcemap and do it client
side. Client-side deobfuscation might work in more situations since it can be synchronous
once the sourcemap is loaded.

Current as of GWT 2.5 rc 1.
Ported from internal issue tracker: http://b/issue?id=6413577

```

Reported by `skybrian@google.com` on 2012-06-27 21:58:34

**Comment by confile** [comment]
Is there some progress on this issue? I have the same problem with GWT 2.8-beta1.

**Comment by jnehlmeier** [comment]
@confile In GWT 2.8 GWT.log(msg, Throwable)` prints the stack trace and that stack trace should be mapped to Java files via source maps in Chrome so you can click on it in SuperDevMode. If the stack trace is not clickable/source mapped then the browser was not able to load source maps from the CodeServer for some reason.

`java.util.logging.Logger` behaves differently though:
- When you have not inherited `Logging.gwt.xml` nor `LoggingDisabled.gwt.xml` then `Logger` behaves the same as `GWT.log` (basically you only have inherited `LogImpl.gwt.xml`)
- When you have inherited either `Logging.gwt.xml` or `LoggingDisabled.gwt.xml` then the property `compiler.stackMode` must be set to `native` to get the same behavior as `GWT.log`.
- If your `compiler.stackMode` is not `native` then `Logger` will not print clickable, source mapped stack traces but ordinary ones as the stack traces are emulated.

**Comment by confile** [comment]
@jnehlmeier and the exception should be unwrapped right?

```
Throwable unwrapped = unwrap(error);
```

```
  public Throwable unwrap(Throwable e) {
    if(e instanceof UmbrellaException) {
      UmbrellaException ue = (UmbrellaException) e;
      if(ue.getCauses().size() == 1) {
        return unwrap(ue.getCauses().iterator().next());
      }
    }
    return e;
  }
```

**Comment by jnehlmeier** [comment]
@confile no, UmbrellaException is handled by GWT 2.8 now. The first cause is the ordinary getCause() and all other causes are handled as suppressed exceptions. So you will see the whole chain of exceptions in the console.

**Comment by confile** [comment]
@jnehlmeier Are you sure I tried both variants and it only works well with the unwrap function I posted above.

**Comment by confile** [comment]
@jnehlmeier You were right it is not so obvious to see. Thanks for help.

**Comment by dnouls** [comment]
GWT.log does not seem to work when an incremental compile has been done. It only seems to work when its a full build when starting codeserver on a clean project.

**Comment by jnehlmeier** [comment]
@dnouls GWT.log() works with incremental compile. However your DevTools must be open before the error occurs, otherwise Chrome does not apply source maps to the logged stack trace.

**Comment by craigmit** [comment]
Can confirm `GWT.log("Error", caught);` gives a stack track like this:
```
TypeError: Cannot read property 'getImage_1_g$' of null
    at new gYg_g$ (TextureMgr.java:141)
    at new Hyj_g$ (GameRenderer.java:221)
    at hVg_g$.HVg_g$ [as lambda$9_1_g$] (GameWidget.java:191)
```
The source is even clickable.  Brilliant!  👍
