### ISSUE TITLE
Compiler hangs when compiling a certain Java code

### ISSUE THREAD

**Issue by dankurka** [gwtproject/gwt#7854]
Originally reported on Google Code with ID 7857

```
Found in GWT Release : 2.4.0

Encountered on OS / Browser : Ubuntu, Eclipse or console

Detailed description (please be as specific as possible):

The compiler hangs when I try to compile the module which contains the code below.

Shortest code snippet which demonstrates issue (please indicate where
actual result differs from expected result):

1.  @Override
2.  public void onModuleLoad() {
3.      int result;
4.      int[] values = new int[10];
5.      LinkedList<Boolean> neverUsedList = new LinkedList<Boolean>();
6.      for (int i = 0; i < 6; i++) {
7.          neverUsedList.add(Boolean.FALSE);
8.      }
9.
10.     List<Integer> pendingValues = new ArrayList<Integer>();
11.     for (int pos = 0; pos < 100; pos++) {
12.             
13.         boolean greater = values[pos] < values[pos + 1];
14.         
15.         boolean more = false;
16.         if (!greater) {
17.             int sum = 0;
18.             for (Integer value : pendingValues) {
19.                 sum += value;
20.             }
21.             more = sum > 15;
22.         }
23.
24.         if (greater || more) {
25.             pendingValues.add(values[pos]);
26.         }
27.         else {
28.             for (Integer value : pendingValues) {
29.                 result = value;
30.             }
31.             pendingValues.clear();
32.         }
33.     }
34. }

Workaround if you have one:

The code compiles with *any* of the following changes:
- remove the LinkedList at line 5, or simply never write it in the loop (it is never
used anyway)
- reuse the 'greater' boolean instead of the 'more' variable at line 21.
- remove lines 28-30 (the result is not used anywhere) 

Links to relevant GWT Developer Forum posts:
-

Link to patch posted at http://gwt-code-reviews.appspot.com:
-

```

Reported by `matyas.vary` on 2012-12-19 15:48:51

<hr>
- _Attachment: [PublicWeb.java](https://storage.googleapis.com/google-code-attachments/google-web-toolkit/issue-7857/comment-0/PublicWeb.java)_

**Comment by RockyMM** [comment]
Hi!

I have encountered this problem in 2.6.1. When I set "optimizeDataflow = false" using gwt-maven-plugin my builds started working properly. Before that they were just hanging 90% of the time (funnily enough, the builds were not hanging all the time).

Is this coming in 2.8.0?

Thanks!

**Comment by vetrovosk** [comment]
We are getting similar issue on GWT 2.8.1 (GWT compilation hang with "Compiling permutation 0" being the last output). Here is what we see in jstack: https://gist.github.com/vetrovosk/3bbd4ed9bca5b4831b3a3988b30692a5

I see `DataflowOptimizer` in stacktrace. Is this related to the issue? 

Setting `optimizeDataflow` to `false` seems to fix compilation.

**Comment by rluble** [comment]
There is a known issue with the DataflowOptimizer, see
https://github.com/gwtproject/gwt/issues/7854

There is no much gain from it so I recommend that turn it off is a good
permanent solution.

**Comment by tbroyer** [comment]
@rluble Should we disable DataflowOptimizer by default? (4 years ago, you said that was the case, but it's currently enabled by default in [`JJSOptionsImpl`](https://github.com/gwtproject/gwt/blob/f3a9fa7374a44422aa4da4a74724474e94f94c8c/dev/core/src/com/google/gwt/dev/jjs/JJSOptionsImpl.java#L43))

BTW, there's a review linked in comments above, from 4 years ago, that was never merged (and now has merge conflicts); you might want to abandon it.

**Comment by rluble** [comment]
We disabled the DataFlowOptimizer internally back then. I think we should disable it by default or just plainly remove it.

The fix could be easily rebased if you prefer to go on with the fix.

**Comment by tbroyer** [comment]
https://gwt-review.googlesource.com/c/gwt/+/19900
