### ISSUE TITLE
Embedded code has improper or no newline placements

### ISSUE THREAD

**Issue by dankurka** [gwtproject/gwt#8232]
Originally reported on Google Code with ID 8242

```
Code in green blocks have no newlines.

http://www.gwtproject.org/doc/latest/tutorial/JUnit.html

FireFox 22.0


```

Reported by `vincent123` on 2013-07-07 23:22:48

**Comment by tbroyer** [comment]
There are other rendering issues on this page (and others), but not (no longer) this one.
