### ISSUE TITLE
Add JAVA 8 Lambda support 

### ISSUE THREAD

**Issue by dankurka** [gwtproject/gwt#8359]
Originally reported on Google Code with ID 8373
```
Lambda expression has following advantages:
1. JavaScript functional (Node.JS) style development
2. Easier GWT RPC calls. Anonymous inner class is ugly.
3. With server side asynchronous (event driven) framework support like Node.JS, great
performance will be achieved. And the code will be more accordance with client asynchronous
calls.
```

Reported by `louxiangming` on 2013-09-30 03:18:24

**Comment by joelhandwell** [comment]
@ccidral yes, it's in master branch, and it will be released with 2.8 (according to @tbroyer on this SO comment http://stackoverflow.com/questions/15693169/java-8-support-in-gwt)
