### ISSUE TITLE
CodeSplit with an Annotation

### ISSUE THREAD

**Issue by dankurka** [gwtproject/gwt#8430]
Originally reported on Google Code with ID 8445

```
Found in GWT Release (e.g. 2.4.0, 2.5.1, trunk):
All

Encountered on OS / Browser (e.g. WinXP, IE9, FF10):
Win8, x64 Oracle Java 7

Detailed description (please be as specific as possible):
I think there should be an annotation like @GwtSplitPoint on translatable types to
force the compiler to split this type from compiled code. As i understand GWT.runAsync(....){
block... } method splits only THE BLOCK. For example I create a composite instance
of my application. And im sure the related composite is never used before (except imports).

By using this method (as i know) the related composite class is not splitted, but invoker
block is splitted only. As a result the application size will be huge in first part
of compiled JavaScript.


Shortest code snippet which demonstrates issue (please indicate where
actual result differs from expected result):
if (path.startsWith("GLXFAccountBrowser_4")){
    GWT.runAsync(new LbsRunAsyncCallback(){
        @Override
        public void onSuccess() {
            FAccountList list= new FAccountList (path, that, null);
            list.setWidth("auto");
            list.setHeight("100%");
            workarea.setWidget(list);
            list.onShow();              
        }
    });
}...
FAccountList will not be in splitted part i think?


Workaround if you have one:


Links to relevant GWT Developer Forum posts:


Link to patch posted at http://gwt-review.googlesource.com

```

Reported by `hakan.cunier` on 2013-11-15 12:13:53

**Comment by niloc132** [comment]
Closing as Will Not Implement. An annotation isn't really enough information - we need to not only know what type should be split, but ensure that it is only reachable in an async way somehow. The old AsyncProxy feature (removed in https://github.com/gwtproject/gwt/commit/fba4d52aa4) got close here, by requiring an API to implement to access the object in a clearly async way (void-returning methods could be "sent" to it and would arrive asynchronously, but no values could be read). The annotated type would need the same restrictions as just implementing this sort of interface, and you'd still need some sort of factory method to create the required scaffolding.

If anyone is looking to recreate that kind of thing, resurrecting that removed feature should be very possible in an external library, either as an old style Generator or as an annotation processor.
