### ISSUE TITLE
Support for Servlet 3.0 annotations and ServletContainerInitializer in the dev mode

### ISSUE THREAD

**Issue by dankurka** [gwtproject/gwt#8456]
Originally reported on Google Code with ID 8472
```
Found in GWT Release (e.g. 2.4.0, 2.5.1, trunk):
2.6.0-rc1


Encountered on OS / Browser (e.g. WinXP, IE9, FF10):
Any


Detailed description (please be as specific as possible):
2.6.0 updated integrated jetty to 8.1 so in theory in dev mode it should support Servlet
3.0 features such as Servlet 3.0 annotations and ServletContainerInitializer. In practice
JettyLauncher does not properly configure the embedded jetty to support this. Attached
is the extension of GWT JettyLauncher that enables it (and is proven to work). 


Shortest code snippet which demonstrates issue (please indicate where
actual result differs from expected result):
@WebServlet, @WebFilter and ServletContainerInitializer classes are not scanned by
the integrated jetty instance.

Workaround if you have one:
use -server switch and supply the attached class as an argument


Links to relevant GWT Developer Forum posts:



Link to patch posted at http://gwt-review.googlesource.com

```

Reported by `ayudichev` on 2013-11-29 13:34:45

**Comment by SiggyRadiation** [comment]
Hello all, Is there any update yet? Using Servlet 3.0 annotations would help me out a lot since I have to manage a lot of servlets that are build in a module and keeping the web.xml's of the projects that use them up-to-date.

**Comment by branflake2267** [comment]
There is a workaround, allowing any servlet container to be used. A launcherDir property can be set in the CodeServer entrypoint pointing to the war output directory of any running server.

**Comment by tbroyer** [comment]
@SiggyRadiation GWT 2.8.0-SNAPSHOT should currently support web fragments; would that help?

**Comment by SiggyRadiation** [comment]
@tbroyer thanks for the info. As far as I'm up-to-date regarding web fragments, in theory it should. 

I could create a web fragment for the servlets (rpc services) in my framework project. Then I wouldn't have to define them again in the web.xml for every project that uses that framework and its servlets.

Of course it would also depend on the practicality of using web fragments in a GWT-RPC environment and debugging my server side code. The annotation route seemed like a more subtle approach to me.But, again, in theory it would be a solution. So I will certainly be testing it soon.

**Comment by tbroyer** [comment]
Is should also, in theory, be possible to write a class extending `com.google.gwt.dev.shell.jetty.JettyLauncher` and overriding `createWebAppContext` to call `setConfigurationClasses` on the value before returning it (see https://www.eclipse.org/jetty/documentation/9.2.10.v20150310/configuring-webapps.html for the value to pass in), then using that class as a `-server` argument to DevMode.
(of course you'd have to add the `jetty-annotations` JAR and its dependencies to the classpath; GWT 2.8.0-SNAPSHOT uses Jetty 9.2.14)

**Comment by tbroyer** [comment]
See https://gwt-review.googlesource.com/c/14460

Strangely, while `ServletContainerInitializer` works well (it's used to bootstrap JSP support, and it always worked during my tests), annotation scanning didn't work every time. I tried debugging what was happening but every time I was in debug, it worked; possibly some kind of race condition. But at least this change adds support for it as well as it possibly can.
