### ISSUE TITLE
Emulate java.util.ArrayDeque

### ISSUE THREAD

**Issue by dankurka** [gwtproject/gwt#8511]
Originally reported on Google Code with ID 8530

```
Found in GWT Release (e.g. 2.4.0, 2.5.1, trunk):
2.5.1, trunk


Detailed description (please be as specific as possible):
GWT lacks in emulation of ArrayDeque (Java 6 API)



```

Reported by `a.korzhevskiy` on 2014-01-13 03:53:51

**Comment by mishadynin** [comment]
What's blocking this?
It would be great to have ArrayDeque for Guava's EvictingQueue; see b/23008533.
