### ISSUE TITLE
Support development of GWT using Java 6

### ISSUE THREAD

**Issue by dankurka** [gwtproject/gwt#8554]
Originally reported on Google Code with ID 8574

```
As long as the project supports Java 6 it should be possible to develop the project
using Java 6. Today the Eclipse project requires Java 7 because of Java 7 tests or
alternatively you must manually remove selected test methods/classes.

The tests which depend on Java 7 should at least be in a separate source directory
so it can be easily excluded. Maybe it does not even need to be on the build path by
default in Eclipse as long as the Ant build builds and runs them.

The problem with using Java 7 when developing the problem is that you easily accidentally
slip in Java 7 code.
```

Reported by `artur@vaadin.com` on 2014-02-12 15:17:39

**Comment by zbynek** [comment]
After 7 years and Java 7 EOL this looks like `won't fix`

**Comment by niloc132** [comment]
When https://github.com/gwtproject/gwt/pull/9780 is reviewed, merged, we will have checks in place to protect against java 9+ code being in the project (by virtue of setting the source version to 8), but will still run on java 8 until we deliberately lift that.

See some of the discussion at https://groups.google.com/g/google-web-toolkit-contributors/c/SuhBveCHoFA, no concrete conclusion there, but we will be dropping java 8 support sooner than later in the compiler itself, for at least one version of GWT.
