### ISSUE TITLE
Update validation related dependencies for Java 8

### ISSUE THREAD

**Issue by dankurka** [gwtproject/gwt#8869]
Originally reported on Google Code with ID 8914

```

Found in GWT Release (e.g. 2.4.0, 2.5.1, trunk):

trunk


Encountered on OS / Browser (e.g. WinXP, IE9, FF10):

N/A

Detailed description (please be as specific as possible):

When running under a java 8 vm some validation tests (e.g org.hibernate.jsr303.tck.tests.constraints.constraintdefinition.ConstraintDefinitionsGwtTest.testConstraintWithCustomAttributes)
fail due to old validation dependencies.

The following jars should probably be updated
hibernate-validator (currently 4.1 probably update to 5.1.2)
jsr303-tck (currently at 1.0.3 probably update to 1.0.7?)
validation-api (currently at 1.0.0 update to 1.1.0?)

Shortest code snippet which demonstrates issue (please indicate where
actual result differs from expected result):



Workaround if you have one:



Links to relevant GWT Developer Forum posts:



Link to patch posted at http://gwt-review.googlesource.com


```

Reported by `rluble@google.com` on 2014-09-25 00:21:38

**Comment by tbroyer** [comment]
Disabling failing tests now that we switched the CI build to Java 8: https://gwt-review.googlesource.com/13781

**Comment by benjamintillman** [comment]
It's not clear to me how far this went, but it looks like GWT now depends on hibernate-validator:4.3.2.Final.

Is there any chance this can be bumped up to 5.x? I suspect it won't be a trivial task since validation-api:1.1 breaks my GWT builds, but I haven't had a chance to look into it.

**Comment by tbroyer** [comment]
@benjamintillman This actually went nowhere. As of today, GWT still relies on hibernate-validator 4.1.0.Final: https://github.com/gwtproject/gwt/blob/5cbb0ff4823f76512a3bb0e91624e393a4def65f/user/build.xml#L120-L124
The patch upgrading to 4.3.2.Final was never merged: https://gwt-review.googlesource.com/9320

**Comment by tbroyer** [comment]
Bean Validation support is now officially deprecated: http://www.gwtproject.org/release-notes.html#Release_Notes_2_8_0_RC1

**Comment by ans1genie** [comment]
Any workaround or a migration guide for the gwt-validation dependcy?

**Comment by dnouls** [comment]
Take a look at this replacement:
https://github.com/ManfredTremmel/gwt-bean-validators
