### ISSUE TITLE
Compiling with GWT 2.7.0 much much slower (3x) than with GWT 2.6.1

### ISSUE THREAD

**Issue by dankurka** [gwtproject/gwt#8960]
Originally reported on Google Code with ID 9006
```
Issue: Compiling with GWT 2.7.0 much much slower (3x) than with GWT 2.6.1.  


Found in GWT Release (e.g. 2.4.0, 2.5.1, trunk):
2.7.0 RC1 and 2.7.0


Encountered on OS / Browser (e.g. WinXP, IE9, FF10):
I am compiling on a Dell Precision 6600 (quad core i7, SSD, 16 GB RAM) with Windows
7.  


Detailed description:
Compiling with GWT 2.6.1 takes about 5 minutes (285 seconds).

Compiling with GWT 2.7.0 takes about 15 minutes (903 seconds).  It takes over 13 minutes
to get to the point where the permutations are being compiled, so most of the time
is spent computing all possible rebind results.


Shortest code snippet which demonstrates issue (please indicate where
actual result differs from expected result):
n/a


Workaround if you have one:
none


Links to relevant GWT Developer Forum posts:
n/a


Link to patch posted at http://gwt-review.googlesource.com
n/a

```

Reported by `marc.durand` on 2014-11-20 15:24:11

**Comment by HelmutReichhold** [comment]
I haven't seen any progress related to the SDM fix. Since Chrome is dropping classic DevMode support in the next version, I get a bit nervous...

**Comment by rluble** [comment]
I have a tentative patch that addresses the code path shown in the stack traces above: https://gwt-review.googlesource.com/13953 

Can someone try it and confirm whether it fixes the problem or not.

**Comment by HelmutReichhold** [comment]
Hi Roberto,
This patch fixes my issues. Thank you very much :-)

**Comment by anton-tregubov** [comment]
Hi Roberto,
This patch make better only project with many JSNI methods. Other project still start SDM longer then 100 000 ms

**Comment by gkdn** [comment]
Please open another bug with details if the you see other performance problems.

**Comment by uhurusurfa** [comment]
Using the G1GC garbage collector on OSX made a big difference for me
