### ISSUE TITLE
SDM: Streamline logging output. Native stack traces should always be logged by Logger and GWT.log

### ISSUE THREAD

**Issue by dankurka** [gwtproject/gwt#8998]
Originally reported on Google Code with ID 9046
```
Found in GWT Release (e.g. 2.4.0, 2.5.1, trunk):

2.7. / trunk

Detailed description (please be as specific as possible):

Chrome 40+ applies source maps to stack traces if the native stack trace will be logged.
To get native stack traces out of GWT you currently have to avoid inheriting Logging/LoggingDisabled
but still use Logger to log the exception. However this actually does not work because
of issue 9045

Even if it would work, the cause chain of an exception is currently missing from the
log output. GWT.log() does not support native stack traces at all.

Ideally GWT.log() and java.util.logging.Logger should behave the same in SDM regardless
of inherits.
```

Reported by `jens.nehlmeier` on 2014-12-08 22:34:50

**Comment by timeu** [comment]
Will this be fixed for 2.8 ? 
As far as I can tell the patch was merged into trunk some while ago

**Comment by jnehlmeier** [comment]
Yes, all the logging improvements are in 2.8-beta1. Doesn't it work for you?

**Comment by gkdn** [comment]
It seems like we forgot to close the bug. Please create new issues if you see a problem with GWT 2.8 beta.

**Comment by timeu** [comment]
Great thanks for clarifying !
I haven't really tried it with 2.8 but I stumbled over the issue in a project that still is on 2.7 and I wasn't sure if this is made it into 2.8
