### ISSUE TITLE
InterfaceGenerator should support CSS3 and GSS

### ISSUE THREAD

**Issue by dankurka** [gwtproject/gwt#9105]
Originally reported on Google Code with ID 9171
```
Found in GWT Release (e.g. 2.4.0, 2.5.1, trunk):

2.7.0


Detailed description (please be as specific as possible):

The InterfaceGenerator tool for generating CssResource interfaces from CSS files is
still using the old Flute parser and thus does not support CSS3 or GSS syntax.


Links to relevant GWT Developer Forum posts:

https://groups.google.com/d/msg/google-web-toolkit/NapIhY6luE0/ISkUEAcFs5kJ
```

Reported by `atomknight033197` on 2015-04-03 00:31:56

**Comment by gkdn** [comment]
@jDramaix if it is a very quick fix, please submit a patch, otherwise let's remove it from 2.8 milestone.

**Comment by jDramaix** [comment]
I think it's an half day task. If I found some hours this weekend, I'll give it a try. Otherwise I'll remove the 2.8 milestone.
I guess as the old syntax is now officially deprecated the tool doesn't have to support it ?

**Comment by gkdn** [comment]
Yes, the tool only needs to support GSS.

**Comment by gkdn** [comment]
(BTW, this is not urgent, you don't need to look at this at the weekend)

**Comment by jDramaix** [comment]
easier than what I thought
https://gwt-review.googlesource.com/#/c/14090/

**Comment by gkdn** [comment]
Ping.

**Comment by jDramaix** [comment]
The patch is there https://gwt-review.googlesource.com/#/c/14090/ waiting for review and +2
