### ISSUE TITLE
Script base discovery in nocache.js doesn't work with native HTML imports

### ISSUE THREAD

**Issue by dankurka** [gwtproject/gwt#9109]
Originally reported on Google Code with ID 9179

```
Found in GWT Release (e.g. 2.4.0, 2.5.1, trunk): 2.8.0-SNAPSHOT

Encountered on OS / Browser (e.g. WinXP, IE9, FF10): Chrome Version 41.0.2272.118 (64-bit)

None of the path resolution strategies in computeScriptBase() in the nocache.js loader
can deal with a location inside an imported document. This is a problem on Chrome,
which supports native HTML imports, not on Firefox where this is polyfilled.

In index.html:

<link rel="import" href="/somepath/somefile.html">

In somefile.html:

<script src="MyModule/MyModule.nocache.js"/>

The calculated resource base is always empty, it should be "/somefile/MyModule/".

Any workaround with base/meta tags won't work if you have several modules.
```

Reported by `christian.bauer` on 2015-04-12 22:30:16

**Comment by niloc132** [comment]
Closing, HTML imports (along with the rest of "v0 web components")  were never implemented by any browser other than Chrome, and Chrome deprecated them in 2018, entirely removed by 2020.

References:
https://stackoverflow.com/a/56614877/860630
https://groups.google.com/a/chromium.org/g/blink-dev/c/h-JwMiPUnuU/m/sl79aLoLBQAJ
https://chromestatus.com/feature/5144752345317376
https://developer.chrome.com/blog/web-components-time-to-upgrade
