### ISSUE TITLE
Argument annotated with @JsFunction should not be inlined

### ISSUE THREAD

**Issue by lorenzosim** [gwtproject/gwt#9144]
If a parameter of a method is annotated with @JsFunction, it shouldn't be inlined.
Suppose for example you have the following class:

```java
@JsType
@JsExport
public class A {
  @JsFunction
   public interface Callback {
     void call();
   }

   public void foo(Callback c) {
     c.call();
   }  
}
```

And only one implementation of the function like so:

```java
@JsType
@JsExport
public class B {
  public String x;

  public void bar() {
    A a = new A();
    a.foo(new A.Callback() {
    	public void call() {
          x = "Hello there!";
        }
    });
  }
}
```

The compiler is inlining the only implementation, but it shouldn't since calls could come from native JS.

**Comment by gkdn** [comment]
You mean foo method is inlined at a.foo line? That should be fine as long as the original is not deleted.

**Comment by gkdn** [comment]
Ok, I talked with @rluble. The real issue is not inlining but type tightening types that may be implemented by javascript (including JsType's as well).

**Comment by gkdn** [comment]
(should be fixed in trunk)
