### ISSUE TITLE
Error in gwt-2.8.0-SNAPSHOT when compiling multiple modules

### ISSUE THREAD

**Issue by smitzkus** [gwtproject/gwt#9155]
Hi,

just upgraded my gwt project to gwt-2.8.0-SNAPSHOT and Java 8. I use maven and the gwt-maven-plugin for building. The plugin is configured to compile two modules:

```javascript
<build>
  <plugins>
    <plugin>
      <groupId>org.codehaus.mojo</groupId>
      <artifactId>gwt-maven-plugin</artifactId>
      <version>2.8.0-SNAPSHOT</version>
      <configuration>
        <modules>
          <module>de.hausbank.kautionen.Kautionen</module>
          <module>de.hausbank.kautionen.changepasswd.Changepasswd</module>
        </modules>
        ...
      </configuration>
    </plugin>
  </plugins>
</build>
```
Here is the maven output:
```
[INFO]    Compiling 8 permutations
[INFO]       Compiling permutation 2...
[INFO]       Process output
[INFO]          Compiling
[INFO]             Compiling permutation 3...
[INFO]       Process output
[INFO]          Compiling
[INFO]             Compiling permutation 0...
[INFO]       Process output
[INFO]          Compiling
[INFO]             Compiling permutation 1...
[INFO]       Compiling permutation 4...
[INFO]          Compiling
[INFO]             Compiling permutation 5...
[INFO]          Compiling
[INFO]             Compiling permutation 6...
[INFO]          Compiling
[INFO]             Compiling permutation 7...
[INFO]    Compile of permutations succeeded
[INFO]    Compilation succeeded -- 221,414s
[INFO] Linking into E:\workspaces\eclipse-jee-mars-R-win32-x86_64\kautionen-parent\kautionen-web-client\target\gwt-generated\kautionen
[INFO]    Link succeeded
[INFO]    Linking succeeded -- 3,665s
[INFO] Compiling module de.hausbank.kautionen.changepasswd.Changepasswd
[INFO]    Compiling 8 permutations
[INFO]       Compiling permutation 3...
[INFO]       [ERROR] Unexpected internal compiler error
[INFO] java.lang.NullPointerException
[INFO] 	at com.google.gwt.dev.jjs.ast.JTypeOracle.recomputeAfterOptimizations(JTypeOracle.java:1072)
[INFO] 	at com.google.gwt.dev.jjs.JavaToJavaScriptCompiler.optimizeJavaOneTime(JavaToJavaScriptCompiler.java:1504)
[INFO] 	at com.google.gwt.dev.jjs.JavaToJavaScriptCompiler.optimizeJavaToFixedPoint(JavaToJavaScriptCompiler.java:1447)
[INFO] 	at com.google.gwt.dev.jjs.JavaToJavaScriptCompiler.optimizeJava(JavaToJavaScriptCompiler.java:495)
[INFO] 	at com.google.gwt.dev.jjs.JavaToJavaScriptCompiler.compilePermutation(JavaToJavaScriptCompiler.java:353)
[INFO] 	at com.google.gwt.dev.jjs.JavaToJavaScriptCompiler.compilePermutation(JavaToJavaScriptCompiler.java:268)
[INFO] 	at com.google.gwt.dev.CompilePerms.compile(CompilePerms.java:198)
[INFO] 	at com.google.gwt.dev.ThreadedPermutationWorkerFactory$ThreadedPermutationWorker.compile(ThreadedPermutationWorkerFactory.java:50)
[INFO] 	at com.google.gwt.dev.PermutationWorkerFactory$Manager$WorkerThread.run(PermutationWorkerFactory.java:74)
[INFO] 	at java.lang.Thread.run(Thread.java:745)
[INFO]       [ERROR] Unrecoverable exception, shutting down
[INFO] com.google.gwt.core.ext.UnableToCompleteException: (see previous log entries)
[INFO] 	at com.google.gwt.dev.javac.CompilationProblemReporter.logAndTranslateException(CompilationProblemReporter.java:112)
[INFO] 	at com.google.gwt.dev.jjs.JavaToJavaScriptCompiler.compilePermutation(JavaToJavaScriptCompiler.java:432)
[INFO] 	at com.google.gwt.dev.jjs.JavaToJavaScriptCompiler.compilePermutation(JavaToJavaScriptCompiler.java:268)
[INFO] 	at com.google.gwt.dev.CompilePerms.compile(CompilePerms.java:198)
[INFO] 	at com.google.gwt.dev.ThreadedPermutationWorkerFactory$ThreadedPermutationWorker.compile(ThreadedPermutationWorkerFactory.java:50)
[INFO] 	at com.google.gwt.dev.PermutationWorkerFactory$Manager$WorkerThread.run(PermutationWorkerFactory.java:74)
[INFO] 	at java.lang.Thread.run(Thread.java:745)
[INFO]       [ERROR] Not all permutation were compiled , completed (0/8)`
```

As you can see, the first module compiles without errors, then an unexpected internal compiler error occures. If i comment out the first module, the second compiles without problems.

**Comment by smitzkus** [comment]
One more thing: the first module ('Kautionen') is quite big, the second ('Changepasswd') very small. The compiler-error no longer occurs when i change the order of the modules (first small, then big). Strange...

**Comment by kevinfahy** [comment]
Ran into this today on `2.8.0-beta1` with an identical stack trace (aside from line numbers) as the one @smitzkus posted above.

Our GWT project has 3 modules (first two small, last one large), and the compilation error consistently occurs on the final (large) module when compiling them in sequence. If I compile the last module separately, compilation seems to succeed.

Is there any additional logging information I can grab for you?

**Comment by kevinfahy** [comment]
OK, I was able to work around the issue by converting some JSOs to use JS interop.

From the GWT stacktrace (sorry, I might be very wrong about this), it appears that the compiler tries to reference a JSO with a Java interface, but it's unexpectedly `null` (there is an `assert` for this case). Looking back at our GWT project, it appeared that whenever we compiled a certain module, compiling the subsequent module would always throw the above exception. The module that compiled first happened to have three classes that extended `JavaScriptObject` and implemented one of our interfaces. Switchings all three of these classes to JS interop fixed the issue.

**Comment by tbroyer** [comment]
@rluble Looks like bad isolation between compilations. Should we just remove the ability to compile multiple modules at once? (force people to invoke the GWT compiler once per module, separately) Or you have an idea where state could leak between compilations and cause those errors?

FWIW, the error apparently is at https://github.com/gwtproject/gwt/blob/cd8e225e556bb36d929661da3fd1b21409e69acd/dev/core/src/com/google/gwt/dev/jjs/ast/JTypeOracle.java#L880, where `implementor` is `null`. This happens before `Pruner` is called, and could `setInstantiatedTypes`: https://github.com/gwtproject/gwt/blob/be51acf6ca4b83452ab7a23c70f202b706e0ba12/dev/core/src/com/google/gwt/dev/jjs/JavaToJavaScriptCompiler.java#L1526

**Comment by rluble** [comment]
Limiting to one module per compiler invocation seems reasonable to me.

**Comment by jonl-percsolutions-com** [comment]
If this limit is imposed, would it break running multiple modules in super dev mode?

**Comment by tbroyer** [comment]
That's a good question! Technically, we could limit it only for the compiler, but it raises a interesting question: how does SDM behave when launched with several modules, for those projects that fail to compile several modules at a time?

**Comment by ismagilov** [comment]
A couple of months passed since I had faced the issue. But as far as I remember, SDM worked without any problems when launched with several modules.

**Comment by ozguraydinli** [comment]
I have the same issue, but if I use draftCompile=true it works fine with multiple modules.

**Comment by niloc132** [comment]
See linked issue for an extremely minimal test case that demonstrates this problem.

**Comment by rluble** [comment]
This is an unintended consequence of incremental compile (SDM). SDM multimodule recompiles are explicitly managed (in codeserver/.../Recompiler), so limiting for one module in dev.Compiler should not affect SDM. That being said the fix in dev.Compiler should be easy to do as well. The problem seems to be that the instance of MinimalRebuildCache is shared between modules in dev.Compiler but it should not be.

**Comment by rluble** [comment]
Fix is up for review: https://gwt-review.googlesource.com/#/c/14780
