### ISSUE TITLE
Math.rint is very slow and needs to be translated to JS Math.round

### ISSUE THREAD

**Issue by kirillp** [gwtproject/gwt#9156]
Found in GWT Release 2.7, trunk
Encountered on OS / Browser (e.g. WinXP, IE9, FF10): All

Detailed description (please be as specific as possible):

Math.rint is very slow. 
This happens because it goes via slow code path and unnecessary conversion via long (call to "long round(double)", long is not supported natively by JS and is emulated in an complex and heavy way )

Shortest code snippet which demonstrates issue (please indicate where
actual result differs from expected result): call to Math.rint

patch:

```javascript
+  public static native double rint(double x) /*-{
+   return Math.round(x);
+  }-*/;

-  public static double rint(double d) {
-    if (Double.isNaN(d)) {
-      return d;
-    } else if (Double.isInfinite(d)) {
-      return d;
-    } else if (d == 0.0d) {
-      return d;
-    } else {
-      return round(d);
-    }
-  }

```

**Comment by kirillp** [comment]
copy of https://code.google.com/p/google-web-toolkit/issues/detail?id=9224#makechanges

**Comment by kirillp** [comment]
The latest JDK documentation says:

Returns the double value that is closest in value
     to the argument and is equal to a mathematical integer. If two
     double values that are mathematical integers are
     equally close, the result is the integer value that is
     even.

So that is what JS Math.round does.

**Comment by tbroyer** [comment]
> So that is what JS Math.round does.

No.

```
> Math.round(4.5)
5
> Math.round(3.5)
4
```

`Math.rint(4.5)` in Java would return `4.0`, not `5.0` (“If two double values that are mathematical integers are equally close, the result is the integer value that is even”)

But the current implementation/emulation is already inaccurate as it delegates to `round()`, and making it accurate would probably be too costly at runtime (probably the reason it's done that way currently).

**Comment by kirillp** [comment]
Suggested change will significantly speed-up current code.

**Comment by tbroyer** [comment]
https://gwt-review.googlesource.com/14560
