### ISSUE TITLE
Deployment Assembly Omitting Maven Dependencies with m2e-wtp 1.2.0

### ISSUE THREAD

**Issue by averigin** [gwtproject/gwt#9160]
The current release of the Google plugin for Eclipse appears to be incompatible with version 1.2.0 of the m2e-wtp plugin [which is required by version 1.6.x of the m2e plugin](https://bugs.eclipse.org/bugs/show_bug.cgi?id=438593). This will cause problems for Eclipse Mars users since it comes with m2e 1.6.1 and m2e-wtp 1.2.0 by default.

With m2e 1.6.1 and m2e-wtp 1.2.0 installed, running "Maven -> Update Project" adds a "Maven Dependencies" entry to my project's Deployment Assembly. However, as soon as I install the Google Plugin for Eclipse 4.4 (3.8.0.v201410302155-rel-r44), running "Maven -> Update Project" now removes the "Maven Dependencies" entry from the Deployment Assembly. This causes things to break in my normal web projects when I try to run them on Tomcat via "Run -> Run on Server".

I can manually re-add the "Maven Dependencies" entry to the Deployment Assembly, but as soon as I re-run "Maven -> Update Project" it disappears again. My interim solution: if use Eclipse Luna running m2e 1.5.2, m2e-wtp 1.1.0 and the Google plugin for Eclipse 4.4, everything works.

The minimal steps to reproduce this:
1. Start with a clean Eclipse Mars install.
2. Create a "Maven Project" (e.g., using the `maven-archetype-webapp` archetype).
3. Run "Maven -> Update Project".
4. Check the Deployment Assembly. It should contain the "Maven Dependencies" entry.
5. Install the Google Plugin for Eclipse 4.4 ([link](https://dl.google.com/eclipse/plugin/4.4)).
6. After restarting Eclipse, run "Maven -> Update Project".
7. Check the project's Deployment Assembly. It should no longer contain the "Maven Dependencies" entry.

**Comment by tbroyer** [comment]
The Google Plugin for Eclipse project is at https://code.google.com/p/google-plugin-for-eclipse/
with a fork at https://github.com/gwt-plugins/gwt-eclipse-plugin
