### ISSUE TITLE
History newItem for URL with Arabic characters

### ISSUE THREAD

**Issue by sameeh-harfoush** [gwtproject/gwt#9162]
when using History.newItem for a URL with arabic characters, the method nativeUpdate in HistoryImpl class is encoding the fragment:

protected native void nativeUpdate(String historyToken) /*-{
    $wnd.location.hash = this.@com.google.gwt.user.client.impl.HistoryImpl::encodeFragment(Ljava/lang/String;)(historyToken);
  }-*/;

the encodeFragment is encoding the arabic characters causing an ugly and unreadable URL
for example:
www.mydomain.com#!/ar/بنك-عوده-المزرعة-بيروت/b-4531

is encoded to:

www.mydomain.com#!/ar/%D8%A8%D9%86%D9%83-%D8%B9%D9%88%D8%AF%D9%87-%D8%A7%D9%84%D9%85%D8%B2%D8%B1%D8%B9%D8%A9-%D8%A8%D9%8A%D8%B1%D9%88%D8%AA/b-4531

URL encoding should be removed or managed in different way

**Comment by tbroyer** [comment]
This is now configurable: c6f95d83ec59c1562e6d63a16bbca1a32abd0cb6

```xml
<set-property name="history.noDoubleEncoding" value="true" />
```

Note however that this might break in some browser. As the comment in `History.gwt.xml` says, you're then responsible for using only tokens that work across browsers.

**Comment by sameeh-harfoush** [comment]
thank you for the reply.

i tried it but it didnt work. below is my gwt.xml file. 
Note that i am using GWT 2.7.0

Any ideas what i might be doing wrong?

```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE module PUBLIC "-//Google Inc.//DTD Google Web Toolkit 2.7.0//EN" "http://google-web-toolkit.googlecode.com/svn/tags/2.7.0/distro-source/core/src/gwt-module.dtd">
<module rename-to="home">
	<inherits name="com.google.gwt.user.History" />
	<inherits name="com.brate.common.CommonMdl" />		

	<entry-point class="com.brate.home.client.HomeMdl" />

	<source path="client" />
	<source path="shared" />

	<extend-property name="locale" values="en" />
	<extend-property name="locale" values="ar" />
	<extend-property name="locale" values="fr" />
	<set-property-fallback name="locale" value="en" />
	
	<define-property name="history.noDoubleEncoding"
		values="true,false" />
	<set-property name="history.noDoubleEncoding" value="true" />

	<replace-with
		class="com.google.gwt.user.client.History.NoopHistoryTokenEncoder">
		<when-type-is class="com.google.gwt.user.client.History.HistoryTokenEncoder" />
		<when-property-is name="history.noDoubleEncoding"
			value="true" />
	</replace-with>
</module>
```

**Comment by tbroyer** [comment]
All you'd need is the `<set-property>` line I posted above; but this is only in _master_ for now (2.8.0-SNAPSHOT).

In GWT 2.7 you'd have to provide your own `HistoryImpl` implementation.

**Comment by sameeh-harfoush** [comment]
ok thank you
