### ISSUE TITLE
Generic to boolean conversion crashes compiler

### ISSUE THREAD

**Issue by stepancheg** [gwtproject/gwt#9169]
```
    private static native void foo(boolean b) /*-{
        console.log(b);
    }-*/;

    private static native <A> A bar() /*-{
        return true;
    }-*/;

    private static void baz() {
        foo(bar());
    }
```

Error is this: https://gist.github.com/stepancheg/fa0cfb6d94183e517352
Browser Chrome.
GWT 2.8.0-20150717.
superdevmode.

**Comment by stepancheg** [comment]
Anybody there? That `NullPointerException` is super annoying.

**Comment by cromwellian** [comment]
I pasted all three of those directly into BooleanTest.java and ran it with
sourceLevel 1.8, with and without draftCompile, and it worked. Are you
super-sourcing java/lang/Boolean by any chance?

**Comment by stepancheg** [comment]
I cannot reproduce it either now, although I see similar exceptions a lot.

I've found that many problems disappear if you just remove $TMPDIR/gwt* directories and/or restart superdevmove script.

It must be a bug in incremental compiler. I've reported a similar issue #9163, which is still reproducible.
