### ISSUE TITLE
Add JSON Support to Editor framework

### ISSUE THREAD

**Issue by mohammadmasoomi** [gwtproject/gwt#9170]
this issue reported in https://github.com/gwtproject/gwt/issues/8770
I commented on reason of dankurka,
Editor framework map a java bean to form, I want to map JSONObject To a form,
I do not user POJO,
Sample code is
public class OurView extends Composite implements Editor<JSONObject> {
        
        private static OurJSONEditorDriver driver = GWT.create(OurJSONEditorDriver.class);

        public interface OurJSONEditorDriver extends JSONEditorDriver<JSONObject, OurView> {
        }

        public OurView() {
            driver.initialize(this);
            driver.edit(new JSONObject());
        }
        
        public void printForm(){
            //this line return JSONObject instead bean
/*line 15*/      JSONObject object = driver.flush();
            Window.alert(object.toString());
        }
    }

notice to line 15

**Comment by tbroyer** [comment]
This is not going to happen.

The Editor framework is based on static analysis mapping bean-like properties to editors, and failing if there's a mismatch in either name or type. This kind of analysis cannot be conducted when the input is a map-like object.

You have two options:

* create overlay types (JavaScriptObject) or use the incubating JsInterop to make the static analysis possible (it can still fail at runtime depending on your input)
* fork the Editor framework to allow such mapping (or find a 3rd party library that does it already)

**Comment by mohammadmasoomi** [comment]
thanks thomas

On Sun, Aug 16, 2015 at 4:14 AM, Thomas Broyer <notifications@github.com>
wrote:

> This is not going to happen.
>
> The Editor framework is based on static analysis mapping bean-like
> properties to editors, and failing if there's a mismatch in either name or
> type. This kind of analysis cannot be conducted when the input is a
> map-like object.
>
> You have two options:
>
>    - create overlay types (JavaScriptObject) or use the incubating
>    JsInterop to make the static analysis possible (it can still fail at
>    runtime depending on your input)
>    - fork the Editor framework to allow such mapping (or find a 3rd party
>    library that does it already)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/gwtproject/gwt/issues/9170#issuecomment-131469863>.
>



-- 
با احترام - محمد معصومی
