### ISSUE TITLE
NodeFilter in Browser.getDocument().createTreeWalker() not recognized

### ISSUE THREAD

**Issue by hpehl** [gwtproject/gwt#9171]
The GWT Elemental version of [Document.createTreeWalker()](https://developer.mozilla.org/en-US/docs/Web/API/Document/createTreeWalker) doesn't support a NodeFilter.

I'm using the following code to replace [handlebar](handlebarsjs.com) like expressions in text nodes:

``` java
public static void replaceHandlebar(Element context, String expression, String value) {
    TreeWalker treeWalker = Browser.getDocument().createTreeWalker(context, NodeFilter.SHOW_TEXT,
            node -> {
                if (node.getNodeValue() != null && node.getNodeValue().contains(expression)) {
                   return NodeFilter.FILTER_ACCEPT;
                }
                return NodeFilter.FILTER_SKIP;
            }, false);

    while (treeWalker.nextNode() != null) {
        String currentValue = treeWalker.getCurrentNode().getNodeValue();
        String newValue = currentValue.replace(expression, value);
        treeWalker.getCurrentNode().setNodeValue(newValue);
    }
}
```

However running the above code gives me

```
Uncaught TypeError: Failed to execute 'nextNode' on 'TreeWalker': NodeFilter object does not have an acceptNode function
```

When I remove the NodeFilter lambda and filter the text nodes manually the code works though.

**Comment by hpehl** [comment]
Any update on this?

**Comment by tbroyer** [comment]
Elemental 1 is a "to the metal" library, so the `NodeFilter` that's passed in must be, in JS, an object that exposes a (JS) `acceptNode` method. This won't be the case of a Java class simply implementing the interface, unless you somehow use JsInterop on it (but then, it's not applicable to lambdas or anonymous classes).
AFAICT, Elemental 2, based on JsInterop, should make things better (automatically declaring a `callback interface` with a single method, or a `callback function`, in IDL as a Java interface annotated with `@JsFunction` and `@FunctionalInterface`). I'm not sure whether `@JsFunction` support is part of JsInterop v1 though.

/cc @gkdn

**Comment by gkdn** [comment]
I don't know much about how Elemental 1 code generation works but it looks like it doesn't see NodeFilter as a callback. Anyway you can work around this with JsInterop:
'''java
@JsType
class MyNodeFilter implement NodeFilter {
  public short acceptNode(elemental.dom.Node n) { ... };
}
```
(Don't forget to enable JsInterop.)

@tbroyer: @JsFunction is available in master and will be part of v1.

**Comment by tbroyer** [comment]
Elemental 1 is deprecated, won't receive fixes.
