### ISSUE TITLE
WhenTypeAnnotatedWith condition <when-annotated with='x.y.z'/>

### ISSUE THREAD

**Issue by BenDol** [gwtproject/gwt#9172]
So I had a use case where I wanted to invoke a generator on classes annotated with a particular Annotation. So I thought I'd propose the idea here a long with submitting my patch that I have tested.

Is this a good idea? It worked well for my situation and unless there is a better solution for something like this it could work.

Submitted patch: https://gwt-review.googlesource.com/#/c/13330/

**Comment by tbroyer** [comment]
The future direction of GWT is rather to deprecate/remove deferred binding and move to annotation processing and explicit if/else in code, so I'm not sure this change is really worth it if it only lasts a single release…

**Comment by BenDol** [comment]
Could serve a purpose until the annotation processing is implemented then perhaps?

**Comment by jnehlmeier** [comment]
@BenDol Why haven't you implemented your GWT generator as Annotation Processor if it should trigger on annotations? I don't think we should add something to GWT which is already covered by a standard Java mechanism. 
You would need convert your GWT generator to an annotation processor anyways if you want to be compatible with GWT 3.0.

Also if this change would get merged then people might start writing GWT generators that trigger on annotation with the assumption that they can probably easily be converted to an annotation processor later. But if these GWT generators start to depend on GWT's type information then it might get a lot tougher if not impossible (e.g. "give me all implementations of interface X" is easy in GWT, but you would never ask that with annotation processors).

So overall I would tend to give a -1 for that change and instead you should convert your generator to be an annotation processor.

**Comment by BenDol** [comment]
I already have it as an annotation processor, for what I'm doing. But I don't want to use auto generated classes for my applications Model's since it has persistence information that changes a lot and I would feel a little uncomfortable relying on server/client auto generated class. The generator basically extends and writes setters/getters containing databinding "signals" in your custom classes (in my case Models). So you can bind data to UI components etc. I was thinking if I do this in GWT having it done as a generator would simply treat the model class as its original type (less boiler-plate, etc). The library I'm writing it against uses annotations for its annotation processor so I wanted to mimic it client side with GWT to keep it simple.

Anyway if this is a bad idea that is fine, I'm by no means an expert with GWT generators. Was just going to submit this as an idea since it solved a problem for me, so with that said I would still like to see it. Thanks for the reply.

**Comment by BenDol** [comment]
Also the generator I wrote is actually line for line the same as the annotation processor that was written for it originally, only difference is when GWT compiles it to JS it can retain its type as well as the databind setters/getters. I had no trouble with the type information differences.

**Comment by BenDol** [comment]
@tbroyer bare in mind what this resolved for me was a problem that I had due to the fact that it was annotation processing already. I needed more for the GWT layer than just the generated source, I actually wanted the generated source to become the "same" type as another. So because the annotation processor already processed these classes it was highly convenient for me to have a condition setup for `when-type-annotated`.

So in my case annotation processing didn't replace the solution for me, I wanted to take it that extra step in the GWT implementation to simplify my code boilerplate.

**Comment by BenDol** [comment]
Is this going to be a considered addition? I has made my life easier and why not is the better question I think. If you are interested in how I have ended up using it to solve a problem for me:
 
https://youtu.be/chkep16dN-I?t=7m30s 

Can also check the repository:
* [HexaBinding.gwt.xml](https://github.com/ltearno/hexa.tools/blob/master/hexa.binding.gwt/src/main/java/fr/lteconsulting/hexa/HexaBinding.gwt.xml)
* [ObservableGenerator.java](https://github.com/ltearno/hexa.tools/blob/master/hexa.binding.gwt/src/main/java/fr/lteconsulting/hexa/databinding/gwt/rebind/ObservableGenerator.java)

The observable objects are being created by this annotation processor: 
* [ObservableAnnotationProcessor.java](https://github.com/ltearno/hexa.tools/blob/master/hexa.binding/processor/src/main/java/fr/lteconsulting/hexa/databinding/annotation/processor/ObservableAnnotationProcessor.java)
* [GwtObservableAnnotationProcessor.java](https://github.com/ltearno/hexa.tools/blob/master/hexa.binding/processor/src/main/java/fr/lteconsulting/hexa/databinding/gwt/annotation/processor/GwtObservableAnnotationProcessor.java)

Would be great to have this feature implemented so I don't need to extend this in my own classpath :+1: Thanks!

**Comment by jnehlmeier** [comment]
@BenDol With GWT 3.0 the `Settings.newInstance()` factory method in the video will not work anymore because GWT.create() will be gone. So the solution would only work for a single GWT release. To be future proof the factory method should return `new ObservableSetting(....)`.

IMHO using a factory method on your model is the best way to decouple the generated code from your project. AutoValue made by Google does the same, see https://github.com/google/auto/tree/master/value#in-examplejava

Then all your code only deals with MyModel and doesn't care about generated classes that extend MyModel and implement some details.

**Comment by tbroyer** [comment]
+1 to what @jnehlmeier said. And if you want to go one extra step, you can also have an annotation processor generate a `SettingsFactory` with a static factory method that does the `GWT.isClient()` check, so your `Settngs.newInstance()` can just call the generated `SettingsFactory.newInstance()`.

@dankurka or @rluble want to weigh in before I close this request?

**Comment by dankurka** [comment]
Exactly what @jnehlmeier  and @tbroyer said. Please do not use GWT generators anymore start using APTs instead.

For checking if you are running in GWT or in a JVM you can also use System.getProperty which gives you access to binding properties.
