### ISSUE TITLE
Pruning methods of class instances that were used by casted Object 

### ISSUE THREAD

**Issue by bertung** [gwtproject/gwt#9181]
The class instances that are passed to a generated method by Object reference get their methods pruned when inside the generated method even though all of the methods are referenced in the method. The instance is casted to its real Class inside the generated code then all of the methods are referenced inside the generated method as said above. Compiler insist on pruning all the methods.

    public class MyBean {
        private name;
        public void setName(name) {
            this.name=name;
        }

        public String getName() {
           return name;
        }
    }

Generator generated method;

    public setBeanProperty(Object target, String property, Object value) {
        MyBean myBean=(MyBean)target;
        if(property.equals("name") {
            myBean.setName((String)value);
        }
    }

    public Object getBeanProperty(Object target, String property) {
        MyBean myBean=(MyBean)target;
        if(property.equals("name") {
            return myBean.getName();
        }
       return null;
    }

Both getProperty and setProperty methods are used in the code, the methods of MyBean are pruned and I get undefined errors on setName and getName calls. Am I missing something? is there a hack to work around this? is it a bug?

**Comment by bertung** [comment]
Is there any compile time annotation to tell compiler not to prune such as
    
    @DisablePruning
    public class MyBean {
        private name;
        public void setName(name) {
            this.name=name;
        }

        public String getName() {
           return name;
        }
    }

I still need the optimization set to factor 9, and -draftcompiler is not an option.

**Comment by rluble** [comment]
The methods get devirtualized because the method calls can be resolved statically. If you want to preserve the API for external callers then use JsInterop. In this case you can annotate the methods as @JsMethod and pass -generateJsInteropExports and that would not only preserve the instance methods but also preserve their names.
