### ISSUE TITLE
gwt-dev included apache httpclient library should be rolled forward

### ISSUE THREAD

**Issue by tflinz** [gwtproject/gwt#9185]
The packaged version of the apache httpclient library is 4.3.1, which doesn't work with SNI, which means that other libraries that use the apache httpclient to do https will sometimes fail. (unless they've happened to be included prior to gwt-dev in the pom.xml).

(see http://stackoverflow.com/questions/32341729/apache-http-client-defaults-dont-work-with-sni/32362975#32362975)

**Comment by slavap** [comment]
Does it work if you specify <scope>provided</scope> for gwt-dev in your pom.xml?

**Comment by tflinz** [comment]
That is what I had originally (though I left it out of the question on stackoverflow so as not to muddy the waters).

**Comment by slavap** [comment]
Actually it means that behavior is different in dev/superdev mode, and production war. Because gwt-dev WON'T be included into resulting war if provided scope is defined.

**Comment by tflinz** [comment]
fair enough.
we were noticing major issues within our integration/unit tests, so I guess that would make sense.

regardless, I think it would still be warranted to bump forward the packaged version, no?

**Comment by slavap** [comment]
It's almost always a good idea to update dependencies to more actual stable version.
