### ISSUE TITLE
RichTextArea: Automatically add <p> tag once paste the text from MS Word

### ISSUE THREAD

**Issue by ndkhoiits** [gwtproject/gwt#9186]
I'm trying to copy text from MS Word to RichTextArea, it works well except IE9 + Windows 7, if there is nothing on the text area, it automatically appends new `<p>` tag between each line, however if I select all the text, and paste (replace actually), the format is good. If I clear everything on that area, and paste the text from MS word, the error appears again.

Please help to check, I tried on the showcase page http://samples.gwtproject.org/samples/Showcase/Showcase.html#!CwRichText

**Comment by tbroyer** [comment]
See #5098
