### ISSUE TITLE
instanceof evaluates to undefined for string values with -draftCompile

### ISSUE THREAD

**Issue by Legioth** [gwtproject/gwt#9187]
This test fails if compiled with -draftCompile, or if running the corresponding code i SDM. 

    public void testInstanceof() {
        Object value = "asdf";
        assertEquals("false", (value instanceof Integer) + "");
    }

**Comment by cromwellian** [comment]
Is this related to the autoboxing CL, or was it always like this?

**Comment by cromwellian** [comment]
Leaf, I tried this test in IntegerTest.java with -web -draftCompile and it succeeded. is this the case for you?

 public void testInstanceOf() {
    Object value = "asdf";
    assertEquals("false", (value instanceof Integer) + "");
  }

**Comment by Legioth** [comment]
I'm seeing this in at least two different projects, one using GWT 2.7 and one with a 2.8 snapshot from last week (used to avoid the recent issue with `JsJsonBoolean.getType()`). It doesn't seem to happen with the latest snapshot.

It turns out -draftCompile is only needed to prevent inlining. The problem reproduces without -draftCompile with this small modification:
        Object[] values = { "asdf" };
        assertEquals("false", (values[0] instanceof Integer) + "");

**Comment by Legioth** [comment]
It could very well be that this has "always" been broken, since instanceof is usually used in a boolean context where `undefined` has the same effect as the expected `false`. I only discovered this when doing something like `if (value instanceof Integer == integerExpected) { ... } `. One simple workaround is to use a double negation: `if (!!(value instanceof Integer) == integerExpected) { ... } `.

**Comment by rluble** [comment]
Is this only in SDM?

**Comment by rluble** [comment]
(values[0] instanceof Integer) is translated to Cast.canCast(values[0], Integer_id). Looking at canCast I don't see a reason for it to ever return undefined. 

The implementation slightly changed in f314f148943f8fcc221b9f68a4cf58acf0175172; can you confirm this is still an issue.

**Comment by rluble** [comment]
I think this got fixed by commit 261a009 (Double and Boolean implemented as unboxed raw types).

Before that canCast had the following code

 return @com.google.gwt.lang.Cast::isJavaString(*)(src) &&
         !!@com.google.gwt.lang.Cast::stringCastMap[dstId] ||
        src.@java.lang.Object::castableTypeMap && !!src.@java.lang.Object::castableTypeMap[dstId];

which would return undefined for Strings (return true && false || undefined;).

Marking it as resolved.
