### ISSUE TITLE
Allow GWT to be built as a RPM package

### ISSUE THREAD

**Issue by sandrobonazzola** [gwtproject/gwt#9193]
Originally reported on January 2007 for version 1.3 at https://code.google.com/p/google-web-toolkit/issues/detail?id=625
After 8 years, with version 2.7.0 it's still not possible to package GWT properly without bundling (obsoleted) libraries.
Quoting original report for not requiring to follow the link:
<blockquote>
Detailed description:
For us die-hards who prefer installing everything as RPM, as well as hoping
to see GWT included in the distribution of our choice, it would be great if
a spec file were provided to allow compiling GWT without embedding Mozilla,
Apache and the other dependencies.

I am not sure what is exactly involved in disentangling GWT from its
dependencies, but I think it would be terrific to be able to install it out
of the box using yum, yast or whatever other tool your RPM-based
distribution uses. As a minor bonus, this would also reduce duplication and
decouples GWT updates from security updates of its dependencies.
</blockquote>

**Comment by tbroyer** [comment]
What's needed *exactly* to allow packaging as RPM?

BTW, note that the issue you link to is now #633.

**Comment by sandrobonazzola** [comment]
Closing as duplicate og #633
