### ISSUE TITLE
GWT Compiler Issue - Lost communication Error

### ISSUE THREAD

**Issue by bchoddny** [gwtproject/gwt#9195]
We came across this error in our build machine, recently. The error doesn't explicitly states any specific reason. I would like to find out if any one came across this, and if any resolution. Any help is appreciated

GWT 2.5.0
jdk1.7.25
gwt-maven-plugin 2.5.0

Maven GWT compile configuraiton

```
                            <configuration>
                    <workDir>${gwt.compile.workDir}</workDir>
                    <extraJvmArgs>-Xmx1024m -Djava.io.tmpdir=${gwt.compile.workDir}</extraJvmArgs>
                    <module>net.dds.idesk.financials.gwt.Application</module>
                    <logLevel>TRACE</logLevel>
                    <!-- URL that should be automatically opened in the GWT shell (gwt:run). -->
                    <runTarget>index.html</runTarget>
                    <!-- Location of the develop-mode web application structure (gwt:run). -->
                    <hostedWebapp>target/www</hostedWebapp>
                    <!-- Ask GWT to create the Story of Your Compile (SOYC) (gwt:compile) -->
                    <soyc>false</soyc>
                </configuration>
```

06:00:16 [INFO] [INFO]       Process output
06:00:16 [INFO] [INFO]          Compiling
06:00:16 [INFO] [INFO]             Compiling permutation 3...
06:02:29 [INFO] [INFO]       [WARN] Lost communication with remote process
06:02:29 [INFO] [INFO] java.io.EOFException
06:02:29 [INFO] [INFO]  at java.io.ObjectInputStream$BlockDataInputStream.peekByte(ObjectInputStream.java:2596)
06:02:29 [INFO] [INFO]  at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1316)
06:02:29 [INFO] [INFO]  at java.io.ObjectInputStream.readObject(ObjectInputStream.java:370)
06:02:29 [INFO] [INFO]  at com.google.gwt.dev.ExternalPermutationWorkerFactory$ExternalPermutationWorker.compile(Externa

**Comment by tbroyer** [comment]
Closing as it's probably stale by now.
