### ISSUE TITLE
$stats conflicts with function name

### ISSUE THREAD

**Issue by samskivert** [gwtproject/gwt#9196]
The optimizer ended up turning one of my methods into a top-level function named $stats, which then conflicts with the synthetic $stats var which GWT uses to track statistics.

``` javascript
//...
var $stats = $wnd.__gwtStatsEvent ? function(a) {
return $wnd.__gwtStatsEvent && $wnd.__gwtStatsEvent(a);
} : null;
//...
function $stats(this$static, id_0){
  return $get_2(this$static.statsC, id_0);
}
// ...
```

I can work around it by renaming my stats function, but GWT should probably be working to avoid name collisions with whatever synthetic top-level vars it's injecting.

**Comment by samskivert** [comment]
This is in compile mode PRETTY in case that wasn't obvious.

**Comment by dankurka** [comment]
@rluble This seems like something worth fixing?!

**Comment by rluble** [comment]
As a workaround you can add the set the configuration property js.identifier.blacklist to prevent the namer using this name. It should be a easy one liner fix by addiding $stat to illegalNames in JsProtectedNames.java.

**Comment by tbroyer** [comment]
https://gwt-review.googlesource.com/c/gwt/+/19522
