### ISSUE TITLE
Integer to int: intValue is not a function

### ISSUE THREAD

**Issue by cpboyd** [gwtproject/gwt#9197]
I initially tried this using a JSONObject and got a double value:
object.get("DT").isNumber().doubleValue()

I was then able to typecast the double to an int and use it in a switch statement.

Trying to make my life easier, I decided to use an overlay type with a function:
public final native Integer getDT() /*-{
    return this.DT;
}-*/;

Unfortunately, Java's intValue() function (which is called implicitly for casting from an Integer to an int) doesn't seem to currently be supported by GWT.

Any suggestions?  I'm using the latest GWT 2.8 snapshot.

**Comment by cpboyd** [comment]
Interestingly, if I change the return type of getDT() to "Double", calling intValue() works fine.

**Comment by tbroyer** [comment]
AFAICT, this is the expected behavior (see #4646 for example). It's always been the case that an `Integer` was not an `int`, and that (until very recently) a JS `Number` could be _cast_ into any Java numeric _primitive_ type, but not their “wrapper” variant.
If you want to return a `java.lang.Integer` for a JS number that can be `null`/`undefined`, you have to use something like:
```java
final native Integer getDT() /*-{
  return this.DT == null ? null : @java.lang.Integer::valueOf(I)(this.DT);
}-*/;
```

There's been a change recently on `master` however (e261a009786b4e855da569c257c12f3d838c65ca) that would treat `java.lang`Double` and `java.lang.Boolean` just like `boolean` and `double`; and this is why it works when you use `Double` instead of `Integer`.

**Comment by cpboyd** [comment]
This seems to defeat the purpose of Overlay Types entirely.

I simply want to reference an optional JSON parameter that should be an integer/enum and use it in a switch statement.

I check to see if the Integer is null, before performing the switch statement on it.

Using an integer in a switch statement doesn't seem like an uncommon practice.

However, in Java, switch statements only work with PRIMITIVES, thus the Integer is implicitly forced to return intValue() by the compiler.

**Comment by cpboyd** [comment]
Moreover, your JSNI code still doesn't address the fact that the Java compiler is implicitly calling intValue() on any Integer used in a switch statement.

Basically, I'd have to have two separate JSNI functions: one to check for null and one to return a primitive int.

I suppose I could return a JsNumber and manually call doubleValue() in code, but I thought the point to overlay types was to provide a go-between from a JS Object to a Java Object.

**Comment by tbroyer** [comment]
With my above JSNI method:
```java
Integer i = foo.getDT();
if (i == null) {
  // do something
} else {
  switch (i) {
  // ...
  }
}
```

But 2 JSNI methods returning `boolean` and `int` could perform better (unless the compiler can optimize the `Integer` to similar results).

**Comment by cromwellian** [comment]
Integer is not an overlay type, you cannot convert raw Javascript primitives into Integer by just 'casting' them in JSNI like that. You can only do raw conversions to other Overlay types. Integer is a wrapper type in Java, not a primitive. If you can't do this kind of operation in standard Java, why expect to do it in GWT? You'd always have to construct a wrapper in Java.

Consider there there are no less than 7 types that can be mapped to a primitive Js Number, including every enum subtype. There's no way to maintain runtime information on a 'primitive' to distinguish between them, for example:

public final native Integer getDT() /-{
return this.DT;
}-/;

public final native Enum getDTEnum() /-{
return this.DT;
}-/;

getDT() instanceof Integer (underlying value, primitive JS 42)
getDTEnum() instanceof Enum (underlying value, primitive JS 42)

What Javascript could possibly be emitted to tell that '42' is an Integer and not an Enum with ordinal 42?

The JsInterop spec contains an annotation (currently unimplemented) @JsConvert which would let you create an annotation to auto-wrap the return value, e.g.

interface Foo {
   @JsProperty
   @JsConvert(IntegerWrapper.class)
   Integer getDT();
}

No JSNI needed, the compiler would invoke IntegerWrapper on the return value to obtain the conversion.

**Comment by cpboyd** [comment]
@cromwellian 
I guess my main question is what's the proper GWT way to check if a value exists?
I don't really care to have an "Integer" vs an int, I just want an easy way to handle nulls/undefined.

Do I need to have a "checkDT()" function for each and every JSON key to see if it exists?

**Comment by cromwellian** [comment]
BTW, have you looked at the Elemental Json library? It's designed for precisely this case. get() methods return JsonValue, which is subclassed by JsonString, JsonNumber, JsonBoolean, JsonObject, JsonArray, and JsonNull.

You can do stuff like:

JsonValue o = Json.parse("....);
switch(o.getType()) {
   case NULL:
     .....
   case NUMBER:
     Window.alert("I got a number " + o.asNumber());   
}

**Comment by tbroyer** [comment]
If you do care about nulls, then either:
```java
final native Integer getDT() /*-{
  return this.DT == null ? null : @java.lang.Integer::valueOf(I)(this.DT);
}-*/;
```
or
```java
final native boolean hasDT() /*-{ return this.DT != null; }-*/;
final native int getDT() /*-{ return this.DT; }-*/;
```

If you don't care about nulls, then "coerce" them into some other primitive value:
```java
final native int getDT() /*-{ return this.DT == null ? -1 : this.DT; }-*/;
```
or (only works for `0`: if `this.DT` is `0`, then it'll evaluate to `false` and use the right-hand side of the `||`):
```java
final native int getDT() /*-{ return this.DT || 0; }-*/;
```

…or Elemental JSON (which more-or-less uses the first solution above internally).

**Comment by cpboyd** [comment]
@cromwellian 
I think that Elemental library might be what I've been looking for.
The GWT tutorials just focused on overlay types for handling JavaScriptObjects.

I'd tried using JSONObject and JSONValue, but that ends up resulting in messy code.

@tbroyer 
Thanks for the assorted options.
I knew I could create "has" functions, but I was hoping there was something better than doubling the number of functions that I need to use.

I think I'll probably check out the Elemental library.
