### ISSUE TITLE
GSS - conditional mixin

### ISSUE THREAD

**Issue by slavap** [gwtproject/gwt#9198]
There should be some way to process mixin parameters in conditional way, e.g.
@defmixin test(AAA) {
  @if (AAA == 5) {...}
  @else {...}
}

**Comment by tbroyer** [comment]
Same as #9199, not a GWT concern.

**Comment by slavap** [comment]
Ok, I've opened these issues here: https://github.com/google/closure-stylesheets/issues
Is it correct place and GWT uses this version of GSS?
