### ISSUE TITLE
GSS - local variables in mixin

### ISSUE THREAD

**Issue by slavap** [gwtproject/gwt#9199]
It should be possible to declare and use local variable somehow in mixin.
Right now it's possible declare @def in mixin, BUT it will be global variable. As workaround I can prefix it with mixin name to prevent names conflict, i.e. @def MIXIN_LOCAL 33;  but it's very inconvenient.

**Comment by tbroyer** [comment]
I believe this as-designed; but it is a [GSS](https://github.com/google/closure-stylesheets) concern, not a GWT one.
