### ISSUE TITLE
IE 10 Mobile on Windows Phone 8 detection

### ISSUE THREAD

**Issue by yuriti89** [gwtproject/gwt#9202]
I have a trouble with opening our ecwid.com store showcase (https://mdemo.ecwid.com/, for example) in Nokia Lumia emulator in Chrome browser. We use GWT 2.6.1. There is error message in browser console: 

```
Failed to execute 'createElement' on 'Document': The tag name provided ('<SELECT>') is not a valid name.
```

I research this trouble and what I get: GWT doesn't detect browser permutation correct. Detection is based on user-agent. So, user-agent from IE10 Mobile (that used in Windows Phone 8.0) looks like "Mozilla/5.0 (compatible; MSIE 10.0; Windows Phone 8.0; Trident/6.0; IEMobile/10.0; ARM; Touch; NOKIA; Lumia 820)".

GWT browser detection is implemented in / user / src / com / google / gwt / useragent / rebind / UserAgentPropertyGenerator.java. IE10 is detected in that way:

```
// IE10
      new UserAgentPropertyGeneratorPredicate("ie10")
      .getPredicateBlock()
        .println("return (ua.indexOf('msie') != -1 && ($doc.documentMode >= 10));")
      .returns("'ie10'"),
```

But, as I researched, Nokia Lumia emulator doesn't set "documentMode", it's undefined. Maybe, browser into device sets this property, but emulator doesn't. So, IE10 Mobile isn't detected as IE10. I add some extra condition to IE10 check:

```
new UserAgentPropertyGeneratorPredicate("ie10")
      .getPredicateBlock()
        .println("return (ua.indexOf('msie') != -1 && ($doc.documentMode >= 10)) || (ua.indexOf('iemobile/10') != -1);")
      .returns("'ie10'"),
```

And after that, GWT uses IE10 permutation for IE10 Mobile, and I haven't any errors.

As i saw, in GWT 2.7 that trouble isn't fixed too.

**Comment by jnehlmeier** [comment]
Can't follow. Which browser have you used now? 

First you say
> I have a trouble with opening our ecwid.com store showcase (https://mdemo.ecwid.com/, for example) in Nokia Lumia emulator in Chrome browser. 

which implies you are using Google Chrome. But then you are talking about IE 10 Mobile. 

So do you use a real IE 10 Mobile browser in the emulator or have you used Google Chrome inside the emulator and told Google Chrome to emulate the User-Agent to be the one of IE 10 Mobile?

**Comment by yuriti89** [comment]
I mean I used device mode in Google Chrome browser. I chose device "Nokia Lumia 7X0, Lumia 8XX, Lumia 900, N800, N810, N900". 
<img width="547" alt="2015-10-14 0 37 07" src="https://cloud.githubusercontent.com/assets/9929072/10469238/a0d0c8a6-720c-11e5-9549-62e3e9319ff3.png">

Also I used Chrome plugin "User-Agent Switcher" (https://chrome.google.com/webstore/detail/user-agent-switcher-for-c/djflhoibgkdhkhhcedjiklpkjnoahfmg), by that I set user agent such as in Windows Phone 8 ("Mozilla/5.0 (compatible; MSIE 10.0; Windows Phone 8.0; Trident/6.0; IEMobile/10.0; ARM; Touch; NOKIA; Lumia 920)".

In both cases I had mentioned error 
```
Failed to execute 'createElement' on 'Document': The tag name provided ('<SELECT>') is not a valid name.
```

**Comment by tbroyer** [comment]
Spoofing the UA will trigger different code paths, but the JS engine in the browser is still the same; so code for another browser is executed in an unexpected environment, and will likely break / not work as intended.
GWT 3 might finally stop using UA detection, but GWT 2 still uses it, so UA spoofing undoubtedly breaks things.
