### ISSUE TITLE
Error handling for invalid permutation value

### ISSUE THREAD

**Issue by chris-malloy-mri** [gwtproject/gwt#9207]
This is a feature request.

Right now when you specify a value for a permutation that is not one of the possible values the bootstrap script will try to load undefined.cache.js. This can happen quite easily since some authors use values such as ["yes", "no"], ["true", "false"] or ["on", "off"] inconsistently with permutations. It would be nice if there was an error explaining that a permutation was expecting certain values, and display what the incorrect value received was. Such as:

    Error: Permutation "test" was expecting values ["yes", "no"] but received "true".

**Comment by tbroyer** [comment]
There's a (undocumented) hook for that actually: `onPropertyErrorFn`; see #8130
