### ISSUE TITLE
[GWT 2.8.0-SNAPSHOT][Polymer] ClassCastException when trying -XjsInteropMode JS_RC

### ISSUE THREAD

**Issue by Mattallica** [gwtproject/gwt#9208]
Hi,

I'm working with GWT 2.8.0-SNAPSHOT and Polymer to create WebComponents.
I'm trying to work with the last version of JsInterop described in this document https://docs.google.com/document/d/10fmlEYIHcyead_4R1S5wKGs1t2I7Fnp_PaNaa7XTEk0/edit#

Here what I did :

1. I changed the <jsInteropMode>JS_RC</jsInteropMode> in the configuration of the gwt-maven-plugin in the pom.xml file.

2. I changed the imports with jsinterop.annotations.*

Here is my JAVA code :

```
import jsinterop.annotations.JsProperty;
import jsinterop.annotations.JsType;

@JsType
public interface MyElement {
  
  public static final String TAG = "my-component";
  public static final String SRC = "my-component/my-component.html";
  
  @JsProperty(name = "data")
  void setData(JavaScriptObject data);
  
}
```

Here is my Polymer declaration :

```
Polymer({
  is : "my-component",
      
  properties: {
    data: {
      type: Array
    },
  }
});
```

When launching the super dev mode I've got a  Uncaught java.lang.ClassCastException in the chrome console.
Maybe I misunderstood something.

Thanks for your help.

**Comment by jDramaix** [comment]
First you should open a thread on the mailing list for that. 

In your snippets, I don't see where you pass the prototype of your MyElement object to Polymer ?

**Comment by Mattallica** [comment]
Hi jDramaix, thanks for your response.

I'm new on Github so how to open a thread on the mailing list ?

To make the link between GWT and Polymer I use the GWT PolymerWidget Object :

```
public class UiMyElement extends PolymerWidget {
  
  public UiMyElement(String html) {
    super(MyElement.TAG, MyElement.SRC, html);
  };
}
```

**Comment by gkdn** [comment]
You need to put isNative=true for any type provided by javascript. i.e.

```java
 @JsType(isNative=true)
 public interface MyElement { .. }
```
