### ISSUE TITLE
GWT super dev mode in 2.8 doesn't respect -style parameter

### ISSUE THREAD

**Issue by damluar** [gwtproject/gwt#9210]
I'm starting SDM and pass "-style PRETTY" or "-style DETAILED" along with other parameters. When I look at compiled JS code or when some exception is thrown, the stack trace is obfuscated and unreadable.
I'm experiencing this issue with 2.8, not sure about 2.7.

**Comment by gkdn** [comment]
To have better stacktraces:

First option is to remove any deps to Logging.gwt.xml & DisabledLogging.gwt.xml.
Second option, If you can't do the first, set gwt.logging.simpleConsoleHandler to ENABLED but it will potentially cause duplicate log messages.

These options will print good stacktrace in browser console.

**Comment by mgoerdes** [comment]
Is this task on the list for final GWT 2.8?

**Comment by jnehlmeier** [comment]
Its not. By default SDM in GWT 2.8 uses obfuscated style to reduce the size of the non-optimized JavaScript. Actually I wanted to look into it so people can opt-out of the default behavior but never found time for it (see: https://groups.google.com/d/msg/google-web-toolkit-contributors/SPJhax-umfw/VXKCg68NCAAJ )

Also its not a super blocker. With source maps and good stack traces I can usually debug everything I need to.

**Comment by mgoerdes** [comment]
We normally used it to find memory leaks. Its much easier to identify the leaking objects in "production mode" when having them available with pretty or detailed names. Same for profiling execution time. Or is there a better way?

**Comment by jnehlmeier** [comment]
@mgoerdes sure. At work we compile out app the same way we would do for production but with -style PRETTY in order to do execution time profiling. The reason is that the performance difference between SDM output and a real production compile output is so large that IMHO its not worth doing execution time profiling with SDM. Finding memory leaks might make sense using SDM but we also do it with a production compile using -style PRETTY.

**Comment by mgoerdes** [comment]
Ok thx. Then its obviously better to compile in pretty mode and profile without SDM. Thats ok and should help enough finding ugly behavior.

**Comment by rluble** [comment]
SDM honours the -style PRETTY flag and produces SDM prettyfied names (which are a bit different than pretty names). You need to do a sdm clean through the web interface for pretty to have effect in the whole program. (just verfied that this functionality works when launching SDM from the command line)
