### ISSUE TITLE
JsExport does not work on types

### ISSUE THREAD

**Issue by hypnoce** [gwtproject/gwt#9212]
Hi,
since https://github.com/gwtproject/gwt/commit/64e3270a9a02eea66fb9beab9e423a14f60b6cec it seems the JsExport annotation does not work on types.

```java
@JsExport
@JsType
public class View {
   public View() {}
   public void setData(String s) {...}
}
```

Neither the constructor nor the public method 'setData' are exported.
Nevertheless, when I do
```java
@JsType
public class View {
   @JsExport  
   public View() {}
   @JsExport
   public void setData(String s) {...}
}
```
it gets correctly exported.

**Comment by MartinMoizard** [comment]
+1

**Comment by tbroyer** [comment]
Have you checked with 51f96f25d7768fd7907b6a1300f60cfe85b0c3d4?

**Comment by hypnoce** [comment]
I tried with the latest get-dev-2.8.0-SNAPSHOT : 
https://oss.sonatype.org/service/local/repositories/google-snapshots/content/com/google/gwt/gwt-dev/2.8.0-SNAPSHOT/gwt-dev-2.8.0-20151107.054831-94.jar
It was released on Sat Nov 07 2015 06:48:34 GMT+0100 (CET).

Indeed, it does not include https://github.com/gwtproject/gwt/commit/51f96f25d7768fd7907b6a1300f60cfe85b0c3d4
I will wait for the next nigthly then.

Thanks

**Comment by hypnoce** [comment]
Seems that build is failing : http://build.gwtproject.org/job/gwt/.

**Comment by gkdn** [comment]
FYI, the old annotations will be deleted very soon before the 2.8 release.

**Comment by hypnoce** [comment]
Good to know.

Indeed I found the new annotations and put the JS_RC mode. It seems to work now.

Thanks
