### ISSUE TITLE
Bug with method references in 2.8 with gwt.optimize=0

### ISSUE THREAD

**Issue by infthi** [gwtproject/gwt#9214]
Sample project is available here: https://github.com/infthi/gwt-method-reference-bug

Making a predicate from an class method and then calling this predicate with an instance results in boolean predicate returning JS 'undefined' value.

This problem only occurs with gwt.optimize=0 and cannot be reproduced with higher optimization levels.

**Comment by rluble** [comment]
A fix is up for review https://gwt-review.googlesource.com/13973.

@infthi, thanks for the small and clear repro case.

**Comment by infthi** [comment]
Yep, that fixed it. Thanks!
