### ISSUE TITLE
Please add support for referencing parent selectors: &

### ISSUE THREAD

**Issue by mediamichael** [gwtproject/gwt#9218]
Referencing Parent Selector with "&" makes styling faster, removes repetition, decreases error potential, and is just awesome!

Example in SASS: "Sometimes it’s useful to use a nested rule’s parent selector in other ways than the default. For instance, you might want to have special styles for when that selector is hovered over or for when the body element has a certain class. In these cases, you can explicitly specify where the parent selector should be inserted using the & character. For example:

a {
  font-weight: bold;
  text-decoration: none;
  &:hover { text-decoration: underline; }
  body.firefox & { font-weight: normal; }
}

is compiled to:

a {
  font-weight: bold;
  text-decoration: none; }
  a:hover {
    text-decoration: underline; }
  body.firefox a {
    font-weight: normal; }"

**Comment by jDramaix** [comment]
You should open this feature request directly to Closure stylesheet project: https://github.com/google/closure-stylesheets
