### ISSUE TITLE
textbox korean click event strange work. 

### ISSUE THREAD

**Issue by parkjaehyuck** [gwtproject/gwt#9219]
sorry I can't write English. 

watch youtube . and read text..

https://youtu.be/gwUBH_Kj8Mo
** korean and  button event test **
** Need scroll **
   .1. typing korean 
   .2. scroll down  ( use mouse scroll button)
   .3. click button  <-- strange work
   .4. focus to textbox
   .5. scoll down
   .6. click button  <-- work
   .7. show window alert (message : button event )
 refresh

** mouse event test **
  .1. typing korean 
  .2. scroll down  ( use mouse scroll button)
  .3. click label  <-- strange work
  .4. focus to textbox
  .5. scoll down
  .6. click label <-- good work
  .7. show window alert (message : click event )

https://youtu.be/OiPnrjfhxXc
** korean, english and  button event test **
** Need scroll **
   .1. typing korean and english
   .2. scroll down  ( use mouse scroll button)
   .3. click button  <-- good work
   .4. show window alert (message : button event )
 refresh
   .1. typing korean and english
   .2. scroll down  ( use mouse scroll button)
   .3. click label  <-- good work
   .4. show window alert (message : click event )

https://youtu.be/0AJHOjtkxZc
** korean and  button event test **
** Need Scorll**
   .1. typing korean 
   .2. click blank. ( textbox focus out)
   .3. scroll down  ( use mouse scroll button)
   .4. click button  <- good work
   .5. show window alert (message : button event )

https://youtu.be/vBBGBbJMo60
** korean and  button event test **
** no scroll **
   Button Event, Label Click Event Good work.

https://youtu.be/nOZiEiWl1z8
** copy and past **
  Button event good work.

## this problem Scroll  Exit or NOT Exist

**Comment by parkjaehyuck** [comment]
GWT Version :  2.7.0 and 2.6.1

**Comment by parkjaehyuck** [comment]
Source Code : 

	public void onModuleLoad() {
		final TextBox tb1 = new TextBox();
		Button btn = new Button("click", new ClickHandler() {
			@Override
			public void onClick(ClickEvent event) {
				Window.alert("button event"); 
				
			}
		});
		
		Label lblClick = new Label("mouse click event");
		lblClick.getElement().getStyle().setCursor(Cursor.POINTER);
		lblClick.getElement().getStyle().setFontSize(2.0, Unit.EM);
		lblClick.addClickHandler(new ClickHandler() {
			@Override
			public void onClick(ClickEvent event) {
				Window.alert("click event"); 
			}
		});

		
		VerticalPanel vp = new VerticalPanel();
		vp.add(btn);
		vp.add(lblClick);
		
		VerticalPanel main = new VerticalPanel();
		main.add(tb1);
		main.add(vp);
		main.setCellVerticalAlignment(vp, HasVerticalAlignment.ALIGN_BOTTOM);
		main.setHeight(Window.getClientHeight()+200+"px");
		
		
		RootPanel.get().add(main);
	}

**Comment by tbroyer** [comment]
Can you try with https://jsfiddle.net/w7kns6f1/embedded/result/
Do you see the same behavior ?

**Comment by parkjaehyuck** [comment]
https://github.com/gwtproject/gwt/issues/9219

same behavior..

and I found something..

한글 englsh   <-- not scroll  
english 한글 <-- scroll

**Comment by parkjaehyuck** [comment]
https://youtu.be/cCi-lxCma5w

This is javascript bug...
test brower
chrome  version  : 46.0.2490.86 m
firefox    version  :  42.0
ie           version  :  11.0.9600.18097


test javscript code.


<!DOCTYPE html>
<html>
<body>

<form action="" onsubmit="return myFunction()">
  Name (max 10 characters): <input type="text" id="fname" size="20">
<br><br>
<br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br>
 <input type="submit" value="Submit"> 
</form>

<script>
function myFunction() {
    Var fname = document.getElementById("fname").value;
    submitOK = "true";

    if (fname.length > 10) {
        alert("The name may have no more than 10 characters");
        submitOK = "false";
    } 

    if (submitOK == "false") {
        return false;
    }
}
</script>

</body>
</html>

**Comment by tbroyer** [comment]
This is what I wanted to confirm; not a GWT bug.
