### ISSUE TITLE
Json.create produces wrong JsonType for number and boolean

### ISSUE THREAD

**Issue by Legioth** [gwtproject/gwt#9225]
With GWT 2.8.0-beta1, `Json.create(double)` and `Json.create(boolean)` produce JsonValue instances where `getType()` returns `JsonType.OBJECT` instead of the expected `JsonType.NUMBER` or `JsonType.BOOLEAN`. The expected values are returned with GWT 2.7.0.

This seems to be caused by dec4e9bb1c726f1b5c69ece639ee54016f3de03e.

**Comment by gkdn** [comment]
Ray, I thought you fixed this problem but doesn't seem like it is fixed?

**Comment by cromwellian** [comment]
Maybe I fixed it in the internal version of elemental and not the gwt sdk
one? I'll take a look.

**Comment by gkdn** [comment]
Ping

**Comment by dankurka** [comment]
I'll move this off the 2.8 milestone. If you feel strongly about this please provide a patch asap and ping this bug with the review URL (we are getting close to releasing RC1 and I we will not be holding RC1 for this small elemental issue).

**Comment by niloc132** [comment]
Elemental has been removed, closing as stale.
