### ISSUE TITLE
Do not generate export for abstract class constructos (and perhaps other cases?)

### ISSUE THREAD

**Issue by gkdn** [gwtproject/gwt#9237]

**Comment by rluble** [comment]
I am not sure that this is what is wanted. If an abstract class is exported you might want to do "instanceof Ctor" even tough you would not want the Ctor used to construct objects.

**Comment by gkdn** [comment]
or similarly it could be used to extend the object in j2cl...

I don't think there is anyway to prevent the construction. Closing this..
