### ISSUE TITLE
Obfuscated CSS class names starting with "ad-" are picked up by adblockers

### ISSUE THREAD

**Issue by jessicaxp** [gwtproject/gwt#9240]
Adblock-style browser plugins detect and hide elements with certain class names and IDs, one of which being "ad-". Ideally this sequence of characters would be blacklisted from the obfuscated class names as to not result in random elements being hidden.

**Comment by jnehlmeier** [comment]
Interesting catch. Not sure if blacklisting is the best approach though. Looking at [EasyList](https://easylist-downloads.adblockplus.org/easylist.txt) (used by Adblock Plus) there are class names listed that do not contain "-ad" or "ad-" but still could possibly be generated by GWT.

Maybe its better to add some (configurable) prefix and maybe even a suffix for generated CSS class, e.g. `_gwt_<obfuscated>`, `_myapp_<obfuscated>` or `__<obfuscated>__`.

**Comment by jDramaix** [comment]
use the CssResource.obfuscationPrefix for that purpose

```xml
<set-configuration-property name="CssResource.obfuscationPrefix" value="_gwt_" />
```
