### ISSUE TITLE
gwt.codesvr=127.0.0.1:-1

### ISSUE THREAD

**Issue by jplwill** [gwtproject/gwt#9245]
I'm debugging a GWT 2.7 app on OSX Yosemite using Eclipse Luna using a local server in Classic Dev Mode using Firefox 24.

On reloading my app in Firefox 24, I got the message in the Development Mode tab that my app ran out of memory.  I've seen this before.  I stopped the development server, and restarted it.  On restart I got a message on the Console that something was already running on port 8888; then the Development Mode tab updated normally, and showed me the URL to display in Firefox.  The URL looked like this:

`http://127.0.0.1:8888/GWT_Examples.html?gwt.codesvr=127.0.0.1:-1`

The code server is at port -1?  Naturally, this didn't work too well.

I shut down Firefox and Eclipse, and verified that nothing was running at port 8888 using `netstat`.  I restarted Eclipse, restarted Dev Mode, and got the same "port 8888" error and a code server port of -1.  This happened multiple times, and didn't go away until I rebooted my machine.

**Comment by branflake2267** [comment]
I think that occurs when there is already a dev mode running.

**Comment by jplwill** [comment]
Eclipse showed no dev mode running.  I used netstat to verify that nothing was on port 8888.  It still happened.  I Googled this problem pretty thoroughly before adding a new bug; if it was as simple as shutting down an existing dev mode, I'd have done that.

**Comment by branflake2267** [comment]
If the launcher automatically selecting a port, check the ActivityManager for any java processes and quit them. I suspect a stray instance of java is in the process stack that may be causing it to spawn on a different port.

**Comment by jplwill** [comment]
I presume you mean the Mac ActivityMonitor app.  (I can't find anything called the Activity Manager) in OSX or Eclipse).  If I see this again, I'll do that.  But still, spawning on port -1 seems like a bug no matter how you slice it.
