### ISSUE TITLE
Possible issue with JsFunction

### ISSUE THREAD

**Issue by BenDol** [gwtproject/gwt#9246]
Granted, I may be missing something here given how new JsInterop is. There is an issue that I'm not sure how to resolve. Please correct me if I have missed something important (I have followed all the latest documentation).

I am trying to use JsInterop to hook into the jQuery library (using [gwt-jquery](https://github.com/BenDol/gwt-jquery)) and the following implementation isn't working properly:

Function.java
```java
/**
 * Represent a Function in JS Environment.
 *
 * @author Cristian Rinaldi
 * @author Andres Testi
 */
@FunctionalInterface
@JsFunction
public interface Function {
    Object call(Event event, Object params);
}
```

JQuery.java
```java
/**
 * Represent a JQuery access model.
 *
 * @author Ben Dol
 */
@JsType(isNative = true)
public class JQuery {

    @JsMethod(namespace = JsPackage.GLOBAL)
    public static native JQueryElement $(String selector);
    ...
}
```

JQueryElement.java
```java
/**
 * Represent a JQuery Element.
 *
 * @author Cristian Rinaldi
 */
@JsType(name = "jQuery", isNative = true, namespace = JsPackage.GLOBAL)
public class JQueryElement extends Node {
    ...
    public native void on(String event, Function fn);
    ...
}
```

Calling this:
```java
import static com.workingflows.js.jquery.client.api.JQuery.$;

...

$("#jsinterop").on("click", (Event e, Object o) -> {
    Window.alert("clicked!");
    return o;
 });
```
throws this:
```java
Uncaught TypeError: ((jQuery.event.special[handleObj.origType] || (intermediate value)).handle || handleObj.handler).apply is not a function.
    jQuery.event.dispatch @ jquery-2.1.4.js:4435
    elemData.handle @ jquery-2.1.4.js:4121
```

The handler passed into the `on(...)` method is not recognized as a javascript function. When I debugged the code inside jquery library this is the handlerObj.handler variable content:
```java
handleObj: Object
    data: undefined
    guid: 17
    handler: Ywc_g$
        guid: 17
        __proto__: F_0_g$
            $init_606_g$: Xwc_g$()
            ___clazz_0_g$: MKc_g$
            call_0_g$: Zwc_g$(arg0_0_g$, arg1_0_g$)
            castableTypeMap_1_g$: Object
            constructor: F_0_g$
            __proto__: F_0_g$
```
Which is obviously not recognized as a javascript function. Is there something I have missed here? Or perhaps its an issue with JsInterop.

**GWT Version:** 2.8.0-beta1

Edit: I just noticed a compiler warning:
```
[WARN] Warnings in com/workingflows/js/jquery/client/api/JQueryElement.java
[INFO] [WARN] Line 51: [unusable-by-js] Type of parameter 'fn' in 'void JQueryElement.on(String, Function)' is not usable by but exposed to JavaScript.
```
Probably the cause of the issue?

Thanks!

**Comment by branflake2267** [comment]
Just a thought, you might find it easier to write the jsinterop if the source maps is off. You can see what it's translating the java into. I found instead of reading the object construction, reviewing the generated javascript source code was a bit easier to delineate. Would that help?

**Comment by BenDol** [comment]
Well to be honest I wouldn't know what to look for here. Someone that knows JsInterop would be able to spot if this is an issue. If this has been implemented properly and yet its still throwing this error perhaps there is an internal problem.

**Comment by BenDol** [comment]
Here is some of the output code referencing this interoped code:
```javascript
function Pwc_g$(){
  var stackIndex_0_g$;
  $stack_0_g$[stackIndex_0_g$ = ++$stackDepth_0_g$] = Pwc_g$;
  $location_0_g$[stackIndex_0_g$] = 'MaterialDesignGridEntry.java:' + '45' , Jwc_g$();
  {
    if ($location_0_g$[stackIndex_0_g$] = 'MaterialDesignGridEntry.java:' + '46' , Dwc_g$()) {

      // This line seems to be where its making the call
      // As you can see its invoking 'new' keyword on the handler where it is suppose to be a function.
      ($location_0_g$[stackIndex_0_g$] = 'MaterialDesignGridEntry.java:' + '47' , $wnd).window.$('#jsinterop').on('click', new Ywc_g$);

      $stackDepth_0_g$ = stackIndex_0_g$ - 1;
      return false;
    }
     else {
      $stackDepth_0_g$ = stackIndex_0_g$ - 1;
      return true;
    }
  }
  $stackDepth_0_g$ = stackIndex_0_g$ - 1;
}
```

Here is the actual function definition:
```javascript
function Ywc_g$(){
  var stackIndex_0_g$;
  $stack_0_g$[stackIndex_0_g$ = ++$stackDepth_0_g$] = Ywc_g$;
  $location_0_g$[stackIndex_0_g$] = 'MaterialDesignGridEntry.java:' + '47' , Wwc_g$();
  $stackDepth_0_g$ = stackIndex_0_g$ - 1;
}
```

And this line which I don't understand:
```javascript
I2b_g$(857, 1, {837:1, 857:1, 1:1}, Ywc_g$);
```

Perhaps this information could help.

**Comment by branflake2267** [comment]
I'm no expert. But I would try typing what you would want to do in the dev tools console. Then take that and compare it to the jquery method above. They should align and if they don't the Java type has to adjust. You'll notice that GWT has to use $wnd to get out of the sandbox. So I suspect it would be something like this maybe $wnd.$('') and not $wnd.window....  `$wnd).window.$('#jsinterop').on('click', new Ywc_g$);
`

**Comment by BenDol** [comment]
`$wnd).window.$('#jsinterop')` works fine on all the other jquery functions, the issue I'm having is in relation to the `Function`/`JsFunction` passed into `.on(...)`. SO yeah, the call to jquery is working fine, seems that `Ywc_g$` needs to be a function reference and not an Object.

**Comment by gkdn** [comment]
You are probably using the wrong @JsFunction.

**Comment by BenDol** [comment]
There's another JsFunction? I will take a look.

**Comment by BenDol** [comment]
This was in fact the issue, thanks @gkdn 

I was using: 
`import com.google.gwt.core.client.js.JsFunction;`
when I changed it to:
`import jsinterop.annotations.JsFunction;`

It worked fine.
