### ISSUE TITLE
-generateJsInteropExports does not generate code without  @JsExport

### ISSUE THREAD

**Issue by mbrigl** [gwtproject/gwt#9247]
The compiler generates JavaScript mappings, only if the Classes are annotated with @JsExport. Looking the final specification the @JsExport should be replaced with @JsType.

**Comment by gkdn** [comment]
You are probably still passing -XjsinteropMode flag; that's deprecated and will be removed soon.

**Comment by mbrigl** [comment]
Thanks, I did remove already -XjsinteropMode. But probably the fix was made in these days. I made un updated today and now its working
