### ISSUE TITLE
Unsupported major.minor version 51.0

### ISSUE THREAD

**Issue by wadezang** [gwtproject/gwt#9249]
I am experiencing an error "com/google/gwt/thirdparty/common/css/SubstitutionMap : Unsupported major.minor version 51.0".
Currently I have installed Eclipse Luna, GPE with GWT 2.7, GXT 4 and Java 1.6 (Java 1.6 is currently required). The error came out only when I add a GXT Widget. It was not a problem for GWT 2.7 alone.
As it's been discussed here 'https://github.com/ArcBees/gwtchosen/issues/199', the GSS requires Java 7. Is there a workaround to make it compatible with Java 6?

**Comment by freytagusu** [comment]
May i ask why Java 1.6 is required on your client side code?

**Comment by wadezang** [comment]
Because the current project was developed with GWT 2.5/GXT 3 and Java 6. We want to upgrade to GWT 2.7/GXT 4 but keep Java 6. I am responsible to test the new environment in order to find out if it is possible to keep Java 6 instead of upgrading to Java 7 or 8.

**Comment by jnehlmeier** [comment]
@wadezang You should not have an issue compiling your GWT UI using Java 7 while still using Java 6 on some servers (for whatever reasons). That would mean you would compile your app twice: Once for the browser (GWT UI using Java7) and once for the server (using Java6). 
Alternatively I would recommend moving the UI into its own project so you can have separate Java versions and class paths for your projects.

Anyways, GWT 2.7 is generally compatible to Java 6 as long as your app and any UI library your app uses does not enable and use GSS support. So you would need to ask the maintainer of the UI libraries you use if their widgets still work correctly if you disable GSS in your app. If thats not the case then you need to upgrade to Java 7 when compiling your GWT UI or don't use a UI library that requires GSS.

GWT 2.8 will require Java 7 and shortly after maybe even Java 8 (that still needs to be figured out).

**Comment by branflake2267** [comment]
If you're using the GXT themebuilder it will need 1.7 too. Like Jens said, using maven modules or different projects to change the classpath configuration is handy. I usually suggest working in 1.7 and then use build server tricks to compile it the way it's needed.

**Comment by wadezang** [comment]
Thank you both.
