### ISSUE TITLE
JsInterop feature request - factory method, that alters constructor

### ISSUE THREAD

**Issue by lleevvyy** [gwtproject/gwt#9251]
Hi, I would like to request for a new feature - factory method, that will alter js constructor. Same feature has Dart lang and is very usefull, when JS object can be created only by calling factory method. Good example are HTMLElement classes - to create an instance you need to call document.createElement.

I belive that the best option would be to add new parameter "factory" to \@JsType annotation. It would contain a js code, that will be called instead of js object constructor. For example:

\@JsType(isNative = true, namespace = JsPackage.GLOBAL, factory = "document.createElement('div')")
public static class HTMLDivElement extends HTMLElement {
    public DivElement () {
    }
}

DivElement newDiv = new DivElement() ----> var newDiv = document.createElement('div');

When constructor and factory needs parameters, then:
\@JsType(isNative = true, namespace = JsPackage.GLOBAL, factory = "SomeObject.createInstance($1, $2)")
public static class SomeObject {
    public SomeObject (String paramA, String paramB) {
    }
}

SomeObject newObject = new SomeObject("Param A value", "Param B value") ----> var newObject = SomeObject.createInstance("Param A value", "Param B value")

Thanks.

**Comment by dankurka** [comment]
JsInterop's intention is to allow easy access to JavaScript APIs, not changing their call APIs.

If an underlying API is clunky it is not the job of JsInterop to change that. Rather people need to fix their JavaScript API.
A good example for that is the fact that we did not go for a fluent style API for getters and setter, if they are not fluent in JavaScript.
This is somewhere on the same scale. If you want to to be able to new an Object it needs to have a JavaScript constructor.

If you feel strongly about this you can always add a static JsOverlay method on the type that creates it. This way creation is still understandable by reading the Java code and is not hidden in a JsInterop feature.
