### ISSUE TITLE
jsinterop and script injection

### ISSUE THREAD

**Issue by lleevvyy** [gwtproject/gwt#9264]
Hi, when external javascript is injected (using ScriptInjector) from TextResource it is not possible to have a class, annotated with JsType(isNative=true) that refers to a class from injected script - the script is not yet injected. The output of a compiled javascript is as follows:

function $clinit_LessFileManagerTextResourceImpl_0_g$(){
  $clinit_LessFileManagerTextResourceImpl_0_g$ = Object;
  null;
}

function LessFileManagerTextResourceImpl_1_g$(){
  $clinit_LessFileManagerTextResourceImpl_0_g$();
  $wnd.less.AbstractFileManager.call(this);
  this.$init_4678_g$();
}

**defineClass_0_g$(3393, $wnd.less.AbstractFileManager, {3391:1, 3393:1, 1:1}, LessFileManagerTextResourceImpl_1_g$);**
copyObjectProperties_0_g$(getClassPrototype_0_g$(1), _);
_.$init_4678_g$ = function $init_4674_g$(){
  $clinit_LessFileManagerTextResourceImpl_0_g$();
}

As you can see, function defineClass_0_g$ requires $wnd.less.AbstractFileManager and it causes an error, as requested namespace ($wnd.less) is not yet defined. Off course it is obvious why this is happening, but this makes impossible to use scriptinjector and JsInterop.

One solution would be to deffer definingClass and call it dynamically, when either instanceof is used or new instance of a class is created.

**Comment by jnehlmeier** [comment]
The following does work well (but I used GWT master branch):

```java
public class Example implements EntryPoint {

  interface JsResource extends ClientBundle {

    // window.jslib = {};
    // window.jslib.Employee = function(name) {
    //   this.name = name;
    // };
    // window.jslib.Employee.prototype.sayName = function() {
    //   console.log("Hello, I am " + this.name);
    // }
    @Source("jslib.js")
    TextResource jsLib();
  }

  @JsType(isNative = true, namespace = "jslib" , name = "Employee" )
  public static class Employee {
    public Employee(String name) {}
    public native void sayName();
  }

  @Override
  public void onModuleLoad() {
    JsResource jsResource = GWT.create(JsResource.class);
    String jsLib = jsResource.jsLib().getText();
    ScriptInjector.fromString(jsLib).setWindow(ScriptInjector.TOP_WINDOW).inject();

    Employee e = new Employee("John");
    e.sayName();
  }
}
```

If you omit `setWindow(ScriptInjector.TOP_WINDOW)` then the script is injected into the iframe that contains all the "normal" GWT code and not the top window. However JsInterop always uses $wnd for native types, so your code won't work then. The above generates:
```javascript
    e_0_g$ = new $wnd.jslib.Employee('John'); // $wnd always points to top window which contains the injected JS
    e_0_g$.sayName();
```

**Comment by gkdn** [comment]
There should be no defineClass for native types. So what you shared as the
generated code seems weird. You are probably extending some native type
(something you cannot do with ScriptInjector as you need the parent type
before the GWT script gets loaded).  Can you share the corresponding java
code as well?

**Comment by lleevvyy** [comment]
@gkdn yes, I was extending native type. Ok, so I have two options - either to drop script injection and load script from host page, or not use isNative and instead of constructors I would have to use jsni to initialize instance. Thanks @gkdn  and @jnehlmeier.
