### ISSUE TITLE
Bugs related to Java 8

### ISSUE THREAD

**Issue by majcn** [gwtproject/gwt#9266]
1. SimpleClass::new
  * can not compile if you are using constructor references. Works ok with methods.

2. forEach
  * lists does not have implemented forEach

3. missing java.util.function.*

4. interface with default methods (gwt can not find function method1(Object val)). It works ok with abstract class
```java
public interface SimpleInterface<T,D> {
    T method1(D val);
    D nonImplementedMethod(T value);
}

@FunctionalInterface
public interface SimpleExtendedInterface<T,D> extends SimpleInterface<T,D> {

    @Override
    default T method1(D val) {}

    default List<D> method2(Collection<? extends T> val) {}

    default List<T> method3(Collection<? extends D> val) {}
}
```

**Comment by jDramaix** [comment]
Could you create separate bugs for point 1 and 4 ?  And please add a simple
reproduce case for point 1. I have already used constructor references with
GWT 2.8 and I had no problems.

point 2 and 3, fell free to propose a patch to add these missing api.

**Comment by jnehlmeier** [comment]
Regarding 2. and 3.: A lot of Java 8 API is already taken care of in form of contributions that are currently reviewed in Gerrit. There is also a stream implementation on Github that should find its way to review sooner or later.

However the GWT 2.8 release will most likely only have Java 8 syntax support without any further Java 8 API emulation. Emulations will come in a follow up release.

**Comment by majcn** [comment]
Created new issues:
#9267 and #9268

**Comment by majcn** [comment]
And thanks for explanation about second and third point.
