### ISSUE TITLE
Java8: constructor references (2.8.0-beta1)

### ISSUE THREAD

**Issue by majcn** [gwtproject/gwt#9267]
SimpleClass::new
> can not compile if you are using constructor references. Works ok with methods.

```java
public static <T, R> R ifNotNull(final T value, final Function<T, R> ifNotNull) {
    return value == null ? null : ifNotNull.apply(value);
}

SomeClass<T> val = ifNotNull(val, SomeClass<T>::new);
```

**Comment by rluble** [comment]
Is it a type error at compile time? If so it is a bug/limitation in JDT; you can verify that by compiling with the currently release version of ecj (Eclipse java compiler).

It should work fine if you use SomeClass::new instead of SomeClass<T>::new.

**Comment by majcn** [comment]
This kind of method reference works in java code (simple main method without gwt).

I don't understand the difference in the last sentence.

**Comment by tbroyer** [comment]
> I don't understand the difference in the last sentence.

It was a formatting issue; I just edited it to fix the formatting.

**Comment by majcn** [comment]
Yes It works that way. Thank you
