### ISSUE TITLE
Java8: interface with default methods (2.8.0-beta1)

### ISSUE THREAD

**Issue by majcn** [gwtproject/gwt#9268]
interface with default methods
> Can not find function method1(Object val)
> It works ok with abstract class

```java
public interface SimpleInterface<T,D> {

    public static class Util {
        public static <T, D> List<T> staticMethod(List<? extends D> dtoList, final SimpleInterface<T, D> mapper) {
            List<T> res = new ArrayList<>();
            res.add(mapper.method1(dtoList.get(0)));
            return res;
        }
    }

    T method1(D val);
}

@FunctionalInterface
public interface SimpleExtendedInterface<T,D> extends SimpleInterface<T,D> {

    @Override
    default T method1(D val) {}

    default List<D> method2(Collection<? extends T> val) {}

    default List<T> method3(Collection<? extends D> val) {
        return SimpleInterface.Util.staticMethod(val, this);
    }
}
```

**Comment by rluble** [comment]
Could you paste the error/stack trace and clarify which source line is referred by the error given that the pasted code does not have line numbers.

**Comment by majcn** [comment]
com.google.gwt.core.client.JavaScriptException: (TypeError) : ((intermediate value)(intermediate value) , mapper_0_g$).domainValueFromDto_1_g$ is not a function
      at Unknown.v1q_g$(SimpleInterface.java:14)
      at Unknown.c2q_g$(SimpleExtendedInterface.java:20)
      at Unknown.zzA_g$(SimpleExtendedInterface.java:19)
      at Unknown.geB_g$(RestServiceClient.java:64)
      at Unknown.O1y_g$(BaseRestRequest.java:71)
      at Unknown.O3c_g$(Request.java:250)
      at Unknown.q5c_g$(RequestBuilder.java:412)
      at Unknown.anonymous(XMLHttpRequest.java:329)
      at Unknown.ohb_g$(Impl.java:233)
      at Unknown.rhb_g$(Impl.java:285)
      at Unknown.anonymous(Impl.java:71)

call -> method3

**Comment by rluble** [comment]
Could not reproduce using the snippet above (after making it valid Java). I guess the snippet above is from a bigger example. 

Please make sure when you reduce the failing code it still fails and post a complete example and relevant details. 

Reopen with a complete repro case.

**Comment by asgs** [comment]
does this mean default methods are indeed supported by GWT? if so, from what versions onward?

**Comment by tbroyer** [comment]
> does this mean default methods are indeed supported by GWT? if so, from what versions onward?

Indeed. Since 2.8.0 beta 1.
http://www.gwtproject.org/release-notes.html

**Comment by bpetridean** [comment]
I have been `default` since version 2.8.0, so yes.

**Comment by brownian-motion** [comment]
I find that I need to annotate `default` methods with `@JsOverlay` for the GWT compiler to process them correctly.
