### ISSUE TITLE
jsInterOp doesn't allow name JsOperation for exported types 

### ISSUE THREAD

**Issue by gautamaino** [gwtproject/gwt#9269]
It may not necessarily be a bug but certainly should be documented if true ... 

take a look at this stackoverflow question for more details...

http://stackoverflow.com/questions/34793497/strange-error-on-gwt-jsinterop-call-back-implementation-gives-strange-error

**Comment by gkdn** [comment]
Can you switch to style PRETTY? That will provide more information.

**Comment by gautamaino** [comment]
@gkdn I haven't tried the PRETTY compilation.. what flag do I need to set in the maven build ? The trial code is committed here - https://github.com/gautamaino/jsInterOp-Callback

**Comment by tbroyer** [comment]
@gautamaino  With the `org.codehaus.mojo:gwt-maven-plugin`, you'd just add `<style>PRETTY</style> to your `<configuration>`: https://gwt-maven-plugin.github.io/gwt-maven-plugin/compile-mojo.html#style

**Comment by gkdn** [comment]
Closing this as it is not reproducible.
