### ISSUE TITLE
Problem with Varargs in JsInterop

### ISSUE THREAD

**Issue by BenDol** [gwtproject/gwt#9272]
Using varargs with JsInterop isn't working with the following scenario:

```java
public native JQueryElement<T> trigger(String eventType, Object... extraParameters);
```
Mirroring [JQuery Trigger](http://api.jquery.com/trigger/)

This call doesn't pass the `extraParameters` as an array. 

For example:
```java
container.trigger("event-type", param1, param2, param3);
```

Only param1 is passed into this call.

When I change this to:
```java
public native JQueryElement<T> trigger(String eventType, Object[] extraParameters);
```

The call works fine. Not sure if I've missed something here, but it seems that this should work in theory.

**Version:** 2.8-SNAPSHOT

Thanks!

**Comment by tbroyer** [comment]
I think varargs map to varargs; i.e. the JS method receives 4 arguments. If you want 2 args with the second being an array you need to declare it as such (I think you could maybe add a varargs method that calls the "array" one, in Java, for the syntactic sugar.)

**Comment by BenDol** [comment]
Ah okay, that does make more sense actually. Thanks!

**Comment by gkdn** [comment]
What @tbroyer said and his suggestion is accurate.
