### ISSUE TITLE
Add an option to generate qualified name without "$wnd." prefix for constructor calls

### ISSUE THREAD

**Issue by dreifachstein** [gwtproject/gwt#9274]
The ExtendScript by Adobe does not define object constructors as properties of the global object, so 'new' expressions generated by gwt do not work, such as "new $wnd.ActionDescriptor()" even if $wnd is aliased to the global Application object.
Currently GenerateJavaScriptAST::createJsQualifier is hardcoded to prepend "$wnd." to a js qualified name. The problem can be solved if the global object alias is customizable and createJsQualifer returns the original name when the alias is an empty string.
I can work out a patch if this feature request is accepted.

**Comment by tbroyer** [comment]
I wonder whether it's a bug of ExtendScript…

As a workaround, couldn't you assign constructors as properties of the global object from the selection script (just after you setup `$wnd` for instance, do `$wnd.ActionDescriptor=ActionDescriptor`)

**Comment by dreifachstein** [comment]
I misread the documentation. The global object is different from the ps 'app' object and does indeed have the ActionDescriptor property.
