### ISSUE TITLE
Long emulation is caching NaN at index 128 and is always returning NaN when we try to marshall 0

### ISSUE THREAD

**Issue by suneelv** [gwtproject/gwt#9278]
https://github.com/gwtproject/gwt/blob/2.8.0-beta1/user/super/com/google/gwt/emul/java/lang/Long.java

  static class BoxedValues {
    // Box values according to JLS - between -128 and 127
    static Long[] boxedValues = new Long[256];
  }

  public static Long valueOf(long i) {
    if (i > -129 && i < 128) {
      int rebase = (int) i + 128;
      Long result = BoxedValues.boxedValues[rebase];
      if (result == null) {
        result = BoxedValues.boxedValues[rebase] = new Long(i);
      }
      return result;
    }
    return new Long(i);
  }

If this method is called with NaN as parameter initially , then in the boxedValues array NaN is stored at index 128, and whenever 0 has to marshalled, it goes to the array and finds NaN and is returning NaN instead of 0.

Please fix this bug

**Comment by tbroyer** [comment]
Can you provide a small repro-case? (or even better, a patch, given you already traced the issue down to that part of code)
Where is the NaN coming from?

(I wonder if the fix should be here –looking for a "NaN long", which theoretically couldn't happen– or in the compiler and `LongLib`, when casting the number to a `long` before calling this method).

**Comment by suneelv** [comment]
thank you for the quick response.
The NaN value is coming from outside javascript.
A javascript method of ours returned NaN due to a bug, and then it is passed to valueOf method. It all happens during runtime.

**Comment by suneelv** [comment]
The quick fix we thought of was, to initialize the boxedValues[128] with 0, so that NaN won't be cached and will always return 0 instead of NaN when we try to marshall 0L

**Comment by tbroyer** [comment]
How is the NaN coming in from JSNI? Passed to Java method as `long` argument? `double` argument and then cast to `long`? Returned from JSNI method as `long`? as `double`?

Re. the workaround, in other words, call `Long.valueOf(0)` from your `onModuleLoad`?

**Comment by suneelv** [comment]
Here are the snippets 
public static native int someMethodWhichReturnsNaN() /*-{

                                                          return timeSpent; // assume that this returns NaN
                                                          }-*/;

And elsewhere in the code, we were doing  Long.valueOf(timeSpent)

Shouldn't this through an exception, instead of storing NaN in the array?

**Comment by dankurka** [comment]
If you are writing jsni methods you are responsible for making sure that
they return the correct type. The compiler does not verify this since it
would lead to massive blow. The JSNI author is responsible for the
correctness of that method. Adding checks in many places through out the
code base will blow up everything.

Fix your jsni to be:

public static native int foo() /*-{
  return timeSpent | 0;
}-*/;
