### ISSUE TITLE
Linker Error

### ISSUE THREAD

**Issue by gwidgets** [gwtproject/gwt#9279]
Hi,

When adding an sso linker to my project, I get the following error when trying to compile:
 
[ERROR] linkers other than CrossSiteIFrameLinker aren't supported. Found: com.google.gwt.core.linker.SingleScriptLinker

Anybody familiar with this error ?

**Comment by tbroyer** [comment]
SuperDevMode only works with the CrossSiteIFrameLinker (which is the default linker one BTW); compilation should work though.

Also, please use https://groups.google.com/forum/#!forum/google-web-toolkit or StackOverflow for support questions; only use this issue tracker to raise bugs.
