### ISSUE TITLE
Permanent recompiling of GWT modules(no changes made ot sources)

### ISSUE THREAD

**Issue by FeyFre** [gwtproject/gwt#9280]
Affected 2.7.0
Simple maven war project.
mvn clean package builds everything
if next issue command
mvn package
it rebuilds gwt modules again(no files was changed)
Problem is in: generated <modulename>.nocache.js timestamp set to timestamp of <modulename>.gwt.xml source file, instead of compilation time(other files set to compilation time). In case when client java sources change more often than module definition file(i.e in most development cases) - it causes problem(.java files always newer than module file).  

In 2.8 it fixed by https://github.com/gwtproject/gwt/issues/9108 I think, but I need it in 2.7 also(2.8 release date unknown).
Attached simple project which reproduces issue

**Comment by FeyFre** [comment]
Attachment

**Comment by FeyFre** [comment]
Attachment
[simple.zip](https://github.com/gwtproject/gwt/files/129167/simple.zip)

**Comment by tbroyer** [comment]
There won't be a 2.7.1, so either use 2.8.0-beta1 or make your own patched 2.7.
Or workaround it: net.ltgt.gwt.maven:gwt-maven-plugin has a workaround, org.codehaus.mojo:gwt-maven-plugin does not.

**Comment by FeyFre** [comment]
Is that drop-in replacement? Or I need add some configuration?

**Comment by FeyFre** [comment]
> patched 2.7.
Any particular commit?

**Comment by tbroyer** [comment]
> Is that drop-in replacement? Or I need add some configuration?

See https://tbroyer.github.io/gwt-maven-plugin/migrating.html and https://github.com/gwtproject/gwt/commit/a0de97b999468b12d6c19d6a470ca03b2a2b4557 as an example of such migration.

> Any particular commit?

That one https://gwt-review.googlesource.com/13918 (use the "download" dropdown on the top right to easily cherry-pick it to your local clone of the `release/2.7` branch)
