### ISSUE TITLE
NullPointerException on compilation

### ISSUE THREAD

**Issue by solomatov** [gwtproject/gwt#9283]
I have the following exception

[INFO] java.lang.NullPointerException
[INFO] 	at com.google.gwt.dev.jjs.ast.JTypeOracle.recomputeAfterOptimizations(JTypeOracle.java:922)
[INFO] 	at com.google.gwt.dev.jjs.JavaToJavaScriptCompiler.optimizeJavaOneTime(JavaToJavaScriptCompiler.java:1526)
[INFO] 	at com.google.gwt.dev.jjs.JavaToJavaScriptCompiler.optimizeJavaToFixedPoint(JavaToJavaScriptCompiler.java:1469)
[INFO] 	at com.google.gwt.dev.jjs.JavaToJavaScriptCompiler.optimizeJava(JavaToJavaScriptCompiler.java:521)
[INFO] 	at com.google.gwt.dev.jjs.JavaToJavaScriptCompiler.compilePermutation(JavaToJavaScriptCompiler.java:360)
[INFO] 	at com.google.gwt.dev.jjs.JavaToJavaScriptCompiler.compilePermutation(JavaToJavaScriptCompiler.java:272)
[INFO] 	at com.google.gwt.dev.CompilePerms.compile(CompilePerms.java:198)
[INFO] 	at com.google.gwt.dev.ThreadedPermutationWorkerFactory$ThreadedPermutationWorker.compile(ThreadedPermutationWorkerFactory.java:50)
[INFO] 	at com.google.gwt.dev.PermutationWorkerFactory$Manager$WorkerThread.run(PermutationWorkerFactory.java:74)
[INFO] 	at java.lang.Thread.run(Thread.java:745)
[INFO]       [ERROR] Unrecoverable exception, shutting down
[INFO] com.google.gwt.core.ext.UnableToCompleteException: (see previous log entries)
[INFO] 	at com.google.gwt.dev.javac.CompilationProblemReporter.logAndTranslateException(CompilationProblemReporter.java:112)
[INFO] 	at com.google.gwt.dev.jjs.JavaToJavaScriptCompiler.compilePermutation(JavaToJavaScriptCompiler.java:459)
[INFO] 	at com.google.gwt.dev.jjs.JavaToJavaScriptCompiler.compilePermutation(JavaToJavaScriptCompiler.java:272)
[INFO] 	at com.google.gwt.dev.CompilePerms.compile(CompilePerms.java:198)
[INFO] 	at com.google.gwt.dev.ThreadedPermutationWorkerFactory$ThreadedPermutationWorker.compile(ThreadedPermutationWorkerFactory.java:50)
[INFO] 	at com.google.gwt.dev.PermutationWorkerFactory$Manager$WorkerThread.run(PermutationWorkerFactory.java:74)
[INFO] 	at java.lang.Thread.run(Thread.java:745)

**Comment by solomatov** [comment]
Here's the screenshot of the debugger at this position: http://postimg.org/image/jsdyirvd3/

**Comment by solomatov** [comment]
This bug is indeterministic and probability of having it on the project is about 1/2.

**Comment by solomatov** [comment]
If I look to the stacktrace, the exception happens before any real optimizations, i.e it's just pass 1.

**Comment by solomatov** [comment]
This bug happens when we have source code intersection in different gwt modules. gwt maven plugin picks up them, first compile goes well, but the second results in error. Splitting source directories fixed the problem.

**Comment by gkdn** [comment]
@rluble Can you take a quick look and see if there is an easy fix when you have time?

**Comment by rluble** [comment]
Could you post a repro case?

**Comment by notz** [comment]
I experience the same issue. I have a project with 2 modules where some code is shared. If i only compile one, it's working. But if i want to compile both i get the follwoing exception (with beta1 but also with latest SNAPSHOT):

[INFO]    Replacing GWT.runAsync with island loader calls
[INFO]    Looking up initial load sequence for split points
[INFO]    Initial load sequence of split points: (none)
[INFO]    Compiling 1 permutation
[INFO]       Creating PermutationWorkerFactory instances
[INFO]       Compiling permutation 0...
[INFO]       [ERROR] Unexpected internal compiler error
[INFO] java.lang.NullPointerException
[INFO] 	at com.google.gwt.dev.jjs.ast.JTypeOracle.recomputeAfterOptimizations(JTypeOracle.java:880)
[INFO] 	at com.google.gwt.dev.jjs.JavaToJavaScriptCompiler.optimizeJavaOneTime(JavaToJavaScriptCompiler.java:1526)
[INFO] 	at com.google.gwt.dev.jjs.JavaToJavaScriptCompiler.optimizeJavaToFixedPoint(JavaToJavaScriptCompiler.java:1469)
[INFO] 	at com.google.gwt.dev.jjs.JavaToJavaScriptCompiler.optimizeJava(JavaToJavaScriptCompiler.java:522)
[INFO] 	at com.google.gwt.dev.jjs.JavaToJavaScriptCompiler.compilePermutation(JavaToJavaScriptCompiler.java:360)
[INFO] 	at com.google.gwt.dev.jjs.JavaToJavaScriptCompiler.compilePermutation(JavaToJavaScriptCompiler.java:272)
[INFO] 	at com.google.gwt.dev.CompilePerms.compile(CompilePerms.java:198)
[INFO] 	at com.google.gwt.dev.ThreadedPermutationWorkerFactory$ThreadedPermutationWorker.compile(ThreadedPermutationWorkerFactory.java:50)
[INFO] 	at com.google.gwt.dev.PermutationWorkerFactory$Manager$WorkerThread.run(PermutationWorkerFactory.java:74)
[INFO] 	at java.lang.Thread.run(Thread.java:745)
[INFO]       Permutation took 168 ms
[INFO]       [ERROR] Unrecoverable exception, shutting down
[INFO] com.google.gwt.core.ext.UnableToCompleteException: (see previous log entries)
[INFO] 	at com.google.gwt.dev.javac.CompilationProblemReporter.logAndTranslateException(CompilationProblemReporter.java:112)
[INFO] 	at com.google.gwt.dev.jjs.JavaToJavaScriptCompiler.compilePermutation(JavaToJavaScriptCompiler.java:459)
[INFO] 	at com.google.gwt.dev.jjs.JavaToJavaScriptCompiler.compilePermutation(JavaToJavaScriptCompiler.java:272)
[INFO] 	at com.google.gwt.dev.CompilePerms.compile(CompilePerms.java:198)
[INFO] 	at com.google.gwt.dev.ThreadedPermutationWorkerFactory$ThreadedPermutationWorker.compile(ThreadedPermutationWorkerFactory.java:50)
[INFO] 	at com.google.gwt.dev.PermutationWorkerFactory$Manager$WorkerThread.run(PermutationWorkerFactory.java:74)
[INFO] 	at java.lang.Thread.run(Thread.java:745)
[INFO]       [ERROR] Not all permutation were compiled , completed (0/1)

The stack trace is with latest snapshot.

**Comment by notz** [comment]
The issue seems to related to #9155

**Comment by tbroyer** [comment]
Closing as duplicate.
