### ISSUE TITLE
With JSInterop Integer and Date type wrong converted

### ISSUE THREAD

**Issue by frami** [gwtproject/gwt#9286]
The value of Date and Integer Objects are wrong converter. 
I have a bean with getter and setter of type Integer, Double, Boolean and Date:
```
@JsType
public class SolarImpl
    implements Solar {
  @JsProperty
  public native Date getFlaeche();
  @JsProperty
  public native void setFlaeche(Date flaeche);
  @JsProperty
  public native Integer getBaujahr();
  @JsProperty
  public native void setBaujahr(Integer baujahr);
....

```
When I set this values:
```
solarItem.setBaujahr(new Integer(1));
solarItem.setFlaeche(new Date());
solarItem.setLeistung(new Boolean(true));
solarItem.setWert(new Double(1.1));
```

I get this. The Double and Boolean are correct, but the Integer and Date are wrong.
```
solarItem_1_g$: Object
    baujahr: yHf_g$
    flaeche: SRd_g$
    leistung: true
    wert: 1.1
```

**Comment by tbroyer** [comment]
This is expected for the `Date` (use a `JsDate` instead), not really sure about `Integer` (might be "expected for now, will be changed later").

**Comment by gkdn** [comment]
Also true for Integer. Only primitives (except long) plus Double and Boolean works seamlessly. You should be already getting a warning about this in your compile.
