### ISSUE TITLE
GWT Upload (com.googlecode.gwtupload:gwtupload:1.0.1) does not work with  gwt 2.8.0-SNAPSHOT

### ISSUE THREAD

**Issue by detlef-brendle** [gwtproject/gwt#9290]
Hello,

we upgraded to gwt 2.8.0 and face an issue with the gwtupload library.

Pressing on a Upload button, which uses the SingleUploader class opens the Client file chooser dialog.
After selecting a file that used to be accepted with gwt 2.6 code nothing happens.
Updating the gwtupload plugin th 1.0.3 gets one step further but then it ends in the infinite loop issue that is already reported (https://github.com/manolo/gwtupload/issues/11)

Now I dont know if this is something for the gwt core team or for the plugin guys.

Can anybody help here ?

thanks,
Detlef

**Comment by jnehlmeier** [comment]
Not sure if thats really a GWT issue since FormPanel and FileUpload both haven't really changed since GWT 2.7. And the difference between GWT 2.6 and GWT 2.7 is that IE 6 and Opera <= 12 support has been removed.

**Comment by dankurka** [comment]
Since this is likely not code in GWT proper closing off here.

**Comment by lanman2000** [comment]
detlef did you ever resolve this issue? We have the exact same problem.

**Comment by detlef-brendle** [comment]
Unfortunately no. There seems to be not much activity on the gwtupload plugin recently.
I cannot upgrade my project to 2.8.0 unless I have a solution for this issue.

**Comment by lanman2000** [comment]
We're in the same boat. That's the danger with open source. We're likely
going to abandon it entirely and rewrite our upload feature using the built
in FileUpload or something else.

**Comment by tbroyer** [comment]
…or use the latest snapshot (there appears to have been a fix for this issue), contribute additional fixes if needed, propose to help maintaining the project, etc.
That's the good thing with open source: you're not forced to go on your own reinventing the wheel inside each and every company, you can benefit from others' work, and contribute what you've done so others benefit from your work ;-)

**Comment by lanman2000** [comment]
Yes there appears to be a fix but it introduces another infinite loop issue
unfortunately. We are going to try to fix it. We'll see...
