### ISSUE TITLE
JSP Support not working after update to JEtty 9.2

### ISSUE THREAD

**Issue by bauna** [gwtproject/gwt#9292]
After updating to Jetty 9.2 in GWT 2.8 the JSP support is not working any more during debug (it doesn't matter if you use SDM o DM).
It seems that since Jetty 9.2[1] jsp support is not enabled by default and need to enabled when embedding. As a workaround you can add this snippet[2] to web.xml.
I don't know if I this expected or I should fill a bug.

[1] http://www.eclipse.org/jetty/documentation/current/configuring-jsp.html

[2] Code Snippet
```
 <servlet id="jsp">
    <servlet-name>jsp</servlet-name>
    <servlet-class>org.apache.jasper.servlet.JspServlet</servlet-class>
    <init-param>
        <param-name>logVerbosityLevel</param-name>
        <param-value>DEBUG</param-value>
    </init-param>
    <init-param>
        <param-name>fork</param-name>
        <param-value>>false</param-value>
    </init-param>
    <init-param>
        <param-name>keepgenerated</param-name>
        <param-value>>true</param-value>
    </init-param>
    <load-on-startup>0</load-on-startup>
  </servlet>
 
  <servlet-mapping>
    <servlet-name>jsp</servlet-name>
    <url-pattern>*.jsp</url-pattern>
    <url-pattern>*.jspf</url-pattern>
    <url-pattern>*.jspx</url-pattern>
    <url-pattern>*.xsp</url-pattern>
    <url-pattern>*.JSP</url-pattern>
    <url-pattern>*.JSPF</url-pattern>
    <url-pattern>*.JSPX</url-pattern>
    <url-pattern>*.XSP</url-pattern>
  </servlet-mapping>
```

**Comment by tbroyer** [comment]
After a quick test, we'd need to add the following JARs:
```
org.eclipse.jetty:apache-jsp:jar:9.2.14.v20151106
org.mortbay.jasper:apache-jsp:jar:8.0.9.M3
org.mortbay.jasper:apache-el:jar:8.0.9.M3
```
in place of the really old ones we're currently shipping:
```xml
           <!-- dependencies needed for JSP support in DevMode: BEGIN -->
           <zipfileset src="${gwt.tools.lib}/tomcat/commons-el-1.0.jar"/>
           <zipfileset src="${gwt.tools.lib}/tomcat/jasper-compiler-1.0.jar"/>
           <zipfileset src="${gwt.tools.lib}/tomcat/jasper-runtime-1.0.jar"/>
           <zipfileset src="${gwt.tools.lib}/tomcat/jsp-api-2.0.jar"/>
           <!-- dependencies needed for JSP support in DevMode: END -->
```

Current workaround adding dependency on `org.eclipse.jetty:apache-jsp` (excluding JDT) works without modification to the `web.xml`:
```xml
    <dependency>
      <groupId>org.eclipse.jetty</groupId>
      <artifactId>apache-jsp</artifactId>
      <version>9.2.14.v20151106</version>
      <scope>provided</scope>
      <exclusions>
        <exclusion>
          <groupId>org.eclipse.jetty.orbit</groupId>
          <artifactId>org.eclipse.jdt.core</artifactId>
        </exclusion>
      </exclusions>
    </dependency>
```
This is because Jetty's built-in `webdefault.xml` is used (as we embed Jetty but use its webapp support), which configures the `JettyJspServlet` by default for JSPs, so all we have to do is add it to the classpath.

**Comment by bauna** [comment]
Hi Thomas,
Thanks for the cleaner workaround and fast response. 
BTW the above workaround works if the new dependency is the last dep in the pom.xml

**Comment by tbroyer** [comment]
OK, not exactly as easy as it seemed; as you mentioned this works because the new dep enables the `org.apache.jasper.servlet.JspServlet`, but only works when the old class bundled in `gwt-dev` is used, not the new one. So when replacing the old JARs with the new, more work has to be done.

**Comment by bauna** [comment]
What do you of think manually adding the jsp servet in the JettyLauncher class, something like 8e533bf99e6b3239fa50e9be616d9f1639362056.
We can also add some options to the launcher for disabling jsp servlet or change init params.

**Comment by tbroyer** [comment]
Managed to make it work; this also enables annotations scanning, which was requested a few times.

https://gwt-review.googlesource.com/14460
