### ISSUE TITLE
Compilation ends in an infinite loop with errorneous recursion in the code.

### ISSUE THREAD

**Issue by pgazdik** [gwtproject/gwt#9297]
In my case, a one-liner method which only calls itself ended up with GWT compilation that is stuck in an infinite loop, where the _JsInliner_ kept saying it did some change, thus the optimization process never stopped.

Example code:
```java
public T create(Factory<T> factory) {
    return create(factory);
}
```
I think such case should be recognized and ideally the compilation should fail with an error.

Note that it is (of course) necessary to build with the "draftCompile" option being OFF.

**Comment by rluble** [comment]
Does it happen if you declare it static also? JsInliner colllects potentally recursive functions using RecursionVisitor, and exclude those from inlining.

**Comment by pgazdik** [comment]
Yes, declaring it static had no effect, infinite loop again.

**Comment by rluble** [comment]
I could not reproduce the failure using just the snippet by itself. It is possible that the failure only happens as an interaction between different optimizations. Please reopen with a complete minimal repro case.
