### ISSUE TITLE
Type inference compilation error when using Java 8 lambdas with GWT 2.8.0-beta1

### ISSUE THREAD

**Issue by dharezlak** [gwtproject/gwt#9299]
The following code:

```java
SettableFuture<List<String>> stringsFuture = SettableFuture.create();
stringsFuture.set(Arrays.asList("first", "second"));
		
ListenableFuture<List<Integer>> stringLengths = transform(stringsFuture, strings ->
				Lists.transform(strings, string -> string.length()));
```

gives a compilation error when compiled as a client-side code with GWT:

`Type mismatch: cannot convert from ListenableFuture<Object> to ListenableFuture<List<Integer>>`

When run in plain Java the code works well.

The testing environment consisted of GWT 2.8.0-beta1, guava-gwt 20.0-SNAPSHOT and Java 1.8.0_74.

To make it work change the last line to:

```java
Lists.transform(strings, string -> new Integer(string.length())));
```

The same thing happens when the final list contains strings and unless the last line in such case goes like this: `new String([a method call returning a string])` similar compilation error is reported and the whole compilation process fails.

**Comment by rluble** [comment]
GWT uses JDT to parse and typecheck java source, there are a few bug reports in the JDT bug tracker related to type inference.

**Comment by dharezlak** [comment]
The problem does not show up in Eclipse Mars.2 (which, I am assuming, also uses JDT) when I edit the source. Does this mean that upgrading the JDT dependency in GWT will solve the issue?

**Comment by rluble** [comment]
Could you try with the latest snapshot. The latest snapshot has that dependency already updated to Mars.2

**Comment by dharezlak** [comment]
Using the latest snapshot helps indeed. Closing the issue...
