### ISSUE TITLE
Provide a way to pass Enums to JsType native methods

### ISSUE THREAD

**Issue by pstockley** [gwtproject/gwt#9303]
Having actual enums is a big win with using Java over javascript. I would like some way to be able to pass an enum to a native javascript function. Ideally you should be able to define in the enum the actual value that would be passed to javascript. I can think of a few possibilities

1) Call toString() on the Enum value and pass that.
2) Call name() on the Enum and pass that.
3) Call a function with a specific annotation set. This would be the most flexible as you could return non string types.

**Comment by dnouls** [comment]
In my case I would need case 3. An enum mapped to an integer. Or will
declaring the enum as a JsType automatically take the order of the enum ?

**Comment by gkdn** [comment]
We are not planning to do Enum ordinilization for GWT 2.8.

**Comment by pstockley** [comment]
Is it planned for a future 2.x release?

**Comment by gkdn** [comment]
It is not planned for a 2.x release.

**Comment by niloc132** [comment]
Closing in favor of https://github.com/gwtproject/gwt/issues/9794 - this appears to be possible with the `@JsEnum` annotation that J2CL supports, but `@JsType` will never make sense here.
