### ISSUE TITLE
Update emulation of java.lang.annotation.ElementType for Java 8

### ISSUE THREAD

**Issue by atomicknight** [gwtproject/gwt#9308]
Java 8 added two new members to the `java.lang.annotation.ElementType` enum: `TYPE_PARAMETER` and `TYPE_USE`. The current emulation of this enum is missing these members, which prevents the use of JSR 308 type annotations in source code even though JDT supports them.

**Comment by tbroyer** [comment]
Good catch!
Also missing were `@Repeatable` and `@Native`: https://gwt-review.googlesource.com/14600
