### ISSUE TITLE
function window.confirm(str) is not working VS2015

### ISSUE THREAD

**Issue by Vikrant-jain** [gwtproject/gwt#9309]
Hello Guys!!

function window.confirm(str) {
execScript('n = msgbox("' + str + '","4132")', "vbscript");
}

is not working. It throws error "JavaScript critical error at line 942, column 24 in http://localhost:1234/JavaScript/abcd.js\n\nSCRIPT1002: Syntax error"
This happens when I am migrating solution from VS2012 to VS2015.

Could you suggest possible solutions?

Thanks!

**Comment by tbroyer** [comment]
Wrong issue tracker?
