### ISSUE TITLE
Document breaking change for GIN

### ISSUE THREAD

**Issue by tbroyer** [gwtproject/gwt#9311]
https://github.com/gwtproject/gwt/commit/1d660d2fc00a5cbfeccf512251f78ab4302ab633 breaks GIN 2.1.2, and suggests a workaround. This should be included in the release notes.

**Comment by dankurka** [comment]
Assigning to Julien since he has been taken care of the release docs for 2.8.0-beta1 and he already has the release notes assigned for rc1

**Comment by jnehlmeier** [comment]
Has been documented as part of the RC1 release notes

**Comment by Koozamo** [comment]
Does this mean that Gin is no longer compatible in GWT 2.8.0, or is there a workaround?

**Comment by tbroyer** [comment]
The commit message linked above says it all:

Use
    -setProperty gin.classloading.exceptedPackages=com.google.gwt.core.client,com.google.gwt.core.client.impl

(or set that property in your gwt.xml with `<set-configuration-property>`)

You'll also have to use a JDK 8.

**Comment by trohr** [comment]
Hello,
I have compiled our application with GWT 2.8.2 and GIN 2.1.2 and so far I cannot see any issues.

Can you please explain the issue in some detail?
- what is the kind of breakage that GWT 2.8.0+ has with GIN 2.1.2?
- is this issue current with GWT 2.8.2 and GIN 2.1.2?
- what is the current recommended solution?

Thank you.
