### ISSUE TITLE
Generics in ListDataProvider#setList

### ISSUE THREAD

**Issue by stswoon** [gwtproject/gwt#9312]
Hi GWT-team. Thank you for your very good framework. 
On my opinion I've found small issue in ListDataProvider#setList. Today I need to 
add redundant line like

```
ListDataProvider<Child> dataProvider = new ListDataProvider<Child>();
List<Parent> list1 = new ArrayList<Parent>();
List<Child> list2 = new ArrayList<Child>(list1); //redundant line 
dataProvider.setList(list2);
```

Would be it better to use `setList(List<? extends T> listToWrap)` instead of `setList(List<T> listToWrap)`? I think using `? extends T` in this case correlated to PECS rule

Best regards, Anatoly.

**Comment by tbroyer** [comment]
The list will be used both for reading **and writing**, so it cannot use `? extends T`.

(sorry for the looong delay; I had starred the notification in my inbox at the time, and it got lost in the flood of many other mails; and I'm only trying to clean my inbox now)
