### ISSUE TITLE
DateUtils.addMonths(Date,int) bug

### ISSUE THREAD

**Issue by Marc358** [gwtproject/gwt#9315]
Hello there,
I've noticed that the function addMonths(Date,int); from DateUtils library adds weeks to a date, not months.

	/**
	 * Adds or subtracts the specified amount of months for the given Date.
	 * 
	 * @param date
	 *            A point in time
	 * @param months
	 *            Number of months to add or substract
	 * @return A new object <em>weeks</em> after to the passed <code>date</code>
	 */
	public static Date addMonths(final Date date, final int months) {
		return new Date(date.getTime() + (months * (MILLIS_IN_A_DAY * DAYS_IN_A_WEEK)));
	}  

Is the same function than DateUtils.addWeeks(Date,int):

	/**
	 * Adds or subtracts the specified amount of weeks for the given Date.
	 * 
	 * @param date
	 *            A point in time
	 * @param weeks
	 *            Number of weeks to add or substract
	 * @return A new object <em>weeks</em> after to the passed <code>date</code>
	 */
	public static Date addWeeks(final Date date, final int weeks) {
		return new Date(date.getTime() + (weeks * (MILLIS_IN_A_DAY * DAYS_IN_A_WEEK)));
	}

I've tested this functions using Firerfox 23.0, Windows 7 x64 and GWT 2.6.0

**Comment by jnehlmeier** [comment]
Which DateUtils library? I don't know any DateUtils class within GWT SDK. There is only CalendarUtil which is used by GWT's DatePicker but that method does not have the method addMonth() you have mentioned.
