### ISSUE TITLE
License should use GWT

### ISSUE THREAD

**Issue by akerekes** [gwtproject/gwt#9316]
The license text should use GWT  instead of Google Web Toolkit.

Files to be changed:

https://github.com/gwtproject/gwt/blob/master/distro-source/core/src/COPYING
https://github.com/gwtproject/gwt/blob/master/distro-source/core/src/COPYING.html

**Comment by branflake2267** [comment]
Do you have the capability of filing the issue here? 
https://github.com/GoogleCloudPlatform/google-plugin-for-eclipse/issues

**Comment by branflake2267** [comment]
Oh I see, the GWT licenses in the distro have Google Web Toolkit, and it needs to be changed to GWT, removing Google.

**Comment by jnehlmeier** [comment]
https://gwt-review.googlesource.com/#/c/14642/
