### ISSUE TITLE
Option -XdisableCastChecking seems to have disappeared from GWT 2.8-beta1

### ISSUE THREAD

**Issue by ltearno** [gwtproject/gwt#9318]
When running super dev mode with the **-XdisableCastChecking** option, i get the following error. Although this flag is still mentionned in the JsInterop specification [document](https://docs.google.com/document/d/10fmlEYIHcyead_4R1S5wKGs1t2I7Fnp_PaNaa7XTEk0/edit#).

Here is the output of SuperDevMode launcher :

```
Unknown argument: -XdisableCastChecking
Google Web Toolkit 2.8.0-beta1
DevMode [-[no]startServer] [-port port-number | "auto"] [-logdir directory] [-logLevel (ERROR|WARN|INFO|TRACE|DEBUG|SPAM|ALL)] [-gen dir] [-bindAddress host-name-or-address] [-codeServerPort port-number | "auto"] [-[no]superDevMode] [-server servletContainerLauncher[:args]] [-startupUrl url] [-war dir] [-deploy dir] [-extra dir] [-modulePathPrefix ] [-workDir dir] [-XmethodNameDisplayMode (NONE|ONLY_METHOD_NAME|ABBREVIATED|FULL)] [-sourceLevel [auto, 1.7, 1.8]] [-XjsInteropMode (JS|JS_RC)] [-[no]generateJsInteropExports] [-[no]incremental] [-setProperty name=value,value...] module[s] 

where 
  -[no]startServer               Starts a servlet container serving the directory specified by the -war flag. (defaults to ON)
  -port                          Specifies the TCP port for the embedded web server (defaults to 8888)
  -logdir                        Logs to a file in the given directory, as well as graphically
  -logLevel                      The level of logging detail: ERROR, WARN, INFO, TRACE, DEBUG, SPAM or ALL (defaults to INFO)
  -gen                           Debugging: causes normally-transient generated types to be saved in the specified directory
  -bindAddress                   Specifies the bind address for the code server and web server (defaults to 127.0.0.1)
  -codeServerPort                Specifies the TCP port for the code server (defaults to 9997 for classic Dev Mode or 9876 for Super Dev Mode)
  -[no]superDevMode              Runs Super Dev Mode instead of classic Development Mode. (defaults to ON)
  -server                        Specify a different embedded web server to run (must implement ServletContainerLauncher)
  -startupUrl                    Automatically launches the specified URL
  -war                           The directory into which deployable output files will be written (defaults to 'war')
  -deploy                        The directory into which deployable but not servable output files will be written (defaults to 'WEB-INF/deploy' under the -war directory/jar, and may be the same as the -extra directory/jar)
  -extra                         The directory into which extra files, not intended for deployment, will be written
  -modulePathPrefix              The subdirectory inside the war dir where DevMode will create module directories. (defaults empty for top level)
  -workDir                       The compiler's working directory for internal use (must be writeable; defaults to a system temp dir)
  -XmethodNameDisplayMode        EXPERIMENTAL: Specifies method display name mode for chrome devtools: NONE, ONLY_METHOD_NAME, ABBREVIATED or FULL (defaults to NONE)
  -sourceLevel                   Specifies Java source level (defaults to auto:1.8)
  -XjsInteropMode                EXPERIMENTAL: DEPRECATED: Specifies JsInterop mode: JS or JS_RC
  -[no]generateJsInteropExports  Generate exports for JsInterop purposes (defaults to OFF)
  -[no]incremental               Compiles faster by reusing data from the previous compile. (defaults to ON)
  -setProperty                   Set the values of a property in the form of propertyName=value1[,value2...].
and 
  module[s]                      Specifies the name(s) of the module(s) to host
```

**Comment by jnehlmeier** [comment]
Not all parameters of the GWT compiler have been made available as CodeServer parameter. You can only use -XdisableCastChecking when you compile your app for production using the GWT compiler.

**Comment by ltearno** [comment]
Is it planned ?

Le lun. 11 avr. 2016 13:14, Jens Nehlmeier <notifications@github.com> a
écrit :

**Comment by jnehlmeier** [comment]
Why would you need it during development/SDM where you want to detect wrong casts early? I don't think its planned for now.

**Comment by ltearno** [comment]
To have the same behavior between prod and dev environments... Let's say i
do (bad) things that the compiler thinks doesn't work but i know will work,
and for that i need to disable cast checking. But if the option is not
available in sdm, then my workflow is completely messed-up : i need to do a
full recompile each time i want to test my application... And i may even
not get source maps in the production mode...


Le lun. 11 avr. 2016 à 13:51, Jens Nehlmeier <notifications@github.com> a
écrit :

**Comment by jnehlmeier** [comment]
As I understand it disabling cast checking is for reducing the final JS output size and not so much about making bad things work.

Out of curiosity do you have a concrete example of such a bad thing you are doing? I assume it has to do with JsInterop.

**Comment by ltearno** [comment]
Yes, for example casting a @jsinterop class which wraps 'Array' to the T[]
class in java.

As i understand, String[] in java is compiled to JavaScript Array, so the
cast is technically possible but forbidden by gwt compiler.

Of course this would not work in the oopm dev mode...

Le mar. 12 avr. 2016 17:44, Jens Nehlmeier <notifications@github.com> a
écrit :

**Comment by gkdn** [comment]
I removed the reference from the doc.

CastChecking is replaced by more generalized and safer jre.checking.* configuration properties. It is safer because for example when you disable cast checking it will throw an AssertionError instead of CCE in dev mode to reduce the likelihood of relying on CCE by mistake.

**Comment by gkdn** [comment]
And Jens has mentioned, it is not for making bad things work, it is for reducing code size.
You can do unsafeCast via JSNI helpers but that could mess things up badly so be aware.

**Comment by tbroyer** [comment]
Would casting to an intermediate `Object` workaround the issue?

```java
Foo[] arr = (Foo[]) (Object) jsArr;
```

**Comment by gkdn** [comment]
String[] or any Foo array is currently only could be assigned by corresponding type or subtypes (i.e. needs a type marker). Otherwise you will see all kinds of weird behavior (e.g. System.arrayCopy failing, ArrayStoreExceptions not thrown, getClass not functioning properly etc.)
The exception to the rule is, JsType arrays which could be assigned by any array and doesn't do array store checking and will return JSO array for getClass.

**Comment by ltearno** [comment]
Thomas i tried that but did not work because the type info is kept in the
wrapped JS object...

Good thing is that is not blocking me integrating angular2 with gwt (it
just makes few more boilerplate lines). I think it will be awesome. Already
it supports 30% (approx.) of the angular2 tutorial.

After playing a bit, it feels a bit like Singular (minus Android and iOS of
course...)

Thanks!

Le mar. 12 avr. 2016 18:32, Thomas Broyer <notifications@github.com> a
écrit :

**Comment by ibaca** [comment]
Sorry, I do not understand exactly when is safe to use JsType arrays 😢 , actually not sure what is a JsType array. You mean a T[] where T is any type annotated with @JsType? Asking because you said there is an exception to the rule, so if there is an exception this means that this kind of arrays are safe?

I'm developing this RestyGWT simplified clone (https://github.com/intendia-oss/autorest-gwt/blob/master/core/src/main/java/com/intendia/gwt/autorest/client/Method.java#L76) and I do some "unsafe"  (I need to understand if are or aren't safe). The thing is that this two method should returns the same; the first works but the later throws a cast exception which I think is exactly the same @ltearno case.
```java
Observable<JsFoo> requestFoosAsStream().subscribe(next -> …);
Single<JsFoo[]> requestFoosAsArray().subscribe(next -> …);
```
The thing is that the exception is thrown when the "next" field is reached, but the internal (autorest.client.Method) T[] is just ignored (at least do not throws any class cast exception).

So the question might be, if I'm sure that T is always a @JsType is this code safe?

**Comment by gkdn** [comment]
If you are sure that T is always JsType(isNative=true), the code is safe. For the isNative=false case, I thought it had the same behavior but I was incorrect.

Being said that; a cast being safe has two sides of the equation; I can't say more without seeing the right hand side. If you have a reference array instance, you can always create another instance using that via Array.copyOf(reference, 0)

**Comment by ltearno** [comment]
OK thanks a lot, that clarifies the thing.

Le mer. 13 avr. 2016 à 17:47, Goktug Gokdogan <notifications@github.com> a
écrit :
