### ISSUE TITLE
SuperDevMode does not support the -generateJsInteropExports

### ISSUE THREAD

**Issue by ltearno** [gwtproject/gwt#9320]
Sadly, when one launches the superdevmode with the **-generateJsInteropExports**, the sdm fails with this error :

```
Runing CodeServer with parameters: [-noprecompile, -port, 9876, -sourceLevel, 1.8, -bindAddress, 127.0.0.1, -launcherDir, C:\Documents\Repos\angular2-gwt\target\angular2-gwt-1.0-SNAPSHOT, -logLevel, INFO, -generateJsInteropExports, JS_RC, -style, OBFUSCATED, fr.lteconsulting.angular2gwt.Angular2Gwt]
Super Dev Mode starting up
   workDir: C:\Users\Arnaud\AppData\Local\Temp\gwt-codeserver-4301561638722279982.tmp
   Loading inherited module 'JS_RC'
      [ERROR] Unable to find 'JS_RC.gwt.xml' on your classpath; could be a typo, or maybe you forgot to include a classpath entry for source?
```

I launch the thing from Eclipse with the Google Plugin for Eclipse.

Note that the maven builds correctly with `<generateJsInteropExports>true</generateJsInteropExports>`

I use the **2.8.0-beta1** version from Maven Central

Maybe am i missing something ?

**Comment by tbroyer** [comment]
That's a known issue with 2.8.0-beta1 and has been fixed already: https://github.com/gwtproject/gwt/issues/9223

(note: I highly suggest using a snapshot rather than beta1 for JsInterop work)

**Comment by ltearno** [comment]
OK sorry, i am definitely be using the SNAPSHOT version from now on so that my reports are useful...
