### ISSUE TITLE
Documentation for GWT-RPC v7 payload format ?

### ISSUE THREAD

**Issue by tinduong94** [gwtproject/gwt#9321]
Is there any documentation for GWT-RPC version 7 payload format ?

**Comment by jnehlmeier** [comment]
Not sure if it matches version 7 but it gives a general understanding of the wire format of GWT-RPC:

https://plus.google.com/+BrianSlesinsky/posts/7JLYQ61dW14

For more detailed information you have to look into the source code yourself.
