### ISSUE TITLE
GWT 2.8.0-beta1 doesn't work with Guava 20.0-SNAPSHOT:errorprone and jsobc needed

### ISSUE THREAD

**Issue by AlexLuya** [gwtproject/gwt#9323]
Hello,
       I have tried to fix this issue:
          https://github.com/google/closure-compiler/pull/1327
       and this leads me to a new issue:
````java
 [ERROR] Errors in 'com/google/common/collect/Lists.java'
            [ERROR] Line 36: The import com.google.errorprone cannot be resolved
           .....
            [ERROR] Line 161: CanIgnoreReturnValue cannot be resolved to a type
         Tracing compile failure path for type 'com.google.common.collect.Lists'
         [ERROR] Hint: Your source appears not to live underneath a subpackage called 'client'; no problem, but you'll need to use the <source> directive in your module to make it accessible
         [ERROR] Errors in 'com/google/common/collect/RegularImmutableAsList.java'
            [ERROR] Line 21: The import com.google.j2objc cannot be resolved
            [ERROR] Line 32: Weak cannot be resolved to a type
  .....
               [ERROR] Line 231: CanIgnoreReturnValue cannot be resolved to a type
         [ERROR] Hint: Your source appears not to live underneath a subpackage called 'client'; no problem, but you'll need to use the <source> directive in your module to make it accessible
````

And I have put:
````java
      error_prone_annotations-2.0.10-20160409.000718-5.jar
````
into to build path,but problem still exists,and I can't figure out where to download the jar of jsobc,should I download that 600mb+ zip source?

**Comment by jnehlmeier** [comment]
From Guava pom.xml (master branch):

```xml
      <dependency>
        <groupId>com.google.errorprone</groupId>
        <artifactId>error_prone_annotations</artifactId>
        <version>2.0.2</version>
      </dependency>
      <dependency>
        <groupId>com.google.j2objc</groupId>
        <artifactId>j2objc-annotations</artifactId>
        <version>0.1</version>
      </dependency>
```

**Comment by AlexLuya** [comment]
I don't not use maven,so I download these two jars from maven center and drop them to war/lib,and the problem still exist.I doubt it is because both of them aren't gwt modules.am I right?

**Comment by jnehlmeier** [comment]
These libraries must be present on classpath of your DevMode / CodeServer / GWT Compiler run configuration. They must not be GWT modules. You also don't need to deploy these libraries on your server so putting them into war/WEB-INF/lib is probably not the best option, but that is up to you.

I have an older local branch in one of my apps that uses guava 20 snapshot from mid february. I have used j2objc-annotations-0.9.8 and error_prone_annotations-2.0.8 and it worked as expected.

**Comment by AlexLuya** [comment]
Thanks,after removing all .classes and unitcache,compilation passes.I actually use guava in server side,so I probably should keep related stuff in war/WEB-INF/lib.

**Comment by dankurka** [comment]
I think there is nothing to do from the GWT side here, closing this off.
