### ISSUE TITLE
default method not found in inheritance tree

### ISSUE THREAD

**Issue by MousePilots** [gwtproject/gwt#9326]
In a largish inheritance tree consisting of several interfaces and (abstract) classes, default methods get lost. Unfortunately I couldn't reproduce this issue in a small code example. A larger example is available on https://github.com/MousePilots/EntityScenarios.git:

1) build the entire project
2) deploy es-test-web on a JEE 7 server (stock Glassfish 4.1 without configuration should do)
3) do mvn gwt:run and browse to http://localhost:8080/es-test-web/index.html

You'll get a browser failure on invocation of org.mousepilots.es.core.model.EntityTypeES.getPersistenceType() noting the function is not found.

Pushing the method down to org.mousepilots.es.core.model.impl.EntityTypeESImpl is a workaround.

I'm using GWT 2.8.0-SNAPSHOT (issue encountered using the march 4, 2016 snapshot)

**Comment by rluble** [comment]
Could you try at the current snapshot?

**Comment by rluble** [comment]
Reopen if reproducible at the current snapshot. If the bug is reproducible please post a command line invocation to the compiler with the relevant flags (as opposed to instructions that involve maven)

**Comment by MousePilots** [comment]
Tried with new snapshots, same issue pops up in sub-interfaces of PluralAttributeES.createEmpty() which have concrete default implementations. The compiler invocation is given below.

C:\Program Files\Java\JDK8\jre\bin\java -Xmx1024m -classpath C:\FastDocuments\NetBeansProjects\EntityScenarios\test\es-test-web\target\classes;C:\FastDocuments\NetBeansProjects\EntityScenarios\test\es-test-web\src\main\java;C:\FastDocuments\NetBeansProjects\EntityScenarios\test\es-test-web\target\generated-sources;C:\Users\jgeenen.PCJURJEN\.m2\repository\org\mousepilots\es-core\0.1-SNAPSHOT\es-core-0.1-SNAPSHOT.jar;C:\Users\jgeenen.PCJURJEN\.m2\repository\org\mousepilots\es-core\0.1-SNAPSHOT\es-core-0.1-SNAPSHOT-sources.jar;C:\Users\jgeenen.PCJURJEN\.m2\repository\org\mousepilots\es-server\0.1-SNAPSHOT\es-server-0.1-SNAPSHOT.jar;C:\Users\jgeenen.PCJURJEN\.m2\repository\org\mousepilots\es-test-domain-mmx\0.1-SNAPSHOT\es-test-domain-mmx-0.1-SNAPSHOT.jar;C:\Users\jgeenen.PCJURJEN\.m2\repository\org\mousepilots\es-test-domain\0.1-SNAPSHOT\es-test-domain-0.1-SNAPSHOT.jar;C:\Users\jgeenen.PCJURJEN\.m2\repository\org\mousepilots\es-test-domain\0.1-SNAPSHOT\es-test-domain-0.1-SNAPSHOT-sources.jar;C:\Users\jgeenen.PCJURJEN\.m2\repository\org\hibernate\javax\persistence\hibernate-jpa-2.1-api\1.0.0.Final\hibernate-jpa-2.1-api-1.0.0.Final.jar;C:\Users\jgeenen.PCJURJEN\.m2\repository\org\hibernate\hibernate-entitymanager\4.3.11.Final\hibernate-entitymanager-4.3.11.Final.jar;C:\Users\jgeenen.PCJURJEN\.m2\repository\org\jboss\logging\jboss-logging-annotations\1.2.0.Beta1\jboss-logging-annotations-1.2.0.Beta1.jar;C:\Users\jgeenen.PCJURJEN\.m2\repository\org\hibernate\hibernate-core\4.3.11.Final\hibernate-core-4.3.11.Final.jar;C:\Users\jgeenen.PCJURJEN\.m2\repository\antlr\antlr\2.7.7\antlr-2.7.7.jar;C:\Users\jgeenen.PCJURJEN\.m2\repository\org\jboss\jandex\1.1.0.Final\jandex-1.1.0.Final.jar;C:\Users\jgeenen.PCJURJEN\.m2\repository\dom4j\dom4j\1.6.1\dom4j-1.6.1.jar;C:\Users\jgeenen.PCJURJEN\.m2\repository\xml-apis\xml-apis\1.0.b2\xml-apis-1.0.b2.jar;C:\Users\jgeenen.PCJURJEN\.m2\repository\org\hibernate\common\hibernate-commons-annotations\4.0.5.Final\hibernate-commons-annotations-4.0.5.Final.jar;C:\Users\jgeenen.PCJURJEN\.m2\repository\org\jboss\spec\javax\transaction\jboss-transaction-api_1.2_spec\1.0.0.Final\jboss-transaction-api_1.2_spec-1.0.0.Final.jar;C:\Users\jgeenen.PCJURJEN\.m2\repository\org\javassist\javassist\3.18.1-GA\javassist-3.18.1-GA.jar;C:\Users\jgeenen.PCJURJEN\.m2\repository\org\mousepilots\es-test-domain-mmx\0.1-SNAPSHOT\es-test-domain-mmx-0.1-SNAPSHOT-sources.jar;C:\Users\jgeenen.PCJURJEN\.m2\repository\org\hibernate\javax\persistence\hibernate-jpa-2.1-api\1.0.0.Final\hibernate-jpa-2.1-api-1.0.0.Final-sources.jar;C:\Users\jgeenen.PCJURJEN\.m2\repository\org\hibernate\hibernate-validator\4.3.2.Final\hibernate-validator-4.3.2.Final.jar;C:\Users\jgeenen.PCJURJEN\.m2\repository\org\jboss\logging\jboss-logging\3.1.0.CR2\jboss-logging-3.1.0.CR2.jar;C:\Users\jgeenen.PCJURJEN\.m2\repository\com\google\gwt\gwt-user\2.8.0-SNAPSHOT\gwt-user-2.8.0-SNAPSHOT.jar;C:\Users\jgeenen.PCJURJEN\.m2\repository\com\google\jsinterop\jsinterop-annotations\1.0.0-SNAPSHOT\jsinterop-annotations-1.0.0-SNAPSHOT.jar;C:\Users\jgeenen.PCJURJEN\.m2\repository\com\google\jsinterop\jsinterop-annotations\1.0.0-SNAPSHOT\jsinterop-annotations-1.0.0-SNAPSHOT-sources.jar;C:\Users\jgeenen.PCJURJEN\.m2\repository\javax\validation\validation-api\1.0.0.GA\validation-api-1.0.0.GA-sources.jar;C:\Users\jgeenen.PCJURJEN\.m2\repository\com\google\gwt\gwt-dev\2.8.0-SNAPSHOT\gwt-dev-2.8.0-SNAPSHOT.jar;C:\Users\jgeenen.PCJURJEN\.m2\repository\org\ow2\asm\asm\5.0.3\asm-5.0.3.jar;C:\Users\jgeenen.PCJURJEN\.m2\repository\org\ow2\asm\asm-util\5.0.3\asm-util-5.0.3.jar;C:\Users\jgeenen.PCJURJEN\.m2\repository\org\ow2\asm\asm-tree\5.0.3\asm-tree-5.0.3.jar;C:\Users\jgeenen.PCJURJEN\.m2\repository\org\ow2\asm\asm-commons\5.0.3\asm-commons-5.0.3.jar;C:\Users\jgeenen.PCJURJEN\.m2\repository\org\eclipse\jetty\websocket\websocket-client\9.2.14.v20151106\websocket-client-9.2.14.v20151106.jar;C:\Users\jgeenen.PCJURJEN\.m2\repository\org\eclipse\jetty\jetty-util\9.2.14.v20151106\jetty-util-9.2.14.v20151106.jar;C:\Users\jgeenen.PCJURJEN\.m2\repository\org\eclipse\jetty\jetty-io\9.2.14.v20151106\jetty-io-9.2.14.v20151106.jar;C:\Users\jgeenen.PCJURJEN\.m2\repository\org\eclipse\jetty\websocket\websocket-common\9.2.14.v20151106\websocket-common-9.2.14.v20151106.jar;C:\Users\jgeenen.PCJURJEN\.m2\repository\org\eclipse\jetty\websocket\websocket-api\9.2.14.v20151106\websocket-api-9.2.14.v20151106.jar;C:\Users\jgeenen.PCJURJEN\.m2\repository\org\eclipse\jetty\jetty-webapp\9.2.14.v20151106\jetty-webapp-9.2.14.v20151106.jar;C:\Users\jgeenen.PCJURJEN\.m2\repository\org\eclipse\jetty\jetty-xml\9.2.14.v20151106\jetty-xml-9.2.14.v20151106.jar;C:\Users\jgeenen.PCJURJEN\.m2\repository\org\eclipse\jetty\jetty-servlet\9.2.14.v20151106\jetty-servlet-9.2.14.v20151106.jar;C:\Users\jgeenen.PCJURJEN\.m2\repository\org\eclipse\jetty\jetty-security\9.2.14.v20151106\jetty-security-9.2.14.v20151106.jar;C:\Users\jgeenen.PCJURJEN\.m2\repository\org\eclipse\jetty\jetty-servlets\9.2.14.v20151106\jetty-servlets-9.2.14.v20151106.jar;C:\Users\jgeenen.PCJURJEN\.m2\repository\org\eclipse\jetty\jetty-continuation\9.2.14.v20151106\jetty-continuation-9.2.14.v20151106.jar;C:\Users\jgeenen.PCJURJEN\.m2\repository\org\eclipse\jetty\jetty-http\9.2.14.v20151106\jetty-http-9.2.14.v20151106.jar;C:\Users\jgeenen.PCJURJEN\.m2\repository\org\eclipse\jetty\jetty-annotations\9.2.14.v20151106\jetty-annotations-9.2.14.v20151106.jar;C:\Users\jgeenen.PCJURJEN\.m2\repository\org\eclipse\jetty\jetty-plus\9.2.14.v20151106\jetty-plus-9.2.14.v20151106.jar;C:\Users\jgeenen.PCJURJEN\.m2\repository\org\eclipse\jetty\jetty-jndi\9.2.14.v20151106\jetty-jndi-9.2.14.v20151106.jar;C:\Users\jgeenen.PCJURJEN\.m2\repository\javax\annotation\javax.annotation-api\1.2\javax.annotation-api-1.2.jar;C:\Users\jgeenen.PCJURJEN\.m2\repository\org\eclipse\jetty\apache-jsp\9.2.14.v20151106\apache-jsp-9.2.14.v20151106.jar;C:\Users\jgeenen.PCJURJEN\.m2\repository\org\eclipse\jetty\jetty-server\9.2.14.v20151106\jetty-server-9.2.14.v20151106.jar;C:\Users\jgeenen.PCJURJEN\.m2\repository\org\eclipse\jetty\toolchain\jetty-schemas\3.1.M0\jetty-schemas-3.1.M0.jar;C:\Users\jgeenen.PCJURJEN\.m2\repository\javax\servlet\javax.servlet-api\3.1.0\javax.servlet-api-3.1.0.jar;C:\Users\jgeenen.PCJURJEN\.m2\repository\org\mortbay\jasper\apache-jsp\8.0.9.M3\apache-jsp-8.0.9.M3.jar;C:\Users\jgeenen.PCJURJEN\.m2\repository\org\mortbay\jasper\apache-el\8.0.9.M3\apache-el-8.0.9.M3.jar;C:\Users\jgeenen.PCJURJEN\.m2\repository\com\google\gwt\gwt-user\2.8.0-beta1\gwt-user-2.8.0-beta1.jar;C:\Users\jgeenen.PCJURJEN\.m2\repository\javax\validation\validation-api\1.0.0.GA\validation-api-1.0.0.GA.jar;C:\Users\jgeenen.PCJURJEN\.m2\repository\javax\validation\validation-api\1.0.0.GA\validation-api-1.0.0.GA-sources.jar;C:\Users\jgeenen.PCJURJEN\.m2\repository\com\google\gwt\gwt-dev\2.8.0-beta1\gwt-dev-2.8.0-beta1.jar;C:\Users\jgeenen.PCJURJEN\.m2\repository\org\ow2\asm\asm\5.0.3\asm-5.0.3.jar;C:\Users\jgeenen.PCJURJEN\.m2\repository\org\ow2\asm\asm-util\5.0.3\asm-util-5.0.3.jar;C:\Users\jgeenen.PCJURJEN\.m2\repository\org\ow2\asm\asm-tree\5.0.3\asm-tree-5.0.3.jar;C:\Users\jgeenen.PCJURJEN\.m2\repository\org\ow2\asm\asm-commons\5.0.3\asm-commons-5.0.3.jar com.google.gwt.dev.Compiler -logLevel INFO -style OBF -war C:\FastDocuments\NetBeansProjects\EntityScenarios\test\es-test-web\target\web-0.1-SNAPSHOT -localWorkers 8 -XfragmentCount -1 -sourceLevel 1.8 -extra C:\FastDocuments\NetBeansProjects\EntityScenarios\test\es-test-web\target\extra -gen C:\FastDocuments\NetBeansProjects\EntityScenarios\test\es-test-web\target\.generated org.mousepilots.es.test.Main
