### ISSUE TITLE
Relax JsInteorp restriction checking so one can perform feature check

### ISSUE THREAD

**Issue by gkdn** [gwtproject/gwt#9327]
Relax JsInteorp restriction checking so one can perform feature check; like:

```java
class Performance { 
  @JsMethod(namespace="performance")
  public static native double now();
  public static boolean hasNow() { return getNow() != null; }
  @JsProperty(namespace="performance")
  private static native Object getNow();
}
```

Above snippet fails due to name restriction checking.

Current workaround:
```java
class Performance { 
  @JsMethod(namespace="performance")
  public static native double now();
  public static boolean hasNow() { return Helper.getNow() != null; }

  private static class Helper {
    @JsProperty(namespace="performance")
    public static native Object getNow();
  }
}
```

**Comment by ibaca** [comment]
Null primitives is quite annoying I hope GWT team will find good solution (manolo already makes a comment in the NextGen doc, and you said that Double and now Boolean can be used) but... 
For example (easy to say, sorry... just ignore if makes no sense 😉):
``@JsProperty(orElse="0") double now();`` where orElse is a literal string. Or at least some primitive flag which if is true, all call will be handled as similar as possible as java primitives so now() will be always translated as (now||0), booleans now||false, etc.

Other more weird idea:
```java
// field is substitude by the field name, this is useful to save the string as a constant somewhere else
@JsProperty(getter=“$field++”) int increment();
// using a constant
@JsProperty(getter=INCREMENT) int increment();
// even more weird example (not sure if this makes sense)
@JsProperty(
  getter=“var l=@java.util.ArrayList::new()();l.@java.util.ArrayList::array=$field;return l;”, 
  setter=“$field = $set.@java.util.ArrayList::array”
) ArrayList<String> tokens();
// using a constant
@JsProperty(getter=ARRAY_LIST_GET, setter=ARRAY_LIST_SET) ArrayList<String> tokens();
// and just because is so easy to say thing a do not implement them...
@JsProperty(getter=ARRAY_LIST_GET, setter=ARRAY_LIST_SET)
@Target(FIELD) @Retention(RUNTIME) @JsDef
public @interface JsList {}
// so can be used as javax.validation annotation composition, just to clean it up the code
@JsList ArrayList<String> tokens();
```

**Comment by gkdn** [comment]
In general JsInterop v1 tries to be close to original JavaScript and avoids features that modifies the underlying abstraction heavily. The future plan to do abstraction modifications is via @JsConvert which will basically let you run the object through a function supplied by you.

**Comment by ibaca** [comment]
Mmm... but... a JsInterop which returns a null primitive java value might be discutible as something that will be solved in v2. At least some module property which allow you to add the minimal safety to use primitive which behaves like java primitives, so primitives getter will be written as (val || def) where def is the default java value for the java primitive. I'll try to stop commenting, and I will try to try it myself 😉, thanks anyways.

**Comment by rluble** [comment]
@Ignacio, I think you misread the point. This is not about primitive types.
This is using JsInterop in an unusual way using a JsFunction type property
to check for the existence of a instance method in a native type.

**Comment by gkdn** [comment]
To answer your last comment;
If you think it could be null then you shouldn't be using Java primitive. The types that corresponds to JavaScript primitives are boxed Java types not Java primitives. You can only use a Java primitives for convenience if you don't have any concerns of nullability.

**Comment by ibaca** [comment]
@rluble yep, I know this is not about primitives, probably not the best place to solve my doubts. But I if the primitives will be safety defaulted to the java primitive default value this use case (double now()) will returns 0, so the second method to check if is null won't be necessary (maybe this isn't good). So I took the opportunity to comment my null-primitive concerns.

Looks like @gkdn are seeing this more in the side of JS, and I'm more in the side of Java. But you said; "you can only use java primitives for convenience if you don't have any concerns of nullability" so.. why are you using it in this now() method? 😞 

My actual use case is for shared DTOs.
```java
@JsType(isNative=true,namespace=GLOBAL,name="Object") class MyDto {
  public int foo;
  public int bar; 
}
```
And my concerns are that the client instance will have null foo/bar but server instances will not (need to be native and "Object" because this can come from a JSON). Just curious in the actual motivation on admit null-primitives. But as @gkdn said, v1 tries to be close to the original JavaScript. So I'm ok. Thanks!

**Comment by gkdn** [comment]
window.performance.now can never return null. window.performance.now not being existent is different that now returning null when you 'call' it.

**Comment by rluble** [comment]
review at: https://gwt-review.googlesource.com/#/c/15002/
