### ISSUE TITLE
Inconsistent JsFunction execution context

### ISSUE THREAD

**Issue by gkdn** [gwtproject/gwt#9328]
Given following code:

```java
@JsType(isNative=true)
class X {
  @JsProperty
  SomeFunction getX(); // SomeFunction is a @JsFunction
}
```

We get different behavior for two different call styles:
```java
 new X().getX().execute();
```
vs.
```java
 SomeFunction fn = new X().getX();
 fn.execute();
```

This is very surprising behavior that is due to the way we generate code. We should be consistent and always follow the latter behavior.

**Comment by rluble** [comment]
review at https://gwt-review.googlesource.com/#/c/15001
