### ISSUE TITLE
Style class font-family setter.

### ISSUE THREAD

**Issue by chris-malloy-mri** [gwtproject/gwt#9329]
Is there a reason the font-family property has been left out of the style class? Currently using Style.setProperty() as a workaround.

**Comment by jnehlmeier** [comment]
I guess no one had a need to it so far, as font families are usually static and thus part of CSS/GSS files. 

It is usually better to add/remove a CSS class to an element instead of applying inline styles using `Style.setXYZ()`. The only exception are dynamic values that you can not define in CSS.

**Comment by chris-malloy-mri** [comment]
Makes sense. Mine is a fairly unusual case loading the font-family from an external asset. I had assumed the implicit design goal of the Style class was to provide setters for every standard style property. Patches welcome?

**Comment by jnehlmeier** [comment]
I don't think that was an implicit design goal. It would be an ever increasing class which already is 2000+ lines long. Using the `*property*` methods isn't really a workaround, its expected that you use them. Personally I don't like all the methods in that class as they do not provide a lot of value, IMHO just providing the `*property*` methods would have been enough. 

But I guess no one will reject your contribution if you want `font-family` to be added as setter/getter/clear methods.

**Comment by chris-malloy-mri** [comment]
If it's not a design goal then I don't see a problem with it. Having these functions can prevent typos when people enter the property names manually, but it sounds like font-family will never be used anyway. 

In the future, will things like this be generated from the spec (like elemental)? Code lines will be a non-issue in that case.

**Comment by tbroyer** [comment]
In the future, you'll use Elemental ;-)

**Comment by jnehlmeier** [comment]
Elemental 2 will probably only have methods defined through the HTML spec: https://developer.mozilla.org/en-US/docs/Web/API/CSSStyleDeclaration

I don't think you will have explicit methods for each style property. You would always use setProperty(). However that does not stop anyone from generating a class with String constants or an enum to use with setProperty().

**Comment by chris-malloy-mri** [comment]
Sounds good! Please close.

**Comment by tbroyer** [comment]
@jnehlmeier Maybe generation for Elemental 2 will use https://chromium.googlesource.com/chromium/blink/+/master/Source/core/css/CSSProperties.in or similar? (those are only the properties supported by Blink, but still)
Elemental 1 had those AFAICT. For now, Elemental 2 is being developed behind closed doors, so only time will tell.

**Comment by jnehlmeier** [comment]
@tbroyer Yeah maybe. But then you only want to use properties without vendor prefixes. Its nice to have but IMHO not really required. Mostly it comes down to top, left, bottom, right, opacity, color, background-color, transform (maybe I miss a few). Basically what you would use after deferred position calculation in JS or for animations using requestAnimationFrame.
