### ISSUE TITLE
JsType public members are removed

### ISSUE THREAD

**Issue by janblok** [gwtproject/gwt#9332]
When a class is annotated with JsType the public members are removed (optimized away) unless used from Java Code.
Using latest snapshot today, via: https://oss.sonatype.org/content/repositories/google-snapshots

**Comment by tbroyer** [comment]
I believe this is intentional, unless the `JsType` has `isNative=true`.
Assigning to @gkdn for confirmation.

**Comment by dankurka** [comment]
You are probably missing the -generateJsInteropExports argument to preserve exported types.

Reopen if this does not fix it.

**Comment by ibaca** [comment]
[Related discussion](https://groups.google.com/forum/#!searchin/google-web-toolkit-contributors/generateJsInteropExports/google-web-toolkit-contributors/XXGsb1QwjTI/3mDl9cD0BgAJ).

**Comment by janblok** [comment]
yep generateJsInteropExports solved it, but why is this an compiler option and not a flag on the JSType annotation? (alike isNative)

**Comment by tbroyer** [comment]
See linked discussion above.
