### ISSUE TITLE
@JsIgnore in a native @JsType should not be valid

### ISSUE THREAD

**Issue by gkdn** [gwtproject/gwt#9334]
```java
@JsType(isNative = true)
public interface A {
  @JsIgnore
  B toB();
}
```

should fail. (See cl/120873646).

**Comment by rluble** [comment]
Added a test that shows there is an error here. Maybe the type was not referenced in the cl and hence not even checked when the type was introduced.

review at: https://gwt-review.googlesource.com/#/c/14983

**Comment by rluble** [comment]
Probably the method was not referenced and because the checking is done after UnifyAST when it would be pruned if not referenced. That scenario is possibly fixed by https://gwt-review.googlesource.com/#/c/14941
