### ISSUE TITLE
Instance of native object array doesn't work correctly

### ISSUE THREAD

**Issue by gkdn** [gwtproject/gwt#9337]
I'm not sure if this is an optimization bug or incorrect implementation but instance of native object arrays fail.

```java
  @JsType(isNative = true, name = "Object", namespace = JsPackage.GLOBAL)
  private static class GlobalObject { }

  public static boolean isArray(Object o) {
    return o instanceof GlobalObject[];
  }
```

(See cl/115628428)

**Comment by rluble** [comment]
The array is considered uninstantiated. I'll send a fix.

**Comment by rluble** [comment]
Review at https://gwt-review.googlesource.com/#/c/14881/
