### ISSUE TITLE
Need explicit support for unknown types

### ISSUE THREAD

**Issue by gkdn** [gwtproject/gwt#9341]
Currently unknown type are represented implicitly with native JsType interfaces but this is not a future proof solution since Closure supports interfaces. As a result those native JsType interfaces actually point to a real known type.
We should have a more explicit support for unknown types like: @JsType(name=JsType.UNKNOWN)

@rluble

**Comment by rluble** [comment]
Decided to use name='*' and name='?'  to mode the types "any" and "unknown" respectively.

Code review at https://gwt-review.googlesource.com/#/c/17620/

**Comment by niloc132** [comment]
Fixed in 2.8.1.
