### ISSUE TITLE
Post 2.8.0-beta1 : NoSuchMethodError - CharMatcher.javaUpperCase()

### ISSUE THREAD

**Issue by PatrickMadden** [gwtproject/gwt#9344]
My code compiles just fine in 2.8.0-beta1. However, when I cloned and built from the master branch I get the following error.

[INFO] Compiling module com.tomsawyer.perspectivesviewer
[INFO]    Compiling 1 permutation
[INFO]       [ERROR] Unexpected internal compiler error
[INFO] java.lang.NoSuchMethodError: com.google.gwt.thirdparty.guava.common.base.CharMatcher.javaUpperCase()Lcom/google/gwt/thirdparty/guava/common/base/CharMatcher;
[INFO] 	at com.google.gwt.thirdparty.javascript.jscomp.parsing.JsDocInfoParser.validTemplateTypeName(JsDocInfoParser.java:1216)
[INFO] 	at com.google.gwt.thirdparty.javascript.jscomp.parsing.JsDocInfoParser.parseAnnotation(JsDocInfoParser.java:946)
[INFO] 	at com.google.gwt.thirdparty.javascript.jscomp.parsing.JsDocInfoParser.parseHelperLoop(JsDocInfoParser.java:283)
[INFO] 	at com.google.gwt.thirdparty.javascript.jscomp.parsing.JsDocInfoParser.parse(JsDocInfoParser.java:273)
[INFO] 	at com.google.gwt.thirdparty.javascript.jscomp.parsing.IRFactory.createJsDocInfoParser(IRFactory.java:889)
[INFO] 	at com.google.gwt.thirdparty.javascript.jscomp.parsing.IRFactory.handleJsDoc(IRFactory.java:656)
[INFO] 	at com.google.gwt.thirdparty.javascript.jscomp.parsing.IRFactory.handleJsDoc(IRFactory.java:670)
[INFO] 	at com.google.gwt.thirdparty.javascript.jscomp.parsing.IRFactory.transform(IRFactory.java:733)
[INFO] 	at com.google.gwt.thirdparty.javascript.jscomp.parsing.IRFactory.access$300(IRFactory.java:163)
[INFO] 	at com.google.gwt.thirdparty.javascript.jscomp.parsing.IRFactory$TransformDispatcher.processAstRoot(IRFactory.java:1013)
[INFO] 	at com.google.gwt.thirdparty.javascript.jscomp.parsing.IRFactory$TransformDispatcher.process(IRFactory.java:2591)
[INFO] 	at com.google.gwt.thirdparty.javascript.jscomp.parsing.IRFactory.justTransform(IRFactory.java:931)
[INFO] 	at com.google.gwt.thirdparty.javascript.jscomp.parsing.IRFactory.transformTree(IRFactory.java:339)
[INFO] 	at com.google.gwt.thirdparty.javascript.jscomp.parsing.ParserRunner.parse(ParserRunner.java:117)
[INFO] 	at com.google.gwt.thirdparty.javascript.jscomp.JsAst.parse(JsAst.java:89)
[INFO] 	at com.google.gwt.thirdparty.javascript.jscomp.JsAst.getAstRoot(JsAst.java:50)
[INFO] 	at com.google.gwt.thirdparty.javascript.jscomp.CompilerInput.getAstRoot(CompilerInput.java:121)
[INFO] 	at com.google.gwt.thirdparty.javascript.jscomp.Compiler.parseInputs(Compiler.java:1330)
[INFO] 	at com.google.gwt.thirdparty.javascript.jscomp.Compiler.parse(Compiler.java:719)
[INFO] 	at com.google.gwt.thirdparty.javascript.jscomp.Compiler.compileInternal(Compiler.java:680)
[INFO] 	at com.google.gwt.thirdparty.javascript.jscomp.Compiler.access$000(Compiler.java:83)
[INFO] 	at com.google.gwt.thirdparty.javascript.jscomp.Compiler$2.call(Compiler.java:651)
[INFO] 	at com.google.gwt.thirdparty.javascript.jscomp.Compiler$2.call(Compiler.java:648)
[INFO] 	at com.google.gwt.thirdparty.javascript.jscomp.CompilerExecutor$2.call(CompilerExecutor.java:93)
[INFO] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[INFO] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
[INFO] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[INFO] 	at java.lang.Thread.run(Thread.java:745)
[INFO]       [ERROR] Unrecoverable exception, shutting down
[INFO] com.google.gwt.core.ext.UnableToCompleteException: (see previous log entries)
[INFO] 	at com.google.gwt.dev.javac.CompilationProblemReporter.logAndTranslateException(CompilationProblemReporter.java:112)
[INFO] 	at com.google.gwt.dev.jjs.JavaToJavaScriptCompiler.compilePermutation(JavaToJavaScriptCompiler.java:459)
[INFO] 	at com.google.gwt.dev.jjs.JavaToJavaScriptCompiler.compilePermutation(JavaToJavaScriptCompiler.java:272)
[INFO] 	at com.google.gwt.dev.CompilePerms.compile(CompilePerms.java:198)
[INFO] 	at com.google.gwt.dev.ThreadedPermutationWorkerFactory$ThreadedPermutationWorker.compile(ThreadedPermutationWorkerFactory.java:50)
[INFO] 	at com.google.gwt.dev.PermutationWorkerFactory$Manager$WorkerThread.run(PermutationWorkerFactory.java:74)
[INFO] 	at java.lang.Thread.run(Thread.java:745)
[INFO]       [ERROR] Not all permutation were compiled , completed (0/1)

**Comment by jnehlmeier** [comment]
Sounds like you have two versions of gwt-dev.jar in your classpath during compilation (the beta1 version and the master branch version).

**Comment by tbroyer** [comment]
Or possibly (and actually more likely), you have an older gwt-servlet earlier than gwt-dev in the classpath.

**Comment by PatrickMadden** [comment]
Thank you both. It turns out I did indeed still have another maven module that was referencing GWT 2.8.0-beta1. When I cleaned it up, the issue went away.
