### ISSUE TITLE
instanceof JsObject returns false functions

### ISSUE THREAD

**Issue by gkdn** [gwtproject/gwt#9347]
instanceof JsObject returns false functions although instanceof Object returns true.
This because it is special cased to be translated as typeof == 'object' which doesn't return true for all cases.

**Comment by rluble** [comment]
should it be typeof == 'object' || typeof == 'function'?

**Comment by gkdn** [comment]
null and undefined should cast as well but instanceof those should fail.
I need to think more about it.

**Comment by rluble** [comment]
Isn't that the current behaviour for null/undefined?

**Comment by gkdn** [comment]
Might be, might be not. Needs to be verified since typeof null is 'object' while typeof undefined is 'undefined' so I would be surprised if the current implementation works correctly at the same time for both scenarios.

**Comment by rluble** [comment]
Yes. instanceof JsObject will return true for null and false for undefined.
Tricky, tricky, tricky.

**Comment by dankurka** [comment]
I am guessing this needs to be in 2.8 correct?

What is left to do here? Go through all cast scenarios in Casts.java and verify that the work as intended?

Who is going to do that work?

**Comment by gkdn** [comment]
We need update the test cases esp. around handling of null and primitives and functions.
The behavior should be like o != null && (typeof == objectt || typeof == function)  - needs to be verified.

**Comment by rluble** [comment]
Code is up for review at https://gwt-review.googlesource.com/#/c/15173
