### ISSUE TITLE
Disallow overriding j.l.Object methods (toString(), etc) and disallow declaring JsMethods on JsFunctions and their implementations

### ISSUE THREAD

**Issue by gkdn** [gwtproject/gwt#9348]

**Comment by dankurka** [comment]
@gkdn I am not sure what the workitem is, can you clarify? Does this need to be on 2.8? Who should be taking care of this?

**Comment by rluble** [comment]
These are restrictions like do not allow to define toString, etc on JsFunction implementations

**Comment by rluble** [comment]
Code review at https://gwt-review.googlesource.com/15171

**Comment by cromwellian** [comment]
Why are we disallowing this? There's no justification listed.

**Comment by rluble** [comment]
JsFunctions are *already* restricted by not allowing subclassing (they can only subclass j.l.Object) nor implementation of interfaces other that the JsFunction interface. 

The extra restrictions mentioned in this issue are the disallowance of overriding of j.l.Object methods.

The motivation is to make JsFunctions very lightweight that can be generated as plain JS functions without the need of an actual class but also allowing Java class expressivity (e.g. instance fields and instance methods).
