### ISSUE TITLE
Add information about SuppressWarning("unusable-by-js")

### ISSUE THREAD

**Issue by gkdn** [gwtproject/gwt#9349]
If there is any warning related to "unusable-by-js" after all checks completed, add a msg that points to usage for @SuppressWarning("unusable-by-js")

**Comment by dankurka** [comment]
@gkdn Seems to be like this should be fairly simple to do and should be in 2.8 right?

**Comment by rluble** [comment]
Should be easy to add.

**Comment by rluble** [comment]
Code review at https://gwt-review.googlesource.com/15172
