### ISSUE TITLE
gwt-dev shouldn't bundle icu without jarjaring it

### ISSUE THREAD

**Issue by lukesandberg** [gwtproject/gwt#9352]
looks like gwt-dev jar artifacts bundles icu4j directly.  this can cause problems for other applications which are using incompatible versions of icu4j.  (I just ran into this due to a transitive mvn dep on some gwt annotations causing build errors,  this took way too long to figure out due to the bundling)

ideally gwt would just have a normal mvn dependency on icu4j (which would make the version conflict obvious), but if that isn't possible then it should jarjar icu it to prevent conflicts.

**Comment by tbroyer** [comment]
I'd start with banning gwt-dev and gwt-user from non-client modules, and banning duplicate classes from distinct deps; but yes, we should probably unbundle ICU.

**Comment by lukesandberg** [comment]
is there a maven way to ban duplicate/incompatible classes from deps?

**Comment by tbroyer** [comment]
Yes: http://www.mojohaus.org/extra-enforcer-rules/banDuplicateClasses.html

**Comment by tbroyer** [comment]
https://gwt-review.googlesource.com/15161

**Comment by tbroyer** [comment]
Patch has been temporarily reverted: https://gwt-review.googlesource.com/15350

**Comment by tbroyer** [comment]
New review: https://gwt-review.googlesource.com/15352 (also unbundles HTMLUnit)

**Comment by tbroyer** [comment]
Merged
