### ISSUE TITLE
Overlay methods in native JsTypes should have access to private native methods

### ISSUE THREAD

**Issue by vtsaplin** [gwtproject/gwt#9355]
It would make sense to allow overlay methods in native JsTypes to access private native methods. The following code produces an error:

```
    @JsOverlay
    public final String render(Map<String, Object> data) {
        JavaScriptObject jso = JavaScriptObject.createObject();
        for (Map.Entry<String, Object> e : data.entrySet()) {
            Utils.setObjectProperty(jso, e.getKey(), e.getValue());
        }
        return render(jso);
    }

    private native String render(JavaScriptObject data);
```

Here is the error message:

> Uncaught TypeError: this$static_0_g$.render_5_g$ is not a function

With protected modifier it works fine but protected modifier doesn't prevent the native API from leaking to the package.

**Comment by rluble** [comment]
Is the type declared JsType(isNative = true)? if not private methods are not automatically JsMethods you need to add 

@JsMethod
private native String render(...);

**Comment by vtsaplin** [comment]
isNative is true, obviously. Otherwise I would not use JsOverlay. I am also not sure if native methods would work at all if isNative is false.

**Comment by vtsaplin** [comment]
I tried to add @JsMethod but it doesn't help.

**Comment by rluble** [comment]
Could you post the complete class declaration?

**Comment by vtsaplin** [comment]
```
@JsType(isNative = true)
public class Template {

    private Template() {
    }

    @JsOverlay
    public final String render(Map<String, Object> data) {
        JavaScriptObject jso = JavaScriptObject.createObject();
        for (Map.Entry<String, Object> e : data.entrySet()) {
            Utils.setObjectProperty(jso, e.getKey(), e.getValue());
        }
        return render(jso);
    }

    protected native String render(JavaScriptObject data);
}
```

**Comment by rluble** [comment]
I notice that the crash is from a SDM run, does this also happen in regular compiles?

**Comment by vtsaplin** [comment]
To be honest I never tried to compile it in a regular fashion.

**Comment by rluble** [comment]
Does this still happen in the current snapshot?
