### ISSUE TITLE
Boolean.booleanValue() and other calls that are devirtualized should not be allowed from JSNI

### ISSUE THREAD

**Issue by Legioth** [gwtproject/gwt#9356]
```
    private static native boolean toPrimitive(Boolean value)
    /*-{
      return value.@Boolean::booleanValue()();
    }-*/;
```
compiles to `value_0.booleanValue()`, which doesn't work since `value_0` is a native JS boolean that doesn't have a member named `booleanValue`. 

Tested with the 2.8.0-beta1 and 2.8.0-SNAPSHOT.

**Comment by rluble** [comment]
Yes. That needs to be banned as we do for all JSOs.

**Comment by jnehlmeier** [comment]
Its the same as with Double, see #9242

**Comment by rluble** [comment]
Review at https://gwt-review.googlesource.com/#/c/15080/

**Comment by rluble** [comment]
A couple of patches related to this bug are up for review

Improvements to the jsni restriction error reporting  - https://gwt-review.googlesource.com/#/c/15120
Only disallow taking a method reference to devirtualized instance methods but allow direct calls to them - https://gwt-review.googlesource.com/#/c/15121

**Comment by Legioth** [comment]
> Only disallow taking a method reference to devirtualized instance methods but allow direct calls to them - https://gwt-review.googlesource.com/#/c/15121

Does this mean that it would work in the way I suggested in #9242, i.e. that `value.@Boolean::booleanValue()` is rejected but `value@Boolean::booleanValue()()` works?

**Comment by rluble** [comment]
Yes. I had to enhance the Devirtualizer to undestand the JS AST; almost all of GWT's Java AST passes it do not deal at all with the JS AST in JSNI, but only use some summary information to know which methods, fields, classliterals are referenced there.

 But it turned out to be a quite straight forward to add to the Devritualizer. 

Thanks for the suggestion.

**Comment by dankurka** [comment]
In reivew: https://gwt-review.googlesource.com/#/c/15121/
