### ISSUE TITLE
@JsProperty method access is optimised to function call in abstract native jstype

### ISSUE THREAD

**Issue by mbarkley** [gwtproject/gwt#9358]
In some cases, methods annotated with `@JsProperty` on a native `@JsType` are optimized to obfuscated function calls in a full compile.

[Here](https://github.com/mbarkley/errai-tutorial/tree/jspropery-failing-case) is a reproducer for the problem. To see the issue, checkout the linked project and do a full compile (mvn clean package), then deploy the war file, and load the host page in Chrome. When you load the host page, you should see the message that calling `getTextContent` has failed and see a stack trace in the console where an obfuscated function was called rather than a property access to `textContent`. If you compile the project with optimization level 0, the property access works as expected.

Strangely enough, the problem goes away if I add a call to `getTextContent` on an `Anchor` field (see [here](https://github.com/mbarkley/errai-tutorial/tree/jsproperty-success-case)).

I spent some time trying to simplify this project, but was unable to reproduce the problem in a project without Errai.

**Comment by gkdn** [comment]
Passing --generateJsInteropExports?

**Comment by mbarkley** [comment]
No but all of the types involved have `isNative=true` so that shouldn't be necessary, right?

**Comment by gkdn** [comment]
That's correct you shouldn't need it if you are calling a isNative=true method from Java.
You need send a smaller repro code snippet. Are you using latest snapshot?

**Comment by mbarkley** [comment]
Yes, that example uses the latest snapshots. There are really only [these two classes](https://github.com/mbarkley/errai-tutorial/tree/jspropery-failing-case/src/main/java/org/jboss/errai/demo/client/local) + Errai, but I will try and make a smaller reproducer.

**Comment by mbarkley** [comment]
@gkdn I have made a new reproducer without Errai.

[Here](https://github.com/mbarkley/jsproperty-reproducer/tree/failing-case) is the failing case. [Here](https://github.com/mbarkley/jsproperty-reproducer/tree/successful-case) is the workaround.

As before you must build the failing case with `mvn clean package` to observe the problem.

**Comment by gkdn** [comment]
Thanks for the smaller repro.

@rluble This might be something around accident overrides; not sure.

**Comment by rluble** [comment]
I'll have a look but I think your diagnostic is spot on. Because it is declared abstract the explicit stub created by the accidental override is probably not inheriting JsInfo.

**Comment by rluble** [comment]
A sketch of a fix is in https://gwt-review.googlesource.com/#/c/15093.
