### ISSUE TITLE
NoSuchMethodError when compiling code in SuperDevMode

### ISSUE THREAD

**Issue by nordligulv** [gwtproject/gwt#9359]
java.lang.NoSuchMethodError: java.lang.StringBuilder.toString()Ljava/lang/String;

How to reproduce:
Just run simple java project in SuperDevMode.
Event if this project does not contain Java 8 labdas, during the compilation you'll get above mentioned error.

It's traced back to compiling Collectors.java class which has method reference to StringBuilder::toString

**Comment by dankurka** [comment]
I think this is unlikely to be a bug that is affecting all projects, since we would have seen lots of reports inside of Google (Collectors has been in for a while).

Do you have a small repro case?

**Comment by nordligulv** [comment]
Yeah, sorry, I had caching problems in Intellij.
