### ISSUE TITLE
Run Java8 tests in open source build

### ISSUE THREAD

**Issue by dankurka** [gwtproject/gwt#9362]

**Comment by tbroyer** [comment]
https://gwt-review.googlesource.com/15103
…and breaks the build: http://build.gwtproject.org/job/gwt/525/testReport/

**Comment by dankurka** [comment]
Let's keep this open then until we run them sucessfully. I believe there is one tests (StringJoiner) that is supposed to fail since we removed some critical null checks, but is supposed to get fixed with:

https://gwt-review.googlesource.com/#/c/15160/

**Comment by dankurka** [comment]
https://gwt-review.googlesource.com/#/c/15180/

**Comment by dankurka** [comment]
Build is now green closing this.
