### ISSUE TITLE
JsInterop base classes available in GWT / as a separate artifact

### ISSUE THREAD

**Issue by dankurka** [gwtproject/gwt#9364]
Put JsInterop base classes (e.g. Array access) in GWT or into a separate artifact so that elemental and others can use this and we can fully deprecate JSNI.

**Comment by dankurka** [comment]
@gkdn I think this is critical to 2.8 and for everybody else in the eco system moving forward and away from JSNI. WDYT?

**Comment by jnehlmeier** [comment]
Beside some basic utils I think we should also provide some copies of java.util.function interfaces without default methods because every project recreates them just because of JsFunction restrictions

**Comment by gkdn** [comment]
We have a separate artifact for jsinterop and it doesn't / will not follow GWT release cycles so this is not required to be done by 2.8. We are mostly bound with Elemental release for that.
