### ISSUE TITLE
Deprecate JSR 303

### ISSUE THREAD

**Issue by tbroyer** [gwtproject/gwt#9367]
JSR 303 support has been unmaintained for years. We should deprecate it in 2.8.0 and aim to remove it in a future version (2.8.1? 2.9?).

This means:
 * [ ] "officially" note it as deprecated in the release notes
 * [ ] add a bold note at the top of http://www.gwtproject.org/doc/latest/DevGuideValidation.html, possibly remove the page from the menu.
 * ~~add `@Deprecated` to the GWT-specific public APIs (`@GwtValidation` et al. in `com.google.gwt.validation`)~~

See discussion at https://groups.google.com/d/topic/google-web-toolkit/KtdRAWNotXE/discussion

**Comment by tbroyer** [comment]
FWIW: besides the two small fixes earlier this year, the last change to JSR 303 was 577b81dc230f858117c4e00b03b75521b535bf84 back in November 2012.

**Comment by tbroyer** [comment]
@dankurka @niloc132 @csadilek @jhickman @meriouma @gwtproject/gwt-maintainers Any opinion on this?

**Comment by dankurka** [comment]
I am all for removing it!

**Comment by csadilek** [comment]
We're using it quite heavily in a number of applications. So, having it go away in 2.8 (short-term) would pose a problem, but OK with deprecating it and removing it in a future version. We can then move the functionality to one of our libs e.g errai-validation.

**Comment by csadilek** [comment]
Of course, we'd also be happy with a standalone third-party lib if there's greater interest and help with that.

**Comment by jhickman** [comment]
I'm okay with deprecation.  This could definitely be a 3rd party moving forward.

**Comment by meriouma** [comment]
I'm good with deprecation too.

**Comment by tbroyer** [comment]
https://gwt-review.googlesource.com/15200

Also assigning to Julien for the release-note part.

**Comment by tbroyer** [comment]
So, Jens asked on the review: should we add those `@Deprecated` annotations in the code (at the risk of having people freaking out, when actually the feature is likely to just move elsewhere and not disappear), or only in the release notes and documentation?

**Comment by csadilek** [comment]
Yes, he has a point as ```@Deprecated``` discourages the use of API and that isn't required if we plan to maintain this feature elsewhere. The desire is to move it outside of GWT (and upgrade it), but not to remove this API entirely.

So, personally I'd be fine with mentioning it in the release notes only. Alternatively, if source-level deprecation is desired, we can add a ```@deprecated``` javadoc tag e.g.
```java
/**
 * @deprecated  JSR-303 bean validation will not be maintained as part of 
 *              GWT going forward. See (link to gwt-contributors) for 
 *              discussions on moving this to a standalone GWT module.
 */
````

**Comment by dankurka** [comment]
Code changes are in, only thing left is to write up the release notes

**Comment by tbroyer** [comment]
Not only the release notes; this page should also have a "deprecation banner": http://www.gwtproject.org/doc/latest/DevGuideValidation.html

**Comment by gkdn** [comment]
I'm not sure why this was deprecated via @deprecated annotation.
Deprecated at source level means update your code to use something else but there is no point on updating existing code and also there is no way to update the existing code that is ok!
We are basically spamming people for using validation and which will just result in users not paying attention to warnings; this is bad.

**Comment by tbroyer** [comment]
So @dankurka, WDYT, do we revert before releasing 2.8?

**Comment by dankurka** [comment]
I think @gkdn is right here. I made the wrong call, this should be release notes instead:
https://gwt-review.googlesource.com/#/c/15430/

**Comment by wlsc** [comment]
According to the last comment by @dankurka, this issue was already merged in gerrit. Maybe its time to close this issue?

**Comment by tbroyer** [comment]
We were mainly waiting for the docs to be updated, which should now be the case.
