### ISSUE TITLE
Change the behavior of generateJsInteropExports to fail-fast in SDM

### ISSUE THREAD

**Issue by gkdn** [gwtproject/gwt#9369]

**Comment by gkdn** [comment]
@rluble If there are other untracked TODOs, can you file issues for them as well?

**Comment by rluble** [comment]
I am not sure what does this issue entail. Could you expand?

**Comment by gkdn** [comment]
IIRC, we decided to play with the idea of renaming JsMethod (non-native) when generateJsinteropExport is false.

**Comment by rluble** [comment]
Review at https://gwt-review.googlesource.com/#/c/15193/
