### ISSUE TITLE
Fix generator type oracle interface for Java8 handling

### ISSUE THREAD

**Issue by gkdn** [gwtproject/gwt#9371]
See https://gwt-review.googlesource.com/#/c/14750/ for the context.

**Comment by rluble** [comment]
Review at https://gwt-review.googlesource.com/15240

**Comment by tazle** [comment]
Is it possible for a generator to somehow discover Java 8 default methods?

We have run into some trouble with gwt-jackson's. It fails to generate serialization code for JSON fields backed by default methods, since it can't see the JMethod for that method.

**Comment by tbroyer** [comment]
@tazle No, and it's on purpose. Default and static methods on interfaces are not exposed to generators. This in part to not break existing generators, and in part to encourage people to move to annotation processing (or other kinds of code generation)

**Comment by gkdn** [comment]
If it is a really important you can add an extra API to just get those.
