### ISSUE TITLE
CellTables created with different resources results in merged styles

### ISSUE THREAD

**Issue by cpboyd** [gwtproject/gwt#9372]
First off, I have two separate resource definitions.  A regular "TableResources" which has (among other styles):
```css
.cellTableFirstColumn {
  font-weight: bold;
}
```

The special variant changes the font-weight back to normal (among other changes).  The font-weight is simply the most noticeable style difference.

I then create separate tables using:
```java
CellTable<Properties> table = new CellTable<>(size, (TableResources) GWT.create(TableResources.class));
CellTable<Properties> table2 = new CellTable<>(size, (SpecialTableResources) GWT.create(SpecialTableResources.class));
```

TableResources.java:
```java
public interface SpecialTableResources extends CellTable.Resources {
    @Override
    @Source({ CellTable.Style.DEFAULT_CSS, "paperTable.css" })
    CellTable.Style cellTableStyle();
}
```
SpecialTableResources.java:
```java
public interface SpecialTableResources extends CellTable.Resources {
    @Override
    @Source({ CellTable.Style.DEFAULT_CSS, "paperTable.css", "specialTable.css" })
    CellTable.Style cellTableStyle();
}
```

After attaching the CellTables to the page, none of them have bolded text in the first column.

Is there any way to create multiple CellTables with distinct styles, without individually styling each cell?

**Comment by cpboyd** [comment]
Forgot to mention:
I'm using the 2.8.0-SNAPSHOT.

**Comment by jnehlmeier** [comment]
@cpboyd You have to extend CellTable.Style as well, otherwise the generated CSS class names are the same for both your CellTables and override each other (and the last one wins).

```java

public interface TableResources extends CellTable.Resources {

  interface TableStyle extends CellTable.Style {}

  @Override
  @Source({ CellTable.Style.DEFAULT_CSS, "paperTable.css" })
  TableStyle cellTableStyle();
}


public interface SpecialTableResources extends CellTable.Resources {

  interface SpecialTableStyle extends CellTable.Style {}

  @Override
  @Source({ CellTable.Style.DEFAULT_CSS, "paperTable.css", "specialTable.css" })
  SpecialTableStyle cellTableStyle();
}
```
The CSS class name generation algorithm uses the interface name and method name. As the method name is the same (cellTableStyle()) you have to use different interfaces in order to get unique CSS class names.

**Comment by cpboyd** [comment]
Ah, I see.

Thanks!

**Comment by tbroyer** [comment]
Duplicate of #6143
