### ISSUE TITLE
JsInteropRestrictionChecker log sorting should put into account Error vs Warning

### ISSUE THREAD

**Issue by gkdn** [gwtproject/gwt#9375]
Currently, if the output it spammed with restriction checking warnings, it is hard to find real errors.

**Comment by gkdn** [comment]
@rluble assigned to you but didn't put into milestone. If it is something quick to fix, you can take a look.

**Comment by rluble** [comment]
Do you mean sort by type, line instead of line, type? or the other way around. You want all warnings first and then all errors? Please clarify.

**Comment by gkdn** [comment]
Yes, sort by type and sort by line. Probably errors first, warnings later. But that sound very good either.
Do you know what JDT / javac does? Maybe javac doesn't report any warnings if there is an error? That might a good solution. WDYT?

**Comment by rluble** [comment]
Javac does not order errors by line (if you have top and nested classes the errors for the top seem to go first then for nested independent of line nbr#, warnings if enabled seem to go last.

**Comment by rluble** [comment]
We give by File, Type (err, warning), line

Log sorting already puts into account err vs warning, but does it withing each file due to the way we output errors (header for file then lines for warn/errors).

Closing.
