### ISSUE TITLE
JsFunction in native JsType method signature causes unusable-by-js warnings

### ISSUE THREAD

**Issue by mbarkley** [gwtproject/gwt#9376]
The GWT compiler emits "unusable-by-js" warnings when a native JsType method has a JsFunction in the signature.

I've observed this while compiling applications using these types:

* [EventListener](https://github.com/errai/errai/blob/master/errai-common/src/main/java/org/jboss/errai/common/client/dom/EventListener.java), a JsFunction
* [GlobalEventHandlers](https://github.com/errai/errai/blob/master/errai-common/src/main/java/org/jboss/errai/common/client/dom/GlobalEventHandlers.java), a native JsType

For projects with JS interop exports enabled, the GWT compiler emits warnings for every method in GlobalEventHandlers even though everything works as expected at runtime.

**Comment by rluble** [comment]
You mean WITHOUT enabling -generateJsInteropExports right?

**Comment by rluble** [comment]
Could not reproduce. Could you isolate a minimal repro case?

**Comment by mbarkley** [comment]
I do not know the cause, but I am no longer able to reproduce this issue.

**Comment by mbarkley** [comment]
Could we please reopen this issue? I've now figured out how to reproduce the issue and have created a reproducer. Please checkout [this](https://github.com/mbarkley/unusable-by-js-reproducer) project and run `mvn clean package` to see the unusable-by-js warning in the console.

The warnings seem to appear when a type has a method with a JsFunction parameter and the method is not used. You can see in the entrypoint of my reproducer that there is a commented out usage of such a method: when that line is uncommented the warning goes away.

**Comment by rluble** [comment]
Code review at https://gwt-review.googlesource.com/#/c/16540.

Thanks for the repro case.
