### ISSUE TITLE
Webapp creater does not create proper launch config for tests

### ISSUE THREAD

**Issue by dankurka** [gwtproject/gwt#9378]
The launch files generated from webApp creator contain "@package.TestProjectSuite" instead of the test class.

**Comment by dankurka** [comment]
This looks related:
https://gwt-review.googlesource.com/#/c/14043/5/user/src/com/google/gwt/user/tools/templates/_eclipse-test/_moduleShortName_Suite-dev.launchsrc

**Comment by tbroyer** [comment]
https://gwt-review.googlesource.com/15440
