### ISSUE TITLE
javax.annotation.Nullable no longer available in 2.8.0-SNAPSHOT

### ISSUE THREAD

**Issue by ibaca** [gwtproject/gwt#9382]
Not sure if this is an issue, but last SNAPSHOT has started throwing this errors:

```
[INFO]             [ERROR] Line ??: The import javax.annotation.Nullable cannot be resolved
[INFO]             [ERROR] Line ??: Nullable cannot be resolved to a type
```

~~😄 but this doesn't affect RC1 that I just realized is in maven central! 👍~~
So last SNAPSHOT and RC1 do not contains findbug classes. Workaround: add the maven dependency manually.

```
<dependency>
  <groupId>com.google.code.findbugs</groupId>
  <artifactId>jsr305</artifactId>
  <version>3.0.0</version>
</dependency>
```

**Comment by tbroyer** [comment]
Do you think we should add them for backwards-compatibility?

My opinion is that if you use those annotations you should have the dependency already.
Possibly we could add something to the release notes (unbundling most dependencies is actually quite a big change, so we should probably mention it anyway).
/cc @jDramaix

**Comment by ibaca** [comment]
GWT 2.8 has already some breaking changes, so adding to the releases notes is enough 👍 

And yep, I most of the project the dependency is explicit, but I found the problem in a project which depends on other project with the findbugs as an optional dependency.

**Comment by mkristian** [comment]
I am OK with adding this depdency to restygwt unless gwt-jackson is doing it. so basically I am saying: 
+1 for leaving it as is and add something in the release notes about it

**Comment by michael-newsrx** [comment]
Confirmed, adding:
```
gwt 'com.google.code.findbugs:jsr305:3.0.0'
```
to my Gradle dependencies has fixed the compile issue for me.

**Comment by ibaca** [comment]
Closing because it should (and is already fixed) by  each lib depending on jsr305.
