### ISSUE TITLE
There is no way to set -style PRETTY in SDM when launched using dev.DevMode entrypoint (was pretty in 2.7)

### ISSUE THREAD

**Issue by TheBojda** [gwtproject/gwt#9385]
In the Scope view in Chorme Dev Tools, class names was shown correctly in GWT 2.7, but in 2.8-rc1 I can see only the obfuscated class names.

**Comment by tbroyer** [comment]
Are you talking about #9210, or that source maps don't work? or something else?

**Comment by TheBojda** [comment]
When I run my project in super dev mode, and the execution stops on a brakepoint (I can add the brakepoint, so source maps works fine) I see the class names correctly in scope view: http://estontorise.hu/scope27.png

But if I run it with 2.8, when it stops on the brakepoint, I see obfuscated names: http://estontorise.hu/scope28.png

I think, it is different issue than #9210 .

**Comment by rluble** [comment]
IIRC, using -style PRETTY you should get the same names as in 2.7

**Comment by tbroyer** [comment]
@rluble #9210 says it's not the case.

**Comment by rluble** [comment]
I see. The code (
https://gwt.googlesource.com/gwt/+/HEAD/dev/core/src/com/google/gwt/dev/jjs/JavaToJavaScriptCompiler.java#1082)
is supposed to honour the -style flag. Can someone debug this issue to see
if the flag is not being passed correctly when in SDM?

**Comment by rluble** [comment]
I verified in our internal workflow and if -style PRETTY is passed to superdevmode then the names of methods are in the PRETTY style. You do have to force clean through the superdevmode console page.

Class names are the names of the constructors so class names are also prettyfied in this mode. 

C

**Comment by TheBojda** [comment]
I'm using Google Plugin for Eclipse, which uses com.google.gwt.dev.DevMode to run CodeServer. I think in 2.7 -style PRETTY was the default for the CodeServer, but in 2.8 the default is OBFUSCATED. Is it possible to set the style parameter for CodeServer if I use com.google.gwt.dev.DevMode? Why OBFUSCATED is the style in 2.8?

**Comment by rluble** [comment]
Google Plugin for eclipse is a separate project and currently dev.DevMode does not handle the parameter (and is deprecated as well). 

IIRC 2.7 did not have an obfuscated SDM mode; it was introduced after the release. The current default is consistent with the rest of the compiler entrypoints where obfuscated is assumed unless otherwise specified.

**Comment by rluble** [comment]
Uploaded a code review at  https://gwt-review.googlesource.com/15523

**Comment by TheBojda** [comment]
Works fine. Ty guys!
