### ISSUE TITLE
Unnecessary cast introduced to internal String.fromCharCode

### ISSUE THREAD

**Issue by gkdn** [gwtproject/gwt#9388]
This is due to String.NativeFunction definition that uses generics which causes a cast to apply call.

**Comment by gkdn** [comment]
https://gwt-review.googlesource.com/15521

**Comment by jnehlmeier** [comment]
Possibly reintroduced by https://gwt-review.googlesource.com/#/c/16720/ ?

**Comment by rluble** [comment]
Fixed by https://gwt-review.googlesource.com/#/c/16740/
