### ISSUE TITLE
Accessing common types (e.g. String) via $wnd cause significant slows down

### ISSUE THREAD

**Issue by gkdn** [gwtproject/gwt#9389]
In Chrome: slowdown is observable only if page is accessed via file url. Changing $wnd to window significantly improves the situation and removing the qualifier fixes the issue.
In Firefox: slowdown is always observable. Removing qualifier or replacing it with window solves the issue.

$wnd is used to make sure we have access to same scope exported stuff to main window and also to help casting/instanceof. The potential solution is to special case some fundamental types (String, Object, Array) that we already customized instanceof operation to no longer get qualified with $wnd.

**Comment by rluble** [comment]
Code review at https://gwt-review.googlesource.com/#/c/15520

Remove $wnd from access to common types.
