### ISSUE TITLE
GWT 2.8 RC2 - still nocache.js timestamp issue

### ISSUE THREAD

**Issue by mxlse** [gwtproject/gwt#9400]
I still have the timestamp issue with GWT 2.8 RC2. The *.nocache.js file gets the timestamp of the last change the module.gwt.xml during compilation instead of the actual timestamp. This issue was already present in GWT 2.7 & GWT 2.8 RC1. There was already a workaround in the maven build, but it would be great to fix this in GWT 2.8.

**Comment by jnehlmeier** [comment]
@tbroyer Haven't you rolled back the change in trunk so that this issue shouldn't exist anymore?

**Comment by tbroyer** [comment]
Yes, the change has been rolled back and the timestamp is always set to the current time (as long as there's at least one permutation, IIUC to exclude legacy devmode so it doesn't overwrite an existing file)

**Comment by tbroyer** [comment]
The rollback was 3cd96f2e1a7974068da61414b4d21c67ec2f7d59

@mxlse Do you have a repro case?

Tentatively closing for now as I don't reproduce. Will reopen if/when we have a repro case.
