### ISSUE TITLE
RC2: InterfaceGenerator mangles @def words that start with a numeral

### ISSUE THREAD

**Issue by ShaunEdiger** [gwtproject/gwt#9401]
When using 2.8.0-rc2, a @def statement such as
`@def DEF_1 #FFF;` in a .gss will confuse InterfaceGenerator (gwt:css).  The resulting method will be nameed `def1`, but calling the method will result in the following failure:

[ERROR] The following method [def1()] doesn't match a constant nor a style class. You could fix that by adding .def1 {}

Using `DEF_N1` will work successfully.

I first encountered the issue on August 1st using SNAPSHOT.

I'm attaching a maven project to demonstrate the problem.  Running `mvn clean prepare-package` ought to be sufficient.  The offending @def is located in `DefsImpl.gss`.

[gss-def-interface-generator.zip](https://github.com/gwtproject/gwt/files/421055/gss-def-interface-generator.zip)

**Comment by gkdn** [comment]
@jDramaix could you take a look and see if there is a quick fix before 2.8?

**Comment by jDramaix** [comment]
The problem seems to come from Guava.

```
   // returns def1
   CaseFormat.UPPER_UNDERSCORE.to(CaseFormat.LOWER_CAMEL, "DEF_1");

   // return DEF1
   CaseFormat.LOWER_CAMEL.to(CaseFormat.UPPER_UNDERSCORE, "def1");
```

I'm checking with the guava team if it's the expected behavior. Otherwise, the quick fix could be to change the InterfaceGenerator to use DEF_1 as method name instead of trying to convert the name of the constant to lower camel case when the pattern `_[0-9]` is detected in the constant name.

**Comment by tbroyer** [comment]
Instead of "the pattern `_[0-9]`", how about testing roundtripping instead?

**Comment by jDramaix** [comment]
agree.

**Comment by jDramaix** [comment]
In review: https://gwt-review.googlesource.com/#/c/17040/2
