### ISSUE TITLE
Methods getTypeName() and getTypeParameters() are missing from the type Class

### ISSUE THREAD

**Issue by zak905** [gwtproject/gwt#9408]
I tried calling the method getTypeName() from the client side: 

```
public String getTypeName(Object object) {
    
         return object.getClass().getTypeName();

}

````

and I got the following error message: 

[ERROR] Line 63: The method getTypeName() is undefined for the type Class<capture#1-of ? extends Object>
[INFO]    [ERROR] Hint: Your source appears not to live underneath a subpackage called 'client'; no problem, but you'll need to use the <source> directive in your module to make it accessible. 

And the same goes for getTypeParameters() . 

I understand that they are not included in the emulated "Class" class. I think they can be useful. Are there any particular reasons they are not included ?

**Comment by rluble** [comment]
GWT does not support the reflection API. Class has only minimal API support. 

http://www.gwtproject.org/doc/latest/DevGuideCodingBasicsCompatibility.html

**Comment by zak905** [comment]
Ok thanks for the information. Is there any way to detect type parameters from the client side? I am aware of JParametrizedType, but I am not sure it can be used there.

**Comment by tbroyer** [comment]
> detect type parameters from the client side

This is reflection, and is not supported, for quite good reasons. Try using some code generation instead (and skip GWT generators and jump right to annotation processing)
