### ISSUE TITLE
GWT 2.8 and htmlunit 2.19: Problems to execute jQuery in htmlunit.

### ISSUE THREAD

**Issue by rdeangelis83** [gwtproject/gwt#9410]
Hi All,

with the following commit: https://github.com/gwtproject/gwt/commit/e29062339d6369b58270ac3bf746a590a278787b the htmlunit version was updated from 2.13 to 2.19 to  upgrade to jetty 9.2.

It seems that the version 2.19 of htmlunit has some problems to handle javascript code containing expression with 'Symbol.iterator' correctly. So it is not possible to load jQuery in GWTTestCases using the ScriptInjector eg. in gwtbootstrap3: 

ScriptInjector.fromString(GwtBootstrap3ClientBundle.INSTANCE.jQuery().getText()).inject();  

With the latest version of htmlunit (2.23) everything works perfectly. But in htmlunit 2.23 the browser support for ie8 was removed. I had to create my own RunStyle (com.google.gwt.junit.RunStyle) to remove the static dependency to  //addBrowser(BrowserVersion.INTERNET_EXPLORER_8, "ie8"); in the RunStyleHtmlUnit class. 

What do you think would it possible to update the htmlunit version? Or maybe possible to losd the htmlunit BrowserVersion over reflection so that it can be updated adding an additional maven dependency?

THX
Rocco

**Comment by tbroyer** [comment]
I think your workaround would be OK for 2.8.0, and we could update HTMLUnit in 2.8.1. WDYT?

**Comment by rdeangelis83** [comment]
Hi Thomas,

yes that would be okay. If you need some help with this issue maybe I can provide a patch or help to test and validate the fix. 

THX
Rocco

**Comment by jschmied** [comment]
Hi!
Would is be possible to share the workaround (the new RunStyle) ?
Thanks!

**Comment by Fractaliste** [comment]
You save my day, HTMLUnit 2.19 is not able to load [Mapbox-gl](https://www.mapbox.com/mapbox-gl-js/api/)'s javascript. The 2.23 can.

**Comment by kevzlou7979** [comment]
Same issue for me with GWT 2.9 when adding 
`ScriptInjector.fromString(jQueryResources.jQuery().getText()).inject(); `

**Comment by kevzlou7979** [comment]
OK I did what @rdeangelis83 suggested for workaround. Will be looking in the future for GWT to update the HtmlUnitTest.

**Comment by niloc132** [comment]
See discussion at https://github.com/gwtproject/gwt/issues/9720, this will be fixed by that htmlunit upgrade.
