### ISSUE TITLE
Problems with GWT.log 'Uncaught TypeError: Cannot read property 'console' of null'

### ISSUE THREAD

**Issue by BenDol** [gwtproject/gwt#9412]
Not sure if this is something wrong on my end, but this issue only just started taking place after a SNAPSHOT update.

```
Uncaught TypeError: Cannot read property 'console' of null
```

My module configuration:

``` xml
<module rename-to='gmdtesting'>
    <inherits name='com.google.gwt.user.User'/>
    <inherits name="com.google.gwt.logging.Logging"/>

    <!-- Specify the paths for translatable code -->
    <source path='client'/>
    <source path='shared'/>

    <!-- Specify the app entry point class -->
    <entry-point class='gwt.material.design.testing.client.GwtMaterialTesting'/>

    <!-- Dev Properties -->
    <set-property name="gwt.logging.logLevel" value="ALL" />
    <set-property name="gwt.logging.developmentModeHandler" value="ENABLED" />

    <set-property name="compiler.stackMode" value="emulated" />
    <set-property name="compiler.emulatedStack" value="true"/>
    <set-property name="compiler.useSourceMaps" value="true" />

    <extend-property name="locale" values="en"/>
    <set-property-fallback name="locale" value="en"/>

    <set-configuration-property name="compiler.emulatedStack.recordLineNumbers" value="true"/>
    <set-configuration-property name="compiler.emulatedStack.recordFileNames" value="true"/>
    <set-configuration-property name="compiler.enum.obfuscate.names" value="false" />

    <set-configuration-property name="CssResource.style" value="pretty"/>
    <collapse-all-properties />

    <add-linker name="xsiframe"/>
</module>
```

How I produce the issue:

``` java
public class MyEntryPoint implements EntryPoint {
    @Override
    public void onModuleLoad() {
         // This will throw the error
        GWT.setUncaughtExceptionHandler(e -> GWT.log(e.getMessage(), e));
        // This will also throw the error
        Scheduler.get().scheduleDeferred(() -> GWT.log("message"));
    }
}
```

Seems that the `ConsoleLogger` is where the issue is happening:

``` java
private static native boolean isSupported() /*-{
  return !!window.console;
}-*/;
```

I could have set something up incorrectly but thought I'd submit the issue encase there is a problem here. Thanks!

**Comment by jnehlmeier** [comment]
At work we also noticed that TypeError every now and then when reloading the page in SDM.

**Comment by gkdn** [comment]
Which browser? Is this consistently happening?

**Comment by BenDol** [comment]
Chrome and yes consistently happening.

**Comment by dsouth** [comment]
This may be completely irrelevant, but I've had a similar issue trying to debug some code someone else wrote. I too am using Chrome and consistently get the error.

However, if I run the same with Firefox running Firebug I don't get this error and do get the expected output on the console log. So maybe it is a Chrome issue?

**Comment by gkdn** [comment]
@dankurka Can you take a look? If you can't, let me know.

**Comment by dankurka** [comment]
I can not reproduce this with my Chrome Version 52.0.2743.116 (64-bit).

Do you maybe have some weird chrome extension, different version etc?

**Comment by gkdn** [comment]
Perhaps different OS?

**Comment by jnehlmeier** [comment]
I'll try to cause this tomorrow at work again and maybe I can figure out a way to reproduce it. The above code works for me so far. 

However at work we do not use 2.8 RC2 but a relatively old version somewhere between 2.7 and 2.8-beta1 (commit: https://github.com/gwtproject/gwt/commit/dde41460883b4a240b65aa85ad62d993355b7304 which is the last commit before GWT cleaned up some internal API that caused Guava 19 to break). 

My colleague uses some Chrome 50 or 51 as he has an older OS X version while I am using latest Chrome Beta (54?) on OS X El Capitan. But we both have seen this issue for a while with different Chrome versions. 

Doesn't occur that often but when it does its always on page reload (which is relatively slow and intense as the app is quite large in SDM).

**Comment by BenDol** [comment]
I am running Windows 7, I disabled all my extensions and still receive this error. I am running the latest snapshot and it is consistently causing the error still.

I have figured out how to reproduce the issue, you can try it out here with this maven project: https://github.com/BenDol/gwt-bugs

![issue](https://cloud.githubusercontent.com/assets/1935706/18375506/fdcb14dc-76aa-11e6-9795-bd283119d807.gif)

**Comment by BenDol** [comment]
Seems that the `RootPanel.get().clear(true)` is what is causing the issue. Is this the intended behavior?

**Comment by gkdn** [comment]
I don't know how they interact but this relatively recently added clear method already beat us multiple times (broke classic dev mode, history etc). It is generally unsafe. I think we should deprecate it.
Any concerns?

**Comment by gkdn** [comment]
@dankurka Can you deprecate the method with an explanation of the potential harms?

**Comment by jnehlmeier** [comment]
Ok just tried it in our app. We always get the error when reloading the page while having a pending GWT-RPC request. When doing so, Chrome will abort the request and `AsyncCallback.onFailure()` is called with a `StatusCodeException: 0` because the connection has been terminated without having any server status code received.

In our `AsyncCallback.onFailure()` we then call `LOGGER.log(Level.SEVERE, "Uncaught: ", caught);` during development which causes 
```java
private static native boolean isSupported() /*-{
  return !!window.console;
}-*/;
```
to trigger the error described here. Interestingly Chrome DevTools won't stop at any breakpoint I set in the `onFailure` method or in the logging code when triggering a page reload. So I had to use `Window.alert()` to get at least some information, which luckily works as it uses `$wnd.alert()` instead of `window.alert()` (console logger also uses `window.console` instead of `$wnd.console`)

So I think the issue is that Chrome somehow "nullifies" the iframe window object when reloading the page but still executes some JS (the `onFailure()` callback). Maybe using `$wnd.console` in `ConsoleLogger` would be a workaround.

**Comment by tbroyer** [comment]
So this is a Chrome quirk? Anyone reviewed the commit history and their associated code-review comments about `window.console` vs. `$wnd.console`? IIRC, using `window` here was to avoid bad polyfill and other conflicts when console wasn't widespread. Maybe this is moot nowadays?

**Comment by rluble** [comment]
W.r.t window.console vs $wnd.console we try not to explicitly refer to $wnd withing JRE files for future compatibility. That said this seems easily replaced by using JsInterop to refer to window.console. Anyway I'll let goktug chime in since he is the authored that code and is aware of the issue.

**Comment by gkdn** [comment]
IIRC, $wnd.console was not working in one of the environments (might be firebug). I should have commented that; I don't remember it now :/ But being said that as @rluble pointed we don't refer $wnd directly anymore but we can still use jsinterop to achieve that.

If you can test this in common Chrome, Firefox, Firebug and verify that it works, we can switch to just 'console' or '$wnd.console' if that fixes the problem.

**Comment by wlsc** [comment]
@gkdn just 'console' would be fine. It works now in all modern browsers.

**Comment by gkdn** [comment]
Uploaded https://github.com/gwtproject/gwt/issues/9412

Could someone test this with CrossSiteIframeLinker in Chrome, Safari, Firefox and Firebug as well and verify that it works fine?

**Comment by gkdn** [comment]
Seems like console is not what we are looking for. If you guys can test this in platforms I listed above, I can send another patch with $wnd. 
However I'm leaning towards just leaving this alone and proceed with release.

**Comment by gkdn** [comment]
Uploaded new version if somebody wants to test.
(I am 90 percent sure $wnd was not working somewhere)

**Comment by gkdn** [comment]
Removed from 2.8. On bright side this is not a regression.

**Comment by tbroyer** [comment]
New review: https://gwt-review.googlesource.com/c/gwt/+/19380; rescheduling for 2.8.2

**Comment by gkdn** [comment]
Fixed

**Comment by tbroyer** [comment]
Related: https://gwt-review.googlesource.com/c/gwt/+/19400
