### ISSUE TITLE
webAppCreator - generated maven sample does not run

### ISSUE THREAD

**Issue by herbalifebc** [gwtproject/gwt#9419]
$ webAppCreator -templates maven,sample -out foo com.foo.app
    // generates project
$ mvn war:exploded
    // compiles OK
$ mvn gwt:run
INFO] Scanning for projects...
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 0.162 s
[INFO] Finished at: 2016-09-08T14:34:25-07:00
[INFO] Final Memory: 16M/981M
[INFO] ------------------------------------------------------------------------
[ERROR] Could not find goal 'run' in plugin net.ltgt.gwt.maven:gwt-maven-plugin:1.0-rc-6 among available goals add-super-sources, add-test-super-sources, codeserver, compile, devmode, enforce-encoding, generate-module, generate-module-metadata, help, import-sources, import-test-sources, package-app, test -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoNotFoundException

Environment:
MacOS: 10.11.16
Java Version: 1.8.0_66"
webAppCreator version: 2.8.0-rc2
maven version: 3.3.3

Here is the GWT Maven Plugin section of the POM (no longer groupId org.codehaus.mojo?!?!?)

      <plugin>
        <groupId>net.ltgt.gwt.maven</groupId>
        <artifactId>gwt-maven-plugin</artifactId>
        <version>1.0-rc-6</version>
        <executions>
          <execution>
            <goals>
              <goal>import-sources</goal>
              <goal>compile</goal>
              <goal>import-test-sources</goal>
              <goal>test</goal>
            </goals>
          </execution>
        </executions>
        <configuration>
          <moduleName>com.foo.app</moduleName>
          <moduleShortName>app</moduleShortName>
          <failOnError>true</failOnError>
          
          <sourceLevel>1.8</sourceLevel>
          
          <compilerArgs>
            
            <arg>-compileReport</arg>
            <arg>-XcompilerMetrics</arg>
          </compilerArgs>
          
          <warDir>${project.build.directory}/${project.build.finalName}</warDir>
          <classpathScope>compile+runtime</classpathScope>
          
          <startupUrls>
            <startupUrl>app.html</startupUrl>
          </startupUrls>
        </configuration>
      </plugin>

**Comment by herbalifebc** [comment]
Solution: use "mvn gwt:codeserver" instead.

Looks like this is a documentation bug or at a minimum something that should be mentioned in the release notes.

**Comment by tbroyer** [comment]
The README generated by the webAppCreator (if you pass the `readme` option to `-templates`) has the up-to-date instructions. The website at gwtproject.org hasn't yet been updated for GWT 2.8.

That being said, I (personally) discourage the use of webAppCreator to create Maven projects (actually, I don't think one should ever use it, except for quickly bootstrapping throwaway projects such as issue repro cases or quick experiments). Use one of my [archetypes](https://github.com/tbroyer/gwt-maven-archetypes) instead.
