### ISSUE TITLE
Deobfuscation by analyzing stack trace

### ISSUE THREAD

**Issue by goelnitish** [gwtproject/gwt#9421]
We have an enterprise level application and we use GWT for it. We need to analyze the stack traces printed in the browser's console but we do not ship the symbol maps into production. We have the symbol maps with us, we just need a provision to deobfuscate the stack trace printed in the console.

The client would send us the printed stack trace (so a String and not a Throwable)  and we would analyze it internally (as we have the symbol maps with us). How can we achieve this?

**Comment by tbroyer** [comment]
You'd have to parse the stacktrace into an array of `StackTraceElement`, construct an `Throwable` and set its stacktrace to that parsed array, then use `StackTraceDeobfuscator`. You can have a look at how `JsonLogRecordServerUtil` does that (from a JSON representation of the stacktrace; note that you can create that JSON on the client using `JsonLogRecordClientUtil`).

BTW, please direct your questions to the [forum](https://groups.google.com/forum/#!forum/google-web-toolkit) or [StackOverflow](https://stackoverflow.com/questions/tagged/gwt) and keep this tracker for issues only.
