### ISSUE TITLE
Remove javascript:'' from codebase

### ISSUE THREAD

**Issue by tbroyer** [gwtproject/gwt#9434]
At the request of @mikewest (see https://twitter.com/mikewest/status/781501462429986816 's parent chain), try to remove our uses of `src="javascript:''"` (and when possible `href="javascript:''"`).

Most instances are for iframes (we historically recommended it for the "history iframe" used by IE6/7), such as  `FormPanel`, `NamedFrame` and `RichTextArea`. But these are not used that much; the instance used by most people actually is in `installLocationIframe.js` used by the xsiframe linker; along with the older/deprecated `HostedModeTemplate.js` (for legacy DevMode) and `IframeTemplate.js` (for the standard linker).

``` bash
$ git grep "javascript:['\"]"
dev/codeserver/java/com/google/gwt/dev/codeserver/dev_mode_on.js:    result.setAttribute('href', 'javascript:' + encodeURIComponent(javascript));
dev/codeserver/java/com/google/gwt/dev/codeserver/frontpage.html:  result.setAttribute("href", "javascript:" + encodeURIComponent(javascript));
dev/core/src/com/google/gwt/core/ext/linker/impl/HostedModeTemplate.js:      iframe.src = "javascript:''";
dev/core/src/com/google/gwt/core/ext/linker/impl/installLocationIframe.js:  scriptFrame.src = 'javascript:""';
dev/core/src/com/google/gwt/core/linker/IFrameTemplate.js:      iframe.src = "javascript:''";
eclipse/reference/code-museum/war/DefaultMuseum.html:    <iframe src="javascript:''" id="__gwt_historyFrame" style="position:absolute;width:0;height:0;border:0"></iframe>
user/src/com/google/gwt/user/client/ui/FormPanel.java:    @Template("<iframe src=\"javascript:''\" name='{0}' tabindex='-1' "
user/src/com/google/gwt/user/client/ui/NamedFrame.java:    @Template("<iframe src=\"javascript:''\" name='{0}'>")
user/src/com/google/gwt/user/client/ui/impl/RichTextAreaImplIE8toIE10.java:    elem.setPropertyString("src", "javascript:''");
user/test/com/google/gwt/user/client/ui/ButtonTest.java:    f.setAction("javascript:''");
user/test/com/google/gwt/user/client/ui/NamedFrameTest.java:    assertEquals("javascript:''", new NamedFrame("defaultSrc").getUrl());
```

(note that the first 2 results are false positives)

FWIW, we use a few `javascript:;` or `javascript:void(0);` for "link buttons" (clickable things that we wanted to make look like links), such as `Anchor#DEFAULT_HREF`, `DisclosurePanel`, `CellTreeNodeView`'s "show more…", in samples, etc. that we'd better change too as we're at it; but they aren't covered by Mike West's request.

**Comment by tbroyer** [comment]
`FormPanel` fixed in 05091ff95a904b42246f5d9b90b6ae362c1bb5fb

**Comment by jnehlmeier** [comment]
I guess we move that to 2.8.2 as it seems like low priority and nobody will push a change to Gerrit in a timely manner so it can land in 2.8.1?

**Comment by tbroyer** [comment]
https://gwt-review.googlesource.com/c/gwt/+/19323
