### ISSUE TITLE
GWT 2.8 debugging issue

### ISSUE THREAD

**Issue by hrstoyanov** [gwtproject/gwt#9442]
Hi all,
I bumped into a nasty problem - I have an exception being thrown at Widget.java:341
The only reason i think this is the place that throws the exception is the exception text as you can see in the attached image. 

However, the Chrome debugger never stops at the breakpoint, and the stack trace in the console is useless.  I can step through other parts of the code and codeserver appears to work ok otherwise.

Any idea whow can I improve my GWT dev experience in Chrome ?

![image](https://cloud.githubusercontent.com/assets/5327044/19294042/2fae6e3a-8fde-11e6-9e20-52543c8b9888.png)

**Comment by hrstoyanov** [comment]
Related posts:
https://developer.jboss.org/thread/272402


I should say that at one occasion, I was able to stop and get the right stack trace - see image attached or Errai issue filed:
https://issues.jboss.org/browse/ERRAI-987

![capture](https://cloud.githubusercontent.com/assets/5327044/19294198/5612f112-8fdf-11e6-823e-0cd79ac860dc.PNG)

**Comment by tbroyer** [comment]
FWIW, in the first image you set the breakpoint in `onAttach` but the exception talks about `onDetach`.

**Comment by hrstoyanov** [comment]
Thank you, Thomas
