### ISSUE TITLE
Error constructing Java AST - NullPointerException

### ISSUE THREAD

**Issue by MdSE** [gwtproject/gwt#9445]
Hi all,

Have a GWT 2.7 app and when I was trying to compile it with GWT 2.8.0-rc3 and got a null pointer exception. I made no changes to the source code, just updated the pom to compile with GWT 2.8 rc3.  I'm not sure if its an application or GWT compile/translate error. Could you please help me?

A strange thing is that it sometimes compiles (without any modification) but most of them it doesn’t.

The stack trace is:
```
com.google.gwt.dev.jjs.InternalCompilerException: Error constructing Java AST
[INFO] 	at com.google.gwt.dev.jjs.impl.GwtAstBuilder.translateException(GwtAstBuilder.java:3944)
[INFO] 	at com.google.gwt.dev.jjs.impl.GwtAstBuilder$AstVisitor.endVisit(GwtAstBuilder.java:1567)
[INFO] 	at org.eclipse.jdt.internal.compiler.ast.MessageSend.traverse(MessageSend.java:1043)
[INFO] 	at org.eclipse.jdt.internal.compiler.ast.MessageSend.traverse(MessageSend.java:1031)
[INFO] 	at org.eclipse.jdt.internal.compiler.ast.MethodDeclaration.traverse(MethodDeclaration.java:357)
[INFO] 	at org.eclipse.jdt.internal.compiler.ast.TypeDeclaration.traverse(TypeDeclaration.java:1360)
[INFO] 	at com.google.gwt.dev.jjs.impl.GwtAstBuilder.processImpl(GwtAstBuilder.java:3887)
[INFO] 	at com.google.gwt.dev.jjs.impl.GwtAstBuilder.process(GwtAstBuilder.java:3918)
[INFO] 	at com.google.gwt.dev.javac.CompilationStateBuilder$CompileMoreLater$UnitProcessorImpl.process(CompilationStateBuilder.java:129)
[INFO] 	at com.google.gwt.dev.javac.JdtCompiler$CompilerImpl.process(JdtCompiler.java:384)
[INFO] 	at org.eclipse.jdt.internal.compiler.Compiler.processCompiledUnits(Compiler.java:546)
[INFO] 	at org.eclipse.jdt.internal.compiler.Compiler.compile(Compiler.java:458)
[INFO] 	at com.google.gwt.dev.javac.JdtCompiler.doCompile(JdtCompiler.java:1092)
[INFO] 	at com.google.gwt.dev.javac.CompilationStateBuilder$CompileMoreLater.compile(CompilationStateBuilder.java:325)
[INFO] 	at com.google.gwt.dev.javac.CompilationStateBuilder.doBuildFrom(CompilationStateBuilder.java:548)
[INFO] 	at com.google.gwt.dev.javac.CompilationStateBuilder.buildFrom(CompilationStateBuilder.java:479)
[INFO] 	at com.google.gwt.dev.javac.CompilationStateBuilder.buildFrom(CompilationStateBuilder.java:465)
[INFO] 	at com.google.gwt.dev.cfg.ModuleDef.getCompilationState(ModuleDef.java:423)
[INFO] 	at com.google.gwt.dev.Precompile.precompile(Precompile.java:222)
[INFO] 	at com.google.gwt.dev.Precompile.precompile(Precompile.java:202)
[INFO] 	at com.google.gwt.dev.Precompile.precompile(Precompile.java:143)
[INFO] 	at com.google.gwt.dev.Compiler.compile(Compiler.java:204)
[INFO] 	at com.google.gwt.dev.Compiler.compile(Compiler.java:155)
[INFO] 	at com.google.gwt.dev.Compiler.compile(Compiler.java:144)
[INFO] 	at com.google.gwt.dev.Compiler$1.run(Compiler.java:118)
[INFO] 	at com.google.gwt.dev.CompileTaskRunner.doRun(CompileTaskRunner.java:55)
[INFO] 	at com.google.gwt.dev.CompileTaskRunner.runWithAppropriateLogger(CompileTaskRunner.java:50)
[INFO] 	at com.google.gwt.dev.Compiler.main(Compiler.java:125)
[INFO] Caused by: java.lang.NullPointerException
[INFO] 	at com.google.gwt.dev.javac.JdtUtil.join(JdtUtil.java:67)
[INFO] 	at com.google.gwt.dev.javac.JdtUtil.asDottedString(JdtUtil.java:59)
[INFO] 	at com.google.gwt.dev.jjs.impl.ReferenceMapper.createType(ReferenceMapper.java:275)
[INFO] 	at com.google.gwt.dev.jjs.impl.ReferenceMapper.get(ReferenceMapper.java:146)
[INFO] 	at com.google.gwt.dev.jjs.impl.GwtAstBuilder$AstVisitor.endVisit(GwtAstBuilder.java:1559)
```

**Comment by rluble** [comment]
Hmm. Could you post the few lines in the output after this exception? Doesn't it mention where in the source the problem is?

**Comment by jsb1** [comment]
Same Problem here. 2.8.0-rc1 -rc3 crashing, compiles with 2.7.0. 
See attached maven project.

[gwt-compiler-nullpointer.zip](https://github.com/gwtproject/gwt/files/535666/gwt-compiler-nullpointer.zip)

**Comment by jsb1** [comment]
forgot something:

java version "1.8.0_101"
Java(TM) SE Runtime Environment (build 1.8.0_101-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.101-b13, mixed mode)

on ubuntu 16.04

**Comment by tbroyer** [comment]
@jsb1: for some reason (apparently `gwtp-mvp-client` dependency), you're using gwt-dev 2.7 with gwt-user 2.8.0-rc3. Adding an explicit dependency on gwt-dev 2.8.0-rc3 fixes the problem (you could also use `dependencyManagement`, possibly with `com.google.gwt:gwt` with `<type>pom</type><scope>import</scope>`; or exclude the `gwt-dev` transitive dependency from `gwtp-mvp-client` to let the gwt-maven-plugin add the "correct" one).

@MdSE Can you check you're not in the same case?

**Comment by MdSE** [comment]
@rluble :

[INFO] --- gwt-maven-plugin:2.8.0-rc3:compile (default) @ multiverse-webui ---
[INFO] Compiling module XXX
[INFO] [ERROR] An internal compiler exception occurred
[INFO] com.google.gwt.dev.jjs.InternalCompilerException: Error constructing Java AST
[INFO] 	at com.google.gwt.dev.jjs.impl.GwtAstBuilder.translateException(GwtAstBuilder.java:3944)
[INFO] 	at com.google.gwt.dev.jjs.impl.GwtAstBuilder$AstVisitor.endVisit(GwtAstBuilder.java:1567)
[INFO] 	at org.eclipse.jdt.internal.compiler.ast.MessageSend.traverse(MessageSend.java:1043)
[INFO] 	at org.eclipse.jdt.internal.compiler.ast.MessageSend.traverse(MessageSend.java:1031)
[INFO] 	at org.eclipse.jdt.internal.compiler.ast.MethodDeclaration.traverse(MethodDeclaration.java:357)
[INFO] 	at org.eclipse.jdt.internal.compiler.ast.TypeDeclaration.traverse(TypeDeclaration.java:1360)
[INFO] 	at com.google.gwt.dev.jjs.impl.GwtAstBuilder.processImpl(GwtAstBuilder.java:3887)
[INFO] 	at com.google.gwt.dev.jjs.impl.GwtAstBuilder.process(GwtAstBuilder.java:3918)
[INFO] 	at com.google.gwt.dev.javac.CompilationStateBuilder$CompileMoreLater$UnitProcessorImpl.process(CompilationStateBuilder.java:129)
[INFO] 	at com.google.gwt.dev.javac.JdtCompiler$CompilerImpl.process(JdtCompiler.java:384)
[INFO] 	at org.eclipse.jdt.internal.compiler.Compiler.processCompiledUnits(Compiler.java:546)
[INFO] 	at org.eclipse.jdt.internal.compiler.Compiler.compile(Compiler.java:458)
[INFO] 	at com.google.gwt.dev.javac.JdtCompiler.doCompile(JdtCompiler.java:1092)
[INFO] 	at com.google.gwt.dev.javac.CompilationStateBuilder$CompileMoreLater.compile(CompilationStateBuilder.java:325)
[INFO] 	at com.google.gwt.dev.javac.CompilationStateBuilder.doBuildFrom(CompilationStateBuilder.java:548)
[INFO] 	at com.google.gwt.dev.javac.CompilationStateBuilder.buildFrom(CompilationStateBuilder.java:479)
[INFO] 	at com.google.gwt.dev.javac.CompilationStateBuilder.buildFrom(CompilationStateBuilder.java:465)
[INFO] 	at com.google.gwt.dev.cfg.ModuleDef.getCompilationState(ModuleDef.java:423)
[INFO] 	at com.google.gwt.dev.Precompile.precompile(Precompile.java:222)
[INFO] 	at com.google.gwt.dev.Precompile.precompile(Precompile.java:202)
[INFO] 	at com.google.gwt.dev.Precompile.precompile(Precompile.java:143)
[INFO] 	at com.google.gwt.dev.Compiler.compile(Compiler.java:204)
[INFO] 	at com.google.gwt.dev.Compiler.compile(Compiler.java:155)
[INFO] 	at com.google.gwt.dev.Compiler.compile(Compiler.java:144)
[INFO] 	at com.google.gwt.dev.Compiler$1.run(Compiler.java:118)
[INFO] 	at com.google.gwt.dev.CompileTaskRunner.doRun(CompileTaskRunner.java:55)
[INFO] 	at com.google.gwt.dev.CompileTaskRunner.runWithAppropriateLogger(CompileTaskRunner.java:50)
[INFO] 	at com.google.gwt.dev.Compiler.main(Compiler.java:125)
[INFO] Caused by: java.lang.NullPointerException
[INFO] 	at com.google.gwt.dev.javac.JdtUtil.join(JdtUtil.java:67)
[INFO] 	at com.google.gwt.dev.javac.JdtUtil.asDottedString(JdtUtil.java:59)
[INFO] 	at com.google.gwt.dev.jjs.impl.ReferenceMapper.createType(ReferenceMapper.java:275)
[INFO] 	at com.google.gwt.dev.jjs.impl.ReferenceMapper.get(ReferenceMapper.java:146)
[INFO] 	at com.google.gwt.dev.jjs.impl.GwtAstBuilder$AstVisitor.endVisit(GwtAstBuilder.java:1559)
[INFO] 	... 26 more
[INFO]    [ERROR] at XXX.java(66): display.okButton()
[INFO]       org.eclipse.jdt.internal.compiler.ast.MessageSend

**Comment by MdSE** [comment]
@tbroyer Don't think is the same problem. please see the (cropped) dependency tree

```
[INFO] --- maven-dependency-plugin:2.10:tree (default-cli) @ XXX ---
....
[INFO] +- com.google.gwt:gwt-servlet:jar:2.8.0-rc3:compile
[INFO] +- com.google.gwt:gwt-user:jar:2.8.0-rc3:compile
[INFO] |  +- com.google.jsinterop:jsinterop-annotations:jar:1.0.0:compile
[INFO] |  +- com.google.jsinterop:jsinterop-annotations:jar:sources:1.0.0:compile
[INFO] |  +- javax.validation:validation-api:jar:sources:1.0.0.GA:compile
[INFO] |  +- javax.servlet:javax.servlet-api:jar:3.1.0:compile
[INFO] |  \- org.w3c.css:sac:jar:1.3:compile
[INFO] +- com.google.gwt:gwt-dev:jar:2.8.0-rc3:compile
[INFO] |  +- com.google.code.gson:gson:jar:2.7:compile
[INFO] |  +- org.ow2.asm:asm:jar:5.0.3:compile
[INFO] |  +- org.ow2.asm:asm-util:jar:5.0.3:compile
[INFO] |  |  \- org.ow2.asm:asm-tree:jar:5.0.3:compile
[INFO] |  +- org.ow2.asm:asm-commons:jar:5.0.3:compile
[INFO] |  +- colt:colt:jar:1.2.0:compile
[INFO] |  +- ant:ant:jar:1.6.5:compile
[INFO] |  +- commons-collections:commons-collections:jar:3.2.2:compile
[INFO] |  +- commons-io:commons-io:jar:2.4:compile
[INFO] |  +- com.ibm.icu:icu4j:jar:50.1.1:compile
[INFO] |  +- tapestry:tapestry:jar:4.0.2:compile
[INFO] |  +- net.sourceforge.htmlunit:htmlunit:jar:2.21:compile
[INFO] |  |  +- xalan:xalan:jar:2.7.2:compile
[INFO] |  |  |  \- xalan:serializer:jar:2.7.2:compile
[INFO] |  |  +- org.apache.commons:commons-lang3:jar:3.4:compile
[INFO] |  |  +- org.apache.httpcomponents:httpclient:jar:4.5.2:compile
[INFO] |  |  |  \- org.apache.httpcomponents:httpcore:jar:4.4.5:compile
[INFO] |  |  +- org.apache.httpcomponents:httpmime:jar:4.5.2:compile
[INFO] |  |  +- net.sourceforge.htmlunit:htmlunit-core-js:jar:2.17:compile
[INFO] |  |  +- net.sourceforge.htmlunit:neko-htmlunit:jar:2.21:compile
[INFO] |  |  |  \- xerces:xercesImpl:jar:2.11.0:compile
[INFO] |  |  +- net.sourceforge.cssparser:cssparser:jar:0.9.18:compile
[INFO] |  |  +- commons-logging:commons-logging:jar:1.2:compile
[INFO] |  |  \- org.eclipse.jetty.websocket:websocket-client:jar:9.3.11.v20160721:compile
[INFO] |  |     \- org.eclipse.jetty.websocket:websocket-common:jar:9.2.14.v20151106:compile
[INFO] |  |        \- org.eclipse.jetty.websocket:websocket-api:jar:9.2.14.v20151106:compile
[INFO] |  +- org.eclipse.jetty:jetty-webapp:jar:9.3.11.v20160721:compile
[INFO] |  |  +- org.eclipse.jetty:jetty-xml:jar:9.3.11.v20160721:compile
[INFO] |  |  \- org.eclipse.jetty:jetty-servlet:jar:9.3.11.v20160721:compile
[INFO] |  |     \- org.eclipse.jetty:jetty-security:jar:9.3.11.v20160721:compile
[INFO] |  +- org.eclipse.jetty:jetty-servlets:jar:9.3.11.v20160721:compile
[INFO] |  |  +- org.eclipse.jetty:jetty-continuation:jar:9.3.11.v20160721:compile
[INFO] |  |  +- org.eclipse.jetty:jetty-http:jar:9.3.11.v20160721:compile
[INFO] |  |  +- org.eclipse.jetty:jetty-util:jar:9.3.11.v20160721:compile
[INFO] |  |  \- org.eclipse.jetty:jetty-io:jar:9.3.11.v20160721:compile
[INFO] |  +- org.eclipse.jetty:jetty-annotations:jar:9.3.11.v20160721:compile
[INFO] |  |  +- org.eclipse.jetty:jetty-plus:jar:9.3.11.v20160721:compile
[INFO] |  |  |  \- org.eclipse.jetty:jetty-jndi:jar:9.2.14.v20151106:compile
[INFO] |  |  \- javax.annotation:javax.annotation-api:jar:1.2:compile
[INFO] |  \- org.eclipse.jetty:apache-jsp:jar:9.3.11.v20160721:compile
[INFO] |     +- org.eclipse.jetty:jetty-server:jar:9.3.11.v20160721:compile
[INFO] |     +- org.eclipse.jetty.toolchain:jetty-schemas:jar:3.1:compile
[INFO] |     +- org.mortbay.jasper:apache-jsp:jar:8.0.33:compile
[INFO] |     |  \- org.mortbay.jasper:apache-el:jar:8.0.33:compile
[INFO] |     \- org.eclipse.jdt.core.compiler:ecj:jar:4.4.2:compile
[INFO] +- com.google.gwt.inject:gin:jar:2.1.2:compile
[INFO] |  +- com.google.inject:guice:jar:3.0:compile
[INFO] |  |  +- javax.inject:javax.inject:jar:1:compile
[INFO] |  |  \- aopalliance:aopalliance:jar:1.0:compile
[INFO] |  \- com.google.inject.extensions:guice-assistedinject:jar:3.0:compile
...
[INFO] +- com.github.gwtd3:gwt-d3-api:jar:1.2.0:compile
[INFO] |  +- com.github.gwtd3:gwt-d3-js:jar:3.5.11:compile
[INFO] |  \- com.github.gwtd3:gwt-d3-js:jar:sources:3.5.11:compile
...
```

**Comment by rluble** [comment]
Actually I think that it is. Your dependencies contain an older version of JDT
   INFO] |     \- org.eclipse.jdt.core.compiler:ecj:jar:4.4.2:compile

**Comment by tbroyer** [comment]
…and this is because for some reason you have upgraded Jetty to 9.3.

**Comment by jsb1** [comment]
sorry, my fault. did not really inspect that project...
