### ISSUE TITLE
Eclipse SuperDev launcher suddenly has class-path related problems since GWT 2.8.0

### ISSUE THREAD

**Issue by dfht** [gwtproject/gwt#9450]
Before I upgraded from GWT 2.8.0-beta1 to 2.8.0 all was fine. 
Suddenly I get a problem when running the SuperDev launcher in Eclipse (from the Google plug-ins).

It regards the class-path, whereby the launcher seems to include jars from both target/****/WEB-INF/lib as well as from my local Maven repository and hence puts multiple 'copies' of the same jar on the class-path causing some third party apache stuff to complain about the duplication during resource look-up...

It did not do this prior to the upgarde to 2.8.0, so I wondered if anyone had any idea what might have triggered this sudden change of behaviour?

**I realize that the problem seems to have no connection to the GWT version I'm using, yet the problems only started after the change, so I am really scratching my head to see the cause ,and just wondered if anyone had any ideas!**

Also, all is well if i run separate Tomcat server and GWT code servers in Eclipse (in SuperDev mode still etc.) - it's only when using the GWT launcher that I get the problems.....

To be clear, I haven't changed my Google plug-ins version - all I have changed is the GWT version used by my projects.

Caused by: org.apache.directory.server.schema.bootstrap.partition.UniqueResourceException: Problem locating bootstrap partition database file list. Be sure there is exactly one bootstrap partition jar in your classpath.

Multiple copies of resource named 'org/apache/directory/server/schema/bootstrap/partition/DBFILES' located on classpath at urls
    ******/WEB-INF/lib/apacheds-bootstrap-partition-1.5.5.jar!/org/apache/directory/server/schema/bootstrap/partition/DBFILES
    jar:file:/I:/.m2/org/apache/directory/server/apacheds-bootstrap-partition/1.5.5/apacheds-bootstrap-partition-1.5.5.jar!/org/apache/directory/server/schema/bootstrap/partition/DBFILES

**Comment by branflake2267** [comment]
I'll need more to go on to determine what is going on. Which version of Eclipse are you using? Are you using Google Plugin for Eclipse? Or are you using the new GWT Eclipse Plugin? 

Here is the documentation for the GWT Eclipse Plugin. 
http://gwt-plugins.github.io/documentation/

The new GWT Eclipse Plugin supports debugging with tomcat. 
http://gwt-plugins.github.io/documentation/gwt-eclipse-plugin/servers/Tomcat.html

**Comment by dfht** [comment]
Hi  Brandon,
I'm using the Google plugin for Eclipse 4.4./4.5/4.6.
What's this new GWT Eclipse Plugin? Should I be using this instead?

I do debug with Tomcat already sometimes (in this case all is well in the Tomcat scenario - it's jus tthe SuperDev launcher in the Google plug-ins that has the problem), but there are extra set-up steps involving the separate code server etc. (and two launchers to start). What does the new GWT Eclipse Plugin do in this regard that the old one didn't?

**Comment by branflake2267** [comment]
GPE is going to be deprecated in the 4th quarter this year. (I'm not the official announcer, so it's early) I'll be talking more about the plugin at GWT Con and how it's evolving. Having said that the GWT Eclipse Plugin is taking the place of what GPE provided. 

Here's what's happening visually. 
![screen shot 2016-11-04 at 10 39 52 am](https://cloud.githubusercontent.com/assets/1326504/20016058/23008920-a27b-11e6-8edc-c302d5f4a84c.png)

**Comment by branflake2267** [comment]
I forgot, the GWT Eclipse plugin now does quite a bit more than the GPE does. Most of the features can be seen in the videos. 
https://www.youtube.com/playlist?list=PLBbgqtDgdc_TqzA-qXrjgTFMC_6DKAQyT

**Comment by dfht** [comment]
Well I went through the whole process of changing over to the GWT Plug-ins instead of GPE, which involved changes to very many projects and to our own suite of Eclipse plug-ins, generative model actions etc. and guess what? I get exactly the same error with the 'com.gwtplugins' variant as I did with the old 'com.google' one. Not so surprising I guess as the latter is clearly a descendant of the first.....

Now I use Maven and M2E for all of my projects, and I notice in the **-GWT console that it logs that there is more than one gwt-user jar on the path (see below). I think this is because gwt-user should have its scope set as provided (I have it as the default compile right now I think). However, this point does illustrate that the launcher includes entries from the local Maven repository on the runtime class-path as well as those from target/WEB-INF/lib, and it is this duplication that is causing the problem in my case. I think the problem is that the upstream Maven dependencies from M2E MavenDependency class-path containers shouldn't be getting on the class-path of the launcher........ 
I'm not sure what I can do about this.......
When running in Tomcat this doesn't happen, so I'm not sure where the difference in class-path computation lies.......


 More than one gwt jar has been found on the classpath. Clear console after fix.
~~~~~> There is more than one gwt-user.jar on the classpath? Recommended removing one:  ::: path=I:/GWT/gwt-2.8.0/gwt-user.jar
~~~~~> There is more than one gwt-user.jar on the classpath? Recommended removing one:  ::: path=I:/.m2/com/google/gwt/gwt-user/2.8.0/gwt-user-2.8.0.jar

**Comment by branflake2267** [comment]
Thanks for the feedback. That warning may need to be tuned. It's goal is to warn folks that there may be multiple sdks on the classpath, which happens in some configurations, and usually it's someone upgrading and they forget. Feel free to file an issue with the GWT Eclipse Plugin project. https://github.com/gwt-plugins/gwt-eclipse-plugin.

**Comment by branflake2267** [comment]
Usually classpath issues stem from maven, and the m2e configurator picks those issues up and adds them to the launcher classpaths.

**Comment by dfht** [comment]
Yes, but if the jars all get automatically put into WEB-INF/lib, then why do the ones they were copied from (under the local Maven repository) also get on the run-time path of the launcher. In my case a third party apache ldap related jar is causing trouble because some kind of lookup done on it demands a unique resource on the class-path (it's kind of silly because there's two copies of the same jar on the class-path). This could be avoided if you pruned out duplicate jars of the same version for all jars and not just the gwt ones (the gwt-user) in my example.

**Comment by dfht** [comment]
I'm still none the wiser as to why it happens under gwt 2.8.0 and not 2.8.0-beta1. Maybe I need a different version of an m2E connector or different version of Maven GWT plug-ins or something (I changed version of Maven GWT plug-in from 2.8.0-beta1 to 2.8.0 at the same time I made the upgrade though, so you'd expect that to be correct.....)....

**Comment by branflake2267** [comment]
With a Maven project m2e is configured from the pom.xml so if something is going awry, it's usually a misconfiguration in the pom.xml. The GWT Eclipse Plugin doesn't add in a copy stuff to the WEB-INF/libs container when maven is being used. If you have a project where you think things aren't working correctly, I'd love to have it so I can test it and fix it.

**Comment by branflake2267** [comment]
Most likely it's not the m2e connector. This comes by default in Eclipse Neon. M2e just picks up the lifecycle processes and runs them accordingly to how they are stated in the pom.xml directions. Well that's the goal. Sometimes the plugin will do stuff, and in the case of the GWT eclipse plugin it passes them on.

**Comment by dfht** [comment]
Thanks Brandon. I'm in England, and it's time to stop work now, so I'll get back to looking at it on Monday. I'm not sure what puts stuff under the web projects target/****/WEB-INF lib, so I'll look into that as well. I thought it was by the plug-ins for use by the embedded Jetty but it sounds like this isn't so, so I'll try and find out!

**Comment by branflake2267** [comment]
Thanks for the report. I'm very interested in fixing any maven issue, please provide me with an issue of what you think is going on in the GWT Eclipse plugin.

**Comment by dfht** [comment]
I'll try. Our project is huge (many Eclispe projects, GWT modules etc.), and many artifacts are generated from our own models so it won't be easy to put together a self-contained example.  I'll try and do so if the problem persists though.... Otherwise I'll have to advise everyone to use the separate Tomcat and Code Server approach (I prefer that anyway - it's more realistic etc. - , but users like just having the single launcher to execute during development).....

**Comment by branflake2267** [comment]
I understand where you're coming from, regarding the embedded server vs WTP server runtime. It's comfy to use the embedded jetty, I see lots of our customers doing just that, but I've found it's not a practical solution for big enterprise environments where like you said have tons of GWT modules, projects, apps, teams, and loads of services running the show. But I understand it's hard to move away from as it hasn't been a smooth processes to understand or use. But I've been making changes to help wit that story and I've begun to sell the story of using local server runtimes like Eclipse WTP server runtimes to run the show locally b/c you can get out of the embedded jetty box and into an emulated environment much easier.  I'm hoping this story grows as the year progresses. And Google has some smoking hot development going on using the same services so I expect the tooling to improve drastically over the next few months. But with enterprises, it will take some time for this debugging story to sink in. :)

**Comment by tbroyer** [comment]
See also https://github.com/gwtproject/gwt/issues/9451#issuecomment-258635066

**Comment by niloc132** [comment]
Closing, this seemed to have been specific to a single project setup, and anyway likely handled by splitting server/client classpaths.
