### ISSUE TITLE
Problem with Element.getPropertyObject for Boolean false

### ISSUE THREAD

**Issue by MyLifeIsJava** [gwtproject/gwt#9455]
We set the property object using below code.
```
HTML html = new HTML(...);
html.getElement().setPropertyObject("data", false);
```
And the code 
`html.getElement().getPropertyObject("data")`
returns "false" in GWT 1.7 
But with GWT 1.8, this returns NULL and this is causing problems in our application.

Because of this bug we can't move to this new version. But we wanted this as this gives proper exception stacktrace in super dev mode.

**Please note, since it is a generic code, we can't use setPropertyBoolean and getPropertyBoolean methods.**

**Comment by tbroyer** [comment]
I think this is a side-effect of no longer "boxing" booleans and doubles (i.e. `false` is not boxed to a `java.lang.Boolean` when calling `setPropertyObject`, but is kept as a "native" JS boolean value), and the fact that `getPropertyObject` is implemented as `return this[name] || null` (so `this[name]` now is `false` rather than a GWT `java.lang.Boolean` object).
I believe this `|| null` could now be removed, and the boolean native `false` would correctly be returned as `java.lang.Boolean.FALSE`.

Can you test that and contribute the (small) patch?

**Comment by MyLifeIsJava** [comment]
Thanks @tbroyer. If I do that, then I will get false for this case, which is correct. But, if I invoke `getPropertyObject `for a property which is not set, then I get 'undefined' instead of NULL :-(

**Comment by tbroyer** [comment]
But `undefined` and `null` are treated the same from GWT's point of view (a Java `null`)

**Comment by MyLifeIsJava** [comment]
Thank you @tbroyer. This works. 

I am new to this Git. Don't know how to create a patch (or even use an existing patch) :-(

**Comment by tbroyer** [comment]
Have a look at http://www.gwtproject.org/makinggwtbetter.html#submittingpatches, and if you have questions, direct them to https://groups.google.com/forum/#!forum/google-web-toolkit-contributors then; we'll help you setup your dev environment and send in your first patch.

Thanks in advance for the patch!

**Comment by MyLifeIsJava** [comment]
I followed the instructions at http://www.gwtproject.org/makinggwtbetter.html#submittingpatches.
But when I tried to push my changes, I was getting some error.
I have put my question in the forum.
https://groups.google.com/forum/#!forum/google-web-toolkit-contributors

**Comment by tbroyer** [comment]
I had some time today to confirm the regression and prepare the patch: https://gwt-review.googlesource.com/17300

Thanks for the report, and for at least trying to send the patch.

**Comment by tbroyer** [comment]
Adding ReleaseNote-BreakingChange label as it changes the behavior for empty-string values that are no longer coerced to null.
