### ISSUE TITLE
GWT 2.8.0 Javadoc incomplete

### ISSUE THREAD

**Issue by pH4Lk0n** [gwtproject/gwt#9456]
In gwt-2.8.0.zip Javadoc is incomplete. It's missing index.html and other files.
RC also were missing this files. Last version that had complete javadoc was 2.7.0.
Is there any way to download javadoc to use offline?

**Comment by jnehlmeier** [comment]
Thanks for the report. As a workaround you can download the source jars from Maven and attach them in your IDE to the corresponding jars. That should give you JavaDoc in your IDE.

http://search.maven.org/#search%7Cga%7C1%7Cg%3A%22com.google.gwt%22

**Comment by tbroyer** [comment]
Fixes in review https://gwt-review.googlesource.com/17562 & https://gwt-review.googlesource.com/17563
