### ISSUE TITLE
Incorrect handling of Jetty arguments - NullPointerException

### ISSUE THREAD

**Issue by grabarczyk-t** [gwtproject/gwt#9472]
gwt-dev-2.8.0-rc2-sources.jar!\com\google\gwt\dev\shell\jetty\JettyLauncher.class line: 658

```java
keyStorePassword = Util.readFileAsString(new File(value)).trim();
if (keyStorePassword == null) {
    logger.log(TreeLogger.ERROR,
        "Unable to read keystore password from '" + value + "'");
    return false;
 }
```

The condition `if (keyStorePassword == null)` will never be true. When `Util.readFileAsString` fails and returns null, calling `trim` will throw a NullPointerException, and the cause of this error - `Unable to read keystore password` - will not be logged. 

Trimming should be done after checking for null

**Comment by tbroyer** [comment]
Good catch, patch welcome (though I think the embedded server is on the way out)
http://www.gwtproject.org/makinggwtbetter.html

**Comment by grabarczyk-t** [comment]
Code review at https://gwt-review.googlesource.com/#/c/17520/

**Comment by tbroyer** [comment]
Thanks
