### ISSUE TITLE
Java 8 Stream API methods (**Match) produce NullPointerException (gwt 2.8.0)

### ISSUE THREAD

**Issue by povadys** [gwtproject/gwt#9477]
Hi. Not sure if anyone have noticed that/opened an issue before.
Trying to verify if the list contains nulls:

      List<Integer> list = new ArrayList<>();
      list.add(1);
      list.add(2);

      GWT.log("" + list.stream().anyMatch(Objects::isNull));   // false

      list.add(null);   // now list contains "null" reference
      GWT.log("" + list.stream().anyMatch(Objects::isNull));   // should be true, throws NPE

Works fine in Java (jdk 1.8.0_112) though.

Used Chrome, Debugger + Source Maps enabled.
Noticed that basically any *Match API method is coded using filter ([source link](https://gwt.googlesource.com/gwt/+/master/user/super/com/google/gwt/emul/java/util/stream/StreamImpl.java#613)):

      @Override
      public boolean anyMatch(Predicate<? super T> predicate) {
        return filter(predicate).findFirst().isPresent();
      }
I assume that the reason of the problem resides [here](https://gwt.googlesource.com/gwt/+/master/user/super/com/google/gwt/emul/java/util/stream/StreamImpl.java#602 ).
Since `findFirst()` calls `Optional.of()`, the value must be non-null, otherwise NPE gets thrown ([link](https://docs.oracle.com/javase/8/docs/api/java/util/stream/Stream.html#findFirst--)). 

For now have to workaround it like `filter(predicate).map(Optional::ofNullable).findFirst().isPresent()`.

**Comment by jnehlmeier** [comment]
Thanks for the bug report. You are right, using `filter(predicate).findFirst().isPresent()` doesn't fit the behavior of `anyMatch()` for `null` elements since `findFirst()` forbids finding `null` elements while `anyMatch()` allows matching them.

**Comment by jnehlmeier** [comment]
@tbroyer @gkdn can anybody put @niloc132 into the correct gwtproject team so he can be assigned to the issue? He wants to look at it.

**Comment by rluble** [comment]
Code review at https://gwt-review.googlesource.com/#/c/17761
