### ISSUE TITLE
The project XXX does not have any GWT SDKs on its build path

### ISSUE THREAD

**Issue by adligo** [gwtproject/gwt#9480]
I have removed and added the GWT SDK several times but this error keeps coming back.  Removing the checkmark in 'Use GWT' seems to work as expected.  This is in Eclipse Neon.2 with the latest Google Plugin for Eclipse as of today.

**Comment by tbroyer** [comment]
@branflake2267 Any idea? Could it be related to https://github.com/gwtproject/gwt/issues/8415 ?

@adligo The Google Plugin for Eclipse will soon be deprecated (or at least its GWT facet), and now might be a good time to migrate to the GWT Eclipse Plugin: https://gwt-plugins.github.io/documentation/

**Comment by tbroyer** [comment]
Google Plugin for Eclipse is offically deprecated, and will be removed in January 2018.
