### ISSUE TITLE
instanceof can cause "(TypeError) : doubleCastMap is undefined"

### ISSUE THREAD

**Issue by niloc132** [gwtproject/gwt#9482]
**GWT version:** 
GWT 2.8.0
**Browser (with version):** 
Any
**Operating System:** 
Any

---

##### Description
Testing a JS number with Java `instanceof` without numbers in the app can result in `Cast.canCast()` throwing an exception. Since `Cast.instanceOfDouble()` would return true, but `Cast.doubleCastMap` can be null, causing an exception when it is checked.

##### Steps to reproduce

```
  public void onModuleLoad() {

    //required to not skip the instanceof check
    new ArrayList<>();

    Object myvalue = getSomeValue();

    try {
      boolean isInstanceOfList = myvalue instanceof List;
      alert("Is it a list? false = " + isInstanceOfList);//expected, false
    } catch (Exception e) {
      alert("Error: " + e.getMessage());//actual, "(TypeError) : doubleCastMap is undefined"
    }
  }

  private native void alert(String message) /*-{
    $wnd.alert(message);
  }-*/;

  private native Object getSomeValue() /*-{
    return 42;
  }-*/;
```
Sample project that builds and fails at runtime: https://github.com/bpilot/GwtReproduceCastError

Use `mvn clean install` and serve `target/main-1.0-SNAPSHOT` to see the error in OBF, or `mvn clean install -Dgwt.style=PRETTY` to see the error in readable code:

```
TypeError: doubleCastMap is undefined
Stack trace:
canCast@gwtcorehellomaven-0.js:682:13
instanceOf@gwtcorehellomaven-0.js:700:27
$onModuleLoad@gwtcorehellomaven-0.js:288:24
```

##### Known workarounds
Create a Double via its constructor or `Double.parse`, then the typemap will be present.

##### Links to further discussions
IRC chat discussing the topic: https://javabot.evanchooly.com/logs/%23%23gwt/2017-01-24

Thanks to @bpilot for helping hunt this down and reproduce it simply.

**Comment by rluble** [comment]
Could you reproduce this problem without JSNI? From the compiler perspective there are no instances of Double. You can trigger lots of quirky behaviors with JSNI and if that is the only way to trigger it is not really a bug. 

I presume if you change the signature of getSomeValue() to return Double the problem should go away. Could you check?

**Comment by niloc132** [comment]
The problem in this case is that it started out as JSON or some other arbitrary JS object structure that the GWT code is iterating through. Since it ends up finding a number, no other type check is possible. This is just an overly simplified example to demonstrate the problem.

Yes, returning a Double (or creating one) makes it go away, but for a simple Java tool that is just walking a JSON tree and type-checking from Java, specifically ignoring leaf values like  strings and numbers, that isn't really a "fix".

One fix that occurred to us is to nullcheck the doubleCastMap in the Cast code, since that check should be optimized out either way (i.e. either always null and no need to check double types anyway, or never null, so always check if typeof is number).

**Comment by bpilot** [comment]
Firstly, appreciate your looking into this.

I am new to GWT, so I might be missing something.

However, I reproduced without JSNI:
https://github.com/bpilot/GwtReproduceCastError/blob/without-jsni/src/main/java/ailabs/client/gwtcorehellomaven.java

**Comment by rluble** [comment]
A fix is up for review at https://gwt-review.googlesource.com/#/c/17660/
