### ISSUE TITLE
References to Class method (isInstance and cast) works incorrectly

### ISSUE THREAD

**Issue by foal** [gwtproject/gwt#9483]
**GWT version: 2.8.0** 
**Browser (with version): NA** 
**Operating System: Windows 10** 

---

##### Description
Incorrect (?) implementation of isInstance method of Class class.

I have in code the following lines (few of `Panel` classes implements `TagAware` interface):
```Java
private final Map<PanelType, Panel<T>> panels;
//...
panels
		.values()
		.stream()
		.filter(TagAware.class::isInstance)
		.map(TagAware.class::cast)
		.forEach(t -> t.setTagsWorkHours(this.tagsWorkHours));
```
The code perfectly compile by javac, but not with GWT compiler: 

      Errors in 'file:/C:/Development/work/repo/JRS/open/gxt/calendar/widget/src/main/java/org/jresearch/gwt/client/date/widget/Calendar.java'
         Line 376: The type Class<TagAware> does not define isInstance(Panel<T>) that is applicable here
         Line 376: The method filter(Predicate<? super Panel<T>>) in the type Stream<Panel<T>> is not applicable for the arguments (TagAware.class::isInstance)

The same with cast

      Errors in 'file:/C:/Development/work/repo/JRS/open/gxt/calendar/widget/src/main/java/org/jresearch/gwt/client/date/widget/Calendar.java'
         Line 377: The method map(Function<? super Panel<T>,? extends R>) in the type Stream<Panel<T>> is not applicable for the arguments (TagAware.class::cast)
         Line 377: The type Class<TagAware> does not define cast(Panel<T>) that is applicable here

##### Known workarounds

Rewrite the above lines without method references:

```Java
panels
		.values()
		.stream()
		.filter(p -> p instanceof TagAware)
		.map(p -> (TagAware) p)
		.forEach(t -> t.setTagsWorkHours(this.tagsWorkHours));
```
##### Links to further discussions

https://groups.google.com/forum/#!topic/google-web-toolkit/cbbySMCzVVQ

**Comment by jnehlmeier** [comment]
GWT does not support Class.isInstance() and Class.cast() methods. So you can not call them, thus you can not use them as method references. These methods are simply not emulated by GWT.

There are only very few methods of the Class class that you can use with GWT, see:

http://www.gwtproject.org/doc/latest/RefJreEmulation.html
