### ISSUE TITLE
Elemental produces null JsJsonValue when value is zero

### ISSUE THREAD

**Issue by christianbauer** [gwtproject/gwt#9484]
**GWT version:** 2.8.0
**Browser (with version):** Chrome Version 56.0.2924.76 (64-bit)
**Operating System:** OS X 10.11.6

---

##### Description

The boxing/unboxing in elemental JSON produces weird behavior In SuperDev mode:

```
JsonArray array = (JsonArray) Json.parse("[0]");

if (array.get(0).asNumber() < 0)
    throw new IllegalStateException("Should not be negative");

if (array.get(0) == null)
    throw new IllegalStateException("This is wrong!");
```

The second exception will be thrown, clearly this should never happen. Change the 0 to 123 in the JSON array and the test passes.

**Comment by christianbauer** [comment]
This also affects production, not only SDM.

**Comment by tbroyer** [comment]
IMO, there's little to no chance that Elemental will be fixed (unless possibly someone provides the patch). Elemental2 will likely come before we cut a new version of GWT and should have new APIs to deal with native objects' properties and native arrays' indices as a replacement for `JsonObject` and `JsonArray` (and `instanceof Double`, `instanceof Boolean`, and `instanceof String` should work to tell JS numbers/booleans/strings apart).

@jDramaix Do you have an upcoming replacement API in Elemental2 (or elsewhere) for `Json.parse()` that could be used both client-side and server-side? That's the main (if not only) argument for using Elemental over com.google.gwt.json AFAICT.

**Comment by christianbauer** [comment]
Using the same API on client and server is indeed why use Elemental.

**Comment by gkdn** [comment]
@tbroyer Elemental 2 will not provide any cross-platform APIs and at the moment we are not planning to release something else in that effect.

**Comment by tbroyer** [comment]
Thanks @gkdn.

So I think we'll probably want to keep some JSON API that could work both on client-side and server-side, though maybe relying on `instanceof Object[]`, `instanceof Double`, `instanceof String` and `instanceof Boolean` to tell types apart (unless you tell me it'd be a bad idea), and with some API to get objects' properties. Or maybe simply port the existing elemental.json to JsInterop? (assuming it's possible)

That being said, it probably shouldn't be in "Elemental" (I think we'll want to retire or deprecate it as soon as Elemental 2 is released; the only 2 things Elemental 2 won't provide AFAICT are `elemental.json` and `elemental.util` collections, and I doubt the latter are widely used), and could possibly have a different API.

@dankurka @niloc132 @jojule @Legioth @Artur- Let's talk about the future of Elemental (and Elemental JSON in particular) at the next SC meeting. WDYT?

**Comment by dankurka** [comment]
+1

**Comment by niloc132** [comment]
Elemental has been removed, closing as stale.
