### ISSUE TITLE
Documentation of JavaScriptObject.equals and hashCode inaccurate

### ISSUE THREAD

**Issue by ygra** [gwtproject/gwt#9486]
**GWT version:** 2.8.0
**Browser (with version):** N/A
**Operating System:** N/A

---

##### Description

GWT 2.8.0 improved `JavaScriptObject.equals` and `hashCode` to pass through same-named functions on the underlying JS object (#9231). While the TODO from the `hashCode` documentation is gone now, the method documentation does not reflect the code at all anymore.

**Comment by tbroyer** [comment]
Good catch!

Do you think you could contribute the new documentation?  
http://www.gwtproject.org/makinggwtbetter.html#submittingpatches

**Comment by tbroyer** [comment]
https://gwt-review.googlesource.com/c/gwt/+/19322
