### ISSUE TITLE
@JsProperty w/ Underscores = Undefined

### ISSUE THREAD

**Issue by washowasho** [gwtproject/gwt#9487]
**GWT version: 2.8.0** 
**Browser (with version): 56.0.2924.87 (64-bit)** 
**Operating System: W10 Pro 64bit** 

---

After performing a JSON.parse() on a JSON string containing keys with underscores, attempting a @JsProperty through JsInterop results in an "undefined" property when there is a value present in the JSON.

E.g., Google Maps Geosearch outputs the following:
...
"formatted_address": "Scranton, PA, USA",
"place_id": "ChIJu0tIdzrZxIkR6PqbqyB58v8",
...

using the below produced an "undefined" when called:
`@JsProperty String getFormatted_Address`
`@JsProperty String getPlace_Id`

Workaround (confirmed): When receiving the string of data, replace the underscore with a blank string, and use the following to access the data:

`@JsProperty String getFormattedaddress`
`@JsProperty String getPlaceid`

I would think that an underscore in the Java variable name is appropriate, but I am thinking the transcompiler does not like that. I tried a few different combinations, but no luck.

**Comment by tbroyer** [comment]
Did you try `getFormatted_address` (lowercase a) ? Also, you can pass the name as value of the annotation: `@JsProperty("formatted_address")`

**Comment by washowasho** [comment]
Hi Thomas - Thank you for the quick response. Both of your recommended solutions worked, however I had to use `@JsProperty(name = "formatted_address")` as the syntax checker yelled at me for `@JsProperty("formatted_address")`... probably due to lack of constructor. Thank you for the solution. 

In other words, for @JsProperty, underscores not allowed and must be case sensitive in JsInterop... unless you use the name='' override. The case sensitive part makes sense as that aligns with JavaScript variable naming rules. However, since underscores are allowed in JavaScript variable names, they should probably be allowed in the Java counterpart. Keeps JsInterop more "interopable". Something to think about?

Also, I was thinking about this after posting the original note. Should the runtime yell at you if you try to use a @JsProperty that doesn't exist in the JavaScript? Similar to how UiBinder annotations yell if @UiField or @UiHandler refers to non-existent UiBinder objects during compile and syntax check. I do understand that this isn't known until runtime in JsInterop, but maybe there should be a way to indicate that a @JsProperty is an existing JavaScript variable, or one you intend on creating. This way, an error can be thrown at runtime...  instead of simply undefined. Make sense?

Anyway, `@JsProperty(name = "formatted_address")` is a good enough (clean) solution for me, but others may be pickier :)

**Comment by tbroyer** [comment]
> probably due to lack of constructor.

Actually because the _attribute_ is called `name` and not `value`.

> However, since underscores are allowed in JavaScript variable names, they should probably be allowed in the Java counterpart. Keeps JsInterop more "interopable".

Didn't you just say that `getFormatted_address` work?

The `f` is upper-cased because the property is transformed to the Java Bean™ naming with `get` prefix, but the rest **must** be left untouched (per Java Bean spec).

> Make sense?

Well, not really :-)  
What if you make a typo in the “way to indicate that a `@JsProperty` is an existing JavaScript variable”?

No, the way to detect this is to run automated tests; or to generate JsInterop interfaces/classes from JS API definitions (Closure externs files, TypeScript definition files, etc.); actually AFAIK JsInterop (with `isNative=true`) is really meant to be generated that way (Google is currently working on such a generator).
