### ISSUE TITLE
Build seems broken to me

### ISSUE THREAD

**Issue by Schahen** [gwtproject/gwt#9489]
Hi! I'm trying to run
`ant clean elemental dist`

> [gwt.javac] /Users/shabunc/open/gwt/dev/core/src/com/google/gwt/core/ext/linker/TypeIndexedSet.java:18: error: package com.google.gwt.thirdparty.guava.common.base does not exist

It looks to me like a fundamental build issue.
Has anyone encountered it?
What can be done to circumvent this?

I mean sure, it looks like a missing dependency issue which after some experimenting can be added but well, this should not be the part of normal workflow.

**Comment by tbroyer** [comment]
Did you clone gwtproject/tools and setup GWT_TOOLS accordingly? (if necessary)

**Comment by Schahen** [comment]
I apologize, I've my mistake thought that the latest tools are already in well, tools folder. 
sorry for wasting your time
