### ISSUE TITLE
HttpServletRequests received by servlets loaded for GWTTestCases have empty contextPath

### ISSUE THREAD

**Issue by djozis** [gwtproject/gwt#9491]
**GWT version: 2.8.0** 
**Browser (with version): Headless via GWTTestCase** 
**Operating System: Windows** 

---

##### Description
Servlets loaded for GWTTestCase receive requests that have the unit test module name added to the start of their requestURI but not their contextPath.
For example, if I use the webjars serlvet (org.webjars:webjars-servlet-2.x:1.1) to serve static javascript, it will get a request in its doGet method with a requestURI like: /com.me.my.module.Name.JUnit/webjars/requirejs/2.3.2/require.min.js
In the implementation of that third party servlet, they strip off contextPath from the start of requestURI to determine the resource to load, but getContextPath() returns empty string instead of: /com.me.my.module.Name.JUnit

##### Steps to reproduce
To show that the contextPath does not include the unit test module prefix added to all servlet mappings, set a breakpoint in any servlet method for servlets loaded by the unit test, for example com.google.gwt.junit.server.JUnitHostImpl.service(HttpServletRequest, HttpServletResponse), and inspect the contextPath property of the request - for me it is "" (empty string).

##### Known workarounds
Use the other fields to determine the contextPath, but this won't work for third party servlets.

**Comment by tbroyer** [comment]
This is the intended behavior. Paths in `<servlet>` in GWT modules are relative to the `GWT.getModuleBaseURL()` (just like paths in `@RemoteServiceRelativePath`), and changing this would break everyone's tests.
