### ISSUE TITLE
Issues with the official Website

### ISSUE THREAD

**Issue by thakurpunk** [gwtproject/gwt#9492]
Hello There,

I was browsing through your official website and found some bugs, please refer to the screenshot attached.
![screenshot_1](https://cloud.githubusercontent.com/assets/8851526/23516714/0fa6d02a-ff94-11e6-8a4d-29b9078dd40b.png)

Thank you!

**Comment by jnehlmeier** [comment]
Hi,

The dots do not work properly that is correct. Tried it with Safari, Chrome and Firefox. If page is loaded you can click them and scrolling will happen, but their status won't update. Once you are at the bottom you can click them and their status updates but scrolling does not happen. Weird.

I can't confirm the strange symbols you are seeing.

**Comment by jnehlmeier** [comment]
But please create an issue at https://github.com/gwtproject/gwt-site and close this one once you have done that.

**Comment by thakurpunk** [comment]
Thank you.
