### ISSUE TITLE
W3C Flute license and source code

### ISSUE THREAD

**Issue by tazle** [gwtproject/gwt#9494]
It appears that gwt-user.jar at http://repo1.maven.org/maven2/com/google/gwt/gwt-user/2.8.0/gwt-user-2.8.0.jar includes w3c.org Flute CSS parser.

Under what license is this code distributed, and is the source code available somewhere?

**Comment by jnehlmeier** [comment]
Flute can be downloaded from W3C directly (or probably maven): https://www.w3.org/Style/CSS/SAC/ or direct download link: https://www.w3.org/2002/06/flutejava-1.3.zip

GWT stores all its libraries in a dedicated repository. It also contains a copy of flute and its software notice/license: https://github.com/gwtproject/tools/tree/master/lib/w3c/flute

**Comment by tbroyer** [comment]
Also note that the version used in GWT has been patched (see gg1 and gg2 files in the gwtproject/tools repo)

**Comment by tazle** [comment]
Thank you, that clears it up :)
