### ISSUE TITLE
Memmory Issue

### ISSUE THREAD

**Issue by achabahe** [gwtproject/gwt#9502]
**GWT version:2.6** 
**Browser (with version):** 
**Operating System:Linux** 

---

##### Description
i have a pretty big gwt application, when i compile it, i should give it 8G of ram just to be compiled, but some times i am obliged to compile it in weeker machines that can have only 6G of RAM and the compiler throws in my face out of memory error, and when i increment the RAM Limits using `"-Xmx8G"`Linux kills it and throws at my face exit code 137, now my question is this, why in god does compilation would take up to 8Gs of RAM and no byte less than that, to be honest i am not the one who wrote that application but i have to developpe something in it, when i launch the maven command `mvn gwt:run-codeserver` i see that gwt creates a draft compilation and puts it in a jetty server,but when i do `mvn clean install` inorder to launch after that 'mvn gwt:run-codeserver' and run my application in an embeded tomcat server the compiler gets either killed by linux or by out of memory  error.

So for now i can't start my developpement using Super Dev Mode because to launch the app in super dev mode i should follow these steps:
1-mvn clean install
2-mvn gwt:run-codeserver
3-mvn tomcat7:run-war-only
now i am blocked in step 1
i have searched in all the dark corners of the internet all what they tell me is to use  `<extraJvmArgs>-Xms1G -Xmx7G -Dgwt.jjs.permutationWorkerFactory=com.google.gwt.dev.ThreadedPermutationWorkerFactory</extraJvmArgs>`
and it does not solve my problems!

##### Steps to reproduce
have a big application , i don't know what causes the application to have such big demand for memory

**Comment by tbroyer** [comment]
If you really want to **know** why your app needs that much memory, I think a profiler could help (or maybe simply JVisualVM or similar tools).

Now if you just want to be unblocked and be able to work, you could probably [skip the GWT compilation](https://gwt-maven-plugin.github.io/gwt-maven-plugin/compile-mojo.html#skip) in the first step by running `mvn clean install -Dgwt.compiler.skip`.

**Comment by achabahe** [comment]
i can run a simple `mvn clean install` by commenting the goal compile and i will try a profiler , do you have any blogs or tools that you would advise me to use !
Thanks tbroyer

**Comment by rluble** [comment]
The issue is stale. It is expected for very large applications to require a large heap since GWT is a whole world optimizing compiler.

**Comment by ibaca** [comment]
In my experience you should be careful with two facts, permutations, for
each parallel permutation you will need a lot more memory so on limited
memory environments always be sure to collapse all or just compile it
sequentially (local workers). And second, the maven plugin fork the gwt
compiler so use jvmArgs as you suggested, but I don't think you will need
more than 3g. There are various layers and some times you miscinfigured the
memory and the compiler process is not configured, so check the argument is
applied. Do not try to profile the compiler, hehe is just a waste of time
;).
