### ISSUE TITLE
getElementsByTagName broken with latest Safari

### ISSUE THREAD

**Issue by eroux** [gwtproject/gwt#9509]
**GWT version:** 2.7 (but the bug should appear in current master branch)
**Browser (with version):** Safari 10.1 (released March 27 2017)
**Operating System:** OSX 10.11

---

##### Description

Safari 10.1 silently changed its behavior when it comes to `getElementsByTagName` for XML with namespaces. See [this fiddle](https://jsfiddle.net/ypc61g60/1/) for an example. GWT uses this function in the compiled JavaScript code only for Safari, certainly to be compatible with archaic versions of Safari not implementing the DOM Level 2 API, so around 10 years ago.

The [current code](https://github.com/gwtproject/gwt/blob/3a41a8067767965ff72f4e49eb015f587fcfee16/user/src/com/google/gwt/xml/client/impl/XMLParserImplSafari.java#L43) still uses this function instead of `getElementsByTagNameNS` as on other browsers, so the bug should still be there.

We are quite paralysed by this bug as it completely breaks our website.

##### Steps to reproduce

Parse some XML with some namespaces, and be sad.

##### Known workarounds

We had to modify the gwt sources to make our app work, the easiest possible way to deal with that would be to modify the prototype of `window.Element` or make sure latest Safari never gets spotted as safari by GWT.

**Comment by tbroyer** [comment]
`com.google.gwt.xml` does not (officially) support XML Namespaces (for legacy reasons) so the behavior is not unexpected (I noted this already more than 3 years ago in another issue: https://github.com/gwtproject/gwt/issues/8465#issuecomment-110889610, saying at the time “Maybe it's time to add support for namespaces there”; it still hasn't happened though, as probably very few people use XML in the browser these days)

BTW, `com.google.gwt.xml` hasn't been updated for more than 8 years now. I'd highly suggest you don't use it, and use JSNI or JsInterop to directly interact with the underlying APIs (hopefully Elemental will eventually provide those APIs for you), as there aren't many differences (if at all) between browsers these days.

**Comment by branflake2267** [comment]
This is affecting our api, and it appears to be a bug to me.

**Comment by branflake2267** [comment]
Not a bug, my mistake. 

https://developer.apple.com/safari/technology-preview/release-notes/

**Comment by branflake2267** [comment]
Workaround for the safari implementation. 

https://gist.github.com/branflake2267/d16365012e27f514685eb5c365dcb315
