### ISSUE TITLE
GWT AngularJS integration

### ISSUE THREAD

**Issue by 19yak** [gwtproject/gwt#9511]
I develop a small UML graphical editor with the following technologies: JointJS, angularJS, angular Bootstrap-ui, jquery.

And when testing the addition of my editor I notice that the use of angularJS with GWT is not possible.

Are there any solutions to do this?

**Comment by tbroyer** [comment]
GWT is not much different from any other JS (widget) library. If you can integrate your editor into other JS applications (e.g. Ember, React, etc.) then it should be possible to do it with GWT as well. There are third-party libraries to make it possible to develop Angular apps using GWT (using Java, just like you could use Dart, TypeScript or JavaScript), it looks like there are (probably outdated) proofs of concept for AngularJS too, either as libraries or as examples (using GWT's JsInterop).

If you have questions about **how** to do the integration, please come discuss on the GWT Forum: https://groups.google.com/forum/#!forum/google-web-toolkit (or post specific questions to StackOverflow: https://stackoverflow.com/questions/tagged/gwt)
