### ISSUE TITLE
PopupPanel positioning broken in standards mode if page is scrolled horizontally

### ISSUE THREAD

**Issue by jnehlmeier** [gwtproject/gwt#9515]
**GWT version:** custom build, between GWT 2.7 and 2.8.
**Browser (with version):** all recent browsers I guess
**Operating System:** OS X 10.12.4

---

##### Description

When a page has horizontal scroll bars and you place a button to the far right so you need to scroll to it (`scrollLeft > 0`) then a `PopupPanel` that is revealed using `PopupPanel.showRelativeTo(button)` will be misaligned because the code calls `DOMImplStandardBase.getAbsoluteLeft()` which in turn tries to account for scrolling by calling `elem.getOwnerDocument().getBody().getScrollLeft()`. However `body.scrollLeft` is deprecated in strict / standards mode and always returns 0. As a result scrolling isn't taken into account and the PopupPanel has a wrong position. GWT should choose `documentElement.scrollLeft` when running in strict / standards mode.

In Quirks mode the correct scrollLeft value will be returned and the PopupPanel is positioned correctly.

##### Known workarounds

In most cases (if not all) instead of using showRelativeTo(Widget) one could use setPopupPositionAndShow() and calculate the popup position manually.

**Comment by amihaiemil** [comment]
I think this issue is related to this one: https://github.com/gwtproject/gwt/issues/9542

**Comment by jnehlmeier** [comment]
Yes. Thanks for reminding me to close this ;)
