### ISSUE TITLE
Utf8 Cyrillic wrong encode via request factory

### ISSUE THREAD

**Issue by MrFreeMan82** [gwtproject/gwt#9517]
**GWT version:** 
2.8
**Browser (with version):** 
**Operating System:** 
Windows7 64

---

##### Description

I am trying send entity from server to client via request factory. Data at server are in utf8. But client receive data in windows 1251.

**Comment by niloc132** [comment]
Can you confirm that your HTML page is set to use UTF-8 (meta tag, Content-Type header)? Can you provide a minimal example of this not working? This isn't something that GWT (or the JS on the page at all) can control, but it is a matter of making sure that the page loads already with the right encoding.

**Comment by MrFreeMan82** [comment]
My page contains header 
<meta http-equiv="content-type" content="text/html; charset=UTF-8">

Server side code 
In resources we have file data.txt with UTF-8 text.
Then request factory call method  getAllTypes() for client request
UserType is a POJO entity

`public class UserTypeDAO 
{
    public List<UserType> getAllTypes()
    {
        System.out.println("Return all types");
        ClassLoader classLoader = getClass().getClassLoader();
        File file = new File(classLoader.getResource("data.txt").getFile());
        try (Scanner scanner = new Scanner(file)) {

            if (scanner.hasNextLine())
            {
                String line = scanner.nextLine();
                UserType type = new UserType();
                type.setId(1L);
                byte[] bytes = line.getBytes();
                type.setName(line);

                List<UserType> list = new ArrayList<>();
                list.add(type);
                return list;
            }
            scanner.close();

        } catch (Exception e) {
            e.printStackTrace();
        }
        return null;
    }
}`

Client side code. When Present is created it call a  loadTypes(). And text in proxy.getName() in Windows-1251 codepage. It seems when Request Factory Serialize entity? it encode strings with server default codepage.


`private void loadTypes()
    {
        AppRequestFactory.UserTypeContext context = Warehouse.requestFactory.userTypeContext();
        context.getAllTypes().fire(new AppReceiver<List<UserTypeProxy>>() {
            @Override
            public void onSuccess(List<UserTypeProxy> result)
            {
                Warehouse.logger.info(new LogEvent(present, present,
                        "Receive list with size = " + result.size()).toString());

                types = result;
                for(UserTypeProxy proxy: types)
                {
                   Window.alert(proxy.getName());
                    lblUserName.setText(proxy.getName());
                    listUserType.addItem(proxy.getName());
                }
            }
        });
    }`

**Comment by dankurka** [comment]
Not a GWT issue you are calling getBytes on your string without passing an encoding which will use platform encoing, if you use getBytes("UTF-8") it will work.
