### ISSUE TITLE
Instantiating native JsTypes from JSNI results in InternalCompilerException.

### ISSUE THREAD

**Issue by hrstoyanov** [gwtproject/gwt#9520]
**GWT version:**  2.8.1 or latest
**Browser (with version):** Any
**Operating System:** Any

---

##### Description
Compiling Errai code with Elemental2 and latest GWT fails. 
Looks like some internal gwt compiler error, but could be Errai related (cc'ed max Barkley too)

See:
https://groups.google.com/forum/#!topic/Google-Web-Toolkit/4CPSiV9_f1k
https://issues.jboss.org/browse/ERRAI-1039

##### Steps to reproduce
Code snippet shown in here:  https://issues.jboss.org/browse/ERRAI-1039

##### Known workarounds
None

##### Links to further discussions
https://groups.google.com/forum/#!topic/Google-Web-Toolkit/4CPSiV9_f1k
https://issues.jboss.org/browse/ERRAI-1039

@mbarkley

**Comment by tbroyer** [comment]
2.8.1 shouldn't have that `unusable-by-js` warning, are you sure you don't have a mix of versions?

**Comment by hrstoyanov** [comment]
I might have compiled with the latest from head, but I remember the same
issues with 2.8.1. let me repeat the test...

/Hristo Stoyanov

**Comment by hrstoyanov** [comment]
Confirmed issue with GWT 2.8.1 and afterwards.

Since it is not clear if this is a GWT or Errai issue, I notified the Errai team as well:
https://issues.jboss.org/browse/ERRAI-1039

**Comment by hrstoyanov** [comment]
Maybe @rluble can help?

**Comment by rluble** [comment]
Could you create a small repro? Maybe triming all the unnecessary code from errai and elemental.

Does this also happen in a non incremental compilation and if so post the stack trace?

**Comment by hrstoyanov** [comment]
@rluble 
Find attached a repro. The compile fails even without using elemental2, but just including it in the build. Try this:
```
./gradle -p recres-webapp assemble
```
or
```
./gradlew -p recres-webapp assemble
```
Errai does generate code, which I suspect is the issue ...  

[issue-9520.zip](https://github.com/gwtproject/gwt/files/980529/issue-9520.zip)

**Comment by rluble** [comment]
The problem seems to stem from the following ERRAI generated code

```java
  public native static MediaStreamTrackEvent MediaStreamTrackEvent_() /*-{
    return @elemental2.dom.MediaStreamTrackEvent::new()();
  }-*/;
```

where the code attempts to call a constructor on an ```@JsType(isNative=true)``` in JSNI. This code is not ideal, native types should be instantiated directly. Sure that GWT should not choke on this input but ERRAI should be updated.

**Comment by rluble** [comment]
Fix is up for review at https://gwt-review.googlesource.com/#/c/18320/

**Comment by hrstoyanov** [comment]
@rlube
Thanks for fixing GWT and identifying the root cause! When can we expect 2.8.2 ?
I will notify the Errai team and @mbarkley as this is a showstopper.

**Comment by rluble** [comment]
Native classes should not be accessed though JSNI references. The patch above only fixes the case for constructors but looking at the code access to static native methods and fields would also fail in a similar manner. I am considering making it a restriction, i.e. disallow accessing native members as JSNI references.

The proper fix is to use native JsType directly, so the proper fix for your use case is in ERRAI.

**Comment by tbroyer** [comment]
+1, similar to the Boolean and Double (and String?) treatment.

**Comment by mbarkley** [comment]
Hi @rluble,

Thanks for identifying this issue so quickly! I would like to make your suggested change, but it looks like `MediaStreamTrackEvent` has a private constructor, which is why Errai has generated this JSNI call.

Is there a reason for this? From the [MDN description](https://developer.mozilla.org/en-US/docs/Web/API/MediaStreamTrackEvent) it seems the constructor is part of the API.

**Comment by tbroyer** [comment]
@mbarkley `MediaStreamTrackEvent`'s constructor takes arguments anyway, so I'm no sure how that'd help you: https://w3c.github.io/mediacapture-main/archives/20170205/getusermedia.html#constructors-1

That moves the question to: why does Errai wants to generate this code to begin with?

**Comment by rluble** [comment]
In general I don't think ERRAI should generate JSNI code to circumvent private access.
The constructor for ```MediaStreamTrackEvent``` is declared ```@private``` in closure externs (https://github.com/google/closure-compiler/blob/830b54eee5af57ff312596d785e674abc96a66c4/externs/browser/w3c_rtc.js#L141) which is then used to generate the elemental2 Java apis.

**Comment by tbroyer** [comment]
(and this line is at least 4 years old https://github.com/google/closure-compiler/blame/830b54eee5af57ff312596d785e674abc96a66c4/externs/browser/w3c_rtc.js#L141; so → ask Closure to update their externs, then ask for an updated elemental2 dump?)

**Comment by mbarkley** [comment]
Having a constructor with arguments for `MediaStreamTrackEvent` would prevent this specific occurrence because Errai doesn't generate factories for types that have constructors with arguments.

But the Errai generated code is wrong and I'm sure there are other types in elemental2 that could trigger the same issue so I will make the fix in Errai.

**Comment by hrstoyanov** [comment]
Thanks @mbarkley, I see you tracking this as [ERRAI-1039](https://issues.jboss.org/browse/ERRAI-1039). If you need a repro, look at the attachments to this issue. 

Slightly off topic: As Elemental2 is here to stay, can we drop the [Errai 4 DOM wrappers](https://github.com/errai/errai/tree/master/errai-common/src/main/java/org/jboss/errai/common/client/dom) before Errai 4 Final ships, as the gap has been filled with the release of Elemental2? I have not compared both in detail, just asking ... as this will future-proof Errai.
