### ISSUE TITLE
StackTraceCreator.dropInternalFrames compiles with null.$_nullMethod while using compiler optimization levels

### ISSUE THREAD

**Issue by PBaranovskyi** [gwtproject/gwt#9521]
**GWT version: 2.8.1** 
**Browser (with version): Any** 
**Operating System: Any** 

---

##### Description
StackTraceCreator.dropInternalFrames compiles with null.$_nullMethod while using compiler optimization levels:

Optimized:
```javascript
function dropInternalFrames(stackTrace){
  var i, numberOfFramesToSearch;
  numberOfFramesToSearch = min_1(stackTrace.length, 5);
  for (i = numberOfFramesToSearch - 1; i >= 0; i--) {
    if (null.$_nullMethod() || null.$_nullMethod()) {
      stackTrace.length >= i + 1 && (stackTrace.splice(0, i + 1) , undefined);
      break;
    }
  }
  return stackTrace;
}
```
Not optimized:
```javascript
cggcci.dropInternalFrames = function dropInternalFrames(stackTrace){
  var dropFrameUntilFnName, dropFrameUntilFnName2, i, numberOfFramesToSearch;
  dropFrameUntilFnName = 'captureStackTrace_0';
  dropFrameUntilFnName2 = 'initializeBackingError';
  numberOfFramesToSearch = jl.min_3(stackTrace.length, 5);
  for (i = numberOfFramesToSearch - 1; i >= 0; i--) {
    if (jl.equals_Ljava_lang_Object__Z__devirtual$_2(stackTrace[i].getMethodName(), dropFrameUntilFnName) || jl.equals_Ljava_lang_Object__Z__devirtual$_2(stackTrace[i].getMethodName(), dropFrameUntilFnName2)) {
      cggcci.splice(stackTrace, i + 1);
      break;
    }
  }
  return stackTrace;
}
```

##### Steps to reproduce
Just compile with 
<gwt.draftCompile>false</gwt.draftCompile>
<gwt.compiler.optimizationLevel>9</gwt.compiler.optimizationLevel>

**Comment by rluble** [comment]
The optimizer in GWT replaces `a.b()` by `null.$_nullMethod()` when it determines that `a` will `null`.  I am assuming that you are seeing the `null.$_nullMethod()` code execute and fail at runtime whereas the unoptimized version produces a meaningfull result.

Could you provide a complete minimal repro case?

**Comment by PBaranovskyi** [comment]
when I call Integer.parseInt("") - the NumberFormatException is fired. And dropInternalFrames is called from method printStackTraceItems in Throwable. 

called code of printStackTraceItems 
function $printStackTraceItems(this$static, out, ident){
  var element, element$array, element$index, element$max, stackTrace;
  for (element$array = (this$static.stackTrace == null && (this$static.stackTrace = ($clinit_StackTraceCreator() , stackTrace = initUnidimensionalArray(Ljava_lang_StackTraceElement_2_classLit, $intern_2, 2830, 0, 0, 1) , dropInternalFrames(stackTrace))) , this$static.stackTrace) , element$index = 0 , element$max = element$array.length; element$index < element$max; ++element$index) {
    element = element$array[element$index];
    out.println(ident + '\tat ' + element);
  }
}

**Comment by rluble** [comment]
Could you create a minimal repro?
