### ISSUE TITLE
Eclipse errors about lineStart and lineEnd due to old xsd file

### ISSUE THREAD

**Issue by jnikkels** [gwtproject/gwt#9524]
**GWT version:** 2.8.0
**Browser (with version):** 
**Operating System:** 

---

##### Description
I'm using DockLayoutPanel in ui binder. I want RTL support therefor need to use lineStart and lineEnd instead of east and west. This is working fine, however Eclipse reports errors for these elements.
The reason is that the XML Catalog refers to the following schema file:
http://dl.google.com/gwt/dtd/com.google.gwt.user.client.ui.xsd
This one does not yet contain lineStart and lineEnd, The one in gwt-user-2.8.0.jar is correct.
Can the dl.google.com version be updated to the latest?

**Comment by tbroyer** [comment]
I'd say this is an issue with the GWT Eclipse Plugin then (that should either use another URL –possibly one that we could host at gwtproject.org– or the schema from the gwt-user JAR) ⇒ https://github.com/gwt-plugins/gwt-eclipse-plugin/issues
/cc @branflake2267

**Comment by jnikkels** [comment]
Yes the plugin defines that URL. While trying to find a workaround I noticed an error in com.google.gwt.user.client.ui.xsd (the one embedded in gwt-user-2.8.0.jar) it contains the element with name LayoutPanel twice. Result alidation error:
sch-props-correct.2: A schema cannot contain two global components with the same name; this schema contains two occurrences of 'urn:import:com.google.gwt.user.client.ui,LayoutPanel'.	line 664	XML Schema Problem

**Comment by tbroyer** [comment]
Wow, and it's been that way for 8 years!

Anyway, as the comment in `UiBinder.xsd` says, those schemas aren't valid anyway (for other reasons) and should not (and cannot) be used for validation (only has hints to IDEs for attribute completion).

**Comment by branflake2267** [comment]
For sure, there are several of those issues. :) I like to fix them, but I batch them. I'm aiming for June for another round of fixes. Although it's a really busy month, so likely it will fall into July.

**Comment by tbroyer** [comment]
Any idea what IntelliJ IDEA does btw?

**Comment by branflake2267** [comment]
I'm not sure. I haven't seen a use of this anywhere, but I haven't been looking either. Now I'm curious. If @jnikkels can file an issue with a sample of the uibinder file, I'd be interested in taking a look at that in the next round.
