### ISSUE TITLE
unsafe usage of file in/output stream, seriously affecting DevMode server operation on Windows

### ISSUE THREAD

**Issue by jjYBdx4IL** [gwtproject/gwt#9528]
Reading and writing of files should only be done using try-with-resources. This might not be an issue on Linux, but it is a serious issue on Windows where I repeatedly get conflicts with GWT DevMode server not releasing file handles.

One example: Output.openSourceFile returns a file input stream. SourceHandler.makeSourcePage then does

    return Responses.newBinaryStreamResponse("text/plain", pageBytes);

where it eventually *might* get closed if no error happens....

Please! This is really poor programming style. If you can't figure out how to reliably do this, use an intermediary ByteArrayInputStream.

I didn't even look at 1% of the code base. A simple search for "InputStream" and the first match already brought up this example.

**Comment by tbroyer** [comment]
I'd happily review patches if you'd want to help us improve GWT!
http://gwtproject.org/makinggwtbetter.html

**Comment by jjYBdx4IL** [comment]
I moved this to the GWT discussion group because I think this needs public discussion before someone is going to write patches that are going to be rejected later on because of some potential dissent.
