### ISSUE TITLE
Add support for WebAssembly

### ISSUE THREAD

**Issue by danroth27** [gwtproject/gwt#9532]
Are there any plans to add WebAssembly support to GWT?

[WebAssembly] is "a new portable, size- and load-time-efficient format suitable for compilation to the web." Code compiled to WebAssembly runs at near native speeds. The spec has reached [browser consensus](http://webassembly.org/roadmap/) and is implemented by all major browsers. 

Instead of compiling Java to JavaScript, you could either:
- Build a JVM in WebAssembly and run Java byte code directly, or
- Compile Java byte code to WebAssembly

Are either of these approaches being considered for GWT?

**Comment by gkdn** [comment]
Building a JVM doesn't seem practical to me due to code size and performance issues.

Compiling java code to to webassembly is also unlikely to be practical until GC is implemented in webassembly. Last time I checked, there was no timeline for that.

**Comment by tbroyer** [comment]
AFAICT, there are other projects that do what's suggested here (I don't have links, I don't track. I suspect there are huge implications on interop with JS (including JSNI).

Actually, GWT is taking quite an opposite direction, favoring JS interop rather than blackbox monolithic code.
