### ISSUE TITLE
Serialization policy and X-GWT-Module-Base header variable

### ISSUE THREAD

**Issue by jomeier** [gwtproject/gwt#9538]
Hi,

I use GWT version 2.7.0 behind a reverse proxy (NGINX) and have a problem with the GWT RPC causing Server 500 errors.

I checked the code and saw that in the request header there is a 

X-GWT-Module-Base

variable which wont be used by the server to set the module path. Several patches for the reverse proxy issue point in the direction to use this variable.

Why it isn't used anywhere to fix this issue? We still have to patch GWT to get it work behind a reverse proxy?

Thanks and best regards,

Josef

**Comment by tbroyer** [comment]
The header **is** used by the server https://github.com/gwtproject/gwt/blob/2.7.0/user/src/com/google/gwt/user/server/rpc/RemoteServiceServlet.java#L209, and you can override the method, no need to "patch" GWT.

**Comment by jomeier** [comment]
It's only called by unit tests.

My problem is that I want to have 3rd party GWT apps behind a reverse proxy. I don't have access to their code. My idea was to remote control the module base path by the header variable X-GWT-Module-Base.

But it seems that the interesting code in GWT is only used by some unit tests and it's no standard feature of GWT to use the header variable for getting the path to the policy file.

This seems not possible out of the box. Am I right?

**Comment by tbroyer** [comment]
Ah right, it apparently was only used for the experimental "deRPC" and should probably have been deleted along with it. I suppose it was kept for backwards compatibility, for people who used it explicitly in their code.

But it remains that the solution if you want to rewrite the paths in the reverse-proxying is to override a method (`doGetSerializationPolicy`); i.e. the application has to explicitly support it; or the reverse-proxy also has to rewrite the GWT-RPC request payload… (rewriting paths is fundamentally broken anyway, you have to possibly rewrite paths everywhere: cookies, redirections, HTML, JavaScript, CSS, JSON, etc. unless applications have specific support built-in, in which case they can do it for GWT-RPC too)

You might be able to workaround this with some awful trickery, by setting the `gwt.codeserver.port` system property for the proxied GWT app, and setting up a small reverse proxy there too.

Or a much less awful trickery: modify the proxied webapp to move/copy the *.gwt.rpc files where the app expects them.

Anyway, rewriting paths needs to be explicitly supported by the proxied webapps (override `doGetSerializationPolicy`, possibly making use of `X-GWT-Module-Base` then), or need some specific processing of GWT-RPC request payload (similar to the specific processing of responses already done to rewrite paths everywhere else).

**Comment by jonl-percsolutions-com** [comment]
Here are two different templates we use successfully for nginx proxy:

**GWT app deployed @ server/root**

```
server {
   listen 443;
   server_name externalserver;

   client_body_buffer_size  16K;
   client_max_body_size  1M;

   include /etc/nginx/ssl.d/ssl.conf;

   root /usr/share/www/server/maintenance;

   location ~ ^/index.html {
        return 301 $scheme://$server_name/?$query_string;
   }

   location / {
        try_files /$uri /$uri/ @proxy;
   }

   location @proxy {
        proxy_pass http://downstream;
        proxy_send_timeout 120s;
        proxy_read_timeout 120s;
        proxy_pass_request_headers      on;
        proxy_set_header        Host            $host;
        proxy_set_header        X-Real-IP       $remote_addr;
        proxy_set_header        X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header        X-GWT-Module-base http://downstream/modulename/;

        proxy_redirect      http://downstream https://server_name;
   }
}
```

**GWT app deployed @ sub context:**

```
server {
   listen 443 ssl;
   server_name externalserver;

   client_body_buffer_size  16K;
   client_max_body_size  1M;

   proxy_send_timeout 120s;
   proxy_read_timeout 120s;
   proxy_pass_request_headers      on;
   proxy_set_header        Host            $host;
   proxy_set_header        X-Real-IP       $remote_addr;
   proxy_set_header        X-Forwarded-For $proxy_add_x_forwarded_for;
   proxy_set_header        X-GWT-Module-base http://downstream/context/modulename/;
   proxy_buffering off;

   include /etc/nginx/ssl.d/jinx_apps_ssl.conf;

   location / {
        proxy_pass http://downstream/context/;
        proxy_cookie_path  /context/ /;


        location ~* \.(html|css|jpg|gif|png|ico|js)$ {
               proxy_cache          cache;
               expires              30m;
               proxy_pass http://downstream;

               location ~* (nocache) {
                      proxy_cache off;
                      proxy_pass http://downstream;
               }
        }

        location /context/ {
              proxy_pass http://downstream/context/;
              proxy_cookie_path  /context/ /;
        }

        location /modulename/ {
                proxy_pass http://downstream/context/modulename/;
                proxy_cookie_path  /context/modulename/ /modulename/;
        }
   }
}
```

Things are easier if you deploy to the root context of the server.
