### ISSUE TITLE
GWT 'String' toLowerCase and toUpperCase emulation

### ISSUE THREAD

**Issue by srkprasadam** [gwtproject/gwt#9540]
**GWT version:2.8.0** 
**Browser (with version):Chrome - Version 59.0.3071.115 (Official Build) (64-bit)** 
**Operating System:windows** 

---

##### Description
Emulation for toLowerCase and toUpperCase methods on a String is different in GWT

public String toLowerCase() {
    return asNativeString().toLowerCase();
  }

public String toUpperCase() {
    return asNativeString().toLocaleUpperCase();
}

The uppercase method is doing Locale specific conversion, which is causing problems for us with Turkish users. 

##### Steps to reproduce
Use String uppercase on a Turkish locale VM

**Comment by tbroyer** [comment]
I think you can use `toUpperCase(Locale.ROOT)`. `toString` is _supposed_ to be locale-dependent.

**Comment by gkdn** [comment]
Unlike Java we chose to be not locale specific by default with toLowerCase/toUpperCase but it looks like [this patch](https://gwt-review.googlesource.com/#/c/gwt/+/13863/1/user/super/com/google/gwt/emul/java/lang/String.java) introduced a regression to toUpperCase :/

You can work around it in a forward compatible way by passing it explicitly as @tbroyer described.

**Comment by srkprasadam** [comment]
I understand that we can workaround this issue by passing Locale explicitly. But that is too much of inconvenience, as we has toUpperCase() all over in the code. Thanks for targeting this bug to 2.8.2

**Comment by tbroyer** [comment]
https://gwt-review.googlesource.com/c/gwt/+/19320
