### ISSUE TITLE
Chrome Browser Version 60 --> XMLParser.getElementsByTagname(...) doesn't work

### ISSUE THREAD

**Issue by Katy91** [gwtproject/gwt#9541]
**Problem with GWT Version 2.8** 
**Chrome Browser Version 60:** 

---
##### Description
The getElementsByTagName(...) Method of the XMLParser doesn't work with the new Chrome Browser Version 60.
I think there went something wrong with the namespace. Adding the namespace to the tagname fixes the problem, but then it doesn't work in all other browsers.

##### Steps to reproduce
<hm: exampleTag ....>

You need a xml-File with different namespaces. Now you can parse the elements by tagnames, without adding the namespace (like getElementsByTagname(exampleTag). Now you get all Elements with this tagname.
With Chrome 60 Browser it is neccessary to add the namespace like getElementsByTagname(hm:exampleTag)

**Comment by tbroyer** [comment]
`cop.google.gwt.xml` is not designed to support XML with namespaces. Your use-case was never actually meant to be supported.

The way forward is JsInterop (have a look at Elemental 2 though, it probably already maps those APIs)
