### ISSUE TITLE
JSP error - SimpleInstanceManager cannot be cast

### ISSUE THREAD

**Issue by SabrinaWons** [gwtproject/gwt#9546]
**GWT version: 2.8.0** 
**IDE: Eclipse Neon (With GWT Plugin)** 

---

##### Description :

When trying to display a JSP, the following error is thrown :

```
org.apache.jasper.JasperException: java.lang.ClassCastException: org.apache.tomcat.SimpleInstanceManager cannot be cast to org.apache.tomcat.InstanceManager
	at org.apache.jasper.servlet.JspServletWrapper.handleJspException(JspServletWrapper.java:585)
```

##### Steps to reproduce

This error is easily reproducible :

- Create a GWT project with the 2.8.0 version (with Eclipse).
- In the web.xml, define a listener :
```
<listener>
	<listener-class>com.example.myproject.client.MyWebAppListener</listener-class>
</listener>
```
- In the listener, write a method (that is not even  called) that uses HttpClientBuilder and SSLConnectionSocketFactory.
```
package com.example.myproject.client;

import javax.servlet.ServletContextEvent;
import javax.servlet.ServletContextListener;
import org.apache.http.conn.ssl.SSLConnectionSocketFactory;
import org.apache.http.impl.client.HttpClientBuilder;

public class MyWebAppListener implements ServletContextListener {

    public void contextInitialized(ServletContextEvent sce) { /* EMPTY  */ }
    public void contextDestroyed(ServletContextEvent sce) { /* EMPTY */ }

    private void myMethod() {
        HttpClientBuilder builder = HttpClientBuilder.create();
        SSLConnectionSocketFactory ssl = new SSLConnectionSocketFactory(null);
        builder.setSSLSocketFactory(ssl);
    }

}
```
- Run the application (with Super Dev Mode or Classic Dev Mode) within Eclipse.

**Comment by tbroyer** [comment]
I can't reproduce with GWT 2.8.1; using the `org.codehaus.mojo:gwt-maven-plugin:2.8.1` archetype to create the project then following your steps above and running with `mvn gwt:run`.
In the DevMode's Jetty tab, I get a warning:
```
00:04:22,355 [WARN] Server class 'org.apache.http.conn.socket.LayeredConnectionSocketFactory' could not be found in the web app, but was found on the system classpath
    
00:04:22,355 [WARN] Adding classpath entry 'file:/home/…/.m2/repository/org/apache/httpcomponents/httpclient/4.5.1/httpclient-4.5.1.jar' to the web app classpath for this session
```
This is expected, as I didn't add a dependency on Apache HTTP Client so it cannot be found in the webapp's `WEB-INF/lib`. In case you're using the GWT SDK downloaded as a ZIP file instead of using artifacts from the Central Repository (e.g. using Maven or Gradle), then you'll have `gwt-dev.jar` adde to the webapp classloader (as if you'd have put it into `WEB-INF/lib`) and this causes all sorts of errors.

Can you share more information about your setup? Maybe share a small project that reproduces the issue? (either as a GitHub/GitLab/Bitbucket project, or a ZIP file attached to the issue)

**Comment by SabrinaWons** [comment]
Hi tbroyer,
Thank you for your reply, it helped me a lot.
Here are the different scenarios I tested :

- **With command line maven gwt : No error** 
 \- Generate and run the project :
```
mvn archetype:generate    -DarchetypeGroupId=org.codehaus.mojo    -DarchetypeArtifactId=gwt-maven-plugin    -DarchetypeVersion=2.8.1
mvn war:exploded
mvn gwt:run
```
 \- Access to the JSP : No error!

- **With Eclipse + GWT SDK : Error**
 \- Create a new project : Eclipse > New Project > Google > Web Application Project > Use GWT SDK 2.8.0 > Finish.
 \- Add the JSP + the listener (that uses HttpClientBuilder and SSLConnectionSocketFactory) 
 \- Run the project : Eclipse > Run as GWT Web Application
 \- Access to the JSP : _SimpleInstanceManager cannot be cast to InstanceManager_


- **With Eclipse + No GWT SDK + Maven dependencies : No Error**
 \- Create a new project : Eclipse > New Project > Google > Web Application Project > Use GWT SDK 2.8.0 > Finish.
 \- Add the maven dependencies : Configure > Convert to Maven Project. Add the gwt-user and gwt-dev dependencies in the pom.xml.
 \- Remove the GWT SDK : Build path > Libraries > GWT SDK 2.8.0 >Remove.
 \- Add the JSP + the listener (that uses HttpClientBuilder and SSLConnectionSocketFactory) 
 \- Run the project : Eclipse > Run as GWT Web Application
 \- Access to the JSP : No error!

pom.xml :
```
        <dependency>
            <groupId>com.google.gwt</groupId>
            <artifactId>gwt-user</artifactId>
            <version>2.8.0</version>
        </dependency>

        <dependency>
            <groupId>com.google.gwt</groupId>
            <artifactId>gwt-dev</artifactId>
            <version>2.8.0</version>
        </dependency>
```

So, it works now!
Thank you

**Comment by tbroyer** [comment]
Note that the proper fix is to have Apache HTTP Client JARs in WEB-INF/lib (when using Maven, add Apache HTTP Client as a dependency to the POM and run `mvn war:exploded`)

Also, you'll likely want to add `<scope>provided</scope>` to your gwt-user and gwt-dev dependencies to **not** include them in your webapp (ideally, you'll split your server-side and client-side code into separate Maven modules; I strongly discourage using `org.codehaus.mojo:gwt-maven-plugin` archetype, or a similar setup, for anything else than a throwable project, such as a bug repro case)
