### ISSUE TITLE
SuperDevMode recompiles RPC since they are unchanged

### ISSUE THREAD

**Issue by javastud** [gwtproject/gwt#9549]
Hi,
We are using GWT 2.7.0, and trying SuperDevMode. Works well unless you restart the jetty server. After starting jetty in superdevmode and launch chrome (sdbg) it compiles and generates rpc manifests. Well no problem, when you shutdown and start jetty, same compilation/calculation thing happens again without ANY CHANGE made in the files. Nothing changed i mean just a restart.

We have 20 RPC services and each has many methods and returning too many types unfortunately taking too long(~5 min/each). Its too interesting that although we currently use Legacy mode (although it was deprecated) it works at acceptable speeds(~90secs for ALL) under this conditions with Firefox 26.

This really stops/aborts/cancels us on development. Should switching to 2.8.1 make sense? Or what we are doing unexpected by the SuperDevMode? Or is this a needed thing?

**Comment by dankurka** [comment]
Please use the gwt user group for questions located at https://groups.google.com/forum/#!forum/Google-Web-Toolkit

**Comment by javastud** [comment]
Hi Daniel. We think this is a bug. Are you sure that it is not a bug should be discussed to solve?

**Comment by tbroyer** [comment]
Whether there are possible improvements or not, we do not support older versions (i.e. there won't ever be a 2.7.1), so I'd suggest you try with 2.8.1 (or even HEAD-SNAPSHOT). You could also possibly make some adjustment to your development workflow, as restarting SDM is not something that should be required often (i.e. how about not stopping it? a slow startup can be paid off by keeping the process running longer)
