### ISSUE TITLE
Update CLDR data (incl. timezone database for recent changes in Russian timezones)

### ISSUE THREAD

**Issue by Maia-Everett** [gwtproject/gwt#9557]
The GWT timezone database (TimeZoneConstants.properties) is over 3 years old, last updated in 2014. It does not consider, for example, the latest changes in Russian timezones from 2014 to 2017.

It would be nice if it was updated for the next GWT release.

**Comment by tbroyer** [comment]
I'm afraid it'll be too late for 2.8.2, as what's actually needed is to update from CLDR from 25 to the latest version (currently 31, 32 is in beta and is scheduled for Oct 19) and update ICU4J from 50.1.1 to 59.1 (or more likely 60.1 that's scheduled for Oct 18). Issue #8703 is (supposedly) tracking the ICU4J update.

**Comment by vegegoku** [comment]
Dears
I have working on this and managed to update the cldr data to version 32, i only have one concern before i open a pull request related to `GoogleMods.patch`.
i already started a discussion on the gwt-contrib group, and i need to know if we still need to fix and apply the patch or we should go for a more standard cldr data.
Thanks

**Comment by vegegoku** [comment]
please follow my commit on gerrit for the latest updates on this issue, where i updated the cldr data to the latest CLDR data version 32.0.1

https://gwt-review.googlesource.com/c/gwt/+/20600

**Comment by niloc132** [comment]
For those following here, https://gwt-review.googlesource.com/c/gwt/+/21400 has now been merged too bringing us to CLDR 34, and an ICU4J patch is in the works.

**Comment by ecerichter** [comment]
Would you please guide me on how can I apply this changes in 2.6.x?
