### ISSUE TITLE
2.8.2 has not been published to maven

### ISSUE THREAD

**Issue by paladox** [gwtproject/gwt#9559]
hi, when i go to https://mvnrepository.com/artifact/com.google.gwt and click one of them, they show only 2.8.1 as the latest. Could 2.8.2 be published please?

**Comment by axls** [comment]
2.8.2 is published to maven central - http://central.maven.org/maven2/com/google/gwt/gwt-user/2.8.2/. Probably, mvnrepository.com did not yet update indexes.

**Comment by paladox** [comment]
ah thanks :).

**Comment by tbroyer** [comment]
Fwiw, if you want something up-to-date (modulo replication / reindexing), use https://search.maven.org/ which is the "official" UI for the Central Repository; mvnrepository is a third party.

**Comment by paladox** [comment]
thanks.
