### ISSUE TITLE
USB function in Chrome 61+ can cause obfuscation conflicts

### ISSUE THREAD

**Issue by efennellboomi** [gwtproject/gwt#9562]
**GWT version:** 
2.7.0

**Browser (with version):** 
Chrome 61+

**Operating System:** 
Linux

---

##### Description

"USB" was formalized as a function in Chrome 61. Obfuscation can produce "USB" as an object / function name.

##### Steps to reproduce

Compiling using the (codehaus) maven gwt plugin / gwt-dev 2.7.0 occasionally results in this issue.

##### Links to further discussions
Seems like adding this as a keyword in JsRootScope should fix the issue.

**Comment by rluble** [comment]
This should have been fixed for 2.8.2 in [#19640](https://gwt-review.googlesource.com/c/gwt/+/19640).

To backport just copy the file dev/core/src/com/google/gwt/dev/js/globals/chrome.txt

**Comment by efennellboomi** [comment]
Thank you for the prompt response.  Also logging a workaround for 2.7 in case folks run into this ticket:
you can set / extend the js.identifier.blacklist property in your gwt.xml as well.

  <extend-configuration-property name="js.identifier.blacklist" value="USB"/>
