### ISSUE TITLE
Injecting CSS and JS into UiBinder - Issue with getting access to image path

### ISSUE THREAD

**Issue by zbeedatm** [gwtproject/gwt#9566]
Hi,
I'm trying to implement a JS library (VisJs: http://visjs.org/) in my GWT project.
So, in order to use it from my UiBinder I used the ScriptInjector:
`ScriptInjector.fromString(JsResources.INSTANCE.visScript().getText()).inject();`

and in ui.xml I used the following:
`<ui:style src='../../../resources/vis.min.css'>
	.htmlPanel {
		font-size: 12px;
		font-family: Verdana, Geneva, sans-serif;
		border: 1px;
		border-style: solid;
		border-color: #969696;
		margin-top: 10px;
	}
	</ui:style>`

in my project I created a folder called resources as follow;
- resources
   vis.js
   vis-min.css
   - img
      - network

in my gwt.xml i added: \<resource path="resources" /> in order to get access to these resources.

The script is working for me and loading the graph, but not completely. I'm getting such errors:

> vis.js:52995 GET http://127.0.0.1:8888/css/img/network/cross.png 404 (Not Found)

Somehow the "css" is part of the url and images can't be found!
Can you please advise how to fix it?

B.R.

**Comment by tbroyer** [comment]
Please use StackOverflow with the gwt tag, or the [GWT Users group](https://groups.google.com/forum/#!forum/google-web-toolkit), for support questions.
