### ISSUE TITLE
JsInterop - Why JsProperty cannot have a vararg parameter?

### ISSUE THREAD

**Issue by TDesjardins** [gwtproject/gwt#9571]
**GWT version: 2.8.2
**Browser (with version): not relevant
**Operating System: not relevant

---

##### Description
JsInterop supports varargs on constructors and methods/functions. Is there a special reason to not allow it on JsProperty?

See: https://github.com/gwtproject/gwt/blob/master/dev/core/src/com/google/gwt/dev/jjs/impl/JsInteropRestrictionChecker.java#L539

##### Steps to reproduce

Create a JsProperty with a varargs-parameter and compile.

**Comment by niloc132** [comment]
Shouldn't it be an array property instead? In the JS, it wouldn't be a single vararg, but would be an array passed in, or it would be a method and not a property, right?

**Comment by rluble** [comment]
@JsProperties represent js fields and they are accessed as such. So when you write it Java `a.setFoo(1)` the corresponding JavaScript code will be `a.foo = 1`. There is no notion of parameters there let alone varargs.

When Java varargs are used in a JavaScript abstraction (JsMethod, JsConstructor) they are seen as optional parameters and passed directly.

In Java varargs are just synticatical sugar, a mere convenience, and are always a single parameter array under the cover.

**Comment by TDesjardins** [comment]
@niloc132 Yes, it should be an array but I thought about a convenience method to also pass "single" elements without creating an array or another method. But I think the clean solution is to use an @JSOverlay method for this purpose. Thanks!

@rluble Your example is crystal clear. I made an error in my logic. Sorry and thank you!
