### ISSUE TITLE
Name conflict between JS method name and local variable

### ISSUE THREAD

**Issue by zbynek** [gwtproject/gwt#9573]
**GWT version:** 2.8.2 (Maven repository)

**Browser (with version):** Chrome 62.0.3202.94

**Operating System:** Windows

---

##### Description
Call to Double.isNaN fails if local variable isNaN is present. Tested with following code
```java
@Override
public void onModuleLoad() {
	boolean isNaN = Double.isNaN(42);
	GWT.log("" + isNaN);
}
```

##### Steps to reproduce
Compile a project with the entry point above, it will fail to initiate (both normal and super dev mode).  When compiled with DETAILED style you can see that isNaN on right hand side of the assignment is also replaced with the local variable. 

##### Known workarounds
Rename the local variable.

**Comment by tbroyer** [comment]
This is a regression from 2.8.1 (possibly due to https://github.com/gwtproject/gwt/commit/638cffa25a2c9268e28400c02ca740490de914a9 ?)

**Comment by gkdn** [comment]
JsProctedNames includes isNaN. I guess there is some bug around namers.

**Comment by gkdn** [comment]
Or worse it might be related to JsSymbolResolver which IIRC was making plenty of incorrect assumptions and connect unrelated names. Having detailed renamer renaming both might be and indication of that. @rluble?

**Comment by rluble** [comment]
That was my initial guess. That for some reason the variable isNan gets the unobfuscated name from Double.isNan. But now that I think about it  there is also the possibility because it sees Double.isNan as a (qualified) name on a class (that gets emitted without the qualifier at some point) and in a different scope than the local variable, the clash is not detected. 

Anyway those are my guesses and I would have to look deeper.

**Comment by rluble** [comment]
Thanks for the easy repro.

**Comment by rluble** [comment]
Patch is ready for review https://gwt-review.googlesource.com/c/gwt/+/20220

**Comment by zbynek** [comment]
@rluble could you please share some status update on this one? After you fixed it within a week from reporting (great!) it got stuck in "waiting for review" for more than a year.

**Comment by rluble** [comment]
I have no  updates on this :(. If someone approves the changes I am happy to merge.
