### ISSUE TITLE
com.google.gwt.dom.client.Node issue

### ISSUE THREAD

**Issue by hrstoyanov** [gwtproject/gwt#9579]
I noticed that in with GWT 2.8.2 com.google.gwt.dom.client.Node on line 173 is using **this**:

  /**
   * The value of this node, depending on its type; see the table above. When it
   * is defined to be null, setting it has no effect.
   */
  public final native String getNodeValue() /*-{
    **return this.nodeValue;**
  }-*/;

which leads to a warning in the latest FF:
```
Use of attributes’ nodeValue attribute is deprecated. Use value instead.
```

Seems like a trivial fix - just add Node.getValue(), so developers would have an alternative, possibly deprecating the getNodeValue() method. 

Can someone commit it, please?

**Comment by tbroyer** [comment]
I'm assuming you're using `someElement.getAttributes()` and using `getNodeValue()` on a `Node` from the `NamedNodeMap`? If that's the case, then you should actually cast the `Node` to an `Attr` and call `getValue()`. I.e. not a bug in GWT (and it has always been that way, and the deprecation warning in Firefox is apparently years old already –as in, 6 years old at least)

**Comment by hrstoyanov** [comment]
+ @mbarkley

@tbroyer Actually no ... this is coming from Errai, specifically [this piece of code, line 145](https://github.com/errai/errai/blob/master/errai-ui/src/main/java/org/jboss/errai/ui/shared/TemplateUtil.java) . If ```Node.getValue()``` was available Errai could have used it.

**Comment by tbroyer** [comment]
Oh, first, sorry, I had read c.g.g.xml instead of c.g.g.dom. Anyway, that doesn't change anything, `value` is only present on `Attr` in DOM, and this code should use it (e.g. define an `Attr` JSO and have the `getAttributes` JSNI method return `JsArray<Attr>`, or define a `getValue(Node)` JSNI method.
