### ISSUE TITLE
Misleading input type value in javadoc

### ISSUE THREAD

**Issue by xotonic** [gwtproject/gwt#9583]
https://github.com/gwtproject/gwt/blob/5092f925d32deb19b54e91432f4e232d95c3c333/user/src/com/google/gwt/user/client/DOM.java#L229
```java
  /**
   * Creates an HTML INPUT type='CHECK' element.
   * 
   * @return the newly-created element
   */
  public static com.google.gwt.user.client.Element createInputCheck() {
    return Document.get().createCheckInputElement().cast();
  }
```
There are no such `type` value as `check`. This is misleading.
The delegated method has right description
```java
  /**
   * Creates an &lt;input type='checkbox'&gt; element.
   * 
   * @return the newly created element
   */
  public final InputElement createCheckInputElement() {
    return DOMImpl.impl.createCheckInputElement(this);
  }
```

**Comment by tbroyer** [comment]
Thank you for the report, but this method (and whole) class is effectively deprecated (we can probably mark it as such by now) so we won't spend time fixing its doc (we'd merge a patch though if you'd like to contribute it)
