### ISSUE TITLE
Development Mode - Jetty - Realm - Redirecting to 403 - Forbidden page

### ISSUE THREAD

**Issue by rsrini7** [gwtproject/gwt#9589]
**GWT version:** 2.8.0
**Browser version:** 62.0.3202.94
**Operating System:** Windows-7

---

##### Description

Redirecting to 403 "/Forbidden.jsp" when we access the "portal.jsp" and below log entry occurs.
```
[WARN] No authenticator for: {RoleInfo,C[samplerole],None}
[WARN] 403 - GET /portal.jsp (127.0.0.1) 15 bytes
```

##### Steps to reproduce

**jetty-web.xml**

```xml
<Configure class="org.eclipse.jetty.webapp.WebAppContext">
	<Call name="addBean">
      <Arg>
		<New class="org.eclipse.jetty.security.HashLoginService">
			<Set name="name">UPSRealm</Set>
			<Set name="config"><SystemProperty name="jetty.home"
                   default="."/>WEB-INF/realm.properties</Set>
		</New>
	  </Arg>
	</Call>
	<Call name="addBean">
      <Arg>
       <New class="org.eclipse.jetty.security.authentication.FormAuthenticator">
           <Arg type="java.lang.String">/Login.jsp</Arg>
           <Arg type="java.lang.String">/Login.jsp?error=true</Arg>
           <Arg type="boolean">true</Arg>
       </New>
       </Arg>
    </Call>
	<Get class="org.eclipse.jetty.util.log.Log" name="rootLogger">
      <Call name="warn"><Arg>demo test-realm is deployed. DO NOT USE IN PRODUCTION!</Arg>
      </Call>
    </Get>
</Configure>
```

**realm.properties**
username: samplerole

**web.xml**
```xml
	<security-constraint>
		<display-name>
			End-User Security Constraint
		</display-name>
		<web-resource-collection>
			<web-resource-name>End-User App</web-resource-name>
			<url-pattern>/portal.jsp</url-pattern>
		</web-resource-collection>
		<auth-constraint>
			<role-name>samplerole</role-name>
		</auth-constraint>
		<user-data-constraint>
			<transport-guarantee>NONE</transport-guarantee>
		</user-data-constraint>
	</security-constraint>
	<error-page>
		 <error-code>403</error-code>
	 	 <location>/Forbidden.jsp</location>
	</error-page>
```

**Comment by rsrini7** [comment]
Resolved as follows. jetty-web.xml

`
<Configure class="org.eclipse.jetty.webapp.WebAppContext">
	<Set name="securityHandler">
		<New class="org.eclipse.jetty.security.ConstraintSecurityHandler">
			<Set name="loginService">
                <New class="org.eclipse.jetty.security.HashLoginService">
					<Set name="name">MyRealm</Set>
					<Set name="config"><SystemProperty name="jetty.home" default="."/>/WEB-INF/realm.properties</Set>
				</New>
            </Set>
		</New>
	</Set> 

	<Get class="org.eclipse.jetty.util.log.Log" name="rootLogger">
      <Call name="warn"><Arg>demo test-realm is deployed. DO NOT USE IN PRODUCTION!</Arg></Call>
    </Get>
</Configure>
`

**Comment by tbroyer** [comment]
See https://www.eclipse.org/jetty/documentation/9.2.22.v20170531/configuring-security-authentication.html#d0e5625, you should probably use `<Get name="securityHandler">` rather than `<Set name="securityHandler"><New class="…">`.
