### ISSUE TITLE
Emulation of Arrays triggers "unusable-by-js" warning

### ISSUE THREAD

**Issue by jnehlmeier** [gwtproject/gwt#9592]
**GWT version:** HEAD and probably 2.8.2
**Browser (with version):** --
**Operating System:** --

---

##### Description

Compiling using GWT HEAD results in
```
Warnings in com/google/gwt/emul/java/util/Arrays.java
  [WARN] Line 1782: [unusable-by-js] Type of parameter 'd1' in 'int Arrays.1methodref$compare$Type.compare(long, long)' is not usable by but exposed to JavaScript.
  [WARN] Line 1782: [unusable-by-js] Type of parameter 'd2' in 'int Arrays.1methodref$compare$Type.compare(long, long)' is not usable by but exposed to JavaScript.
  [WARN] Suppress "[unusable-by-js]" warnings by adding a `@SuppressWarnings("unusable-by-js")` annotation to the corresponding member.
```

The code in question already has a `@SuppressWarnings("unusable-by-js")` annotation, so I guess the compiler does not see it because of the method reference.

```java
  @JsFunction
  private interface CompareLongFunction {
    @SuppressWarnings("unusable-by-js")
    int compare(long d1, long d2);
  }

  private static CompareFunction getLongComparator() {
    return JsUtils.uncheckedCast((CompareLongFunction) Long::compare);
  }
```

**Comment by rluble** [comment]
The compiler builds the synthetic classes implementing lambdas upfront in GwtAstBuilder.java but does not propagate the suppressions. 

The simplest reasonable solution is to blindly add unusable-by-js suppressions to synthetic methods. The reasoning being that the check will be performed for the functional interface nonetheless and the warning will be emitted there where the user wrote the offending code.

I'll gladly review the fix if anyone wants to tackle it.

There are two places in GwtAstBuilder where these are created:
1- for method references
https://gwt.googlesource.com/gwt/+/master/dev/core/src/com/google/gwt/dev/jjs/impl/GwtAstBuilder.java#1850
2- for lambdas
https://gwt.googlesource.com/gwt/+/master/dev/core/src/com/google/gwt/dev/jjs/impl/GwtAstBuilder.java#1252

JMethod has a fied that stores the suppressions.

**Comment by rluble** [comment]
Also the synthetic method is not marked as such. Another possible solution is to mark it as synthetic (which should be done nonetheless) and skip synthetic methods from being checked.

**Comment by axls** [comment]
@rluble Patch to review https://gwt-review.googlesource.com/c/gwt/+/20440.

**Comment by tbroyer** [comment]
Thanks @axls
