### ISSUE TITLE
Allow $ at the end of an attribute name

### ISSUE THREAD

**Issue by Waxolunist** [gwtproject/gwt#9595]
**GWT version:** 2.8.2
**Browser (with version):** -
**Operating System:** - 

---

##### Description

I use polymer elements in gwt.xml files with UIBinder. When I want to set native attributes (see [https://www.polymer-project.org/1.0/docs/devguide/data-binding](https://www.polymer-project.org/1.0/docs/devguide/data-binding)) I can't, because GWT does not allow attributes ending on $.

##### Steps to reproduce

Try following uiBinder file:

```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE ui:UiBinder SYSTEM "http://dl.google.com/gwt/DTD/xhtml.ent">
<ui:UiBinder xmlns:ui="urn:ui:com.google.gwt.uibinder" 
             xmlns:g="urn:import:com.google.gwt.user.client.ui">

  <g:HTMLPanel>
    <paper-icon-button icon="create" data-id$="something"></paper-icon-button>
  </g:HTMLPanel>
</ui:UiBinder>
```
The project can not be compiled with following error:

    Attribute name "data-id" associated with an element type "paper-icon-button" must be followed by the ' = ' character.

**Comment by jnehlmeier** [comment]
GWT uses `javax.xml` APIs to create a `SAXParser` to [parse the XML](https://github.com/gwtproject/gwt/blob/master/user/src/com/google/gwt/uibinder/rebind/W3cDomHelper.java). The `SAXParser` will be bound to a Xerces implementation which in turn does not allow the syntax you are using.

So GWT would need to provide a different SAXParser implementation to support that syntax.

**Comment by vegegoku** [comment]
if you can use elemental2 and ditch the uibinder then you can use [elemento](https://github.com/hal/elemento)

**Comment by tbroyer** [comment]
`.ui.xml` files are, as their name implies, XML files, and XML forbids the use of `$` in names: https://www.w3.org/TR/xml/#NT-Name

You may want to look at Errai UI templates: http://erraiframework.org/

**Comment by Waxolunist** [comment]
@vegegoku Elemento seems a good choice. The fifth annotation processor then. 
Thx for the tipp.
