### ISSUE TITLE
SuperDevMode memory issue in PersistentUnitCache

### ISSUE THREAD

**Issue by jnehlmeier** [gwtproject/gwt#9596]
**GWT version:** GWT HEAD @ 8ea92c387665f4c04481f3fb023eba1bb198c15d
**Browser (with version):** --
**Operating System:**  --

---

##### Description

![persistenceunitcache - inbound references](https://user-images.githubusercontent.com/1703797/36429175-45a684a6-1652-11e8-960a-1ecf3bbd5316.png)

In the image above you can see that a (increasing) number of `CompilerContext` hold a reference to `PersistenceUnitCache`. These `CompilerContext` instances belong to `JdtCompiler` instances which in turn are kept alive through stored `CompiledClass` instances in `PersistenceUnitCache` (see GC root below)

![gc root](https://user-images.githubusercontent.com/1703797/36429182-4b8d49fe-1652-11e8-8025-5212b76cd73b.png)

After several recompiles using SDM the `PersistenceUnitCache` retains just enough heap that an additional compile succeeds but linking the final JS fails with an OutOfMemoryError (some ArrayList wants to adjust its capacity but can't).

We used a custom GWT build of a commit somewhere between GWT 2.7 and 2.8 beforehand and it did not show that behavior.

**Comment by rluble** [comment]
I am not sure when/how/if the regression was introduced but looking at the
code it seems that you could make nameEnvironmentAnswer in CompiledClass a
WeakReference.

**Comment by gkdn** [comment]
Only relevant change I remember: 4c1b09147125c854603cdf9028c7e6996bbc7045

**Comment by jnehlmeier** [comment]
I think the issue simply appears because GWT has updated JDT compiler. A GWT `CompiledClass` holds a reference to a JDT class called `NameEnvironmentAnswer` [which has been modified to support Java9](https://git.eclipse.org/r/plugins/gitiles/jdt/eclipse.jdt.core/+/905307ba95aeaa4570286fd98cd5fee0aa7ea5d7%5E%21/org.eclipse.jdt.core/compiler/org/eclipse/jdt/internal/compiler/env/NameEnvironmentAnswer.java) and now has a reference to a `ModuleBinding` which in turn pulls in `JdtCompiler$INameEnvironmentImpl`.

I think the issue might also go away if GWT's `JdtCompiler$INameEnvironmentImpl` would be a static class so it does not hold an implicit reference to `JdtCompiler`. `INameEnvironmentImpl` uses `JdtCompiler.packages` field, so that would need to be passed on. Or does the implementation of `INameEnvironmentImpl ` require a "live" view on the `packages` field?

**Comment by rluble** [comment]
`JdtCompiler$INameEnvironmentImpl` needs also other fields fields from `JdtCompiler`like `internalTypes`and `additionalTypeProviderDelegate`. At least `internalTypes` and `packages` need to be live, but these are final fields that hold collections so they can be passed on construction.

**Comment by jnehlmeier** [comment]
You are right, had just taken a very short look at it. After a closer look it seems like

- `additionalTypeProviderDelegate` is always null. Couldn't find a path back to something that does not pass in null. So it could theoretically be deleted unless I am missing something.
- `cachedClassPathAnswerByInternalName` and the only method that uses this field `findTypeInClassPath` could both be moved into ´INameEnvironmentImpl`
- `packages` and `internalTypes` must be passed on as they need to be live

Any objection? Especially on the first point?

**Comment by rluble** [comment]
Agreed. There does not seem to be any instantiation/subclassing of `AdditionalTypeProviderDelegate` except for its unit test. Go ahead and remove everywhere. 

No objection.

**Comment by jnehlmeier** [comment]
https://gwt-review.googlesource.com/c/gwt/+/20500

**Comment by jnehlmeier** [comment]
Looks like it is not fully solved yet. `JdtCompiler.CompilerImpl` also keeps `JdtCompiler` alive with a similar GC root.

![gcroot2](https://user-images.githubusercontent.com/1703797/36608843-56046ba8-18cb-11e8-8d20-18d4b40334e3.png)

**Comment by rluble** [comment]
Hmm. Not completely solved but improved? It definitely improved the build times for some of our bigger apps (probably due to less memory pressure)

**Comment by rluble** [comment]
This patch  https://gwt-review.googlesource.com/c/gwt/+/20540 should fix the remaining issue.

**Comment by jnehlmeier** [comment]
Removed milestone as more work needs to be done. Both patches above improve the situation but retained heap memory still grows over time. See comments in https://gwt-review.googlesource.com/c/gwt/+/20540

**Comment by rluble** [comment]
Commit 477d512 fixed the remaining issue.
