### ISSUE TITLE
Lambda cast to inherited Type gives $_nullMethod

### ISSUE THREAD

**Issue by MorganPHudson** [gwtproject/gwt#9598]
**GWT version: 2.8.2** 
**Browser (with version): Chrome (64.0.3282.186)** 
**Operating System: Win10** 

---

##### Description
Got null.$_nullMethod expressions in potentially runnable code, which results in javascript errors.
I believe the culprit is Lambda expressions in overload methods that are cast to subTypes of functional interface.

##### Steps to reproduce
Working example in https://github.com/MorganPHudson/gwt-lambda-bug
Compiling project results in TestLambdaReceiver#find(Predicate) method in being optimised incorrectly with null.$_nullMethod instead of "Predicate.test(this)" expressions.
Commenting or removing TestLambdaReceiver#sibling(String) results in properly optimised code.

##### Links to further discussions
https://github.com/MorganPHudson/gwt-lambda-bug

**Comment by rluble** [comment]
Thanks for the concise repro case, I haven't not had a chance to look at this yet. Could you attach the generated (PRETTY) unoptimized and optimized code?

**Comment by rluble** [comment]
code review at https://gwt-review.googlesource.com/c/gwt/+/20580

**Comment by rluble** [comment]
Found the root cause and turned out to be a bad initial AST construction which was exposed by the optimizations.
