### ISSUE TITLE
Java10 JEP286 (Local-Variable Type Inference) support

### ISSUE THREAD

**Issue by axls** [gwtproject/gwt#9609]
##### Description
Support for [JEP286](http://openjdk.java.net/jeps/286) in GWT compiler.

##### Links to further discussions
https://groups.google.com/forum/#!topic/google-web-toolkit-contributors/DiGNHTKKe6Y

**Comment by axls** [comment]
I'm working on the patch for the issue.

**Comment by axls** [comment]
Patch to review https://gwt-review.googlesource.com/c/gwt/+/20720

**Comment by axls** [comment]
While working on the patch, I've noticed that the compiler's super-sourced integration tests (`user/test-super/com/google/gwt/dev/jjs/super/com/google/gwt/dev/jjs/test/Java8Test.java`) do not actually fail until `sourceLevel` 9/10 has defined in command line explicitly. E.g:

```
( cd user && ant test.draft.htmlunit -Dgwt.junit.testcase.web.includes="**/CompilerSuite.class" -Dtest.args="-sourceLevel 10")
```
But GWT build on http://build.gwtproject.org/job/gwt doesn't pass sourceLevel in build command (below is an output from the Jenkins log):

```
time nice ant clean elemental test dist doc -Dgwt.version=HEAD-SNAPSHOT -Dgwt.threadsPerProcessor=1 -Dgwt.threadCount=1 -Dtest.web.htmlunit.disable=true -Dtest.nometa.htmlunit.disable=true -Dtest.emma.htmlunit.disable=true
```

So the question is, are compiler's integration tests really executed on build.gwtproject.org?

**Comment by rluble** [comment]
Hmmm, It seems that they are not run. When we submit patches, we run all
the tests through our internal bazel-like build system which include the
all the Java8/9 tests.

We should upgrade the jvm in Jenkins to 10 so that the tests are run at 10
by default.

I don't like the option of adding to the jenkin command as it makes the
command fragile (i.e. we need to wait till the patch is landed to run the
test and we can no longer run the test on old commits).

**Comment by rluble** [comment]
Ignacio could you open a separate bug for this. Is there a stack trace that we can look at?

**Comment by axls** [comment]
Example could be narrowed to
```
var s = Stream.generate(() -> new Object() {
    String s = "42";
});
System.out.println(s.findFirst().get().s);
```
This code is able to be compiled (and executed) by JavaC. But JDT failed to compile this code.
I found related issue in JDT (still opened) - https://bugs.eclipse.org/bugs/show_bug.cgi?id=477894.

I don't think that the issue is about `local var` types. It's more about type inference for lambda return type in case of anonymous type. Next code (without var type) also cannot be compiled by JDT:
```
Stream.generate(() -> new Object() {
    String s = "42";
}).findFirst().get().s;
```

**Comment by jnehlmeier** [comment]
I find it kind of weird that you can propagate type information using `var` that you can not propagate without `var`.

```java
// Works. Anonymous Object type information propagates
String s = Stream.generate(() -> new Object() { String s = "42"; }).findFirst().get().s;

var o = Stream.generate(() -> new Object() { String s = "42"; }).findFirst().get();
s = o.s; // Works. Anonymous Object type information propagates

Object o2 = Stream.generate(() -> new Object() { String s = "42"; }).findFirst().get();
s = o2.s; // Fails. o2.s not accessible. Anonymous Object type information lost
```
Wondering if this is really an intended feature or more like a known quirk you better not rely on.

Your example code also has a surprising assignment behavior:
```java
// Assignment fails. Incompatible types: Optional<Object> vs Optional<anonymous Object>
Optional<Object> optO = Stream.generate(() -> new Object() { String s = "42"; }).findFirst();

// Assignment works.
Stream<Object> optStream = Stream.generate(() -> new Object() { String s = "42"; });
```

**Comment by jnehlmeier** [comment]
> I find it kind of weird that you can propagate type information using var that you can not propagate without var. 

Well ok, after reading the linked bug and realizing that 
```java
String s = Stream.generate(() -> new Object() { String s = "42"; }).findFirst().get().s;
```
already works in Java 8, the `var` identifier consistently carries on the type inference solution and allows a little more flexibility. However that they introduced a type inference solution in Java 8 that was impossible to write explicitly in code is an interesting decision.

**Comment by rluble** [comment]
```java
var o = Stream.generate(() -> new Object() { String s = "42"; }).findFirst().get();
s = o.s; // Works because o is *statically* typed as the anonymous class now *and* s has default visibility.
````
```java
var o = Stream.generate(() -> new Object() { private String s = "42"; }).findFirst().get();
s = o.s; // Should fail (I did not try it but I am sure). Because even though o has the anonymous object type, the field is private.
```
```java
Object o2 = Stream.generate(() -> new Object() {  String s = "42"; }).findFirst().get();
s = o2.s; // Fails. o2.s not accessible because o2 is statically typed as Object.
```

This is exactly how it is supposed to work, I don't find it surprising. It makes sense.

**Comment by jnehlmeier** [comment]
@rluble yeah, you are right. See my additional comment. I think what I don't like is that Java can produce type inference solutions that you can not write yourself explicitly. It started with Java 8 but even in Java 10 with `var` keyword you have that situation, e.g.
```java
// (1) while this works
var newOStream = Stream.generate(() -> new Object() { String s= "42"; });
String s = newOStream.findFirst().get().s;

// (2) this doesn't
var newO = (Supplier<Object>) () -> new Object() { String s= "42"; };
var newOStream2 = Stream.generate(newO);
String s1 = newOStream2.findFirst().get().s;
```
So it is impossible to split up the first code line of (1). That's what I don't like. However at least `var` stays consistent once you have that stream of anonymous Object types.

**Comment by rluble** [comment]
> So it is impossible to split up the first code line of (1). That's what I don't like. However at least var stays consistent once you have that stream of anonymous Object types.

I am not sure what you mean by this but if you think at the recursive structure of expressions and they way they are statically types none of this should be surprising.

You should read `var` as having the exact same static type of the expression on the right. You can write:

```java
// (1) this shouldn't work (I have not tried it though but I am sure) because the expression now is typed Steam<Object> and that would be the type of newOStream.
var newOStream = (Stream<Object>) Stream.generate(() -> new Object() { String s= "42"; });
String s = newOStream.findFirst().get().s;
```
In your second example by changing the type of `newO` the expression in the following in line will be inferred differently and have `Supplier<Object>` as its type hence `newOStream2` will in turn have `Stream<Object>` as its type.

**Comment by ibaca** [comment]
FYI https://developer.oracle.com/java/jdk-10-local-variable-type-inference, defines this "anoymous" types as **non-denotables types**.

**Comment by rluble** [comment]
Any type that doesn't have a syntactic representation is non-denotable, that includes anonymous types, intersection types, union types (like the ones in multi catch) and captures. Some non denotable types can become the type of a var variable and some don't. That is probably due to the fact that in Java type inference is not only driven by the recursive subexpressions but it also flows from left to right of an assignment. 

IMHO, Java has a quite ad-hoc messy and limited type system when compared with the principled type systems of ML or Haskell. But among the imperative languages it is one of the better ones.
