### ISSUE TITLE
HEAD-SNAPSHOT from Maven with -sourceLevel 10 fails due to ASM version incompatible with Java 10 classes

### ISSUE THREAD

**Issue by tbroyer** [gwtproject/gwt#9613]
**GWT version:** HEAD-SNAPSHOT (20180423.054422-445)
**Browser (with version):** n/a
**Operating System:** n/a (Linux)

---

##### Description

When GWT was updated to support Java 10 source level, its ASM was updated from 6.0 to 6.1.1, but the POMs published to Maven repos still use ASM 6.0.

##### Steps to reproduce

Use `-sourceLevel 10`, resolving GWT and its dependencies from the google-snapshots Maven repository.

##### Known workarounds

Force using ASM 6.1.1 by declaring them as dependencies and/or in dependency management.

**Comment by niloc132** [comment]
Is this going to impact our support for running the compiler itself on a Java7 JRE?

**Comment by tbroyer** [comment]
That should be safe: http://asm.ow2.io/faq.html#Q14 (says Java 5), https://gitlab.ow2.org/asm/asm/blob/ASM_6_1_1/build.gradle and https://gitlab.ow2.org/asm/asm/commit/5eac80e548c6076d23a06cefa8b3420b22193185#f07866736216be0ee2aba49e392191aeae700a35 (says 1.6, "retrofitted" to 1.5 using… ASM :wink:)

**Comment by axls** [comment]
Patch with fix for this issue https://gwt-review.googlesource.com/c/gwt/+/20740.

**Comment by tbroyer** [comment]
New patch (previous was reverted): https://gwt-review.googlesource.com/c/gwt/+/20800

**Comment by tbroyer** [comment]
Merged
