### ISSUE TITLE
JS root name "u2f" conflict

### ISSUE THREAD

**Issue by ibaca** [gwtproject/gwt#9619]
**GWT version:** All
**Browser (with version):** Firefox 
**Operating System:** All

---

##### Description
Invalid GWT compilation output caused by a "u2f" webauth utility. This token must be added to JsRootScope to avoid this name conflict.

##### Steps to reproduce
Enable "security.webauth.u2f" in Firefox (quantum or pervious versions). You must have a big enought app so the name "u2f" gets used by some type. Firefox will NOT allow to override the "u2f" token so it will break the GWT compiled code at runtime.

This can also be reproduced in old firefox if you use the "U2F support extension".

**Comment by rluble** [comment]
You can add it to 

https://gwt.googlesource.com/gwt/+/HEAD/dev/core/src/com/google/gwt/dev/js/globals/firefox25.txt 

That is one of the lists that GWT uses to avoid browser identifiers.

Maybe you can rename it to firefox.txt and change  the reference iin https://gwt.googlesource.com/gwt/+/HEAD/dev/core/src/com/google/gwt/dev/js/JsProtectedNames.java#80

**Comment by rluble** [comment]
That is the mechanism GWT uses to exclude names in the namers. And don't forget that static fields are emitted on the global scope. In any case safer is better.

**Comment by ibaca** [comment]
@rluble renamed to firefox.txt and added "u2f" and "U2F" as a protected name. I have used the "globals.html" but it adds many changes and removed much more entries that it adds. Also, there are small differences if you open it in http and https, for example, "u2f" it is only visible in https. So I think that updating those globals it is better in its own change. This is an actual problem with a client, and "u2f" seems to be some kind of secured protected name in Firefox. Chrome also have it defined, but the GWT iframe overrides it without any problem. So the problem is not that you lose access to "u2f" (this happens in chrome) is that the GWT app doesn't work.

**Comment by tbroyer** [comment]
Better with the xref :wink: https://gwt-review.googlesource.com/c/gwt/+/20920

**Comment by niloc132** [comment]
I think we should avoid hiding hiding/overriding browser-supplied names as a general rule, at least for SSO-linked applications if nothing else.

**Comment by rluble** [comment]
>  I have used the "globals.html" but it adds many changes and removed much more entries that it adds.
I didn't mean to replace them, just add the ones that are missing. The firefox.txt should be cummulative.

**Comment by varmentano** [comment]
When could we expect a release with this fix?

With the latest version of Firefox (67) this has become a serious issue.  I suggest a patch release to address this.

**Comment by shtief** [comment]
Hi, you can also use this in your GWT XML config:

`<set-configuration-property name="js.identifier.blacklist" value="u2f" />`

This is only a workaround that the u2f will not be used when obfuscating.

**Comment by varmentano** [comment]
Excellent, I didn't realize there was a workaround.  I will try this, thanks.
