### ISSUE TITLE
Java9 support for GWT 2.7

### ISSUE THREAD

**Issue by irachita** [gwtproject/gwt#9620]
**GWT version: 2.7** 
**Java version: 9** 

Hi,

I have a legacy application developed with GWT 2.7. Running the application with Tomcat + Java 9 fails directly from the login (the application was compiled with Java7). Also compiling the code with Java 9 doesn't work.
Will there be any official support for GWT2.7 with Java 9?

Thank you

**Comment by jnehlmeier** [comment]
GWT 2.7 class files in `gwt-servlet.jar`, `gwt-servlet-deps.jar` and `requestfactory-server.jar` (the only GWT jars you ever deploy on a server) target Java 6 and it should run on server side with Java 9. 

What is the concrete issue?

**Comment by tbroyer** [comment]
> Will there be any official support for GWT2.7 with Java 9?

No. GWT 2.7 is EOL, and has been as soon as 2.8.0 was released. You'll have to upgrade to GWT 2.8.2 (or 2.9 when it's released).

That being said, I don't think there has been changes on the server-side code related to Java 9 (only to the GWT compiler).
