### ISSUE TITLE
Jsinterop: How to get function's context (this) in @JsMethod or @JsFunction?

### ISSUE THREAD

**Issue by stockiNail** [gwtproject/gwt#9631]
**GWT version: 2.8.2** 

I'm going to port my GWT wrapper (based on JSNI) to JSinterop (mainly because JSNI could be deprecated in near future even if it's working perfectly for me!).

I haven't found any way to get the function's context ("`this`" javascript) inside a @JsMethod or JsFunction. 
Any trick?

**Comment by tbroyer** [comment]
I think this is one of the few places where JSNI is still needed/required.

I also don't think it'll be fixed, as AFAICT it's regarded as bad API design in JS, as it prevents using fat-arrow functions (whose `this` is different from regular functions).

@gkdn should be able to confirm this.

I would do it that way:
```java
@JsOverlay
public native void someMethod(SomeJsFunction handler) /*-{
  this.someMethod(function() {
    handler.@SomeJsFunction::handle(*)(this);
  });
}-*/;
```

That way, if/when the JS API is modified to pass the `this` as an argument, you can rewrite this to
```java
@JsMethod
public native void someMethod(SomeJsFunction handler);
```

**Comment by niloc132** [comment]
This arguably could be added to the jsinterop-base `Js` type, as was done with some other confusing-to-do-in-jsinterop things like `debugger`, `arguments`, `undefined`, `typeof (and I'm also proposing `throw` once I have tests running in a consistent way through bazel):

```
  @JsProperty(namespace = "<window>", name = "this")
  public static native Object thisRef();
```

**Comment by stockiNail** [comment]
Thank you @tbroyer 

I knew that solution but honestly I was thinking that the main goal of JSInterop was to remove Javascript embedded code from Java one.
Furthermore, seeing that in GWT project JSNI page:

**(INFO: For new implementations use the future-proof JsInterop instead. JSNI will be removed with GWT 3.)** 

If I'm understanding well the sentence, your workaround (written above) to use JSNI won't work anymore in GWT 3.

**Comment by stockiNail** [comment]
@niloc132 sounds good.

**Comment by tbroyer** [comment]
> Furthermore, seeing that in GWT project JSNI page:
> 
> **(INFO: For new implementations use the future-proof JsInterop instead. JSNI will be removed with GWT 3.)**
> 
> If I'm understanding well the sentence, your workaround (written above) to use JSNI won't work anymore in GWT 3.

That's true, though there will still be a way to "put JS into your Java" in GWT 3 (if only to make jsinterop-base possible; see https://github.com/google/jsinterop-base/blob/master/java/jsinterop/base/Js.native.js for an –incomplete– example). This "almost JSNI equivalent" will be discouraged though, unless absolutely required.

Colin's proposal will likely not work though, as the `this` in the method (in the JsFunction implementation), whether Java or JS, will be the JsFunction implementing class (see https://github.com/gwtproject/gwt/blob/f031aba1e5aff65143005de841a491b42fe1031a/dev/core/super/com/google/gwt/dev/jjs/intrinsic/com/google/gwt/lang/Runtime.java#L162-L169)

**Comment by niloc132** [comment]
Yep, @tbroyer is right, I didn't think that through... Technically it will give you a `this` literal in JS, but just not the one you are expecting to find (similar to how Js.arguments() might not have the actual arguments passed to a function if the compiler manages to optimize one or more out at runtime).

**Comment by stockiNail** [comment]
@tbroyer I tested using my class (instead of Js of JSInterop base) and in fact it doesn't work.

**Comment by stockiNail** [comment]
@tbroyer nevertheless this missing feature is in my opinion a big constraint for JSinterop adoption.

**Comment by niloc132** [comment]
I'm not sure I'd consider it missing, so much as encouragement to not port straight JS, but migrate it to Java code that can be handled more consistently (and reasoned about more easily).

**Comment by tbroyer** [comment]
Maybe `@JsFunction` could be enhanced to automatically _remap_ `this` to the first argument of the method, basically changing the `makeLambdaFunction` in this case to:
```diff
- var lambda = function() { return samMethod.apply(lambda, arguments); }
+ var lambda = function() { return samMethod.apply(lambda, [this].concat(arguments)); }
  ctor.apply(lambda, ctorArguments);
  return lambda;
```
using, e.g.
```java
@JsFunction(passThisAsFirstArgument = true)
interface TooltipOnBeforeTitle {
  void onBeforeTitle(Tooltip tooltip, TooltipItem[] items, Object data);
}
```
(I took the first example from Chart.JS that I saw explicitly documented as to what would be the `this`; I notice that in your wrapper you're not currently using the `this` for this callback)

But keep in mind that this would have to be done in both GWT 2 and J2Cl (for GWT 3), and it opens other questions (e.g. what would it mean for an API written in Java and exported to JS through JsInterop: would the first argument be remapped as the `this` of the JS function call?)

I'd still posit that it is bad API design for the `this` value to only be accessible through the `this` keyword (e.g. event handlers in the DOM give you access to the same value as the `this` through the `Event.target` of the event passed as argument to the callback; and AFAICT new JS APIs don't make the same mistakes as `JSON.stringify` and `JSON.parse`).
YMMV (and it's likely not the place to have this discussion)

Also, AFAIK, JsInterop is not meant to be able to interact with any kind of JS API; it was originally tailored to work with Closure-style JS.
There are things that don't map to Java (such as a _changing_ `this` value, as in Chart.JS callbacks or `JSON` _replacer_/_reviver_) and for which _mappers_ are (currently) required (you could for example inject a JS to easily wrap your `@JsFunction` into JS functions that would do this `this` _remapping_, and call it through JsInterop; or you could use JSNI/native.js).
And keep in mind that JsInterop is _low-level_, JS APIs mapped to Java through JsInterop might not be easy to use, and possibly need to be wrapped into Java-friendly higher-level APIs.

**Comment by stockiNail** [comment]
> (I took the first example from Chart.JS that I saw explicitly documented as to what would be the this; I notice that in your wrapper you're not currently using the this for this callback)

yes not all callbacks needs this but, if you see the implementation, to call a this interface I have a JavaScriptObject which is wrapping the CHART.JS callback, calling the the implemented one. This is done by JSNI and using `this` I'm able to provide the right parameters to the interface. 
A good example where I'm using `this` is [controllers](https://github.com/pepstock-org/Charba/tree/master/src/org/pepstock/charba/client/controllers) package.

> But keep in mind that this would have to be done in both GWT 2 and J2Cl (for GWT 3), and it opens other questions (e.g. what would it mean for an API written in Java and exported to JS through JsInterop: would the first argument be remapped as the this of the JS function call?)

In my opinion yes, because this is what the developer needs, specifying `passThisAsFirstArgument = true`.
The default must be false, of course.

> I'd still posit that it is bad API design for the this value to only be accessible through the this keyword (e.g. event handlers in the DOM give you access to the same value as the this through the Event.target of the event passed as argument to the callback; and AFAICT new JS APIs don't make the same mistakes as JSON.stringify and JSON.parse).
> YMMV (and it's likely not the place to have this discussion)
> 

FULLY AGREE!!! That's javascript and that's why I'm using GWT for years! But the world is not perfect, you know.

> Also, AFAIK, JsInterop is not meant to be able to interact with any kind of JS API; it was originally tailored to work with Closure-style JS.

In my opinion, that's  a limitation. I don't think we could assume that all JS code is working with Closure-style JS. This is why I love JSNI where I can do more or less everything.

I really appreciated your reply! THANK YOU!

**Comment by stockiNail** [comment]
Let me try to recap.

Waiting for GWT 3, I should use JSNI to catch JS `this`. Maybe it could be helpful to know if what @tbroyer suggested could be in same way implemented ootb (enhancement?). I mean

```java
@JsFunction(passThisAsFirstArgument = true)
```
Have I understood correctly?

**Comment by stockiNail** [comment]
@tbroyer waiting for some new implementations, I want to share that I could have found a workaround, without using JSNI.

First of all, I have created a Java script (mapped by JSTYPE native) which is returning a object with 2 properties:
```javascript
function JsFactory() {};
JsFactory.newCallbackProxy = function() {
   	var obj = new Object();
   	obj.callback = null;
   	obj.proxy = function() {
   		console.log(this);
   		console.log(Array.prototype.slice.call(arguments));
	    if (obj.callback != null && typeof obj.callback === 'function'){
			var args = Array.of(this).concat(Array.prototype.slice.call(arguments));
			var result = obj.callback.apply(this, args);
			if (result === null){
				console.log("null");
			} else if (result === undefined){
				console.log("undefined");
			} else {
				console.log(result);
				return result;
			}
   		} else {
   			console.log("No caller");
   		}
	};
  	return obj;
}
```

This java script code is injecting by a text resource. Of course some configurations are missing (like defining the property proxy immutable) and it could be improved.

From java side, I have a JStype native:

```java
@JsType(isNative = true, name = "JsFactory", namespace = JsPackage.GLOBAL)
public final class JsFactory {

	public static native CallbackProxy newCallbackProxy();
}
```

and a callback proxy:

```java
@JsType(isNative = true, namespace = JsPackage.GLOBAL, name = "Object")
public class CallbackProxy {

	@JsFunction
	public interface Proxy {
	    void call();
	}
	
	@JsProperty
	public native Proxy getProxy();
	
	@JsProperty
	public native Object getCallback();

	@JsProperty
	public native void setCallback(Object callback);
	
}
```

Every time I have to set a callback, I create a `CallbackProxy`, I set my JSFunction callback to the proxy by `setCallback(Object callback)` and then I set the `Proxy` to JS library.

The callback will always have JS `this` as first argument.

```java
@JsFunction
public interface VoidCallback {
    void call(Object context, int val1);
}
	
@JsFunction
public interface ResultCallback {
    Object call(Object context, int val1, int val2);
}
```

**Comment by tbroyer** [comment]
Yup, this is exactly what I suggested [above](https://github.com/gwtproject/gwt/issues/9631#issuecomment-419158809):
> you could for example inject a JS to easily wrap your `@JsFunction` into JS functions that would do this `this` _remapping_, and call it through JsInterop

**Comment by stockiNail** [comment]
Ops.... I had not grasped your suggestion... But at least this code could be helpful to anyone else needs, as starting point to address this topic.
