### ISSUE TITLE
Sub-optimal performance in com.google.gwt.dom.client.DOMImplMozilla.java

### ISSUE THREAD

**Issue by chocoboSan** [gwtproject/gwt#9644]
**GWT version: 2.8.2** 
**Browser (with version): Firefox 63.0.3**
**Operating System: Windows 10**

---

##### Description

When calling extensively the method getGeckoVersion(), called by many of the DOMImplMozilla methods, the regex is called too many times and causes a hefty performance drop.

The browser version is not bound to change after each call, so why not keeping track of its version once it has been called already? 

##### Steps to reproduce

Call many times getScrollLeft , and the top CPU usage method will be getGeckoVersion().

##### Known workarounds

Override at compilation time the class by your own implementation. This is sub-optimal as it would hide future changes to the DOMImpl in the next GWT versions. 

##### Eventual patch 

We made our own quick workaround for now , and here is the simple code logic behind (saves for our use case 20% of total compute time) : 

    private static boolean isGecko = true;

    private static int geckoVersion = -1;
    
    private static int getGeckoVersion() {
        // do we know yet if this is a Gecko browser
        if (!isGecko)
        {
            return -1;
        }
        // have we never done the native method 
        if (geckoVersion == -1)
        {
            geckoVersion = getNativeGeckoVersion();
            if (geckoVersion < 0)
            {
                // store that this is not a gecko, it will skip the -1 test condition
                isGecko = false;
            }
        }
        return geckoVersion;
    }

    /**
     *  This is the classic native call from GWT
     *  @return the gecko version if found, -1 otherwise
     */ 
    private static native int getNativeGeckoVersion() 
    /*-{
        var result = /rv:([0-9]+)\.([0-9]+)(\.([0-9]+))?.*?/.exec(navigator.userAgent.toLowerCase());
        if (result && result.length >= 3) {
          var version = (parseInt(result[1]) * 1000000) + (parseInt(result[2]) * 1000) +
            parseInt(result.length >= 5 && !isNaN(result[4]) ? result[4] : 0);
          return version;
        }
        return -1; // not gecko
    }-*/;

**Comment by niloc132** [comment]
Thanks for the report - I believe we've already entirely removed this version checking code from the updated version of this module, which is undergoing development at https://github.com/jnehlmeier/gwt-dom. 

That said, I think this looks like a good change to make, caching the version like this. Would you make a patch at http://gwt-review.googlesource.com/ to get it added to the next version of gwt?

**Comment by chocoboSan** [comment]
Thanks for the feedback. I'll start taking a look at all those WIP reworked modules for GWT3 as well. 
For tracking purposes, the change is pushed, id 21460.

BR,

**Comment by jnehlmeier** [comment]
https://gwt-review.googlesource.com/c/gwt/+/21460
