### ISSUE TITLE
Dropdown button menu in celltable header for filtering 

### ISSUE THREAD

**Issue by cRUSHER-HLG** [gwtproject/gwt#9645]
Hello guys,
I want to ask if someone can say/help me to tell me how do i need to implement a dropdown menu button into the celltable header. The dropdown menu button will contain a textbox who you can search and at the bottom the filtering option for the given column. With uibinder it dont works for me so i need todo it programmaticaly.
I hope that you can give me a answer how i need todo it or give me a way how do i need to implement it.
Good Regards,
cRUSHER

**Comment by niloc132** [comment]
This is not the right place to ask questions on how to achieve something with this toolkit, but is for reporting bugs, requesting features etc. Please consider StackOverflow (with the tag "gwt"), the gwt mailing list https://groups.google.com/forum/#!forum/google-web-toolkit), or some gwt-related chat (https://gitter.im/gwtproject/gwt is fairly popular these days, the ##gwt channel on freenode still exists too, but isn't used much)
