### ISSUE TITLE
Add Java11 sourceLevel support to the compiler

### ISSUE THREAD

**Issue by axls** [gwtproject/gwt#9649]
This issue is targeted only to adding new sourceLevel `11` to the copiler and updating related dependencies. For new API emulation for Java 9/10/11 see #9547.

I'm working on the patch for the issue.

**Comment by axls** [comment]
Patch to review https://gwt-review.googlesource.com/c/gwt/+/21540.

**Comment by tlamr** [comment]
jdt 4.11 is out https://github.com/eclipse/eclipse.jdt/releases

**Comment by axls** [comment]
Patch had been updated with latest versions of JDT and ASM.

**Comment by axls** [comment]
Fixed in 205b88a4d88cc0c23b2cd0df681a18d114443a7c (hubot missed the commit).

**Comment by mauriciovalli** [comment]
I understand that the jetty version 9.2.14.v20151106 does not support ASM7. 
What version of jetty do you use with these changes?

**Comment by jnehlmeier** [comment]
@mauriciovalli This is just the JDT + ASM update for the GWT compiler and does not have any impact on bundled jetty. You also never deploy `gwt-user.jar` and `gwt-dev.jar` as part of your server side `*.war` file. 

However the bundled Jetty does not support Java 9 `module-info.class` files. If you have server side libraries that contain such files you should use Jetty 9.4.x (which also requires Java 8 as a minimum to start Jetty)
