### ISSUE TITLE
JsUtils.stringFromArrayBuffer gives "Maximum call stack size exceeded"

### ISSUE THREAD

**Issue by TMTHY** [gwtproject/gwt#9657]
**GWT version:**  ALL 
**Browser (with version):** Safari 11.0.3
**Operating System:** MacOS
---

##### Description
JsUtils.stringFromArrayBuffer fails with "Maximum call stack size exceeded" when input buffer is larger then 65535 bytes.

##### Steps to reproduce
Call the function with large enough buffer.

**Comment by niloc132** [comment]
Thanks for the report - can you try this as a non-JSNI way to solve that?
```
  public static String stringFromArrayBuffer(ArrayBuffer buf) {
    return new String(Js.uncheckedCast(Int8ArrayNative.create(buf)), StandardCharsets.UTF_8);
  }
```

As part of updating the typedarrays package to work in J2CL I wrote this, but didn't port it back to GWT 2. If it solves this issue for you, I'll see about doing so.

**Comment by TMTHY** [comment]
Your solution works. 

When I faced the problem, I solved it for myself using simple workaround, replacing GWT stringFromArrayBuffer:
```
private native String stringFromArrayBuffer(ArrayBuffer buf) /*-{
        var chunkSize = 10240;
        var i8 = new Uint8Array(buf);
        var result = [];
        for (var i=0; i < buf.byteLength; i+=chunkSize) {
            result.push(String.fromCharCode.apply(null, i8.subarray(i, i + chunkSize)));
        }
        return result.join("");
    }-*/;
```

But I think that non-JSNI is better, and should be faster

**Comment by niloc132** [comment]
The non-JSNI solution will do the loop still, inside of the String constructor, to check each byte. This is actually semantically different from the old stringFromArrayBuffer code, with the advantage that it correctly handles utf-8. I have some new tests which can be used to confirm correctness with regard to utf-8, will also port those back too, but be aware that this is another chance from the code you've used in the past.
