### ISSUE TITLE
Security Vulnerability Detected in GWT Library

### ISSUE THREAD

**Issue by hrishikeshgjoshi** [gwtproject/gwt#9659]
[dependency-check-report.zip](https://github.com/gwtproject/gwt/files/3062789/dependency-check-report.zip)

Security Vulnerability Detected in GWT Library

GWT 2.8.2:
All
All

---

##### Description
Security Vulnerability Detected in gwt-dev.jar & gwt-servlet.jar are reported by Dependency checker tool
https://jeremylong.github.io/DependencyCheck/

Below are the details -
1. Gwt-dev.jar - 
               1.1 Vulnerable version of jetty library(current version-- 9.2.14, available ) 
               1.2 Vulnerable version of commons-collections(current version - 3.2.1)
               1.3 Vulnerable version of org.apache.httpcomponents:httpclient(current version - 4.3.1)

2. Gwt-servlet.jar             
               1.1 Vulnerable version of Google Protobuf(current version - 2.5.0, available version - 3.4.0)

Refer attached report

##### Steps to reproduce
Refer instruction from following web site.
https://jeremylong.github.io/DependencyCheck/dependency-check-ant/index.html

##### Links to further discussions
https://groups.google.com/d/msg/google-web-toolkit/3bza7qEVWg8/ASgXB1GCAgAJ

**Comment by tbroyer** [comment]
Those can all be flagged as false positives.

 * gwt-dev is only used during development or at build-time
 * protocol buffer in gwt-servlet is never actually used for serialization, it's an internal dependency of sourcemaps and streaminghtmlparser (used for SafeHtml)

**Comment by hrishikeshgjoshi** [comment]
Thank you for confirming this.

**Comment by hrishikeshgjoshi** [comment]
> 
> 
> Those can all be flagged as false positives.
> 
>     * gwt-dev is only used during development or at build-time
> 
>     * protocol buffer in gwt-servlet is never actually used for serialization, it's an internal dependency of sourcemaps and streaminghtmlparser (used for SafeHtml)

Is it possible to update these libraries if someone contributes to GWT project or there are technical issues for the updates?
