### ISSUE TITLE
Impossible to build  GWT after 'Update ASM & JDT for Java11 sourceLevel support'

### ISSUE THREAD

**Issue by dma1979** [gwtproject/gwt#9662]
it is impossible to build GWY on JDK 8 after update which include bug #9649 
Class not found:
 com.google.errorprone.ErrorProneAntCompilerAdapter

**Comment by tbroyer** [comment]
There's no apparent link between the error message and the linked change, and as you can see at http://build.gwtproject.org/job/gwt/ the project builds, so it's on your side.

Which commit did you update from? ErrorProne was added 2 years ago in https://github.com/gwtproject/gwt/commit/e2fe2c658959f9e020cda695c18e18889d1a5d47. Did you update your `GWT_TOOLS` repository (https://github.com/gwtproject/tools) to bring in the new/updated dependencies and tools?

**Comment by dma1979** [comment]
Hello, Thomas! Thank you for your quick answer.I was acccidently using https://github.com/vaadin/gwt-tools Now it works. Sincerely, Dima.16.05.2019, 10:41, "Thomas Broyer" <notifications@github.com>:There's no apparent link between the error message and the linked change, and as you can see at http://build.gwtproject.org/job/gwt/ the project builds, so it's on your side.
Which commit did you update from? ErrorProne was added 2 years ago in e2fe2c6. Did you update your GWT_TOOLS repository (https://github.com/gwtproject/tools) to bring in the new/updated dependencies and tools?

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.
С наилучшими пожеланиями, Димитрий.
