### ISSUE TITLE
gwt-dev.jar - uses jdk internal APIs & its support with Java11

### ISSUE THREAD

**Issue by PriyaKolekar** [gwtproject/gwt#9677]
Hi All,

gwt-dev.jar is being used by one of our application. While scanning jar for supporting Java11, it is found that below classes present in jar having some issues -
1. com.google.gwt.dev.url.CloseableJarHandler uses sun.net.www.protocol.jar.Handler (JDK internal API (java.base))
2. org.apache.tools.ant.taskdefs.email.UUMailer uses sun.misc.UUEncoder (JDK internal API (JDK removed internal API)).

Any idea what is significance of these classes & where they are used?Also, are there any plans to support this jar with Java11.

**Comment by jnehlmeier** [comment]
> 1. com.google.gwt.dev.url.CloseableJarHandler uses sun.net.www.protocol.jar.Handler (JDK internal API (java.base))

While I agree that it should be rewritten you can still use it with Java 11. Actually the Handler class still exists in Java 13.

> 2. org.apache.tools.ant.taskdefs.email.UUMailer uses sun.misc.UUEncoder (JDK internal API (JDK removed internal API)).

That ANT task is not used by GWT itself. gwt-dev.jar has bundled ANT 1.6.5 which would need to be updated (or removed completely).

**Comment by PriyaKolekar** [comment]
Thank you very much for response!. Are there any plans to remove bundling of ANT 1.6.5?
Or cal I contribute & remove it?

**Comment by niloc132** [comment]
ClosableJarHandler has been removed - https://gwt-review.googlesource.com/c/gwt/+/22360

**Comment by niloc132** [comment]
Closing in favor of #9690, review is up to change this https://gwt-review.googlesource.com/c/gwt/+/22600.
