### ISSUE TITLE
Upgrade to HtmlUnit 2.39.0

### ISSUE THREAD

**Issue by foal** [gwtproject/gwt#9684]
**GWT version: 2.8.2** 
**Browser (with version): NA** 
**Operating System: Windows 10** 

---

##### Description
HtmlUnit (2.19) used in GWT 2.8.2 is 2-year-olds and doesn't reflect the current capabilities of modern browsers.

##### Steps to reproduce
Try to run any test with the JS Intl package.

##### Known workarounds
Use runStyle manual, because the Selenium way does not work (see https://github.com/gwtproject/gwt/issues/7765)

**Comment by niloc132** [comment]
See https://github.com/gwtproject/gwt/issues/9720#issuecomment-921251414 for a patch that will bring us up to latest htmlunit (at least 2.53.0) and jetty 9.4.x.
