### ISSUE TITLE
[gwt-dev] Librairies with same package name

### ISSUE THREAD

**Issue by Y09B** [gwtproject/gwt#9685]
Hi,
This is my first post on github, please be indulgent.

Within my project, I use the library commons-digester-1.8

Following a need, I now use the library gwt-dev-2.3.0

When launching the application I get this error : 

![erreur](https://user-images.githubusercontent.com/64909959/81187431-54ee2580-8fb4-11ea-8487-a0a015b381ec.PNG)

It turns out that the two libraries have the same class in the same package with the same method :

![img](https://user-images.githubusercontent.com/64909959/81187257-16f10180-8fb4-11ea-9825-e7c4ae9953ab.png)

Package : org.apache.commons.digester.xmlrules
Class : DigesterLoader
Method : createDigester

Since the use of gwt-dev, it is the method of this library which is called.
I tried to use newer versions of gwt-dev but the environment makes it not possible

How can I fix it?

Thanks for your help :)

**Comment by niloc132** [comment]
The gwt-dev.jar should not be on your server classpath - it is only used to compile your application. The same is true for gwt-user.jar. Only gwt-servlet.jar (and possibly requestfactory-server.jar) should end up on your server classpath, the others are intended only to be present when compiling, either to do the work of compiling, or to provide the compiler the classes you need.
