### ISSUE TITLE
tanh(x) wrong for x above around 360

### ISSUE THREAD

**Issue by murkle** [gwtproject/gwt#9687]
Tested in GWT 2.8.2

Actual
Math.tanh(400) gives NaN

Expected
Math.tanh(400) should give 1

The problem is here
https://github.com/gwtproject/gwt/blob/master/user/super/com/google/gwt/emul/java/lang/Math.java
```
  public static double tanh(double x) {
    if (x == 0.0) {
      return x;
    } else if (Double.isInfinite(x)) {
      return signum(x);
    } else {
      double e2x = exp(2 * x);
      return (e2x - 1) / (e2x + 1);
    }
  }
```

So an additional check is needed for if x > 350 and return 1 in that case.

Note that Internet Explorer doesn't have Math.tanh() so that should be added as a comment to explain why the native method isn't used (and maybe one day this method can be changed to use the native method.)
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Math/tanh

**Comment by rluble** [comment]
Actually the proper solution to check whether e2x isInfinite

```java
  public static double tanh(double x) {
    if (x == 0.0) {
      return x;
    } else if (Double.isInfinite(x)) {
      return signum(x);
    } else {
      double e2x = exp(2 * x);
      if (Double.isInfinite(e2x)) {
        return 1;
     }
      return (e2x - 1) / (e2x + 1);
    }
  }
```

**Comment by niloc132** [comment]
https://gwt-review.googlesource.com/c/gwt/+/22540
