### ISSUE TITLE
Deploy gwt-elemental:2.9.0 to the maven central repo

### ISSUE THREAD

**Issue by robinroos** [gwtproject/gwt#9689]
gwt-2.9.0 has been deployed to the maven central repo.

The pom references gwt-elemental, but gwt-elemental 2.9.0 is absent from maven central repo (2.9.0-RC1 is its most recent artefact version).

This causes issues when running "man clean site" over projects which depend upon gwt-2.9.0, e.g.:

> Could not find artifact com.google.gwt:gwt-elemental:pom:2.9.0 in central (https://repo.maven.apache.org/maven2)

**Comment by niloc132** [comment]
Confirmed, it doesn't seem to be there according to https://search.maven.org/search?q=a:gwt-elemental - though I'm confused as to how the build passed the sanity checks on https://search.maven.org/artifact/com.google.gwt/gwt/2.9.0/pom if it was missing.

Julien, could you confirm from the sonatype release that the artifact was deployed and maybe got lost on its way to central? Either we need to redeploy just that one artifact, or reach out to central/sonatype support and see if just those jars failed to sync? Either way though, seems like a bug in the central sync to me...?

**Comment by jDramaix** [comment]
I think I simply forgot to regenerate the elemental jar when I built the final release. I just did it and pushed it to maven central. Sorry for the inconvenience.

I'm wondering why we didn;t catch that during the test of the release. We should have a test testing the release with maven.

**Comment by tbroyer** [comment]
Or maybe elemental wasn't generated to begin with: https://github.com/gwtproject/gwt/blob/178c60a224e9ff8b9e05904e099a91c0e12f107e/maven/lib-gwt.sh#L79
(IIRC it depends on external tools and won't fail if these tools aren't there)

**Comment by niloc132** [comment]
@tbroyer in that case, wouldnt the "close" button in sonatype have said "hey, you are referencing a non-existent jar, we don't allow that" when it did its validation steps?

**Comment by jDramaix** [comment]
This is what happened. I forgot to call the elemental goal when I invoked
ant to generate the official 2.9.0 release.

**Comment by niloc132** [comment]
Done, see https://search.maven.org/search?q=a:gwt-elemental.
