### ISSUE TITLE
Image is pasting twice in gwtmaterialdesign editor with chrome 83.0.4103.116

### ISSUE THREAD

**Issue by rinkugulia466** [gwtproject/gwt#9698]
**GWT version:** 
**Browser (with version):** 
**Operating System:** 

GWT version:2.8.2
Chrome:- Version 83.0.4103.116 (Official Build) (64-bit)
Operating system : centos 7

---

##### Description

In case of copy and pasting a image in editor, image is pasting twice.
As per my analysis, it is happening with latest chrome version 83.0.4103.116
For older chrome version 80.0.  it is working fine

##### Steps to reproduce

copy any image(cntrl+shift+print)
and paste it

![image](https://user-images.githubusercontent.com/68102304/87130462-8e8f2580-c2b0-11ea-8566-280d485abea6.png)

**Comment by tbroyer** [comment]
This is likely a bug in the component itself: https://github.com/GwtMaterialDesign/gwt-material-addins
(which AFAICT is actually only a GWT wrapper around a pure-JS component: https://github.com/Cerealkillerway/materialNote, so the bug might actually be there).

Please comment back here in case I'm wrong, so we can reopen this issue.
