### ISSUE TITLE
java.math.BigDecimal can't be initialized by BigDecimal(char[] in, int offset, int len)

### ISSUE THREAD

**Issue by harbouryan** [gwtproject/gwt#9700]
**GWT version: 2.9.0
**Browser (with version): Google Chrome 83.0.4103.116
**Operating System: Windows 7

---

##### Description

     when a double value added to another double value using by java.math.BigDecimal, JS can't initialized BigDecimal instance by BigDecimal(char[] in, int offset, int len).

     The Java source code are following:
		public static double add(double v1, double v2) {
			BigDecimal b1 = new BigDecimal(Double.toString(v1));
			BigDecimal b2 = new BigDecimal(Double.toString(v2));
		
			return b1.add(b2).doubleValue();
		}

     The compiled JS are following:
		function add_31(v1, v2){
		  var b1, b2;
		  b1 = new BigDecimal_0('' + v1);
		  b2 = new BigDecimal_0('' + v2);
		  return $doubleValue(__parseAndValidateDouble($toString_4($add_10(b1, b2).internalBigDecimal)));
		}

		function BigDecimal_0(val){
		  $clinit_BigDecimal();
		  try {
		    __parseAndValidateDouble(val);
		    this.internalBigDecimal = new InternalBigDecimal_0(val);
		  }
		   catch ($e0) {
		    $e0 = toJava($e0);
		    if (instanceOf($e0, 40)) {
		      throw toJs(new NumberFormatException_0("Value of BigDecimal isn't a right value."));
		    }
		     else 
		      throw toJs($e0);
		  }
		}

		function InternalBigDecimal_0(inchars){
		  $clinit_InternalBigDecimal();
		  this.jsObj = $create_0(inchars, 0, inchars.length);
		}

		function $create_0(inchars, offset, length_0){
		  return new $wnd.BigDecimal(inchars, offset, length_0);
		}

       JS is crashed by "$create_0(inchars, 0, inchars.length);" .
       The problem also happened by subtract/multiply/divide operations.

**Comment by tbroyer** [comment]
There's no such thing as `InternalBigDecimal` or even `$wnd.BigDecimal` in GWT's emulation: https://github.com/gwtproject/gwt/blob/2.9.0/user/super/com/google/gwt/emul/java/math/BigDecimal.java

Check your dependencies, it looks like one of them has its own emulation shadowing the one from GWT.

**Comment by harbouryan** [comment]
Thanks,very much.
I found a jar file called "gwt-math-2.1.jar" which has been used, it is not compatible with GWT 2.9(include 2.7 and later), and something of GWT 2.9 are replaced by it . The problem is fixed after remove it.
