### ISSUE TITLE
ProcessBuilder for GWT-compiler throws error=206 on large CPs

### ISSUE THREAD

**Issue by sstamm** [gwtproject/gwt#9701]
**GWT version:** 2.9.0
**Browser (with version):** -
**Operating System:** Windows

---

##### Description

Windows is limited by the size of the path for process-arguments

[INFO] java.io.IOException: Cannot run program "C:\Program Files\AdoptOpenJDK\jdk-8.0.262.10-openj9\jre\bin\java": CreateProcess error=206, Der Dateiname oder die Erweiterung ist zu lang
[INFO]  at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
[INFO]  at com.google.gwt.dev.ExternalPermutationWorkerFactory.launchExternalWorker(ExternalPermutationWorkerFactory.java:282)

##### Known workarounds

Solution: use CLASSPATH-enviroment variable instead:
[https://github.com/sstamm/gwt/commit/408d13bcbafc4fbe6910f66182e522d943165c92](https://github.com/sstamm/gwt/commit/408d13bcbafc4fbe6910f66182e522d943165c92)

**Comment by niloc132** [comment]
Thanks for the report! Would you be able to sign the CLA and submit this to https://gwt-review.googlesource.com/ to be merged?

**Comment by sstamm** [comment]
I'm challenging the following error:

C:\GIT\gwt\gwt (master -> origin/HEAD:refs/for/master)
λ git push origin Master:refs/for/Master
remote: PERMISSION_DENIED: The caller does not have permission
remote: [type.googleapis.com/google.rpc.LocalizedMessage]
remote: locale: "en-US"
remote: message: "No Contributor Agreement on file for user Sebastian ... (id=11550)"

Is there any further documentation?  (.gitcoockies files exists)

**Comment by tbroyer** [comment]
Apparently you didn't sign the CLA: http://www.gwtproject.org/makinggwtbetter.html#clas

**Comment by sstamm** [comment]
That was easy :man_facepalming:
https://gwt-review.googlesource.com/c/gwt/+/22700

**Comment by niloc132** [comment]
Merged https://github.com/gwtproject/gwt/commit/5ae20794ca38d3f79a5bdfa94d1f96f6f0c219c2
