### ISSUE TITLE
GWT compiler optimization prunes useful JsInterop code

### ISSUE THREAD

**Issue by raftAtGit** [gwtproject/gwt#9721]
**GWT version: 2.9.0** 

---

##### Description

I have a `JsInterop` interface which is annotated with `@JsType` and acting as a bridge with other native JavaScript code. Like  below:
```
@JsType
public interface GuiListener {
  void onMenuItemSelected(String item);
  void onLevelSelected(int level);
   // some other methods 
}
```
It's set by native Javascript code and used to notify native code about certain events. Like below:
```
@JsType
public class Gui {
  private static GuiListener guiListener;

  public static void setGuiListener(GuiListener listener) {
    guiListener = listener;
  }

  @JsIgnore
  public static void postLevelSelected(int level) {
    consoleLog("postLevelSelected: " + level);
    if (guiListener != null)                               // -> 
        guiWidget.guiListener.onLevelSelected(level);      // -> these two lines are pruned
  }

  static native void consoleLog(String message) /*-{
    console.log(message);
  }-*/;

  // some other methods 
}
```

This works fine in development mode but not in production mode. Some digging showed this is caused by GWT compiler pruning the code calling the callback (possibly because noticing it's initially null and never set in GWT code). This happens on all optimization levels (except 0, which means optimization is off)

I believe this is a bug in the optimizer. Since the types are `JsInterop` types, optimizer should not make a decision code is not used and should be pruned.

##### Known workarounds

* Disable optimization

**Comment by rluble** [comment]
See issue #9332

**Comment by raftAtGit** [comment]
I don't think this is duplicate of #9332.

My issue is not the interface or functions of it are pruned, but **the call to the interface functions** are pruned. 

I'm already using `-generateJsInteropExports` option, otherwise native JavaScript code cannot reach GWT code at all.

**Comment by rluble** [comment]
So `GuiListener` is not implemented by a Java class? If there are no Java implementors the `@JsType` interface will not 
 be considered live and the situation you describe will happen.

Non native `@JsType` interfaces are not meant to be implemented by JavaScript classes (because they would lack the markers that are needed to do things like casts and `instanceof`). If you want to define an interface that is implemented by JavaScript classes, you need to use `@JsType(isNative = true)`

**Comment by raftAtGit** [comment]
Thanks. `@JsType(isNative = true)` did the trick
