### ISSUE TITLE
Maven Central maven-metadata.xml missing all versions except 2.9.0

### ISSUE THREAD

**Issue by pedrolamarao** [gwtproject/gwt#9722]
Below is the current full contents for the `gwt-servlet` module on Maven Central.
All versions are missing except 2.9.0.
Our internal mirror has just sync'ed with Maven Central and now all our builds, which strictly require version 2.8.2, are failing.

```xml
<metadata>
<groupId>com.google.gwt</groupId>
<artifactId>gwt-servlet</artifactId>
<versioning>
<latest>2.9.0</latest>
<release>2.9.0</release>
<versions>
<version>2.9.0-RC1</version>
<version>2.9.0</version>
</versions>
<lastUpdated>20200513175310</lastUpdated>
</versioning>
</metadata>
```

**Comment by pedrolamarao** [comment]
Bintray's jcenter seems correct.

**Comment by tbroyer** [comment]
Apparently, all previous versions were going through Sonatype OSSRH "Google Releases" repository, but 2.9.0-RC1 and 2.9.0 went through the "Releases" repo, and that probably trips Nexus, which is the one that generates/maintains the maven-metadata.xml file that eventually gets published to the Central repository.

According to https://maven.apache.org/repository/central-metadata.html#other-issues, I'd suggest opening an issue on Sonatype's issue tracker, explaining how it's breaking your workflow, so they can fix it; but nothing can be done on our side.
Please comment here with the link to the issue you create so we can follow the resolution.

**Comment by pedrolamarao** [comment]
Done: https://issues.sonatype.org/browse/MVNCENTRAL-6499

**Comment by pedrolamarao** [comment]
Closed by Maven Central support team.

**Comment by tbroyer** [comment]
Thanks for the update.

(closed, and fixed!)
