### ISSUE TITLE
Fuck Your Mother for bad Jsonobject implementation

### ISSUE THREAD

**Issue by AmirNorozi1995** [gwtproject/gwt#9723]
Hi and go fuck yourself for bad Jsonobject implementation in all version
working with it is so hard and i will fuck your sisters so fucking hard

**Comment by HoomanDevp** [comment]
**that's Right**
I face with this issue too
wtf is that 
do something wit it

**Comment by jnehlmeier** [comment]
elemental2 provides JsPropertyMap which might give you a better experience. However it requires GWT 2.9+. 

https://github.com/google/elemental2

**Comment by tbroyer** [comment]
BTW, @AmirNorozi1995 and @HoomanDevp, there's no need to be this disrespectful. It looks like you didn't read http://www.gwtproject.org/makinggwtbetter.html#befriendly before writing here.

If you have specific pain points, you're welcome to describe them so we as a community can try to make things better; but [we don't have to](https://docs.github.com/en/github/building-a-strong-community/blocking-a-user-from-your-organization) endure your rudeness.

**Comment by TDesjardins** [comment]
@AmirNorozi1995 Seems that the JsonObject implementation is older than you.

> elemental2 provides JsPropertyMap which might give you a better experience. However it requires GWT 2.9+.
> 
> https://github.com/google/elemental2

@jnehlmeier You can also use JsPropertyMap with GWT 2.8+ with older elemental2 versions.

**Comment by AmirNorozi1995** [comment]
Just fix it and shut up.

**Comment by HoomanDevp** [comment]
@tbroyer its not my job to waste my time to fix this issue and we have to use this bullshit version 2.8 in our project
`obj.put("isviewd",true)` !!!!??
wtf is that?
BTW i dont know u and u dont know me so i cant be your friend #be_professional and do your own job!

**Comment by bpetridean** [comment]
@HoomanDevp 
This is a community driven project, thus it is not @tbroyer job to fix anything. 
Btw, feel free to come up with a PR that fixes it... 

Off topic: 
@AmirNorozit1995 @HoomanDevp you guys studied English with the same teacher, right?...I mean the extensive use of  `fuck` and `wtf` makes it kind'a obvious...

**Comment by dnouls** [comment]
My initial guess was that they are using google translate. For some languages this can lead to unexpected results. But after seeing there additional comments I am not so sure anymore.

**Comment by HoomanDevp** [comment]
@bpetridean 
i dont care about this bullshit i will switch my toolkit #Thymeleaf
_Important INFO:_
your mother is my english teacher and i fuck her everyday instead of learning english you cyka blyat  =))
بیا سرش چغا وت دیاره کس نمک

**Comment by nicolasps** [comment]
Please don't feed the troll
