### ISSUE TITLE
Cannot build GWT according to the README.md (with java 11)

### ISSUE THREAD

**Issue by dcheung2** [gwtproject/gwt#9728]
I am following https://github.com/gwtproject/gwt#building-the-gwt-sdk
but The README.md does not mansion which version of JRE/JDK should be used.

It failed on both java 16 and java 11.

> $ ant clean elemental dist-dev
> Buildfile: /home/dcheung/gwt/gwt/build.xml
> 
> clean:
> 
> elemental:
> 
> user:
> 
> dev:
> 
> buildtools:
> 
> build:
> 
> doctool:
> 
> BUILD FAILED
> /home/dcheung/gwt/gwt/build.xml:75: The following error occurred while executing this line:
> /home/dcheung/gwt/gwt/build.xml:27: The following error occurred while executing this line:
> /home/dcheung/gwt/gwt/build.xml:69: The following error occurred while executing this line:
> /home/dcheung/gwt/gwt/build.xml:27: The following error occurred while executing this line:
> /home/dcheung/gwt/gwt/build.xml:57: The following error occurred while executing this line:
> /home/dcheung/gwt/gwt/build.xml:27: The following error occurred while executing this line:
> /home/dcheung/gwt/gwt/build.xml:108: The following error occurred while executing this line:
> /home/dcheung/gwt/gwt/build_tools/build.xml:16: The following error occurred while executing this line:
> /home/dcheung/gwt/gwt/build_tools/build.xml:10: The following error occurred while executing this line:
> /home/dcheung/gwt/gwt/build_tools/doctool/build.xml:6: The following error occurred while executing this line:
> /home/dcheung/gwt/gwt/common.ant.xml:366: Cannot find /home/dcheung/.sdkman/candidates/java/16-open/../lib/tools.jar; please use a JDK when building doc rather than a JRE.

I read https://github.com/gwtproject/gwt/blob/073679594c6ead7abe501009f8ba31eb390047fc/build_tools/doctool/build.xml#L6
and it explicitly require tools.jar which is removed from JDK https://docs.oracle.com/javase/9/migrate/toc.htm#JSMIG-GUID-A78CC891-701D-4549-AA4E-B8DD90228B4B

If I give it a random JAR, e.g.
`$ ant -Djava.tools.path=$(pwd)/../tools/lib/jsinterop/jsinterop-annotations-2.0.0.jar clean elemental dist-dev`
It will fail somewhere else

>     [mkdir] Created dir: /home/dcheung/gwt/gwt/build/out/build_tools/doctool/bin
> [gwt.javac] Compiling 14 source files to /home/dcheung/gwt/gwt/build/out/build_tools/doctool/bin
> [gwt.javac] An exception has occurred in the compiler (9-internal). Please file a bug against the Java compiler via the Java bug reporting page (http://bugreport.java.com) after checking the Bug Database (http://bugs.java.com) for duplicates. Include your program and the following diagnostic in your report. Thank you.
> [gwt.javac] java.io.UncheckedIOException: java.nio.file.NotDirectoryException: /home/dcheung/.sdkman/candidates/java/16-open/lib/modules
> [gwt.javac]     at com.sun.tools.javac.file.Locations$BootClassPathLocationHandler.lazy(Locations.java:712)
> [gwt.javac]     at com.sun.tools.javac.file.Locations$BootClassPathLocationHandler.isDefault(Locations.java:546)
> [gwt.javac]     at com.sun.tools.javac.file.Locations.isDefaultBootClassPath(Locations.java:126)
> [gwt.javac]     at com.sun.tools.javac.file.BaseFileManager.isDefaultBootClassPath(BaseFileManager.java:204)
> [gwt.javac]     at com.sun.tools.javac.code.ClassFinder.<init>(ClassFinder.java:213)
> [gwt.javac]     at com.sun.tools.javac.code.ClassFinder.instance(ClassFinder.java:177)
> [gwt.javac]     at com.sun.tools.javac.main.JavaCompiler.<init>(JavaCompiler.java:354)
> [gwt.javac]     at com.sun.tools.javac.main.JavaCompiler.instance(JavaCompiler.java:96)
> [gwt.javac]     at com.sun.tools.javac.api.JavacTaskImpl.prepareCompiler(JavacTaskImpl.java:182)
> [gwt.javac]     at com.sun.tools.javac.api.JavacTaskImpl.access$000(JavacTaskImpl.java:69)
> [gwt.javac]     at com.sun.tools.javac.api.JavacTaskImpl$1.call(JavacTaskImpl.java:96)
> [gwt.javac]     at com.sun.tools.javac.api.JavacTaskImpl$1.call(JavacTaskImpl.java:93)
> [gwt.javac]     at com.sun.tools.javac.api.JavacTaskImpl.handleExceptions(JavacTaskImpl.java:128)
> [gwt.javac]     at com.sun.tools.javac.api.JavacTaskImpl.doCall(JavacTaskImpl.java:93)
> [gwt.javac]     at com.sun.tools.javac.api.JavacTaskImpl.call(JavacTaskImpl.java:87)
> 

---------
Environment
Ubuntu 20.04 in Windows 10 WSL
Java 16-open from https://sdkman.io/
(also Java 11.0.10-open from https://sdkman.io/ )
ant 1.10.9 from https://sdkman.io/
tools commit 194772ed94078802d8030136796de344eb1fdbe1
gwt commit 073679594c6ead7abe501009f8ba31eb390047fc

**Comment by dcheung2** [comment]
also the doc is unclear which version of python should be used.  
I guess it is 2.7 for old project like GWT.

**Comment by vjay82** [comment]
Had the same issue with JDK 16 and 8. Worked with AdoptOpenJDK 11 hotspot on Windows (no WSL).

Used the following "java11path.bat" to switch to that:
set PATH=C:\Program Files\AdoptOpenJDK\jdk-11.0.8.10-hotspot\bin;%PATH%
set JDK_HOME=C:\Program Files\AdoptOpenJDK\jdk-11.0.8.10-hotspot
set JRE_HOME=C:\Program Files\AdoptOpenJDK\jdk-11.0.8.10-hotspot
set JAVA_HOME=C:\Program Files\AdoptOpenJDK\jdk-11.0.8.10-hotspot

**Comment by niloc132** [comment]
Python 2.7 is to be used for the elemental, but please note that as of GWT 2.9, elemental is deprecated (every class is now annotated as such), and future releases will omit it entirely.

The build itself definitely is limited to running on Java8 at this time - there are a few changes that need to be made to update this, mostly in the form of porting the custom javadoc tags handling to a form which is compatible with java9+ (unfortunately, due to how that migration was done in the JRE, this will break compatibility for building with Java8 - we can't have it both ways).

**Comment by niloc132** [comment]
Never got a reply back on this, but at this time there are no longer any py scripts in the git repo, and the build works on Java 11, so I'm closing this.
