### ISSUE TITLE
GWT compiler options -XmethodNameDisplayMode stops working correctly in latest Chrome versions (>=93)

### ISSUE THREAD

**Issue by rdeangelis83** [gwtproject/gwt#9735]
**GWT version: 2.9.0** 
**Browser (with version): Chrome 93.0** 
**Operating System: Windows** 

---

##### Description

GWT compiler options -XmethodNameDisplayMode  doesn't works anymore correctly in Chrome >= 93
Currently GWT is using the [fn.displayName](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function/displayName) property to change the display name of functions in the browser. The non-standard fn.displayName support has now been removed in chrome and replaced with a more standardized solution. For more details see: 
- https://chromium.googlesource.com/v8/v8/+/c5cf7db1f2180472bd8df6cf0b55a12389e20096
- https://bit.ly/devtools-function-displayName-removal
- https://bugs.chromium.org/p/v8/issues/detail?id=8742

`var f = function() { /* ... */ }
f.displayName = "super duper function";`

can now be replaced with

`var f = function() { /* ... */ }
Object.defineProperty(f, "name", {value: "super duper function"});`

##### Steps to reproduce

1. Run GWT compiler with `-XmethodNameDisplayMode ABBREVIATED`  option
2. Debug you JS code in Chrome browser 
2. In Chrome DevTools Call Stack the function name will not be replaced with the value assigned with fn.displayName. The  full qualified class and method name will not be displayed.

##### Known workarounds
No know workaround, but following patch from @niloc132 will solve the issue:
https://gist.github.com/niloc132/79683daade7688de0dceb1e99f0e31f0

##### Links to further discussions
https://gitter.im/gwtproject/gwt?at=6128f8081179346966e569e6

**Comment by niloc132** [comment]
https://gwt-review.googlesource.com/c/gwt/+/23580

**Comment by niloc132** [comment]
Fix is merged, will be in the next version of GWT.

**Comment by NorbertSandor** [comment]
> Fix is merged, will be in the next version of GWT.

Do you plan to release a 'maintenance' version in the near future? Thanks.

**Comment by niloc132** [comment]
We're waiting on three reviews, and then should tentatively be able to start the release process for GWT 2.10.

This patch should be able to be applied locally, or even added inside your own project if you happen to depend on gwt-dev directly from your js app.

**Comment by niloc132** [comment]
GWT 2.10 will be released in the next few days, marking this as closed.
