### ISSUE TITLE
Getting method resetTime(Date) from the type CalendarUtil is not visible error in GWT 2.9

### ISSUE THREAD

**Issue by souradeep07** [gwtproject/gwt#9744]
**GWT version: 2.9** 
**Browser (with version): N/A** 
**Operating System: CentOS** 

---

##### Description

Getting the below error during GWT compilation for my project.  

```
[INFO]       70% complete (ETR: 13 seconds)
[INFO]       80% complete (ETR: 8 seconds)
[INFO]       90% complete (ETR: 4 seconds)
[INFO]       100% complete (ETR: 0 seconds)
[INFO]       Compilation completed in 48.59 seconds
[INFO]    Tracing compile failure path for type 'com.google.gwt.user.datepicker.client.DefaultCalendarView'
[INFO]       [ERROR] Errors in 'jar:file:/home/user/.m2/repository/com/google/gwt/gwt-user/2.9.0/gwt-user-2.9.0.jar!/com/google/gwt/user/datepicker/client/DefaultCalendarView.java'
[INFO]          [ERROR] Line 210: The method resetTime(Date) from the type CalendarUtil is not visible
[INFO]       Checked 1 dependencies for errors.
[INFO]    Removing invalidated units
[INFO]    Resolving enclosing classes
```

**Comment by niloc132** [comment]
Could you provide more details about your set? The CalendarUtil.resetTime method did used to be private, but this was changed back in 2013 in https://gwt-review.googlesource.com/c/gwt/+/4630. Is it possible that you might have some other copy of CalendarUtil on your classpath, either from an older version of gwt-user, or from some other dependency you have?

Perhaps share the entire log of your build? This question might be better suited for StackOverflow or the gitter community chat at https://gitter.im/gwtproject/gwt to help hunt down this bug in your build.

**Comment by souradeep07** [comment]
@niloc132 Please find the detailed logs @ https://termbin.com/twnw

Also, Tried printing the detailed dependency tree,  couldn't find any other versions of gwt other than 2.9

**Comment by tbroyer** [comment]
It's not much the presence of another version of GWT than the presence of another `…/com/google/gwt/user/datepicker/client/CalendarUtil.java` file (initially copied from a different version of GWT) in any other JAR.

**Comment by souradeep07** [comment]
@tbroyer Thanks for that. there was an older version of `CalendarUtil` present in the codebase.
