### ISSUE TITLE
GWT 2.9 has dependancies which are not supported in latest Java versions.

### ISSUE THREAD

**Issue by wrbst** [gwtproject/gwt#9750]
**GWT version:**  2.9
**Browser (with version):** Chrome (latest)
**Operating System:** Windows Server 2016

---

##### Description

Hello mates,
Me and my colleagues are bumping our existing project from java 8 to java 16, later to 17 (due yet unsupported libs/plugins, etc.).
And today we hit a problem with the ASM, the lib which comes with GWT 2.9 is version 7.1 (from 2019), which supports up to Java 13 - the latest version is 9.2.

Can I kindly request for a bump. As well probably and other dependencies will need to be updated in order to support the latest Java LTS version - 17.

##### Steps to reproduce

Use Java 17.

**Comment by shrhoads** [comment]
I made a release that may fix your issues:
https://www.icoa.com/gwt-with-jetty-9-4/

**Comment by wrbst** [comment]
Hello Shawn,

Thank you for the quick answer, but we cannot use private projects/repos. 
As well we don't use Jetty.

Into the maven POM, we have tried to exclude bundled extension ASM 7.1 and then include the new version 9.2 as dependency, but then another lib -> Typostry "blow's up" ( _**java.lang.NoClassDefFoundError: org/apache/tapestry/util/text/LocalizedProperties**_) - they also use ASM as dependency and they have introduce support for ASM 9.2 in the latest version 5.8.0.
Even trying to updating the Typostry the same way as ASM we still got this error during compile:  _**java.lang.NoClassDefFoundError: org/apache/tapestry/util/text/LocalizedProperties**_

So some more general solution will be needed.

**Comment by niloc132** [comment]
There is a patch under review right now (it has been +2'd, but I haven't had the chance to return to it to finalize it) which updates to latest Jetty 9.4, and asm 9.2.

With that said, can you confirm that you are specifically failing when trying to run your _server_ app inside GWT's dev mode? If so, this is not encouraged (and the jetty/asm updates are to allow htmlunit to be made more recent, not to target your use case) - it is far better to run your own server, and to run DevMode/CodeServer separately, with the -war/-launchDir argument to build JS where your usual server can see it, and provide it to the browser. That guarantees that problems like this or jetty specific configuration issues cannot affect you.

**Comment by wrbst** [comment]
Hello Colin,

Thanks for very much for you answer as well.
We use the _LocalizableResource_ in a very custom way. The first try described in my previous comment was in gwt-dev.
But changing the dependencies in gwt-user and "reverting" gwt-dev seem to solve the problem for now.

Still... work in progress.

You have done a lot of work as I saw the commits here. Good job! Hope to see new GWT version soon.

**Comment by niloc132** [comment]
@wrbst if you're having other issues outside of the jetty version, can you file a new issue?

GWT 2.10 will be released in the next few days, marking this as closed.
