### ISSUE TITLE
Migrate GWT source control to GitHub

### ISSUE THREAD

**Issue by niloc132** [gwtproject/gwt#9756]
With the GWT 2.10.0 release finalized, and no longer publishing artifacts on with a `com.google.*` groupId, we're able to finish moving the GWT 2 toolkit development entirely to GitHub. Issues have been managed here for several years, and while builds haven't been publicly visible for some time, they have been running until the release process began. This ticket is to track and discuss remaining work to migrate to GitHub.

- [x] File a ticket with github support to disable the "Public Mirror".
- [x] Enable Github Actions (and set up a build badge on the readme) for nightly builds, pull requests.
  - [x] Set up snapshots for nightly builds (GitHub packages are not a viable option, as this requires authentication to read, Sonatype Snapshots are probably best?)
  - [ ] Optional: Always add PR comments instead of diff annotations in the case of checkstyle violations (see https://github.com/gwtproject/gwt/issues/9768 for this)
- [x] Update pull request template with basic guidelines for developing on github first.

**Comment by niloc132** [comment]
I'm intending to close this, with a separate follow-up ticket for posting PRs about style issues, unless anyone has any other thoughts on tasks that need to be done to finish migration? I think we've covered everything listed at https://docs.google.com/document/d/10Cn0Z7SDv0ZW5OVZdoIdw5EAEDUbtK6vracOOnxj7po/edit.

**Comment by tbroyer** [comment]
👍 for closing this.

Wrt the doc, did Google already delete (or ask Sonatype) the snapshots? If not, in what timeframe do we want to have it done? Should we open an issue to track it?

**Comment by niloc132** [comment]
The HEAD-SNAPSHOT builds in google-snapshots have not yet been deleted, though I have requested this, as they are going to be stale soon and not reflect other changes being made.

Closing this issue, https://github.com/gwtproject/gwt/issues/9768 will follow up for the remaining task.

**Comment by niloc132** [comment]
HEAD-SNAPSHOTs for com.google artifacts have been deleted.
