### ISSUE TITLE
GWT 2.10.0 DTD

### ISSUE THREAD

**Issue by Sara-Youssef** [gwtproject/gwt#9770]
**GWT version:** 2.10.0
**Browser (with version):** Chrome 105.0.5195.102
**Operating System:** Ubuntu 22.04.1

---

##### Description
GWT 2.10.0 DTD hasn't been uploaded to the gwt project website yet although it's supported with the release source repository, it cann't be accessed through http://gwtproject.org/doctype/2.10.0/gwt-module.dtd. 
This causes conflict during upgrading GWT 2.8.1 to GWT 2.10.0 in my project as some modules need to reference the DTD as the following:
```
<\!DOCTYPE module PUBLIC "-//Google Inc.//DTD Google Web Toolkit 2.10.0//EN"
  "http://gwtproject.org/doctype/2.10.0/gwt-module.dtd">
```
##### Known workarounds
Use SYSTEM identifier and specify the location of an external file containing GWT 2.10.0 DTD declarations instead of PUBLIC identifier.

**Comment by tommyettinger** [comment]
This appears to have been closed prematurely. A month later, https://www.gwtproject.org/doctype/2.10.0/gwt-module.dtd is still returning 404 Not Found.

**Comment by jhickman** [comment]
The pull request on gwt-site was merged.   I don't think it's been deployed yet.

**Comment by niloc132** [comment]
This is updated now, sorry for the delay.
