### ISSUE TITLE
DataGrid overlaps its boundaries

### ISSUE THREAD

**Issue by d4aniellintner** [gwtproject/gwt#9774]
**GWT Version**
2.8.0 - 2.10.0

**Browser (with version):** 
Microsoft Edge Version 105.0.1343.42 
Chrome Version 105.0.5195.127 

outdated IE11 **does not show** the issue

**Operating System:** 
Windows 10

---

##### Description
When embedding a DataGrid into a layout (e.g. DockLayoutPanel) its lower and right edges overlap its defined space by some pixels (~17) by using the **inset** css property. The issue may come from the CustomScrollPanel inside DataGrid.

As a result, close, active elements, like a pager, may become unfunctional if they are positioned to closely the the DataGrids bottom, as the get overlapped by an invisible area.

##### Steps to reproduce
One can reproduce the behaviour with the official DataGrid showcase 
(https://samples.gwtproject.org/samples/Showcase/Showcase.html#!CwDataGrid)
By removing the footer on the Age column, the pager elements come close enough to get overlaped by at least 50%, thus becoming unclickable in the upper region (other pagers may get entirely covered). 

One can quickly reproduce the behaviour by modifying the DOM in the browser on the above mentioned showcase. 

##### Known workarounds
Kepp distance; use keyboard navigation

**Comment by rdeangelis83** [comment]
In my opinion this is an issue of Chrome. I have already created a simple example to reproduce it. I will create an issue for the Chrome team and see what is there opinion.
[negativInsetAndOverflowScroll.zip](https://github.com/gwtproject/gwt/files/9625907/negativInsetAndOverflowScroll.zip)

**Comment by rdeangelis83** [comment]
Okay, issue created on chromium project: https://bugs.chromium.org/p/chromium/issues/detail?id=1367185
Let's wait for a response. 

Workaround: By increasing the z-index of the element that will be overlapped by the datagrid hidden scrollbar, this issue can be solved.

**Comment by rdeangelis83** [comment]
Is fixed in coming chrome version: 106
https://bugs.chromium.org/p/chromium/issues/detail?id=1360727
I thing we can close this issue

**Comment by d4aniellintner** [comment]
Thank you very much!
