### ISSUE TITLE
Checkstyle errors exist, and are reported

### ISSUE THREAD

**Issue by FredFrance** [gwtproject/gwt#9776]
**GWT version: 2.10** 
**Operating System:Windows10** 

---

##### Description
After verify GWT code conventions:
C:\temp\gwt_retest\trunk\common.ant.xml:361: Checkstyle errors exist, and are re
ported at C:\temp\gwt_retest\trunk\build\out\user/checkstyle_log.xml

##### Steps to reproduce
Use README.md in trunk
"ant clean dist-dev" is OK
"ant clean dist" is OK
"ant compile.tests apicheck checkstyle" is KO

Sample error in checkstyle_log.xml:

file name="C:\temp\gwt_retest\trunk\user\src\com\google\gwt\activity\shared\ActivityManager.java"
error line="175" severity="warning" message="Line is longer than 100 characters (found 115)." source="com.puppycrawl.tools.checkstyle.checks.sizes.LineLengthCheck"/

file name="C:\temp\gwt_retest\trunk\user\src\com\google\gwt\animation\client\AnimationScheduler.java"
error line="121" severity="warning" message="Line is longer than 100 characters (found 101)." source="com.puppycrawl.tools.checkstyle.checks.sizes.LineLengthCheck"/

file name="C:\temp\gwt_retest\trunk\user\src\com\google\gwt\aria\client\AriaAttributeType.java"
error line="20" severity="info" message="First sentence should end with a period." source="com.puppycrawl.tools.checkstyle.checks.javadoc.JavadocStyleCheck"/
error line="57" severity="info" message="First sentence should end with a period." source="com.puppycrawl.tools.checkstyle.checks.javadoc.JavadocStyleCheck"/
error line="69" severity="info" message="First sentence should end with a period." source="com.puppycrawl.tools.checkstyle.checks.javadoc.JavadocStyleCheck"/

**Comment by niloc132** [comment]
Yes, not all code fits the current checkstyle, but we don't prevent merging if your code doesn't fix every instance of style issues. Instead, each diff is only checked to ensure that any lines that it changes correctly match the project style.

The tool we use is called reviewdog (see github.com/reviewdog/reviewdog), and the "quick check" build at https://github.com/gwtproject/gwt/blob/main/.github/workflows/quick-check.yml first checks out the change to be checked, and when reviewdog is invoked, it is told to use that git diff:

https://github.com/gwtproject/gwt/blob/038928ac7752251a273b6412dea0ef60ea600cc3/.github/workflows/quick-check.yml#L44-L55

Is there a specific problem that this is causing for you? If you are working on making a change to GWT, you can ignore any style failures that don't affect the files you've touched.

**Comment by FredFrance** [comment]
Thank you for your reply.
I tried running the tests as marked in the trunk\readme.md to verify my build using the command:
'ant-test'
The tests also fail because the checkstyle_log.xml file is recreated each time.
What should be done to make all the tests work without the style check?

**Comment by niloc132** [comment]
All tests can be run with `ant test`, but probably you want to specify a particular test or suite for your own purposes. Nightly CI runs `ant clean test dist doc` to verify that docs can also be generated correctly. The readme specifies the directory in and the properties to set to be able to fine tune and just run the tests you want https://github.com/gwtproject/gwt/blob/main/README.md#how-to-run-gwt-tests
