### ISSUE TITLE
2.10 artifacts on maven repositories seem to be broken.

### ISSUE THREAD

**Issue by keinhaar** [gwtproject/gwt#9834]
The Jar File on 
https://repo.maven.apache.org/maven2/com/google/gwt/gwt-user/2.10.0/ 
and
https://repo1.maven.org/maven2/com/google/gwt/gwt-user/2.10.0/
isn't a jar file. Instead it is the pom file renamed to jar.
gwt-user-2.10.0.jar and gwt-user-2.10.0.pom have the same size and the same content.

**Comment by niloc132** [comment]
That definitely seems odd, but shouldn't have any effect - the contents of the pom file direct maven/etc to instead us groupId org.gwtproject for this and future releases. The GWT Project does not have access to the com.google.gwt groupId, only Googlers can ask for artifacts to be created there.

The final com.google.gwt release of any jars was 2.9.0, 2.10.0 and future releases will be under org.gwtproject:
https://repo.maven.apache.org/maven2/org/gwtproject/gwt-user/
https://repo1.maven.org/maven2/org/gwtproject/gwt-user/

Are you using some tooling which makes this a problem?
