### ISSUE TITLE
Update ErrorProne to support building (and testing) GWT on Java 21

### ISSUE THREAD

**Issue by ssibrahimpur** [gwtproject/gwt#9859]
**GWT version:** 
**Browser (with version):** 
**Operating System:** 

---

##### Description

Do you have a tentative date for GWT support of the Java 21 LTS version?

##### Links to further discussions

The current supported version of GWT is https://www.gwtproject.org/release-notes.html#Release_Notes_2_10_0, it supports Java 17.

**Comment by jnehlmeier** [comment]
There is one open issue for RequestFactory/AutoBeans and Java 21 so far: https://github.com/gwtproject/gwt/issues/9855

If you don't use any of these I assume that you can run GWT compiler / SuperDevMode using Java 21.

Generally GWT does not plan release dates as it all depends on volunteers fixing issues and reviewing code. GWT 2.11 release is planned but there is still some work to be done, see: https://groups.google.com/g/google-web-toolkit-contributors/c/JfIAPN6XFCo

**Comment by niloc132** [comment]
As part of the linked PR, I ran all the other tests today and at this time I expect the rest of GWT (outside of autobeans and requestfactory) as of GWT 2.10 to work correctly with Java 21. @ssibrahimpur can you specify any issues you're encountering?

**Comment by ssibrahimpur** [comment]
@niloc132 We have a roadmap to support the GWT 2.10 and Java 21 LTS versions. I was checking on plans for the upcoming release of GWT 2.11 and then doing the upgrade. Thank you for the details, that helped me with my planning for now. Looks like 2.11 is on the way!

**Comment by niloc132** [comment]
I'm updating the title of this to outline the work required to test/validate this in 2.12.
