### ISSUE TITLE
GWT compiler does not support Java9 diamond-operator-extension for inner classes

### ISSUE THREAD

**Issue by lgemeinhardt** [gwtproject/gwt#9877]
**GWT version: 2.10.0 and the latest snapshot (20231214.073040-493)** 
**Operating System: Win11** 

---

##### Description
GWT compiler does not support Java9 [diamond-operator-extension](https://www.baeldung.com/new-java-9#2-diamond-operator-extension) for inner classes:

`[ERROR] Line 94: '<>' cannot be used with anonymous classes`

##### Steps to reproduce

This code (Java8 style) compiles

```
	public static Validator<String> textBoxValidator(final Function<String, String> verifier, final TextBox textBox) {
		return new Validator<String>() {

			@Override
			public List<EditorError> validate(final Editor<String> editor, final String value) {
				final ArrayList<EditorError> result = new ArrayList<>();
				// do something
				return result;
			}

			@Override
			public int getPriority() {
				return Priority.MEDIUM;
			}
		};
	}
```

This (Java9 style) **does not** compile

```
	public static Validator<String> textBoxValidator(final Function<String, String> verifier, final TextBox textBox) {
		return new Validator<>() {

			@Override
			public List<EditorError> validate(final Editor<String> editor, final String value) {
				final List<EditorError> result = new ArrayList<>();
				// do something
				return result;
			}

			@Override
			public int getPriority() {
				return Priority.MEDIUM;
			}
		};
	}
```

##### Known workarounds

Keep Java8 style (w/o diamond) for GWT

**Comment by jnehlmeier** [comment]
Hm, seems like a special case / bug in JDT then. In my code base I regularly use the diamond operator for anonymous classes, usually for callbacks, e.g.

```java
Command<MyResult> command = ...;
server.execute(command, new Callback<>() { 

  public void onSuccess(MyResult result) {

  }

})
```

**Comment by lgemeinhardt** [comment]
@niloc132  I was not aware of this switch :-( but this did the trick :-)
Thanks!
