### ISSUE TITLE
Add compiler implementation, tests for switch expressions for Java 14

### ISSUE THREAD

**Issue by niloc132** [gwtproject/gwt#9878]
See https://openjdk.org/jeps/361.

At first glance, this seems like a fairly easy construct to consider, but at a minimum it requires executing statements inside of expressions - this seems to either require decomposing the enclosing expression(s) into statements and executing a switch/case or if/else, or extracting statements to synthetic lambdas or methods (closing over appropriate other locals, etc). As a pathological example, consider this, a switch expression with only one case that executes unconditionally, with embedded statements, passed as an argument to a method call with other expressions that may have side effects:

```java
someMethod(obj.affectState(), switch(0) {
  default -> {
    List<String> list = new ArrayList<>();
    list.add("a");
    list.addAll(obj.affectState());
    yield list;
  }
});
```

Rewriting away just the switch expression while staying in Java could look like
```java
// All sibling expressions (but not children/parents as far as I can tell?) must
// be extracted to ensure they are executed in the correct order. These can/should
// be final.
final Collection<String> arg1 = obj.affectState();
// Provide another local for the switch expression's value, to be assigned in
// each case/default
final Collection<String> arg2;
switch(0) {// switch expression becomes switch statement, with child expressions
  default: {
    List<String> list = new ArrayList<>();
    list.add("a");
    list.addAll(obj.affectState());
    // yield <value> is rewritten to assignment and break
    arg2 = list;
    break;
  }
}
// Actual parent express resumes
someMethod(arg1, arg2);
```

Or, again as a synthetic method:
```java
// notice that we close over `obj`, but not .affectState(), as we might not invoke it
someMethod(obj.affectState(), syntheticSwitchMethod(obj));

...

private static Collection<String> syntheticSwitchMethods(OtherObject obj) {
  switch(0) {// switch expression becomes switch statement, with child expressions
    default: {
      List<String> list = new ArrayList<>();
      list.add("a");
      list.addAll(obj.affectState());
      // yield <value> is rewritten to return <value>
      return list;
    }
  }
}
```

Supporting multiple expressions values in each case, and the `->` label both appear to purely be syntactic sugar, and the JDT should automatically cover this for us.

**Comment by niloc132** [comment]
The method approach likely does not make any sense as it would prevent case blocks from assigning values to local variables.

**Comment by niloc132** [comment]
Short-circuiting operations like `&&` and `||` will also need to be handled. These will need to behave like ternary expressions, and all be broken down into temp local variable statements with if/else statements to do the branching

```java
foo(value(), bar() && switch(val) {...});
```
would need to become something like
```java
var tmp1 = value();
var tmp2;
if (bar()) {
  var tmp3 = switch(val) {...};
  if (tmp3) {
    tmp2 = true;
  } else {
    tmp2 = false;
  }
} else {
  tmp2 = false;
}
foo(tmp1, tmp2);
```
and so on.

**Comment by niloc132** [comment]
Hi @rluble, thanks for your thoughts - how did you handle the ability to assign to locals if you use a lambda? I considered that briefly, but it seems incomplete out of the gate:

```
int i = 0;
someMethod(i++, switch(0) {
  default -> {
    yield i++;
  }
}, i++);
```

**Comment by rluble** [comment]
Well they are not really lambdas in J2CL, or I should say that in the internal represenation lambdas are allowed to change variables that are in scope, i.e. they have JavaScript semantics not Java semantics.

**Comment by niloc132** [comment]
Got it - I am not sure that will fly with GWT (since GWT has an AST between the JDT and JS), but it might be worth a try:
 * Implement Switch Expression (and Case Expression, and the Yield Statement) as JNodes, so that when the GenerateJavaScriptAST translation happens, those JS Functions can be emitted with Js switch+case statements. My concern there was that this will then require updating the various JVisitor types, and reconsider how each subtype might respond to a switch expression...
 * Read from the JDT and directly implement switch expression in JNodes, with js lambda semantics (wrapping the actual switch statement). GwtAstBuilder would then be responsible for this, but my read of the Java 8 lambda implementation was done by punting and _not_ adding new JNode types, or extending what existing JNodes did (this is a slight exageration, but endVisit(LambdaExpression, scope) clearly shows that a class is emitted with a constructor, fields, and a SAM method). Making a "js lambda" ast node seems like a bigger step here, and also likely to require more work with downstream visitors ("this local might be reassigned outside of this local scope")

This is why I picked the above, more difficult approach - let us avoid adding new JNode types, change visitors. In theory we could have a JSwitchExpression type to keep GwtAstBuilder from getting too much bigger, but then immediately normalize those switch/case expressions away into statements (and rewrite other sibling expressions, _and_ wrap in conditionals as above) - but at least it keeps the rewriting local to "how do you translate this". Do you think I missed something here, a way that would allow something like the semantics you described, with minimal rewriting?
