### ISSUE TITLE
GWT release with Jetty 11.x 

### ISSUE THREAD

**Issue by RoshaniChoudhari** [gwtproject/gwt#9907]
As Jetty has announced the End of Community Support for Jetty 9.x in June 2022, Is there a plan to release a GWT version with Jetty 11+ version ???

**GWT version:**  2.11.0
**Browser (with version):** 
**Operating System:** 

---

##### Description
Below issue can be seen when using below artifacts:

gwt-dev 2.11.0
gwt-servlet 2.11.0
gwt-user 2.11.0
Jetty artifacts 11.0.19

java.lang.NoClassDefFoundError: org/eclipse/jetty/util/preventers/GCThreadLeakPreventer
Caused by: java.lang.ClassNotFoundException: org.eclipse.jetty.util.preventers.GCThreadLeakPreventer

##### Steps to reproduce
 -->

**Comment by jnehlmeier** [comment]
GWT 2.11 has deprecated using DevMode as application server:

*Using DevMode as an application server is deprecated, and may be removed or changed in a future release. Please migrate local development workflows to using a general purpose server, or a custom ServletContainerLauncher.*

https://www.gwtproject.org/release-notes.html#Release_Notes_2_11_0

So you are better off using a local jetty installation or using a jetty docker image to run your application in a newer jetty. You can even use Jetty 12 and select the EE environment you would like to use. There isn't really a need to use Jetty 11. Personally I am doing just that. Using Jetty 12 with EE 8 module. Switching to Jakarta is just switching the module to EE 10.

**Comment by niloc132** [comment]
Closing this as not-planned - please check out https://www.gwtproject.org/gettingstarted-v2.html for some advice on starting a project without a built-in app server.
