### ISSUE TITLE
Compile error - GWT Google Web Toolkit (2.10.0, 2.10.1, 2.11.0) on java17.

### ISSUE THREAD

**Issue by Dejiva** [gwtproject/gwt#9929]
Unable to Compile on latest GWT Google Web Toolkit (2.10.0, 2.10.1, 2.11.0) on java17,  getting error as below.
Source level must be one of [auto, 1.8, 9, 10, 11].
Google Web Toolkit 2.11.0
-----------------------------------------------------------------------------------------------------------------------------------------------------
We are upgrading our Java projects from Java11 to Java17 as mentioned in the release note here "https://www.gwtproject.org/release-notes.html", and upgraded GWT from 2.9.0 to 2.10.0 which supports java17 when we try to compile it but failing(eclipse GWT plugin and maven plugins)
I tried with a simple code snippet too, but I ended up with the same error.

Please, anybody, help/guide me to compile and build my project in java17.
**Note: I don't want to pass -sourceLevel 11 argument to compile on 17**

Thanks,

**Comment by jnehlmeier** [comment]
What is the actual error?

**Comment by Dejiva** [comment]
**Error is getting as below**  then stops the compilation.
Source level must be one of [auto, 1.8, 9, 10, 11].
Google Web Toolkit 2.11.0

**Comment by bpetridean** [comment]
_Note: I don't want to pass -sourceLevel 11 argument to compile on 17_

Why not?

**Comment by bpetridean** [comment]
btw: are u using GIN?

**Comment by Dejiva** [comment]
> _Note: I don't want to pass -sourceLevel 11 argument to compile on 17_
> 
> Why not?

Don't want to bypass the java17 compiler.

**Comment by bpetridean** [comment]
Since source level 17 is not available with gwt 2.11.0 and AFAIK if you do not set a value it should resolve to source level 1.8, you're left with one choice....

For what is worth in my configs I am setting the source level to 11

**Comment by bpetridean** [comment]
[According to @niloc132 ](https://matrix.to/#/!AvXTCxQwVkniJBaCEi:gitter.im/$JyRIRMvcuZw6TqlWGjtXE-IALAO5MMl2qLc_uJidXOo?via=gitter.im&via=matrix.org&via=delightfullyoffto.pics )in order to get the new lang features you'll have to set source level to either auto or 11

**Comment by Dejiva** [comment]
> Since source level 17 is not available with gwt 2.11.0 and AFAIK if you do not set a value it should resolve to source level 1.8, you're left with one choice....
> 
> For what is worth in my configs I am setting the source level to 11
> 
> PS: but I do see your point

Do you mean, it won't support java17 compiler?
Our project is upgrading to java17 so, all its modules should be compiled by 17 only. 
I just want to make sure why it's not allowing to compile in "17" event it mentioned in GWT release document.

**Comment by bpetridean** [comment]
Also see this [gitter thread](https://matrix.to/#/!AvXTCxQwVkniJBaCEi:gitter.im/$Vf6fImMwAyLcVhY4_G50MjZHLBvoLdKPKHAJUpPm5eg?via=gitter.im&via=matrix.org&via=delightfullyoffto.pics)

**Comment by jnehlmeier** [comment]
> > Since source level 17 is not available with gwt 2.11.0 and AFAIK if you do not set a value it should resolve to source level 1.8, you're left with one choice....
> > For what is worth in my configs I am setting the source level to 11
> > PS: but I do see your point
> 
> Do you mean, it won't support java17 compiler? Our project is upgrading to java17 so, all its modules should be compiled by 17 only. I just want to make sure why it's not allowing to compile in "17" even though it was mentioned in GWT release document.

You can use JDK 17 to compile your project and also use it to start the GWT compiler. The `sourceLevel` argument defines which Java language features the GWT compiler will accept while compiling your Java code to JavaScript. That is independent of the JVM you are using to compile your app and run the GWT compiler.

**Comment by jnehlmeier** [comment]
Closing the issue because `-sourceLevel 17` is expected to fail with GWT 2.11 as GWT only understands language features up to Java 11.

**Comment by Dejiva** [comment]
Thank you all for your support and quick response.

**Comment by venkataseshammabolineni-efx** [comment]
what is the final statement here? do we have to use -sourceLevel 17?

**Comment by niloc132** [comment]
@venkataseshammabolineni-efx yes - if you want to use Java 17 language features, you need to indicate this with `-sourceLevel 17` (or `-sourceLevel auto` if using java 17+).

**Comment by venkataseshammabolineni-efx** [comment]
But with GWT 2.10.0, Java 17 is not accepting and it is giving Compile error - GWT Google Web Toolkit (2.10.0, 2.10.1, 2.11.0) on java17.

**Comment by jnehlmeier** [comment]
> But with GWT 2.10.0, Java 17 is not accepting and it is giving Compile error - GWT Google Web Toolkit (2.10.0, 2.10.1, 2.11.0) on java17.

@venkataseshammabolineni-efx You have to use GWT 2.12+ if you want to use `-sourceLevel 17`. Any earlier version does not support compiling source code with Java 17 language features to JavaScript. GWT 2.10 and 2.11 support running on Java 17 (e.g. running `DevMode` or `CodeServer` with Java 17 installed on your host) and compile source code with Java 11 language features to JavaScript.

**Comment by venkataseshammabolineni-efx** [comment]
Thanks for details expiation @jnehlmeier , but we don't have 2.12+ version for gwt-maven-plugin. The higher version we can use only 2.10.0. 

Also smartgwt 12.0  supports Java17?

**Comment by niloc132** [comment]
The old gwt-maven-plugin can be made to use a newer gwt version by adding gwt-user and gwt-dev in a `<dependencies>` block within the gwt-maven-plugin `<plugin>` block. Otherwise, [updating to the new plugin](https://tbroyer.github.io/gwt-maven-plugin/migrating.html) is always a good idea.

Last I heard, SmartGWT was not compatible with Java 16+ due to their own `Record` type being used without imports. If they've fixed this, it probably works with newer Java. You'll have to ask them or try it yourself though.

**Comment by volkenborn** [comment]
GWT 2.12 works; it just changed its group name:
`servlet group: 'org.gwtproject', name: 'gwt-servlet', version: '2.12.2'`

I just successfully compiled our project using Java 17.
