### ISSUE TITLE
GWT Issue with JDK 17

### ISSUE THREAD

**Issue by priyaagrawal842** [gwtproject/gwt#9969]
I'm looking to upgrade an ANT-based build tool project developed with Java 1.8.0.161 and GWT to utilize Java 17. To achieve this, I'm seeking guidance on the necessary modifications within the build.xml file and if any upgrade to GWT are required. Additionally, I'd appreciate insights on the most suitable Apache ANT version for compatibility with Java 17 and any other crucial changes required for a smooth transition from Java 1.8 to 17. Any advice from the community on best practices and potential challenges would be greatly appreciated. Thanks in advance!

**Comment by niloc132** [comment]
Closing in favor of the mailing list post, this isn't an issue with GWT.
https://groups.google.com/g/google-web-toolkit/c/0dDFpTPTEZg/m/BO2ehSIKAAAJ
