### ISSUE TITLE
Whitespace check inconsistency

### ISSUE THREAD

**Issue by zbynek** [gwtproject/gwt#9973]
**GWT version: 2.11** 
**Browser (with version): Chrome** 
**Operating System: N/A** 

---

##### Description

GWT emulation of isWhitespace is listing characters explicitly to avoid discrepancies between Java and JS notion of "whitespace", but there is one inconsistency with Java 8 and one inconsistency with Java 11.
For comparison the table below also shows which characters are recognized as whitespace using `chr.match(/\s/)` in JS (Chrome).

|        range | java 8 | java 11 | GWT | JS  |
|--------------|--------|---------|-----|-----|
|\u0009-\u000D, \u0020, \u1680, \u2000-\u2006, \u2008-\u200A, \u2028, \u2029, \u205F, \u3000  | yes    | yes     | yes | yes |
|\u001C-\u001F | yes    | yes     | yes | no  |
|\u00A0,\u2007,\u202F        | no     | no      | no  | yes |
|\u180E        | yes    | no     | yes | no |
|\uFEFF        | no     | no      | yes | yes |

##### Steps to reproduce
* Call `Character.isWhitespace('\uFEFF')` in GWT and JVM (version 8 or 11), observe different results.
* Call `Character.isWhitespace('\u180E')` in GWT and JVM (version 11, Temurin), observe different results.

##### Known workarounds
Implement own utility method for whitespace detection.

##### Links
* https://www.compart.com/en/unicode/U+FEFF zero width no break space
* https://www.compart.com/en/unicode/U+180E Mongolian vowel separator
* https://stackoverflow.com/a/4731164/2270026 explicit regex for Java 8
* j2objc emulation https://github.com/google/j2objc/blob/add4718cf098c3565f49576a5f642173cac0c884/jre_emul/android/platform/libcore/ojluni/src/main/java/java/lang/Character.java#L7350

**Comment by niloc132** [comment]
With regards to `\u180E`, do we consider Java 8 to be broken here? Or do we think that GWT should be aware if it is running "as Java8" or "as Java 11"?

**Comment by tbroyer** [comment]
AFAICT, U+180E was a space (Unicode Zs category) priori to Unicode 6.3.0, and Java 8 was based on Unicode 6.2.0 (Java 9 used Unicode 8)

I'd go with the more recent Unicode stance and **not** consider U+180E a space, even if it means GWT with `-sourceLevel 8` behaves differently from a JDK 8 (but that would likely be the same as running Java 8 bytecode on a JDK 8 vs a more recent JDK)
