### ISSUE TITLE
UI component library

### ISSUE THREAD

**Issue by raindroplvy** [gwtproject/gwt#9992]
The GWT ecosystem lacks a fully functional UI component library. Is it possible to convert some popular UI libraries to the GWT environment with AI transcoding capabilities?

**Comment by FrankHossfeld** [comment]
Take a look here:

https://github.com/DominoKit/domino-ui

or 

https://github.com/patternfly-java/patternfly-java

I am the first one and not missing anything.

**Comment by niloc132** [comment]
https://github.com/dncomponents/dncomponents/ is still getting updates too, but I have no direct experience with it.

https://github.com/GWTReact/gwt-react appears to no longer be updated, but is capable of using react with your GWT business logic.

To directly answer the question, there might be LLM tooling capable of such rewriting, but I haven't seen anything reliable at any kind of scale without strong supervision.

I'm closing this issue (as it isn't really an issue with GWT) - consider [posting to the mailing list](https://groups.google.com/g/google-web-toolkit) to start a discussion there, or the [gitter chat](https://matrix.to/#/#gwtproject_gwt:gitter.im).

**Comment by raindroplvy** [comment]
1. I have some knowledge of domino-ui & patternfly-java before. Currently, both libraries are not stable and strong enough, and their low popularity leads to the lack of functional coverage of some scenes.
2 dncomponents, gwt-react, or others, are either no longer maintained or no one uses them, far from real commercial use;
3 I think the lack of mature and stable ui library is the main reason that restricts the development of gwt, because all technologies should be used to solve real business problems, gwt's idea is very advanced, but it needs a complete set of landing solutions;
4 ui library implementation may not be the responsibility of the gwt team, but whose responsibility should it be, and who is going to fill in the pieces?

**Comment by FrankHossfeld** [comment]
Please, can you explain, why patternfly-java & domino-ui aren't stable and strong enough.  

Why do you think, that low popularity leads to "to the lack of functional coverage of some scenes"? Which "scenes" are you talking about?

Why do you think, that GWT or these UI libs does not solve "real business problems"?

"ui library implementation may not be the responsibility of the gwt team, but whose responsibility should it be, and who is going to fill in the pieces?" what's about you? Contributors are usually highly welcome.

**Comment by treblereel** [comment]
From my side, I want to point out that we have been using GWT for years, and what distinguishes GWT from the kaleidoscope of JS frameworks is its stability. I would also like to note that patternfly-java is based on the Red Hat Patternfly framework, which certainly cannot be considered unready for production.

Perhaps you should clarify your requirements for a UI framework for GWT?
